act_code: '121802'
requisite: Решение Шетского районного маслихата Карагандинской области от 5 мая 2018 года № 21/181. Зарегистрировано Департаментом юстиции Карагандинской области 18 мая 2018 года № 4761. Утратило силу решением Шетского районного маслихата Карагандинской области от 24 июня 2020 года № 39/364 (вводится в действие после дня его первого официального опубликования)
title:
  rus: О повышении ставки земельного налога и ставки единного земельного налога на не используемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения
  kaz: Қазақстан Республикасының жер заңнамасына сәйкес пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-05
approved_by:
- '160015000002'
version_date:
  kaz: 2018-05-05
  rus: 2018-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/121802/kaz/05.05.2018
  rus: https://zan.gov.kz/client/#!/doc/121802/rus/05.05.2018
