act_code: '68098'
requisite: Решение 8 сессии Бухар-Жырауского районного маслихата Карагандинской области от 20 сентября 2012 года № 5. Зарегистрировано Департаментом юстиции Карагандинской области 18 октября 2012 года № 1951. Утратило силу решением Бухар-Жырауского районного маслихата Карагандинской области от 26 июня 2024 года № 6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил о размере и порядке оказания жилищной помощи населению Бухар-Жырауского района
  kaz: Бұқар жырау ауданының тұрғындарына тұрғын үй көмегін көрсету мөлшері мен тәртібі туралы ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-09-20
approved_by:
- '160017000002'
version_date:
  kaz: 2019-12-25
  rus: 2019-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/68098/kaz/25.12.2019
  rus: https://zan.gov.kz/client/#!/doc/68098/rus/25.12.2019
caused_by:
  code: '138019'
  requisite: Решение Бухар-Жырауского районного маслихата Карагандинской области от 25 декабря 2019 года № 8. Зарегистрировано Департаментом юстиции Карагандинской области 6 января 2020 года № 5664. Утратило силу решением Бухар-Жырауского районного маслихата Карагандинской области от 26 июня 2024 года № 6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение 8 сессии Бухар-Жырауского районного маслихата от 20 сентября 2012 года № 5 «Об утверждении Правил о размере и порядке оказания жилищной помощи населению Бухар-Жырауского района»
    kaz: Бұқар жырау аудандық мәслихатының 8 сессиясының 2012 жылғы 20 қыркүйектегі № 5 «Бұқар жырау ауданының тұрғындарына тұрғын үй көмегін көрсету мөлшері мен тәртібі туралы ережесін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/138019/rus
