act_code: '83683'
requisite: Решение Темиртауского городского маслихата Карагандинской области от 16 сентября 2014 года № 32/6. Зарегистрировано Департаментом юстиции Карагандинской области 13 октября 2014 года № 2799. Утратило силу решением Темиртауского городского маслихата Карагандинской области от 26 июня 2018 года № 27/6 (вводится в действие с 1 января 2019 года).
title:
  rus: О понижении или повышении ставок земельного налога и об утверждении схемы зонирования земель города Темиртау для целей налогообложения
  kaz: Жер салығының ставкаларын төмендету немесе жоғарылату туралы және салық салу мақсаты үшін Теміртау қаласы жерлерін аймақтарға бөлу схемасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-09-16
approved_by:
- '160005000002'
version_date:
  kaz: 2015-07-20
  rus: 2015-07-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/83683/kaz/20.07.2015
  rus: https://zan.gov.kz/client/#!/doc/83683/rus/20.07.2015
caused_by:
  code: '92782'
  requisite: Решение Темиртауского городского маслихата Карагандинской области от 20 июля 2015 года № 41/4. Зарегистрировано Департаментом юстиции Карагандинской области 10 августа 2015 года № 3363. Утратило силу решением Темиртауского городского маслихата Карагандинской области от 26 июня 2018 года № 27/6 (вводится в действие с 1 января 2019 года).
  title:
    rus: О внесении изменения в решение 32 сессии Темиртауского городского маслихата от 16 сентября 2014 года № 32/6 «О понижении или повышении ставок земельного налога и об утверждении схемы зонирования земель города Темиртау для целей налогообложения»
    kaz: Теміртау қалалық мәслихатының 2014 жылғы 16 қыркүйектегі 32 сессиясының № 32/6 «Жер салығының ставкаларын төмендету немесе жоғарылату туралы және салық салу мақсаты үшін Теміртау қаласы жерлерін аймақтарға бөлу схемасын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/92782/rus
