act_code: '45370'
requisite: Решение 13 сессии Бухар-Жырауского районного маслихата Карагандинской области от 31 марта 2009 года № 6. Зарегистрировано Управлением юстиции Бухар-Жырауского района Карагандинской области 24 апреля 2009 года № 8-11-74
title:
  rus: Об установлении стоимости разовых талонов для рынков Бухар-Жырауского района и на отдельные виды предпринимательской деятельности, носящих эпизодический характер
  kaz: Эпизодтық сипатқа ие кәсіпкерлік қызметтің жекеленген түрлеріне және Бұқар жырау ауданының базарларындағы бір жолғы талондардың құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-31
approved_by:
- '160017000002'
version_date:
  kaz: 2009-03-31
  rus: 2009-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/45370/kaz/31.03.2009
  rus: https://zan.gov.kz/client/#!/doc/45370/rus/31.03.2009
