act_code: '176586'
requisite: Решение Актогайского районного маслихата Карагандинской области от 27 декабря 2022 года № 214
title:
  rus: О бюджете поселков, села, сельских округов Актогайского района на 2023-2025 годы
  kaz: Ақтоғай ауданының кенттерінің, ауыл, ауылдық округтерінің 2023-2025 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '160014000002'
version_date:
  kaz: 2022-12-27
  rus: 2022-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/176586/kaz/27.12.2022
  rus: https://zan.gov.kz/client/#!/doc/176586/rus/27.12.2022
