act_code: '200689'
requisite: Решение Абайского районного маслихата Карагандинской области от 12 сентября 2024 года № 23/216. Зарегистрировано в Департаменте юстиции Карагандинской области 16 сентября 2024 года № 6653-09
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Абайском районе
  kaz: Абай ауданында тұрғын үй көмегін көрсету мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-09-12
approved_by:
- '160011000002'
version_date:
  kaz: 2024-09-12
  rus: 2024-09-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/200689/kaz/12.09.2024
  rus: https://zan.gov.kz/client/#!/doc/200689/rus/12.09.2024
