act_code: '190783'
requisite: Решение Актогайского районного маслихата Карагандинской области от 26 декабря 2023 года № 110
title:
  rus: О бюджете поселков, села, сельских округов Актогайского района на 2024-2026 годы
  kaz: Ақтоғай ауданының кенттерінің, ауыл, ауылдық округтерінің 2024-2026 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-26
approved_by:
- '160014000002'
version_date:
  kaz: 2024-07-09
  rus: 2024-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/190783/kaz/09.07.2024
  rus: https://zan.gov.kz/client/#!/doc/190783/rus/09.07.2024
caused_by:
  code: '198586'
  requisite: Решение Актогайского районного маслихата Карагандинской области от 9 июля 2024 года № 173
  title:
    rus: О внесении изменений в решение Актогайского районного маслихата от 26 декабря 2023 года № 110 «О бюджете поселков, села, сельских округов Актогайского района на 2024-2026 годы»
    kaz: Ақтоғай аудандық мәслихатының 2023 жылғы 26 желтоқсандағы № 110 «Ақтоғай ауданының кенттерінің, ауыл, ауылдық округтерінің 2024-2026 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198586/rus
