act_code: '49566'
requisite: Қарағанды облысы Ақтоғай аудандық мәслихатының 18 сессиясының 2009 жылғы 23 желтоқсандағы № 192 шешімі. Қарағанды облысы Ақтоғай ауданының Әділет басқармасында 2009 жылғы 28 желтоқсанда № 8-10-96 тіркелді. Күші жойылды - Қарағанды облысы Ақтоғай аудандық мәслихатының 2012 жылғы 10 сәуірдегі № 34 шешімімен
title:
  rus: Азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету Қағидасы туралы
  kaz: Азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету Қағидасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '160014000002'
version_date:
  kaz: 2009-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/49566/kaz/23.12.2009
