act_code: '124119'
requisite: Решение XXIII сессии Улытауского районного маслихата Карагандинской области от 23 июля 2018 года № 198. Зарегистрировано Департаментом юстиции Карагандинской области 7 августа 2018 года № 4887. Утратило силу решением Улытауского районного маслихата области Ұлытау от 20 сентября 2022 года № 148 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества Улытауского района
  kaz: Ұлытау ауданының бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2018-07-23
approved_by:
- '160019000002'
version_date:
  kaz: 2018-07-23
  rus: 2018-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/124119/kaz/23.07.2018
  rus: https://zan.gov.kz/client/#!/doc/124119/rus/23.07.2018
