act_code: '123493'
requisite: Решение XXIX сессии Каркаралинского районного маслихата Карагандинской области от 21 июня 2018 года № VI-29/263. Зарегистрировано Департаментом юстиции Карагандинской области 11 июля 2018 года № 4860. Утратило силу решением Каркаралинского районного маслихата Карагандинской области от 24 февраля 2022 года № VII-15/122 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения по Каркаралинскому району
  kaz: Қарқаралы ауданы бойынша пайдаланылмайтын ауылшаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-21
approved_by:
- '160013000002'
version_date:
  kaz: 2018-06-21
  rus: 2018-06-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/123493/kaz/21.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123493/rus/21.06.2018
