act_code: '53389'
requisite: Қарағанды облысы Жаңаарқа ауданының Атасу кенті әкімінің 2010 жылғы 9 маусымдағы № 01 шешімі. Қарағанды облысы Жаңаарқа ауданының Әділет басқармасында 2010 жылғы 1 шілдеде № 8-12-76 тіркелді
title:
  rus: Атасу кентіндегі ДЭУ-37 көшесіне Үмбетжан Абжановтың атын беру туралы
  kaz: Атасу кентіндегі ДЭУ-37 көшесіне Үмбетжан Абжановтың атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-09
approved_by:
- '160016014001'
version_date:
  kaz: 2010-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/53389/kaz/09.06.2010
