act_code: '127175'
requisite: Решение акима Киргизского сельского округа Каркаралинского района Карагандинской области от 5 декабря 2018 года № 03. Зарегистрировано Департаментом юстиции Карагандинской области 11 декабря 2018 года № 5047
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-05
approved_by:
- '160013012002'
version_date:
  kaz: 2018-12-05
  rus: 2018-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/127175/kaz/05.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127175/rus/05.12.2018
