act_code: '62143'
requisite: Решение акима Улытауского района Карагандинской области от 14 декабря 2011 года № 06. Зарегистрировано управлением юстиции Улытауского района Карагандинской области 22 декабря 2011 года № 8-16-75
title:
  rus: О приписке граждан 1995 года рождения проживающих в Улытауском районе к призывному участку в период январь-март месяца 2012 году
  kaz: Ұлытау ауданы аумағында тұратын 1995 жылы туған азаматтарды 2012 жылы қаңтар-наурыз айларында әскерге шақыру учаскесіне тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-14
approved_by:
- '160019000001'
version_date:
  kaz: 2011-12-14
  rus: 2011-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/62143/kaz/14.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62143/rus/14.12.2011
