act_code: '62248'
requisite: Решение XLI сессии Карагандинского областного маслихата от 29 ноября 2011 года № 465. Зарегистрировано Департаментом юстиции Карагандинской области 26 декабря 2011 года № 1903. Утратило силу решением Карагандинского областного маслихата от 14 декабря 2023 года № 124 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О ставках платы за эмиссии в окружающую среду
  kaz: Қоршаған ортаға эмиссиялар үшін төлемақы ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-29
approved_by:
- '160000000002'
version_date:
  kaz: 2020-12-10
  rus: 2020-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/62248/kaz/10.12.2020
  rus: https://zan.gov.kz/client/#!/doc/62248/rus/10.12.2020
caused_by:
  code: '149947'
  requisite: Решение Карагандинского областного маслихата от 10 декабря 2020 года № 593. Зарегистрировано Департаментом юстиции Карагандинской области 15 декабря 2020 года № 6127. Утратило силу решением Карагандинского областного маслихата от 14 декабря 2023 года № 124 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение XLI сессии Карагандинского областного маслихата от 29 ноября 2011 года № 465 «О ставках платы за эмиссии в окружающую среду»
    kaz: Қарағанды облыстық мәслихатының 2011 жылғы 29 қарашадағы XLI сессиясының № 465 «Қоршаған ортаға эмиссиялар үшін төлемақы ставкалары туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149947/rus
