act_code: '56346'
requisite: Қарағанды облысы Жаңаарқа ауданы мәслихатының XXXI сессиясының 2010 жылғы 22 желтоқсандағы № 31/258 шешімі. Қарағанды облысы Жаңаарқа ауданының Әділет басқармасында 2010 жылғы 29 желтоқсанда № 8-12-99 тіркелді
title:
  rus: 2011-2013 жылдарға арналған аудандық бюджет туралы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-22
approved_by:
- '160016000002'
version_date:
  kaz: 2010-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/56346/kaz/22.12.2010
