act_code: '31412'
requisite: Решение Приозерского городского маслихата Карагандинской области от 15 декабря 2006 года № 206/36. Зарегистрировано управлением юстиции города Балхаша 24 января 2007 года за № 8-4-60. Утратило силу решением Приозерского городского маслихата Карагандинской области от 23 декабря 2008 года № 81/15
title:
  rus: Об установлении ставок фиксированного суммарного налога для объектов игорного бизнеса
  kaz: Ойын бизнесі объектілеріне арналған тіркелген жиынтық салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-15
approved_by:
- '160009000002'
version_date:
  kaz: 2006-12-15
  rus: 2006-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/31412/kaz/15.12.2006
  rus: https://zan.gov.kz/client/#!/doc/31412/rus/15.12.2006
