act_code: '39182'
requisite: Қарағанды облысы Ұлытау аудандық мәслихатының V сессиясының 2008 жылғы 31 наурыздағы № 67 шешімі. Қарағанды облысы Ұлытау ауданы Әділет басқармасында 2008 жылғы 28 сәуірде № 8-16-32 тіркелді. Күші жойылды - Қарағанды облысы Ұлытау аудандық мәслихатының ХVI сессиясының 2013 жылғы 28 қарашадағы № 131 шешімімен
title:
  rus: Қарағанды облысы Ұлытау ауданы аумағында құрылыс салу Қағидасын бекіту туралы
  kaz: Қарағанды облысы Ұлытау ауданы аумағында құрылыс салу Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2008-03-31
approved_by:
- '160019000002'
version_date:
  kaz: 2008-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/39182/kaz/31.03.2008
