act_code: '37809'
requisite: Қарағанды облысы Нұра ауданы Киевка кентінің әкімінің 2008 жылғы 15 қаңтардағы № 1 шешімі. Қарағанды облысы Нұра ауданы Әділет басқармасында 2008 жылғы 18 ақпанда № 8-14-66 тіркелді
title:
  rus: Киевка кенті көшелерінің аттарын өзгерту туралы
  kaz: Киевка кенті көшелерінің аттарын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-01-15
approved_by:
- '160012027001'
version_date:
  kaz: 2008-01-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/37809/kaz/15.01.2008
