act_code: '125831'
requisite: Решение акима поселка Топар Абайского района Карагандинской области от 31 октября 2018 года № 10. Зарегистрировано Департаментом юстиции Карагандинской области 9 ноября 2018 года № 5002
title:
  rus: О переименовании составных частей в поселке Топар
  kaz: Топар кентіндегі құрамдас бөліктерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-10-31
approved_by:
- '160011003001'
version_date:
  kaz: 2018-10-31
  rus: 2018-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/125831/kaz/31.10.2018
  rus: https://zan.gov.kz/client/#!/doc/125831/rus/31.10.2018
