act_code: '76439'
requisite: Решение Сатпаевского городского маслихата Карагандинской области от 26 декабря 2013 года № 198. Зарегистрировано Департаментом юстиции Карагандинской области 8 января 2014 года № 2490
title:
  rus: О городском бюджете на 2014-2016 годы
  kaz: 2014-2016 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-26
approved_by:
- '160007000002'
version_date:
  kaz: 2014-04-17
  rus: 2014-04-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/76439/kaz/17.04.2014
  rus: https://zan.gov.kz/client/#!/doc/76439/rus/17.04.2014
caused_by:
  code: '79156'
  requisite: Решение Сатпаевского городского маслихата Карагандинской области от 17 апреля 2014 года № 246. Зарегистрировано Департаментом юстиции Карагандинской области 23 апреля 2014 года № 2606
  title:
    rus: О внесении изменений и дополнений в решение Сатпаевского городского маслихата от 26 декабря 2013 года № 198 "О городском бюджете на 2014-2016 годы"
    kaz: Сәтбаев қалалық мәслихатының "2014-2016 жылдарға арналған қалалық бюджет туралы" 2013 жылғы 26 желтоқсандағы № 198 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/79156/rus
