act_code: '64087'
requisite: Решение Сатпаевского городского маслихата Карагандинской области от 21 февраля 2012 года № 26. Зарегистрировано Управлением юстиции города Сатпаев Карагандинской области 15 марта 2012 года № 8-6-136. Утратило силу решением Сатпаевского городского маслихата Карагандинской области от 20 августа 2014 года № 262
title:
  rus: Об утверждении Правил определения размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) города Сатпаев
  kaz: Сәтбаев қаласының аз қамтамасыз етілген отбасыларына (азаматтарына) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2012-02-21
approved_by:
- '160007000002'
version_date:
  kaz: 2012-08-17
  rus: 2012-08-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/64087/kaz/17.08.2012
  rus: https://zan.gov.kz/client/#!/doc/64087/rus/17.08.2012
caused_by:
  code: '67524'
  requisite: Решение Сатпаевского городского маслихата Карагандинской области от 17 августа 2012 года № 73. Зарегистрировано Департаментом юстиции Карагандинской области 10 сентября 2012 года № 1930. Утратило силу решением Сатпаевского городского маслихата Карагандинской области от 20 августа 2014 года № 262
  title:
    rus: О внесении изменений в решение Сатпаевского городского маслихата от 21 февраля 2012 года № 26 "Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам) города Сатпаев"
    kaz: Сәтбаев қалалық мәслихатының 2012 жылғы 21 ақпандағы "Сәтбаев қаласының аз қамтамасыз етілген отбасыларына (азаматтарына) тұрғын үй көмегін көрсету ережесін бекіту туралы" № 26 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/67524/rus
