act_code: '19614'
requisite: Решение акима Карагандинской области от 8 апреля 2004 года № 39. Зарегистрировано Департаментом юстиции Карагандинской области 27 апреля 2004 года за № 1492. Утратило силу - решением акима Карагандинской области от 14 апреля 2008 года № 01
title:
  rus: Об организации и проведении учебно-полевых сборов в оборонно-спортивных оздоровительных лагерях городов и районов области с юношами допризывного и призывного возрастов
  kaz: Шақыруға дейінгі және шақырылу жасындағы жасөспірімдермен облыс қалалары мен аудандарының қорғаныс-спорттық сауықтыру лагерлерінде оқу-дала жиындарын ұйымдастыру және өткізу
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-04-07
approved_by:
- '160000000003'
version_date:
  kaz: 2004-04-07
  rus: 2004-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/19614/kaz/07.04.2004
  rus: https://zan.gov.kz/client/#!/doc/19614/rus/07.04.2004
