act_code: '194861'
requisite: Решение Каркаралинского районного маслихата Карагандинской области от 28 марта 2024 года № VIII-20/160
title:
  rus: Об утверждении программы по управлению коммунальными отходами Каркаралинского района Карагандинской области на 2024-2028 годы
  kaz: Қарағанды облысы Қарқаралы ауданының коммуналдық қалдықтарды басқару жөніндегі 2024–2028 жылдарға арналған бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-28
approved_by:
- '160013000002'
version_date:
  kaz: 2024-03-28
  rus: 2024-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/194861/kaz/28.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194861/rus/28.03.2024
