act_code: '34263'
requisite: Қарағанды облысы Шет аудандық мәслихатының 2007 жылғы 9 шілдедегі № 39/404 шешімі. Қарағанды облысы Шет ауданы әділет басқармасында 2007 жылғы 25 шілдеде № 8-17-47 тіркелді
title:
  rus: Шет ауданы елді мекендерінде жасыл желекті екпелер кұру, күтіп ұстау және қорғау ережелерін бекіту туралы
  kaz: Шет ауданы елді мекендерінде жасыл желекті екпелер кұру, күтіп ұстау және қорғау ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-07-09
approved_by:
- '160015000002'
version_date:
  kaz: 2007-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/34263/kaz/09.07.2007
