act_code: '50272'
requisite: Қарағанды облысы Ақтоғай ауданының әкімінің 2010 жылғы 21 қаңтардағы № 01ш шешімі. Қарағанды облысы Ақтоғай ауданы Әділет басқармасында 2010 жылғы 27 қаңтарда № 8-10-98 тіркелді
title:
  rus: Ақтоғай ауданы бойынша 1993 жылғы туған ер жынысты азаматтарды Балқаш қаласының қорғаныс істері жөніндегі біріктірілген бөлімінің шақыру учаскесіне тіркеуді өткізу туралы
  kaz: Ақтоғай ауданы бойынша 1993 жылғы туған ер жынысты азаматтарды Балқаш қаласының қорғаныс істері жөніндегі біріктірілген бөлімінің шақыру учаскесіне тіркеуді өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-01-21
approved_by:
- '160014000001'
version_date:
  kaz: 2010-01-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/50272/kaz/21.01.2010
