act_code: '28784'
requisite: Қарағанды қалалық мәслихатының III шақырылған XXXIII сессиясының 2006 жылғы 7 маусымдағы № 18 шешімі. Қарағанды қаласы әділет басқармасында 2006 жылғы 7 шілдеде № 8-1-34 тіркелді
title:
  rus: Сыртқы (көрнекi) жарнама объектілерін орналастырғаны үшiн төленетiн төлемақыларды белгілеу туралы
  kaz: Сыртқы (көрнекi) жарнама объектілерін орналастырғаны үшiн төленетiн төлемақыларды белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-06-07
approved_by:
- '160002000002'
version_date:
  kaz: 2006-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/28784/kaz/07.06.2006
