act_code: '47528'
requisite: Қарағанды облысы Ақтоғай аудандық мәслихатының 12 сессиясының 2009 жылғы 24 сәуірдегі № 141 шешімі. Қарағанды облысы Ақтоғай ауданы Әділет басқармасында 2009 жылғы 26 тамызда № 8-10-87 тіркелді. Күші жойылды - Қарағанды облысы Ақтоғай аудандық мәслихатының 2011 жылғы 3 желтоқсандағы № 369 шешімімен
title:
  rus: Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақысын беру және телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы берудің Қағидасын бекіту туралы
  kaz: Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақысын беру және телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы берудің Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2009-04-24
approved_by:
- '160014000002'
version_date:
  kaz: 2009-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/47528/kaz/24.04.2009
