act_code: '144127'
requisite: Решение Каркаралинского районного маслихата Карагандинской области от 18 июня 2020 года № VI-57/484. Зарегистрировано Департаментом юстиции Карагандинской области 25 июня 2020 года № 5911
title:
  rus: Об установлении повышенных на двадцать пять процентов должностных окладов и тарифных ставок специалистам в области социального обеспечения и культуры, являющимся гражданскими служащими и работающим в сельской местности
  kaz: Азаматтық қызметшілер болып табылатын және ауылдық жерде жұмыс iстейтiн әлеуметтiк қамсыздандыру және мәдениет саласындағы мамандарға жиырма бес пайызға жоғарылатылған лауазымдық айлықақылар мен тарифтік мөлшерлемелерді белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-18
approved_by:
- '160013000002'
version_date:
  kaz: 2020-06-18
  rus: 2020-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/144127/kaz/18.06.2020
  rus: https://zan.gov.kz/client/#!/doc/144127/rus/18.06.2020
