act_code: '30991'
requisite: Решение 36 сессии Абайского районного маслихата Карагандинской области от 21 декабря 2006 года № 36/362. Зарегистрировано Управлением юстиции Абайского района Карагандинской области 3 января 2007 года за № 8-9-25. Утратило силу решением 5 сессии Абайского районного маслихата Карагандинской области от 19 декабря 2007 года № 5/36
title:
  rus: О размерах ставок на отдельные виды налогов
  kaz: Салықтың жекелеген түрлеріне арналған ставкалардың мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-21
approved_by:
- '160011000002'
version_date:
  kaz: 2006-12-21
  rus: 2006-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/30991/kaz/21.12.2006
  rus: https://zan.gov.kz/client/#!/doc/30991/rus/21.12.2006
