act_code: '56890'
requisite: Қарағанды облысы Шет аудандық мәслихатының 2010 жылғы 23 желтоқсандағы № 28/290 шешімі. Қарағанды облысы Шет ауданының Әділет басқармасында 2011 жылғы 20 қаңтарда № 8-17-110 тіркелді
title:
  rus: 2011-2013 жылдарға арналған аудандық бюджет туралы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '160015000002'
version_date:
  kaz: 2011-06-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/56890/kaz/03.06.2011
caused_by:
  code: '59474'
  requisite: Решение Шетского районного маслихата Карагандинской области от 3 июня 2011 года № 32/330. Зарегистрировано Управлением юстиции Шетского района Карагандинской области 4 июля 2011 года № 8-17-122
  title:
    rus: О внесении изменения в решение XXVIII сессии районного маслихата от 23 декабря 2010 года № 28/290 "О районном бюджете на 2011-2013 годы"
    kaz: Аудандық мәслихаттың 2010 жылғы 23 желтоқсандағы ХХVIII сессиясының "2011–2013 жылдарға арналған аудандық бюджет туралы" № 28/290 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/59474/rus
