act_code: '56890'
requisite: Қарағанды облысы Шет аудандық мәслихатының 2010 жылғы 23 желтоқсандағы № 28/290 шешімі. Қарағанды облысы Шет ауданының Әділет басқармасында 2011 жылғы 20 қаңтарда № 8-17-110 тіркелді
title:
  rus: 2011-2013 жылдарға арналған аудандық бюджет туралы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '160015000002'
version_date:
  kaz: 2011-11-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/56890/kaz/10.11.2011
caused_by:
  code: '61725'
  requisite: Решение Шетского районного маслихата Карагандинской области от 10 ноября 2011 года № 39/369. Зарегистрировано Управлением юстиции Шетского района Карагандинской области 2 декабря 2011 года № 8-17-125
  title:
    rus: О внесении изменений в решение XXVIII cессии районного маслихата от 23 декабря 2010 года № 28/290 "О районном бюджете на 2011-2013 годы"
    kaz: Аудандық мәслихаттың 2010 жылғы 23 желтоқсандағы ХХVIII сессиясының "2011–2013 жылдарға арналған аудандық бюджет туралы" № 28/290 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/61725/rus
