act_code: '76440'
requisite: Решение 27 сессии Саранского городского маслихата Карагандинской области от 12 декабря 2013 года № 279. Зарегистрировано Департаментом юстиции Карагандинской области 8 января 2014 года № 2491. Утратило силу решением Саранского городского маслихата Карагандинской области от 23 ноября 2023 года № 75 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан города Сарани и поселка Актас
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерін белгілеудің және Саран қаласы мен Ақтас кентінің мұқтаж азаматтарының жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-12-12
approved_by:
- '160003000002'
version_date:
  kaz: 2023-06-15
  rus: 2023-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/76440/kaz/15.06.2023
  rus: https://zan.gov.kz/client/#!/doc/76440/rus/15.06.2023
caused_by:
  code: '183115'
  requisite: Решение Саранского городского маслихата Карагандинской области от 15 июня 2023 года № 33. Зарегистрировано в Департаменте юстиции Карагандинской области 21 июня 2023 года № 6437-09. Утратило силу решением Саранского городского маслихата Карагандинской области от 23 ноября 2023 года № 75 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Саранского городского маслихата от 12 декабря 2013 года № 279 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан города Сарани и поселка Актас»
    kaz: «Әлеуметтік көмек көрсетудің, оның мөлшерін белгілеудің және Саран қаласы мен Ақтас кентінің мұқтаж азаматтарының жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Саран қалалық мәслихатының 2013 жылғы 12 желтоқсандағы № 279 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183115/rus
