act_code: '108673'
requisite: Решение VI сессии Карагандинского областного маслихата от 12 декабря 2016 года № 131. Зарегистрировано Департаментом юстиции Карагандинской области 28 декабря 2016 года № 4066
title:
  rus: Об областном бюджете на 2017-2019 годы
  kaz: 2017-2019 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-12
approved_by:
- '160000000002'
version_date:
  kaz: 2016-12-12
  rus: 2016-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/108673/kaz/12.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108673/rus/12.12.2016
