act_code: '43336'
requisite: Решение 10 сессии Абайского районного маслихата Карагандинской области от 25 декабря 2008 года № 10/119. Зарегистрировано Управлением юстиции Абайского района Карагандинской области 12 января 2009 года № 8-9-51. Утратило силу - решением Абайского районного маслихата Карагандинской области от 21 декабря 2009 года № 18/217
title:
  rus: Об установлении стоимости разовых талонов и размеров ставок на отдельные виды налогов на 2009 год
  kaz: 2009 жылға арналған бір жолдық талондардың және салықтың жекелеген түрлеріне арналған ставкалар мөлшерінің құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-25
approved_by:
- '160011000002'
version_date:
  kaz: 2008-12-25
  rus: 2008-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/43336/kaz/25.12.2008
  rus: https://zan.gov.kz/client/#!/doc/43336/rus/25.12.2008
