act_code: '43524'
requisite: Решение акима города Шахтинск Карагандинской области от 5 декабря 2008 года № 1. Зарегистрировано Управлением юстиции города Шахтинск Карагандинской области 16 января 2009 года № 8-8-61
title:
  rus: О проведении приписки граждан 1992 года рождения к призывному участку
  kaz: Әскерге шақыру учаскесіне 1992 жылы туған азаматтарды тіркеуге өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-05
approved_by:
- '160004000001'
version_date:
  kaz: 2008-12-05
  rus: 2008-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/43524/kaz/05.12.2008
  rus: https://zan.gov.kz/client/#!/doc/43524/rus/05.12.2008
