act_code: '120960'
requisite: Решение 22 сессии Бухар - Жырауского районного маслихата Карагандинской области от 29 марта 2018 года № 9. Зарегистрировано Департаментом юстиции Карагандинской области 17 апреля 2018 года № 4706. Утратило силу решением Бухар-Жырауского районного маслихата Карагандинской области от 31 марта 2022 года № 11 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении Правил управления бесхозяйными отходами, признанными решением суда поступившими в коммунальную собственность Бухар - Жырауского района
  kaz: Бұқар жырау ауданындағы сот шешімімен коммуналдық меншікке түскен болып танылған иесіз қалдықтарды басқару қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2018-03-29
approved_by:
- '160017000002'
version_date:
  kaz: 2018-03-29
  rus: 2018-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/120960/kaz/29.03.2018
  rus: https://zan.gov.kz/client/#!/doc/120960/rus/29.03.2018
