act_code: '107235'
requisite: Решение VII сессии Нуринского районного маслихата Карагандинской области от 6 октября 2016 года № 73. Зарегистрировано Департаментом юстиции Карагандинской области 28 октября 2016 года № 4020. Утратило силу решением Нуринского районного маслихата Карагандинской области от 18 ноября 2020 года № 503 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении Правил выдачи служебного удостоверения государственного учреждения «Аппарат Нуринского районного маслихата» и его описание
  kaz: «Нұра аудандық мәслихатының аппараты» мемлекеттік мекемесінің қызметтік куәлігін беру Қағидаларын және оның сипаттамасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-10-06
approved_by:
- '160012000002'
version_date:
  kaz: 2016-10-06
  rus: 2016-10-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/107235/kaz/06.10.2016
  rus: https://zan.gov.kz/client/#!/doc/107235/rus/06.10.2016
