act_code: '190401'
requisite: Решение Абайского районного маслихата Карагандинской области от 21 декабря 2023 года № 13/127
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Абайскому району на 2024-2025 годы
  kaz: Абай ауданы бойынша 2024-2025 жылдарға арналған Жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-21
approved_by:
- '160011000002'
version_date:
  kaz: 2023-12-21
  rus: 2023-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/190401/kaz/21.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190401/rus/21.12.2023
