act_code: '153126'
requisite: Решение Нуринского районного маслихата Карагандинской области от 19 февраля 2021 года № 18. Зарегистрировано Департаментом юстиции Карагандинской области 25 февраля 2021 года № 6208
title:
  rus: Об установлении повышенных на двадцать пять процентов должностных окладов и тарифных ставок специалистам в области социального обеспечения, культуры и спорта являющимся гражданскими служащими и работающим в сельских населенных пунктах, а также указанным специалистам, работающим в государственных организациях, финансируемых из местных бюджетов Нуринского района
  kaz: Азаматтық қызметші болып табылатын және ауылдық елдi мекендерде жұмыс iстейтiн әлеуметтiк қамсыздандыру, мәдениет және спорт саласындағы мамандарға, сондай-ақ Нұра ауданының жергілікті бюджеттерден қаржыландырылатын мемлекеттік ұйымдарда жұмыс істейтін аталған мамандарға жиырма бес пайызға лауазымдық жоғарылатылған айлықақылар мен тарифтiк мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-02-19
approved_by:
- '160012000002'
version_date:
  kaz: 2021-02-19
  rus: 2021-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/153126/kaz/19.02.2021
  rus: https://zan.gov.kz/client/#!/doc/153126/rus/19.02.2021
