act_code: '5964'
requisite: Решение Акима Карагандинской области от 30 марта 2000 года № 41. Зарегистрировано управлением юстиции Карагандинской области 28 апреля 2000 года за № 81.Утратило силу решением акима Карагандинской области от 14 мая 2004 года № 44
title:
  rus: О проведении призыва граждан на срочную военную службу в 2000 году
  kaz: 2000 жылы азаматтарды мерзімді әскери қызметке шақыруды өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-03-29
approved_by:
- '160000000001'
version_date:
  kaz: 2000-03-29
  rus: 2000-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/5964/kaz/29.03.2000
  rus: https://zan.gov.kz/client/#!/doc/5964/rus/29.03.2000
