act_code: '86095'
requisite: Решение Балхашского городского маслихата Карагандинской области от 19 декабря 2014 года № 34/267. Зарегистрировано Департаментом юстиции Карагандинской области 9 января 2015 года № 2913. Прекращено действие в связи с истечением срока, на который решение было принято (письмо Балхашского городского маслихата Карагандинской области от 13 января 2016 года № 1-23/5)
title:
  rus: О городском бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-19
approved_by:
- '160008000002'
version_date:
  kaz: 2015-11-20
  rus: 2015-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/86095/kaz/20.11.2015
  rus: https://zan.gov.kz/client/#!/doc/86095/rus/20.11.2015
caused_by:
  code: '96115'
  requisite: Решение Балхашского городского маслихата Карагандинской области от 20 ноября 2015 года № 44/344. Зарегистрировано Департаментом юстиции Карагандинской области 25 ноября 2015 года № 3510. Прекращено действие в связи с истечением срока, на который решение было принято (письмо Балхашского городского маслихата Карагандинской области от 13 января 2016 года № 1-23/5)
  title:
    rus: О внесении изменений в решение городского маслихата от 19 декабря 2014 года № 34/267 "О городском бюджете на 2015-2017 годы"
    kaz: Қалалық мәслихаттың 2014 жылғы 19 желтоқсандағы № 34/267 "2015-2017 жылдарға арналған қалалық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/96115/rus
