act_code: '185889'
requisite: Решение акима Дубовского сельского округа Абайского района Карагандинской области от 6 сентября 2023 года № 04
title:
  rus: О переименовании улиц в селе Дубовка Дубовского сельского округа Абайского района Карагандинской области
  kaz: Қарағанды облысы Абай ауданы Дубовка ауылдық округі Дубовка ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-09-06
approved_by:
- '160011015001'
version_date:
  kaz: 2023-09-06
  rus: 2023-09-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/185889/kaz/06.09.2023
  rus: https://zan.gov.kz/client/#!/doc/185889/rus/06.09.2023
