act_code: '207108'
requisite: Решение Осакаровского районного маслихата Карагандинской области от 13 февраля 2025 года № 30/293. Зарегистрировано Департаментом юстиции Карагандинской области 13 февраля 2025 года № 6713-09
title:
  rus: Об утверждении положения о награждении Почетной грамотой Осакаровского района
  kaz: Осакаров ауданының Құрмет грамотасымен наградтау туралы ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2025-02-13
approved_by:
- '160018000002'
version_date:
  kaz: 2025-02-13
  rus: 2025-02-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/207108/kaz/13.02.2025
  rus: https://zan.gov.kz/client/#!/doc/207108/rus/13.02.2025
