act_code: '51711'
requisite: Решение XXХI сессии IV созыва Карагандинского городского маслихата от 25 марта 2010 года № 320. Зарегистрировано Управлением юстиции города Караганды 14 апреля 2010 года № 8-1-111
title:
  rus: Об оказании единовременной материальной помощи отдельным категориям граждан к празднованию 65-годовщины Победы в Великой Отечественной войне
  kaz: Ұлы Отан соғысындағы Жеңістің 65 жылдығын мерекелеуге орай азаматтардың жекелеген санаттарына біржолғы материалдық көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-25
approved_by:
- '160002000002'
version_date:
  kaz: 2012-04-20
  rus: 2012-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/51711/kaz/20.04.2012
  rus: https://zan.gov.kz/client/#!/doc/51711/rus/20.04.2012
