act_code: '69477'
requisite: Решение 15 сессии Нуринского районного маслихата Карагандинской области от 14 декабря 2012 года № 149. Зарегистрировано Департаментом юстиции Карагандинской области 26 декабря 2012 года № 2062
title:
  rus: О районном бюджете на 2013-2015 годы
  kaz: 2013-2015 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-14
approved_by:
- '160012000002'
version_date:
  kaz: 2013-03-20
  rus: 2013-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/69477/kaz/20.03.2013
  rus: https://zan.gov.kz/client/#!/doc/69477/rus/20.03.2013
caused_by:
  code: '71903'
  requisite: Решение 17 сессии Нуринского районного маслихата Карагандинской области от 20 марта 2013 года № 165. Зарегистрировано Департаментом юстиции Карагандинской области 5 апреля 2013 года № 2280
  title:
    rus: О внесении изменений в решение 15 сессии Нуринского районного маслихата от 14 декабря 2012 года № 149 "О районном бюджете на 2013-2015 годы"
    kaz: Нұра аудандық мәслихатының 2012 жылғы 14 желтоқсандағы 15 сессиясының "2013-2015 жылдарға арналған аудандық бюджет туралы" № 149 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/71903/rus
