act_code: '76221'
requisite: Решение Сатпаевского городского маслихата Карагандинской области от 5 декабря 2013 года № 189. Зарегистрировано Департаментом юстиции Карагандинской области 26 декабря 2013 года № 2479. Утратило силу решением Сатпаевского городского маслихата Карагандинской области от 18 апреля 2018 года № 265
title:
  rus: Об утверждении проекта (схемы) зонирования земель для целей налогообложения с корректировкой базовых ставок земельного налога за исключением земель, выделенных (отведенных) под автостоянки (паркинги), автозаправочные станции и занятых под казино
  kaz: Автотұраққа (паркингке), автомобильге май құю станцияларына бөлінген (бөліп шығарылған) және казино орналасқан жерлерді қоспағанда, салық салу мақсаты үшін жер салығының базалық ставкасын түзетумен жерлерді өңірлерге бөлу жобасын (схемасын) бекіту туралы
form: РЕШ
type_codes:
- ПРОЕ
- РЕШ
- СХЕМ
approved_on: 2013-12-05
approved_by:
- '160007000002'
version_date:
  kaz: 2013-12-05
  rus: 2013-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/76221/kaz/05.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76221/rus/05.12.2013
