act_code: '32644'
requisite: Қарағанды облысы Жаңаарқа ауданы мәслихатының 2007 жылғы 4 сәуірдегі № 36/288 шешімі. Жаңаарқа ауданы әділет басқармасында 2007 жылғы 9 сәуірде № 8-12-29 тіркелді. Қолданылу мерзімінің аяқталуына байланысты шешімнің күші жойылды - Қарағанды облысы Жаңаарқа аудандық мәслихат аппараты хатшысының 2013 жылғы 1 қазандағы № 01-18/48 хатымен
title:
  rus: «2007 жылға арналған аудандық бюджет туралы» аудандық Мәслихаттың 2006 жылғы 22 желтоқсандағы № 32/265 шешіміне өзгертулер енгізу туралы
  kaz: «2007 жылға арналған аудандық бюджет туралы» аудандық Мәслихаттың 2006 жылғы 22 желтоқсандағы № 32/265 шешіміне өзгертулер енгізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-04-04
approved_by:
- '160016000002'
version_date:
  kaz: 2007-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/32644/kaz/04.04.2007
