act_code: '118041'
requisite: Решение ХVII сессии Приозерского городского маслихата Карагандинской области от 25 декабря 2017 года № 17/147. Зарегистрировано Департаментом юстиции Карагандинской области 11 января 2018 года № 4556
title:
  rus: О городском бюджете на 2018 - 2020 годы
  kaz: 2018 - 2020 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-25
approved_by:
- '160009000002'
version_date:
  kaz: 2018-11-29
  rus: 2018-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/118041/kaz/29.11.2018
  rus: https://zan.gov.kz/client/#!/doc/118041/rus/29.11.2018
caused_by:
  code: '126971'
  requisite: Решение XXV сессии Приозерского городского маслихата Карагандинской области от 29 ноября 2018 года № 25/245. Зарегистрировано Департаментом юстиции Карагандинской области 10 декабря 2018 года № 5043
  title:
    rus: О внесении изменений в решение Приозерского городского маслихата от 25 декабря 2017 года № 17/147 «О городском бюджете на 2018 - 2020 годы»
    kaz: Приозерск қалалық мәслихатының 2017 жылғы 25 желтоқсандағы № 17/147 «2018 - 2020 жылдарға арналған қалалық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/126971/rus
