act_code: '127872'
requisite: Решение Абайского районного маслихата Карагандинской области от 25 декабря 2018 года № 40/431. Зарегистрировано Департаментом юстиции Карагандинской области 29 декабря 2018 года № 5116
title:
  rus: О районном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-25
approved_by:
- '160011000002'
version_date:
  kaz: 2019-04-25
  rus: 2019-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/127872/kaz/25.04.2019
  rus: https://zan.gov.kz/client/#!/doc/127872/rus/25.04.2019
caused_by:
  code: '131105'
  requisite: Решение Абайского районного маслихата Карагандинской области от 25 апреля 2019 года № 47/508. Зарегистрировано Департаментом юстиции Карагандинской области 30 апреля 2019 года № 5304
  title:
    rus: О внесении изменений в решение 40 сессии Абайского районного маслихата от 25 декабря 2018 года № 40/431 «O районном бюджете на 2019-2021 годы»
    kaz: Абай аудандық мәслихаттың 2018 жылғы 25 желтоқсандағы 40 сессиясының № 40/431 «2019-2021 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131105/rus
