act_code: '193140'
requisite: Решение Осакаровского районного маслихата Карагандинской области от 5 февраля 2024 года № 16/153
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию на территории земель Осакаровского района на 2024-2025 годы
  kaz: Осакаров ауданының аймағы жерлеріндегі жайылымдарды басқару және оларды пайдалану бойынша 2024-2025 жылдарға арналған іс-шаралар Жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-05
approved_by:
- '160018000002'
version_date:
  kaz: 2024-02-05
  rus: 2024-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/193140/kaz/05.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193140/rus/05.02.2024
