act_code: '143619'
requisite: Решение акима Актогайского района Карагандинской области от 5 июня 2020 года № 01. Зарегистрировано Департаментом юстиции Карагандинской области 8 июня 2020 года № 5862. Утратило силу решением акима Актогайского района Карагандинской области от 22 января 2025 года № 1 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков в Актогайском районе
  kaz: Ақтоғай ауданында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-05
approved_by:
- '160014000003'
version_date:
  kaz: 2021-07-14
  rus: 2021-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/143619/kaz/14.07.2021
  rus: https://zan.gov.kz/client/#!/doc/143619/rus/14.07.2021
caused_by:
  code: '157033'
  requisite: Решение акима Актогайского района Карагандинской области от 14 июля 2021 года № 2. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 июля 2021 года № 23549. Утратило силу решением акима Актогайского района Карагандинской области от 22 января 2025 года № 1 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение акима Актогайского района от 5 июня 2020 года № 1 «Об образовании избирательных участков в Актогайском районе»
    kaz: Ақтоғай ауданы әкімінің 2020 жылғы 5 маусымдағы № 1 «Ақтоғай ауданында сайлау учаскелерін құру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157033/rus
