act_code: '52861'
requisite: Қарағанды облысы Ұлытау аудандық мәслихатының 2010 жылғы 21 сәуірдегі XXІ сессиясының № 225 шешімі. Қарағанды облысы Ұлытау ауданының Әділет басқармасында 2010 жылғы 28 мамырда № 8-16-59 тіркелді. Күші жойылды - Қарағанды облысы Ұлытау аудандық мәслихатының XXX сессиясының 2011 жылғы 16 қыркүйектегі № 360 шешімімен
title:
  rus: Ұлытау ауданының жекеленген санаттағы мұқтаж азаматтарға әлеуметтiк төлемдерді іске асыру жөніндегі Ережені бекіту туралы
  kaz: Ұлытау ауданының жекеленген санаттағы мұқтаж азаматтарға әлеуметтiк төлемдерді іске асыру жөніндегі Ережені бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-04-21
approved_by:
- '160019000002'
version_date:
  kaz: 2010-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/52861/kaz/21.04.2010
