act_code: '42770'
requisite: Решение Осакаровского районного маслихата Карагандинской области от 19 ноября 2008 года № 86. Зарегистрировано Управлением юстиции Осакаровского района Карагандинской области 18 декабря 2008 года № 8-15-94. Утратило силу решением Осакаровского районного маслихата Карагандинской области от 26 сентября 2024 года № 25/241 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении схемы зонирования земель, поправочные коэффициенты к базовым ставкам земельного налога для целей налогообложения Осакаровского района Карагандинской области Республики Казахстан
  kaz: Қазақстан Республикасы Қарағанды облысы Осакаров ауданының жерлерін салық салу мақсаттары үшін аймақтандыру сызбасын, жер салығының базалық мөлшерлемесіне түзету коэффициентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
- СХЕМ
approved_on: 2008-11-19
approved_by:
- '160018000002'
version_date:
  kaz: 2008-11-19
  rus: 2008-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/42770/kaz/19.11.2008
  rus: https://zan.gov.kz/client/#!/doc/42770/rus/19.11.2008
