act_code: '79993'
requisite: Решение Шетского районного маслихата Карагандинской области от 10 апреля 2014 года № 21/181. Зарегистрировано Департаментом юстиции Карагандинской области 16 мая 2014 года № 2645. Утратило силу решением Шетского районного маслихата Карагандинской области от 10 октября 2017 года № 16/126
title:
  rus: Об утверждении Регламента Шетского районного маслихата
  kaz: Шет аудандық мәслихатының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-04-10
approved_by:
- '160015000002'
version_date:
  kaz: 2015-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/79993/kaz/23.06.2015
caused_by:
  code: '91813'
  requisite: Решение Шетского районного маслихата Карагандинской области от 23 июня 2015 года № 30/267. Зарегистрировано Департаментом юстиции Карагандинской области 3 июля 2015 года № 3318
  title:
    rus: О внесении изменения в решение ХХІ сессии Шетского районного маслихата от 10 апреля 2014 года № 21/181 «Об утверждении Регламента Шетского районного маслихата»
    kaz: Шет аудандық мәслихатының  2014 жылғы 10 сәуірдегі ХХІ сессиясының «Шет аудандық  мәслихатының Регламентін бекіту туралы» № 21/181 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/91813/rus
