act_code: '128494'
requisite: Решение акима Абайского района Карагандинской области от 9 января 2019 года № 01. Зарегистрировано Департаментом юстиции Карагандинской области 15 января 2019 года № 5150
title:
  rus: О проведении приписки граждан мужского пола 2002 года рождения к призывному участку отдела по делам обороны Абайского района
  kaz: Абай ауданының қорғаныс істері жөніндегі бөлімінің шақыру учаскесіне 2002 жылы туған ер азаматтарды тіркеуді өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-09
approved_by:
- '160011000003'
version_date:
  kaz: 2019-01-09
  rus: 2019-01-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/128494/kaz/09.01.2019
  rus: https://zan.gov.kz/client/#!/doc/128494/rus/09.01.2019
