act_code: '179316'
requisite: Решение акима поселка Гулшат города Балхаш Карагандинской области от 27 марта 2023 года № 3
title:
  rus: Об установлении публичного сервитута на земельный участок для проведения операций по разведке твердых полезных ископаемых товариществу с ограниченной ответственностью «Balhash Mining»
  kaz: «Balhash Mining» жауапкершілігі шектеулі серіктестігіне пайдалы қатты қазбаларды барлау операцияларды жүзеге асыру үшін жер учаскеге жария сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-03-27
approved_by:
- '160008001001'
version_date:
  kaz: 2023-03-27
  rus: 2023-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/179316/kaz/27.03.2023
  rus: https://zan.gov.kz/client/#!/doc/179316/rus/27.03.2023
