act_code: '76438'
requisite: Решение ХXVI сессии Каражалского городского маслихата Карагандинской области от 26 декабря 2013 года № 190. Зарегистрировано Департаментом юстиции Карагандинской области 6 января 2014 года № 2489
title:
  rus: О бюджете города на 2014 - 2016 годы
  kaz: 2014 - 2016 жылдарға арналған қала бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-26
approved_by:
- '160010000002'
version_date:
  kaz: 2014-09-15
  rus: 2014-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/76438/kaz/15.09.2014
  rus: https://zan.gov.kz/client/#!/doc/76438/rus/15.09.2014
caused_by:
  code: '83225'
  requisite: Решение ХXXII сессии Каражалского городского маслихата Карагандинской области от 15 сентября 2014 года № 254. Зарегистрировано Департаментом юстиции Карагандинской области 19 сентября 2014 года № 2755
  title:
    rus: О внесении изменений в решение ХХVI сессии Каражалского городского маслихата от 26 декабря 2013 года № 190 "О бюджете города на 2014-2016 годы"
    kaz: Қаражал қалалық мәслихатының 2013 жылғы 26 желтоқсандағы ХХVI сессиясының № 190 "2014-2016 жылдарға арналған қала бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/83225/rus
