act_code: '2753'
requisite: Решение XXV сессии Карагандинского областного маслихата от 14 января 1999 года № 5. Зарегистрировано управлением юстиции Карагандинской области 27 апреля 1999 года за № 27
title:
  rus: Об областном бюджете на 1999 год
  kaz: 1999 жылға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-01-14
approved_by:
- '160000000002'
version_date:
  rus: 1999-07-21
source:
  rus: https://zan.gov.kz/client/#!/doc/2753/rus/21.07.1999
caused_by:
  code: '4084'
  requisite: Решение ХХVII сессии Карагандинского областного Маслихата от 22 июля 1999 года № 6 зарегистрировано управлением юстиции Карагандинской области 26.08.1999 г. за № 37
  title:
    rus: О внесении изменений и дополнений в решение XXVI сессии областного маслихата от 29.04.1999 г. № 9 "О внесении изменений и дополнений в решение XXV сессии областного маслихата от 14.01.99 г. "Об областном бюджете на 1999 год"
    kaz: Облыстық Мәслихаттың 29.04.1999 ж. XXYI сессиясының "Облыстық Мәслихаттың 14.01.1999 ж. XXY сессиясының "1999 жылға арналған облыстық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы" № 9 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/4084/rus
