act_code: '8675'
requisite: Решение IХ сессии Карагандинского областного Маслихата от 5 апреля 2001 года № 4. Зарегистрировано Управлением юстиции Карагандинской области 12 апреля 2001 года за № 252. Утратило силу решением Х сессии Карагандинского областного Маслихата от 11 декабря 2004 года № 157
title:
  rus: О Правилах предоставления малообеспеченным гражданам жилищных пособий на содержание жилья и оплату коммунальных услуг
  kaz: Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақыларды беру Ережелері туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2001-04-04
approved_by:
- '160000000002'
version_date:
  kaz: 2001-04-04
  rus: 2001-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/8675/kaz/04.04.2001
  rus: https://zan.gov.kz/client/#!/doc/8675/rus/04.04.2001
