act_code: '161810'
requisite: Решение Карагандинского областного маслихата от 9 декабря 2021 года № 122. Зарегистрировано в Министерстве юстиции Республики Казахстан 21 декабря 2021 года № 25867
title:
  rus: Об областном бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-09
approved_by:
- '160000000002'
version_date:
  kaz: 2022-04-15
  rus: 2022-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/161810/kaz/15.04.2022
  rus: https://zan.gov.kz/client/#!/doc/161810/rus/15.04.2022
caused_by:
  code: '166995'
  requisite: Решение Карагандинского областного маслихата от 15 апреля 2022 года № 179. Зарегистрировано в Министерстве юстиции Республики Казахстан 26 апреля 2022 года № 27758
  title:
    rus: О внесении изменений в решение Карагандинского областного маслихата от 9 декабря 2021 года № 122 «Об областном бюджете на 2022-2024 годы»
    kaz: Қарағанды облыстық мәслихатының 2021 жылғы 9 желтоқсандағы № 122 «2022-2024 жылдарға арналған облыстық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166995/rus
