act_code: '136131'
requisite: Решение акима Каркаралинского района Карагандинской области от 19 ноября 2019 года № 5. Зарегистрировано Департаментом юстиции Карагандинской области 20 ноября 2019 года № 5529
title:
  rus: О признании утратившим силу решения акима Каркаралинского района от 24 мая 2019 года № 3 «Об объявлении чрезвычайной ситуации»
  kaz: Қарқаралы ауданы әкімінің 2019 жылғы 24 мамырдағы № 3 «Төтенше жағдай жариялау туралы» шешімін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-11-19
approved_by:
- '160013000003'
version_date:
  kaz: 2019-11-19
  rus: 2019-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/136131/kaz/19.11.2019
  rus: https://zan.gov.kz/client/#!/doc/136131/rus/19.11.2019
