act_code: '218640'
requisite: Решение Карагандинского областного маслихата от 9 декабря 2025 года № 343
title:
  rus: Об областном бюджете на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-09
approved_by:
- '160000000002'
version_date:
  kaz: 2026-02-19
  rus: 2026-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/218640/kaz/19.02.2026
  rus: https://zan.gov.kz/client/#!/doc/218640/rus/19.02.2026
caused_by:
  code: '222439'
  requisite: Решение Карагандинского областного маслихата от 19 февраля 2026 года № 363
  title:
    rus: О внесении изменений в решение Карагандинского областного маслихата от 9 декабря 2025 года № 343 «Об областном бюджете на 2026-2028 годы»
    kaz: Қарағанды облыстық мәслихатының 2025 жылғы 9 желтоқсандағы № 343 «2026-2028 жылдарға арналған облыстық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/222439/rus
