act_code: '31274'
requisite: Решение Сатпаевского городского маслихата Карагандинской области от 14 декабря 2006 года № 384. Зарегистрировано управлением юстиции города Сатпаева 15 января 2007 года за № 8-6-41. Утратило силу решением Сатпаевского городского маслихата Карагандинской области от 11 июня 2010 года № 45
title:
  rus: Об утверждении Правил содержания и защиты зеленых насаждений в г. Сатпаев и прилегающих населенных пунктов
  kaz: Сәтбаев қаласындағы және оның маңындағы елді мекендердің жасыл желектерін күтіп ұстау және қорғау қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2006-12-14
approved_by:
- '160007000002'
version_date:
  kaz: 2006-12-14
  rus: 2006-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/31274/kaz/14.12.2006
  rus: https://zan.gov.kz/client/#!/doc/31274/rus/14.12.2006
