act_code: '168722'
requisite: Решение Осакаровского районного маслихата Карагандинской области от 10 июня 2022 года № 242. Утратило силу решением Осакаровского районного маслихата Карагандинской области от 28 февраля 2024 года № 17/159 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей поселка Осакаровка Осакаровского района Карагандинской области для участия в сходе местного сообщества
  kaz: Қарағанды облысы Осакаров ауданы Осакаровка кентінің жергілікті қоғамдастық жиындарына қатысу үшін жергілікті қоғамдастықтың бөлек жиындарын өткізу тәртібі және кент тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2022-06-10
approved_by:
- '160018000002'
version_date:
  kaz: 2022-06-10
  rus: 2022-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/168722/kaz/10.06.2022
  rus: https://zan.gov.kz/client/#!/doc/168722/rus/10.06.2022
