act_code: '41627'
requisite: Постановление акимата Абайского района Карагандинской области от 4 сентября 2008 года № 25/14. Зарегистрировано Управлением юстиции Абайского района Карагандинской области 26 сентября 2008 года № 8-9-46. Утратило силу - постановлением акимата Абайского района Карагандинской области от 5 мая 2009 года № 12/05
title:
  rus: О проведении очередного призыва на срочную воинскую службу в 2008 году
  kaz: 2008 жылда кезекті жедел әскери қызметке шакыруды өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-09-04
approved_by:
- '160011000001'
version_date:
  kaz: 2008-09-04
  rus: 2008-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/41627/kaz/04.09.2008
  rus: https://zan.gov.kz/client/#!/doc/41627/rus/04.09.2008
