act_code: '34082'
requisite: Решение Балхашского городского маслихата Карагандинской области от 27 июня 2007 года № 44/429. Зарегистрировано управлением юстиции города Балхаша Карагандинской области 17 июля 2007 года № 8-4-78. Утратило силу решением Балхашского городского маслихата Карагандинской области от 1 декабря 2010 года № 37/285
title:
  rus: Об утверждении Правил содержания и выпаса сельскохозяйственных животных в городе Балхаш и прилегающих поселках
  kaz: Балқаш қаласы және маңындағы кенттердегі ауыл шаруашылық жануарларын ұстау, бағу Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-06-27
approved_by:
- '160008000002'
version_date:
  kaz: 2007-06-27
  rus: 2007-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/34082/kaz/27.06.2007
  rus: https://zan.gov.kz/client/#!/doc/34082/rus/27.06.2007
