act_code: '219668'
requisite: Решение Бухар-Жырауского районного маслихата Карагандинской области от 18 декабря 2025 года № 39/06
title:
  rus: О бюджетах сел, поселков и сельских округов района на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған ауданның ауылдары, кенттері, ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-18
approved_by:
- '160017000002'
version_date:
  kaz: 2025-12-18
  rus: 2025-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/219668/kaz/18.12.2025
  rus: https://zan.gov.kz/client/#!/doc/219668/rus/18.12.2025
