act_code: '137778'
requisite: Решение Темиртауского городского маслихата Карагандинской области от 27 декабря 2019 года № 49/4. Зарегистрировано Департаментом юстиции Карагандинской области 31 декабря 2019 года № 5630
title:
  rus: О бюджете поселка Актау на 2020-2022 годы
  kaz: Ақтау кентінің 2020-2022 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '160005000002'
version_date:
  kaz: 2019-12-27
  rus: 2019-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/137778/kaz/27.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137778/rus/27.12.2019
