act_code: '202933'
requisite: Решение акима города Караганды от 14 ноября 2024 года № 04. Утратило силу решением акима города Караганды от 3 февраля 2025 года № 01 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба
  kaz: Жергілікті ауқымдағы табиғи сипаттағы төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-14
approved_by:
- '160002000003'
version_date:
  kaz: 2024-11-14
  rus: 2024-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/202933/kaz/14.11.2024
  rus: https://zan.gov.kz/client/#!/doc/202933/rus/14.11.2024
