act_code: '141058'
requisite: Решение акима Курминского сельского округа Абайского района Карагандинской области от 4 марта 2020 года № 1. Зарегистрировано Департаментом юстиции Карагандинской области 12 марта 2020 года № 5745
title:
  rus: О переименовании улиц в селе Курминское, Курминского сельского округа
  kaz: Курмин ауылдық округі Құрма ауылындағы көшелерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-03-04
approved_by:
- '160011009001'
version_date:
  kaz: 2020-03-04
  rus: 2020-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/141058/kaz/04.03.2020
  rus: https://zan.gov.kz/client/#!/doc/141058/rus/04.03.2020
