act_code: '11643'
requisite: Решение XVII сессии Бухар-Жырауского районного маслихата Карагандинской области от 16 января 2002 года № 11. Зарегистрировано Департаментом юстиции Карагандинской области 18 февраля 2002 года № 641. Утратило силу решением 39 сессии Бухар-Жырауского районного маслихата Карагандинской области от 21 июня 2007 года № 8
title:
  rus: О Регламенте районного Маслихата
  kaz: Аудандық Мәслихаттың Регламенті туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2002-01-16
approved_by:
- '160017000002'
version_date:
  kaz: 2006-03-20
  rus: 2006-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/11643/kaz/20.03.2006
  rus: https://zan.gov.kz/client/#!/doc/11643/rus/20.03.2006
caused_by:
  code: '26803'
  requisite: Постановление акимата Денисовского района Костанайской области от 23 января 2006 года № 15. Зарегистрировано Управлением юстиции Денисовского района Костанайской области 16 февраля 2006 года № 9-8-33
  title:
    rus: О внесении изменения в постановление акимата от 7 ноября 2005 года № 298 «Об утверждении Правил проведения проверок соблюдения лицензионного законодательства и оформления их результатов»
    kaz: Әкімдіктің 2005 жылғы 7 қарашадағы № 298 «Лицензиялық заңдарын сақтау бойынша тексерулер жүргізу және олардың қорытындыларын ресімдеу Қағидаларын бекіту туралы» қаулысына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/26803/rus
