act_code: '6726'
requisite: Решение IV сессии Карагандинского областного маслихата от 22 июня 2000 года № 4. Зарегистрировано управлением юстиции Карагандинской области 3 июля 2000 года за № 106. Утратило силу в связи с истечением срока действия письмом Карагандинского областного маслихата от 17 января 2005 года № 1-12/40
title:
  rus: Об информации "О ходе выполнения в области Постановления Правительства РК № 839 от 04.09.98 г. "О неотложных мерах защиты населения от туберкулеза в Республике Казахстан"
  kaz: Облыста ҚР Үкiметiнiң 04.09.98 ж. № 839 "Қазақстан Республикасында халықты туберкулезден қорғаудың кезек күттiрмес шаралары туралы" қаулысын орындау барысы туралы" ақпарат туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-06-21
approved_by:
- '160000000002'
version_date:
  kaz: 2000-06-21
  rus: 2000-06-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/6726/kaz/21.06.2000
  rus: https://zan.gov.kz/client/#!/doc/6726/rus/21.06.2000
