act_code: '117713'
requisite: Решение XXII сессии Жанааркинского районного маслихата Карагандинской области от 27 декабря 2017 года № 22/170. Зарегистрировано Департаментом юстиции Карагандинской области 5 января 2018 года № 4537
title:
  rus: О бюджете поселка и сельских округов на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған кент және ауылдық округтердің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-27
approved_by:
- '160016000002'
version_date:
  kaz: 2018-09-25
  rus: 2018-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/117713/kaz/25.09.2018
  rus: https://zan.gov.kz/client/#!/doc/117713/rus/25.09.2018
caused_by:
  code: '125233'
  requisite: Решение XXXIII сессии Жанааркинского районного маслихата Карагандинской области от 25 сентября 2018 года № 33/238. Зарегистрировано Департаментом юстиции Карагандинской области 10 октября 2018 года № 4969
  title:
    rus: О внесении изменений в решение Жанааркинского районного маслихата от 27 декабря 2017 года № 22/170 «О бюджете поселка и сельских округов на 2018-2020 годы»
    kaz: Жаңаарқа аудандық мәслихатының 2017 жылғы 27 желтоқсандағы № 22/170 «2018-2020 жылдарға арналған кент және ауылдық округтердің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/125233/rus
