act_code: '228380'
requisite: Решение Приозерского городского маслихата Карагандинской области от 29 июля 2026 года № 43/325
title:
  rus: Об утверждении размера и перечня категорий получателей жилищных сертификатов по городу Приозерск
  kaz: Приозерск қаласы бойынша тұрғын үй сертификаттарының мөлшері мен алушылар санаттарының тізбесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-07-29
approved_by:
- '160009000002'
version_date:
  kaz: 2026-07-29
  rus: 2026-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/228380/kaz/29.07.2026
  rus: https://zan.gov.kz/client/#!/doc/228380/rus/29.07.2026
