act_code: '197865'
requisite: Решение Шахтинского городского маслихата Карагандинской области от 14 июня 2024 года № 341/11. Зарегистрировано в Департаменте юстиции Карагандинской области 19 июня 2024 года № 6611-09
title:
  rus: Об определении размера и правил оказания жилищной помощи в городе Шахтинске и прилегающих поселках Долинка, Новодолинский, Шахан
  kaz: Шахтинск қаласында және іргелес Долинка, Новодолинский, Шахан кенттерінде тұрғын үй көмегін көрсетудің мөлшері мен қағидаларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-06-14
approved_by:
- '160004000002'
version_date:
  kaz: 2024-06-14
  rus: 2024-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/197865/kaz/14.06.2024
  rus: https://zan.gov.kz/client/#!/doc/197865/rus/14.06.2024
