act_code: '164139'
requisite: Решение Осакаровского районного маслихата Карагандинской области от 24 января 2022 года № 179. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 января 2022 года № 26672
title:
  rus: Об утверждении Правил и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Осакаровского района
  kaz: Осакаров ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету Қағидасын және мөлшерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2022-01-24
approved_by:
- '160018000002'
version_date:
  kaz: 2022-01-24
  rus: 2022-01-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/164139/kaz/24.01.2022
  rus: https://zan.gov.kz/client/#!/doc/164139/rus/24.01.2022
