act_code: '54510'
requisite: Қарағанды облысы Жаңаарқа ауданының Атасу кенті әкімінің 2010 жылғы 7 қыркүйектегі № 3 шешімі. Қарағанды облысы Жаңаарқа ауданының Әділет басқармасында 2010 жылғы 13 қыркүйекте № 8-12-81 тіркелді
title:
  rus: Атасу кентіндегі Қазақстанның 40 жылдығы көшесіне Ақселеу Сланұлы Сейдімбековтың атын беру туралы
  kaz: Атасу кентіндегі Қазақстанның 40 жылдығы көшесіне Ақселеу Сланұлы Сейдімбековтың атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-07
approved_by:
- '160016014001'
version_date:
  kaz: 2010-09-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/54510/kaz/07.09.2010
