act_code: '117519'
requisite: Решение XXI сессии Жанааркинского районного маслихата Карагандинской области от 22 декабря 2017 года № 21/159. Зарегистрировано Департаментом юстиции Карагандинской области 3 января 2018 года № 4529
title:
  rus: О районном бюджете на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-22
approved_by:
- '160016000002'
version_date:
  kaz: 2018-03-20
  rus: 2018-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/117519/kaz/20.03.2018
  rus: https://zan.gov.kz/client/#!/doc/117519/rus/20.03.2018
caused_by:
  code: '120394'
  requisite: Решение XXV сессии Жанааркинского районного маслихата Карагандинской области от 20 марта 2018 года № 25/185. Зарегистрировано Департаментом юстиции Карагандинской области 9 апреля 2018 года № 4680
  title:
    rus: О внесении изменений и дополнений в решение Жанааркинского районного маслихата от 22 декабря 2017 года № 21/159 «О районном бюджете на 2018 - 2020 годы»
    kaz: Жаңаарқа аудандық мәслихатының 2017 жылғы 22 желтоқсандағы № 21/159 «2018 - 2020 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/120394/rus
