act_code: '97859'
requisite: Решение Балхашского городского маслихата Карагандинской области от 23 декабря 2015 года № 46/352. Зарегистрировано Департаментом юстиции Карагандинской области 11 января 2016 года № 3610
title:
  rus: О городском бюджете на 2016-2018 годы
  kaz: 2016-2018  жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '160008000002'
version_date:
  kaz: 2016-12-15
  rus: 2016-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/97859/kaz/15.12.2016
  rus: https://zan.gov.kz/client/#!/doc/97859/rus/15.12.2016
caused_by:
  code: '108517'
  requisite: Решение Балхашского городского маслихата Карагандинской области от 15 декабря 2016 года № 6/61. Зарегистрировано Департаментом юстиции Карагандинской области 20 декабря 2016 года № 4056
  title:
    rus: О внесении изменений и дополнения в решение городского маслихата от 23 декабря 2015 года № 46/352 «О городском бюджете на 2016-2018 годы»
    kaz: Қалалық мәслихаттың 2015 жылғы 23 желтоқсандағы № 46/352 «2016-2018 жылдарға арналған қалалық бюджет туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/108517/rus
