act_code: '97859'
requisite: Решение Балхашского городского маслихата Карагандинской области от 23 декабря 2015 года № 46/352. Зарегистрировано Департаментом юстиции Карагандинской области 11 января 2016 года № 3610
title:
  rus: О городском бюджете на 2016-2018 годы
  kaz: 2016-2018  жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '160008000002'
version_date:
  kaz: 2016-10-18
  rus: 2016-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/97859/kaz/18.10.2016
  rus: https://zan.gov.kz/client/#!/doc/97859/rus/18.10.2016
caused_by:
  code: '107490'
  requisite: Решение Балхашского городского маслихата Карагандинской области от 18 октября 2016 года № 5/58. Зарегистрировано Департаментом юстиции Карагандинской области 27 октября 2016 года № 4018
  title:
    rus: О внесении изменений и дополнений в решение городского маслихата от 23 декабря 2015 года № 46/352 «О городском бюджете на 2016-2018 годы»
    kaz: Қалалық мәслихаттың 2015 жылғы 23 желтоқсандағы № 46/352 «2016-2018 жылдарға арналған қалалық бюджет туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/107490/rus
