act_code: '64175'
requisite: Решение 2 сессии Нуринского районного маслихата Карагандинской области от 16 февраля 2012 года № 22. Зарегистрировано Управлением юстиции Нуринского района Карагандинской области 20 марта 2012 года № 8-14-170. Утратило силу решением Нуринского районного маслихата Карагандинской области от 26 июня 2024 года № 98 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил предоставления жилищной помощи населению Нуринского района
  kaz: Нұра ауданының тұрғындарына тұрғын үй көмегін көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2012-02-16
approved_by:
- '160012000002'
version_date:
  kaz: 2014-09-12
  rus: 2014-09-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/64175/kaz/12.09.2014
  rus: https://zan.gov.kz/client/#!/doc/64175/rus/12.09.2014
caused_by:
  code: '83535'
  requisite: Решение 30 сессии Нуринского районного маслихата Карагандинской области от 12 сентября 2014 года № 326. Зарегистрировано Департаментом юстиции Карагандинской области 6 октября 2014 года № 2790. Утратило силу решением Нуринского районного маслихата Карагандинской области от 26 июня 2024 года № 98 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение 2 сессии Нуринского районного маслихата от 16 февраля 2012 года № 22 "Об утверждении Правил предоставления жилищной помощи населению Нуринского района"
    kaz: Нұра аудандық мәслихатының 2 сессиясының 2012 жылғы 16 ақпандағы № 22 "Нұра ауданының тұрғындарына тұрғын үй көмегін көрсету Ережесін бекіту туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/83535/rus
