act_code: '51605'
requisite: Қарағанды облысы Ақтоғай ауданы Қызыларай селолық округі әкімінің 2010 жылғы 25 ақпандағы № 1 шешімі. Қарағанды облысы Ақтоғай ауданының Әділет басқармасында 2010 жылғы 6 сәуірде № 8-10-108 тіркелді
title:
  rus: Қызыларай селолық округінің орталығы Ақжарық аулындағы көшелерін қайта атау туралы
  kaz: Қызыларай селолық округінің орталығы Ақжарық аулындағы көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-25
approved_by:
- '160014006001'
version_date:
  kaz: 2010-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/51605/kaz/25.02.2010
