act_code: '36806'
requisite: Қарағанды облысы Ұлытау аудандық мәслихатының IV сессиясының 2007 жылғы 24 желтоқсандағы № 43 шешімі. Қарағанды облысы Ұлытау ауданы әділет басқармасында 2007 жылғы 26 желтоқсанда № 8-16-27 тіркелді
title:
  rus: 2008 жылға арналған аудандық бюджет туралы
  kaz: 2008 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-24
approved_by:
- '160019000002'
version_date:
  kaz: 2007-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/36806/kaz/24.12.2007
