act_code: '107082'
requisite: Решение IV сессии Карагандинского областного маслихата от 29 сентября 2016 года № 87. Зарегистрировано Департаментом юстиции Карагандинской области 18 октября 2016 года № 3996. Утратило силу решением Карагандинского областного маслихата от 11 июня 2020 года № 542 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении Правил выдачи служебного удостоверения государственного учреждения «Аппарат Карагандинского областного маслихата» и его описания
  kaz: «Қарағанды облыстық мәслихатының аппараты» мемлекеттік мекемесінің қызметтік куәлікті беру қағидаларын және оның сипаттамасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-09-29
approved_by:
- '160000000002'
version_date:
  kaz: 2016-09-29
  rus: 2016-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/107082/kaz/29.09.2016
  rus: https://zan.gov.kz/client/#!/doc/107082/rus/29.09.2016
