act_code: '36355'
requisite: Решение 5 сессии Нуринского районного маслихата Карагандинской области от 25 декабря 2007 года № 81. Зарегистрировано управлением юстиции Нуринского района 27 декабря 2007 года № 8-14-64
title:
  rus: Об установлении ставок акциза на объекты игорного бизнеса
  kaz: Ойын бизнесі объектілеріне акциздік ставкалар белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-25
approved_by:
- '160012000002'
version_date:
  kaz: 2007-12-25
  rus: 2007-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/36355/kaz/25.12.2007
  rus: https://zan.gov.kz/client/#!/doc/36355/rus/25.12.2007
