act_code: '145087'
requisite: Решение Шахтинского городского маслихата Карагандинской области от 20 июля 2020 года № 1742/40. Зарегистрировано Департаментом юстиции Карагандинской области 24 июля 2020 года № 5966
title:
  rus: О специализированных местах для организации и проведения мирных собраний и границах, прилегающих территорий, в которых запрещено проведение пикетирования на территории города Шахтинска
  kaz: Шахтинск қаласының аумағында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындар және пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекаралары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-07-20
approved_by:
- '160004000002'
version_date:
  kaz: 2020-07-20
  rus: 2020-07-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/145087/kaz/20.07.2020
  rus: https://zan.gov.kz/client/#!/doc/145087/rus/20.07.2020
