act_code: '30190'
requisite: Решение Шахтинского городского маслихата Карагандинской области от 10 октября 2006 года № 240/27. Зарегистрировано Управлением юстиции города Шахтинска Карагандинской области 3 ноября 2006 года за № 8-8-28. Утратило силу - решением XXI сессии IV созыва Шахтинского городского маслихата Карагандинской области от 9 июля 2010 года № 581/21
title:
  rus: Об утверждении Правил предоставления гражданам жилищных пособий на содержание жилья, коммунальных услуг и компенсацию повышения тарифов абонентской платы за оказание услуг телекоммуникаций
  kaz: Азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақыларды беру және телекоммуникация қызметтерін көрсеткені үшін абоненттік ақы тарифтерінің арттырылуына өтемақы берудің Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2006-10-10
approved_by:
- '160004000002'
version_date:
  kaz: 2009-07-03
  rus: 2009-07-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/30190/kaz/03.07.2009
  rus: https://zan.gov.kz/client/#!/doc/30190/rus/03.07.2009
caused_by:
  code: '47206'
  requisite: Решение Шахтинского городского маслихата Карагандинской области от 3 июля 2009 года № 488/13. Зарегистрировано Управлением юстиции города Шахтинск Карагандинской области 7 августа 2009 года № 8-8-71. Утратило силу - решением XXI сессии IV созыва Шахтинского городского маслихата Карагандинской области от 9 июля 2010 года № 581/21
  title:
    rus: О внесении изменений в решение XXVII сессии городского Маслихата от 10 октября 2006 года № 240/27 "Об утверждении Правил предоставления гражданам жилищных пособий на содержание жилья, коммунальных услуг и компенсацию повышения тарифов абонентской платы за телефон абонентам городских сетей телекоммуникаций"
    kaz: Шахтинск қалалық Мәслихатының 2006 жылғы 10 қазандағы ХХVІІ сессиясының "Азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақыларды беру және қалалық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы берудің Ережесін бекіту туралы" N 240/27 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/47206/rus
