act_code: '20074'
requisite: Қарағанды облысы Шахтинск қалалық мәслихатының VII сессиясының 2004 жылғы 22 мамырдағы № 40/7 шешімі. Қарағанды облысының Әділет Департаментінде 2004 жылғы 28 мамырда № 1526 тіркелді
title:
  rus: Қалалық Мәслихаттың 2001 жылғы 17 тамыздағы XIV сессиясының № 134/14 шешімімен бекітілген қалалық Мәслихаттың Регламентіне нормативтік-құқықтық актілер реестріндегі тіркелу нөмірі - 425, қосымшалар енгізу туралы
  kaz: Қалалық Мәслихаттың 2001 жылғы 17 тамыздағы XIV сессиясының № 134/14 шешімімен бекітілген қалалық Мәслихаттың Регламентіне нормативтік-құқықтық актілер реестріндегі тіркелу нөмірі - 425, қосымшалар енгізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-05-21
approved_by:
- '160004000002'
version_date:
  kaz: 2004-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/20074/kaz/21.05.2004
