act_code: '43110'
requisite: Қарағанды облысы Жаңаарқа ауданы әкімінің 2008 жылғы 11 желтоқсандағы № 01 шешімі. Қарағанды облысы Жаңаарқа ауданы Әділет басқармасында 2008 жылғы 30 желтоқсанда № 8-12-48 тіркелді. Күші жойылды - Қарағанды облысы Жаңаарқа ауданы әкімінің 2009 жылғы 30 желтоқсандағы № 1 шешімімен
title:
  rus: Жаңаарка ауданы аумағында тұратын 1992 жылы туған азаматтарды 2009 жылғы әскерге шақыру учаскесіне тіркеу туралы
  kaz: Жаңаарка ауданы аумағында тұратын 1992 жылы туған азаматтарды 2009 жылғы әскерге шақыру учаскесіне тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-11
approved_by:
- '160016000003'
version_date:
  kaz: 2008-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/43110/kaz/11.12.2008
