act_code: '50846'
requisite: Қарағанды облысы Ақтоғай ауданы Нүркен селолық округі әкімінің 2010 жылғы 19 ақпандағы № 1 шешімі. Қарағанды облысы Ақтоғай ауданының Әділет басқармасында 2010 жылғы 25 ақпанда № 8-10-103 тіркелді
title:
  rus: Нүркен селолық округінің Ақсеңгір елді мекеніне Жантөбетұлы Машақтың атын беру туралы
  kaz: Нүркен селолық округінің Ақсеңгір елді мекеніне Жантөбетұлы Машақтың атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-19
approved_by:
- '160014009001'
version_date:
  kaz: 2010-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/50846/kaz/19.02.2010
