act_code: '13584'
requisite: Решение ХXI сессии Карагандинского областного Маслихата от 31 октября 2002 года № 4-3/21. Зарегистрировано Управлением юстиции Карагандинской области 11 ноября 2002 года за № 997. Утратило силу в связи с истечением срока действия письмом Карагандинского областного Маслихата от 17 января 2005 года № 1-12/40
title:
  rus: О ставках платежей за загрязнение окружающей среды на 2003 год
  kaz: 2003 жылға қоршаған ортаны ластағаны үшін төлем туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-10-31
approved_by:
- '160000000002'
version_date:
  kaz: 2002-10-31
  rus: 2002-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/13584/kaz/31.10.2002
  rus: https://zan.gov.kz/client/#!/doc/13584/rus/31.10.2002
