act_code: '133893'
requisite: Решение Карагандинского областного маслихата от 8 августа 2019 года № 438. Зарегистрировано Департаментом юстиции Карагандинской области 12 августа 2019 года № 5429
title:
  rus: Об утверждении Правил погребения и организации дела по уходу за могилами в Карагандинской области
  kaz: Қарағанды облысында жерлеудің және зираттарды күтіп-ұстау ісін ұйымдастырудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-08-08
approved_by:
- '160000000002'
version_date:
  kaz: 2022-03-17
  rus: 2022-03-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/133893/kaz/17.03.2022
  rus: https://zan.gov.kz/client/#!/doc/133893/rus/17.03.2022
caused_by:
  code: '166072'
  requisite: Решение Карагандинского областного маслихата от 17 марта 2022 года № 155
  title:
    rus: О внесении изменения в решение Карагандинского областного маслихата от 8 августа 2019 года № 438 «Об утверждении Правил погребения и организации дела по уходу за могилами в Карагандинской области»
    kaz: Қарағанды облыстық мәслихатының 2019 жылғы 8 тамыздағы «Қарағанды облысында жерлеудің және зираттарды күтіп-ұстау ісін ұйымдастырудың қағидаларын бекіту туралы» № 438 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166072/rus
