act_code: '139878'
requisite: Решение акима Ынталинского сельского округа Каркаралинского района Карагандинской области от 14 февраля 2020 года № 05. Зарегистрировано Департаментом юстиции Карагандинской области 21 февраля 2020 года № 5706
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-02-14
approved_by:
- '160013023002'
version_date:
  kaz: 2020-02-14
  rus: 2020-02-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/139878/kaz/14.02.2020
  rus: https://zan.gov.kz/client/#!/doc/139878/rus/14.02.2020
