act_code: '42987'
requisite: Решение 10 сессии Абайского районного маслихата Карагандинской области от 25 декабря 2008 года № 10/115. Зарегистрировано Управлением юстиции Абайского района Карагандинской области 29 декабря 2008 года № 8-9-50
title:
  rus: О районном бюджете на 2009 год
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-25
approved_by:
- '160011000002'
version_date:
  kaz: 2009-04-23
  rus: 2009-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/42987/kaz/23.04.2009
  rus: https://zan.gov.kz/client/#!/doc/42987/rus/23.04.2009
caused_by:
  code: '45526'
  requisite: Решение 13 сессии Абайского районного маслихата Карагандинской области от 23 апреля 2009 года № 13/163. Зарегистрировано Управлением юстиции Абайского района Карагандинской области 29 апреля 2009 года № 8-9-58
  title:
    rus: О внесении изменений и дополнений в решение 10 очередной сессии Абайского районного маслихата от 25 декабря 2008 года № 10/115 "О районном бюджете на 2009 год"
    kaz: Абай аудандық мәслихатының 2008 жылғы 25 желтоқсандағы 10 кезекті сессиясының "2009 жылға арналған аудандық бюджет туралы" № 10/115 шешіміне өзгертулер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/45526/rus
