act_code: '41885'
requisite: Қарағанды облысы Шет аудандық мәслихатының 2008 жылғы 30 қыркүйектегі № 8/113 шешімі. Қарағанды облысы Шет ауданы Әділет басқармасында 2008 жылғы 16 қазанда № 8-17-63 тіркелді
title:
  rus: Шет ауданында тұратын денсаулық сақтау, әлеуметтік қамтамасыз ету, білім беру, мәдениет және спорт мемлекеттік мекемелері мамандарына отын сатып алуға әлеуметтік көмек көрсету Қағида туралы
  kaz: Шет ауданында тұратын денсаулық сақтау, әлеуметтік қамтамасыз ету, білім беру, мәдениет және спорт мемлекеттік мекемелері мамандарына отын сатып алуға әлеуметтік көмек көрсету Қағида туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2008-09-30
approved_by:
- '160015000002'
version_date:
  kaz: 2008-09-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/41885/kaz/30.09.2008
