act_code: '205541'
requisite: Решение Шетского районного маслихата Карагандинской области от 24 декабря 2024 года № 19/168
title:
  rus: Об утверждении бюджетов на 2025-2027 годы сельских округов и поселков Шетского района
  kaz: Шет ауданының ауылдық округтерінің және кенттерінің 2025-2027 жылдарға арналған бюджеттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-24
approved_by:
- '160015000002'
version_date:
  kaz: 2025-09-23
  rus: 2025-09-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/205541/kaz/23.09.2025
  rus: https://zan.gov.kz/client/#!/doc/205541/rus/23.09.2025
caused_by:
  code: '214921'
  requisite: Решение Шетского районного маслихата Карагандинской области от 23 сентября 2025 года № 26/231
  title:
    rus: О внесении изменений в решение Шетского районного маслихата от 24 декабря 2024 года № 19/168 «Об утверждении бюджетов на 2025-2027 годы сельских округов и поселков Шетского района»
    kaz: Шет аудандық мәслихатының 2024 жылғы 24 желтоқсандағы «Шет ауданының ауылдық округтерінің және кенттерінің 2025-2027 жылдарға арналған бюджеттерін бекіту туралы» № 19/168 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214921/rus
