act_code: '35907'
requisite: Қарағанды облысы Шет аудандық мәслихатының 2007 жылғы 23 қазандағы № 2/24 шешімі. Қарағанды облысы Шет ауданы әділет басқармасында 2007 жылғы 23 қарашада № 8-17-51 тіркелді
title:
  rus: Шет ауданы аумағында үй иттері мен мысықтарды ұстау Ережесі туралы
  kaz: Шет ауданы аумағында үй иттері мен мысықтарды ұстау Ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-10-23
approved_by:
- '160015000002'
version_date:
  kaz: 2007-10-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/35907/kaz/23.10.2007
