act_code: '29595'
requisite: Решение Абайского районного маслихата Карагандинской области от 8 августа 2006 года № 34/335. Зарегистрировано Управлением юстиции Абайского района Карагандинской области 7 сентября 2006 года за № 8-9-22. Утратило силу - решением 23 сессии Абайского районного маслихата Карагандинской области от 17 июня 2010 года № 23/278
title:
  rus: Об утверждении Правил предоставления малообеспеченным гражданам жилищных пособий на содержание жилья, оплату коммунальных услуг и компенсацию повышения тарифов абонентской платы за телефон абонентам городских сетей телекоммуникаций
  kaz: Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақыларын беру және қалалық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы берудің Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2006-08-08
approved_by:
- '160011000002'
version_date:
  kaz: 2006-08-08
  rus: 2006-08-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/29595/kaz/08.08.2006
  rus: https://zan.gov.kz/client/#!/doc/29595/rus/08.08.2006
