act_code: '187746'
requisite: Решение акима Ростовского сельского округа Бухар-Жырауского района Карагандинской области от 30 октября 2023 года № 7
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-10-30
approved_by:
- '160017022002'
version_date:
  kaz: 2023-12-07
  rus: 2023-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/187746/kaz/07.12.2023
  rus: https://zan.gov.kz/client/#!/doc/187746/rus/07.12.2023
caused_by:
  code: '189664'
  requisite: Решение акима Ростовского сельского округа Бухар-Жырауского района Карагандинской области от 7 декабря 2023 года № 8
  title:
    rus: О внесении изменений в Решение акима Ростовского сельского округа за № 7 от 30 октября 2023 года «Об установлении публичного сервитута»
    kaz: «Қауымдық сервитут белгілеу туралы» Ростов ауылдық округі әкімінің 2023 жылғы 30 қазан № 7 шешіміне өзгертулер еңгізу туралы
  link: https://zan.gov.kz/client/#!/doc/189664/rus
