act_code: '129354'
requisite: Решение Осакаровского районного маслихата Карагандинской области от 13 февраля 2019 года № 599. Зарегистрировано Департаментом юстиции Карагандинской области 22 февраля 2019 года № 5198. Утратило силу решением Осакаровского районного маслихата Карагандинской области от 24 января 2022 года № 180 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения по Осакаровскому району
  kaz: Осакаров ауданы бойынша пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-02-13
approved_by:
- '160018000002'
version_date:
  kaz: 2019-02-13
  rus: 2019-02-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/129354/kaz/13.02.2019
  rus: https://zan.gov.kz/client/#!/doc/129354/rus/13.02.2019
