act_code: '79258'
requisite: Решение ХXVIII сессии Каражалского городского маслихата Карагандинской области от 31 марта 2014 года № 220. Зарегистрировано Департаментом юстиции Карагандинской области 28 апреля 2014 года № 2622. Утратило силу решением Каражалского городского маслихата области Ұлытау от 18 августа 2022 года № 154 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении правил проведения раздельных сходов местного сообщества на территории поселка Шалгинск
  kaz: Шалғы кентінің аумағында бөлек жергілікті қоғамдастық жиындарын өткізу қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-03-31
approved_by:
- '160010000002'
version_date:
  kaz: 2016-12-23
  rus: 2016-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/79258/kaz/23.12.2016
  rus: https://zan.gov.kz/client/#!/doc/79258/rus/23.12.2016
caused_by:
  code: '109500'
  requisite: Решение VIII сессии Каражалского городского маслихата Карагандинской области от 23 декабря 2016 года № 74. Зарегистрировано Департаментом юстиции Карагандинской области 23 января 2017 года № 4129. Утратило силу решением Каражалского городского маслихата области Ұлытау от 18 августа 2022 года № 154 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение XXVIII сессии Каражалского городского маслихата от 31 марта 2014 года № 220 «Об утверждении правил проведения раздельных сходов местного сообщества на территории посёлка Шалгинск»
    kaz: Қаражал қалалық мәслихатының 2014 жылғы 31 наурыздағы ХХVIII сессиясының № 220 «Шалғы кентінің аумағында бөлек жергілікті қоғамдастық жиындарын өткізу қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/109500/rus
