act_code: '163247'
requisite: Решение Жанааркинского районного маслихата Карагандинской области от 21 декабря 2021 года № 15/91. Зарегистрировано в Министерстве юстиции Республики Казахстан 23 декабря 2021 года № 25927
title:
  rus: О районном бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-21
approved_by:
- '160016000002'
version_date:
  kaz: 2022-03-18
  rus: 2022-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/163247/kaz/18.03.2022
  rus: https://zan.gov.kz/client/#!/doc/163247/rus/18.03.2022
caused_by:
  code: '165648'
  requisite: Решение Жанааркинского районного маслихата Карагандинской области от 18 марта 2022 года № 18/111
  title:
    rus: О внесении изменений в решение Жанааркинского районного маслихата от 21 декабря 2021 года № 15/91 «О районном бюджете на 2022-2024 годы»
    kaz: Жаңаарқа аудандық мәслихатының 2021 жылғы 21 желтоқсандағы № 15/91 «2022-2024 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165648/rus
