act_code: '78863'
requisite: Решение Сатпаевского городского маслихата Карагандинской области от 31 марта 2014 года № 224. Зарегистрировано Департаментом юстиции Карагандинской области 14 апреля 2014 года № 2586. Утратило силу решением Сатпаевского городского маслихата Карагандинской области от 26 февраля 2015 года № 318
title:
  rus: О льготном проезде на общественном транспорте (кроме такси) учащихся очной формы обучения
  kaz: Күндізгі оқу нысанындағы оқушылардың қоғамдық көлікте (таксиден басқа) жеңілдікпен жол жүруі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-31
approved_by:
- '160007000002'
version_date:
  kaz: 2014-03-31
  rus: 2014-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/78863/kaz/31.03.2014
  rus: https://zan.gov.kz/client/#!/doc/78863/rus/31.03.2014
