act_code: '143666'
requisite: Решение акима Коксунского сельского округа Абайского района Карагандинской области от 8 июня 2020 года № 3. Зарегистрировано Департаментом юстиции Карагандинской области 9 июня 2020 года № 5865
title:
  rus: Об установлении публичного сервитута на земельные участки для проведения геологоразведочных работ товариществом с ограниченной ответственностью «Корпорация Казахмыс»
  kaz: «Қазақмыс корпорациясы» жауапкершілігі шектеулі серіктестігінің геологиялық барлау жұмыстарын жүргізу үшін жер учаскелеріне қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-08
approved_by:
- '160011006001'
version_date:
  kaz: 2020-06-08
  rus: 2020-06-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/143666/kaz/08.06.2020
  rus: https://zan.gov.kz/client/#!/doc/143666/rus/08.06.2020
