act_code: '204681'
requisite: Решение Нуринского районного маслихата Карагандинской области от 24 декабря 2024 года № 130
title:
  rus: О районном бюджете на 2025-2027 годы
  kaz: 2025–2027 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-24
approved_by:
- '160012000002'
version_date:
  kaz: 2025-03-27
  rus: 2025-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/204681/kaz/27.03.2025
  rus: https://zan.gov.kz/client/#!/doc/204681/rus/27.03.2025
caused_by:
  code: '208494'
  requisite: Решение Нуринского районного маслихата Карагандинской области от 27 марта 2025 года № 137
  title:
    rus: О внесении изменений в решение Нуринского районного маслихата от 24 декабря 2024 года № 130 «О районном бюджете на 2025-2027 годы»
    kaz: Нұра аудандық мәслихатының 2024 жылғы 24 желтоқсандағы № 130 «2025 – 2027 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/208494/rus
