act_code: '204681'
requisite: Решение Нуринского районного маслихата Карагандинской области от 24 декабря 2024 года № 130
title:
  rus: О районном бюджете на 2025-2027 годы
  kaz: 2025–2027 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-24
approved_by:
- '160012000002'
version_date:
  kaz: 2025-07-11
  rus: 2025-07-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/204681/kaz/11.07.2025
  rus: https://zan.gov.kz/client/#!/doc/204681/rus/11.07.2025
caused_by:
  code: '212275'
  requisite: Решение Нуринского районного маслихата Карагандинской области от 11 июля 2025 года № 169
  title:
    rus: О внесении изменений в решение Нуринского районного маслихата от 24 декабря 2024 года № 130 «О районном бюджете на 2025-2027 годы»
    kaz: Нұра аудандық мәслихатының 2024 жылғы 24 желтоқсандағы № 130 «2025–2027 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212275/rus
