act_code: '56721'
requisite: Решение Жезказганского городского маслихата Карагандинской области от 23 декабря 2010 года № 28/332. Зарегистрировано Управлением юстиции города Жезказган Карагандинской области 13 января 2011 года № 8-2-133
title:
  rus: Об установлении стоимости разового талона за право реализации товаров на рынках территории города Жезказгана на 2011 год
  kaz: 2011 жылға арналған Жезқазған қаласы аумағында базарларда тауарларды сату құқығына берілетін бір жолғы талонның құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '160006000002'
version_date:
  kaz: 2010-12-23
  rus: 2010-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/56721/kaz/23.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56721/rus/23.12.2010
