act_code: '56652'
requisite: Решение Балхашского городского маслихата Карагандинской области от 1 декабря 2010 года № 37/286. Зарегистрировано Управлением юстиции города Балхаш Карагандинской области 10 января 2011 года № 8-4-209. Утратило силу - решением Балхашского городского маслихата Карагандинской области от 12 июня 2012 года № 5/43
title:
  rus: Об утверждении Правил содержания собак и кошек в городе Балхаш
  kaz: Балқаш қаласында иттер мен мысықтарды ұстау Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-12-01
approved_by:
- '160008000002'
version_date:
  kaz: 2011-08-22
  rus: 2011-08-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/56652/kaz/22.08.2011
  rus: https://zan.gov.kz/client/#!/doc/56652/rus/22.08.2011
caused_by:
  code: '60598'
  requisite: Решение Балхашского городского маслихата Карагандинской области от 22 августа 2011 года № 49/379. Зарегистрировано Управлением юстиции города Балхаш Карагандинской области 26 сентября 2011 года № 8-4-242. Утратило силу - решением Балхашского городского маслихата Карагандинской области от 12 июня 2012 года № 5/43
  title:
    rus: О внесении изменений и дополнения в решение городского маслихата от 1 декабря 2010 года № 37/286 "Об утверждении Правил содержания собак и кошек в городе Балхаш"
    kaz: Қалалық мәслихаттың 2010 жылғы 1 желтоқсандағы "Балқаш қаласында иттер мен мысықтарды ұстау Ережесін бекіту туралы" № 37/286 шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/60598/rus
