act_code: '107523'
requisite: Решение V сессии Улытауского районного маслихата Карагандинской области от 12 октября 2016 года № 49. Зарегистрировано Департаментом юстиции Карагандинской области 26 октября 2016 года № 4014. Утратило силу решением Сатпаевского городского маслихата области Ұлытау от 28 февраля 2024 года № 106 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Улытаускому району
  kaz: Ұлытау ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-10-12
approved_by:
- '160019000002'
version_date:
  kaz: 2021-11-25
  rus: 2021-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/107523/kaz/25.11.2021
  rus: https://zan.gov.kz/client/#!/doc/107523/rus/25.11.2021
caused_by:
  code: '162272'
  requisite: Решение Улытауского районного маслихата Карагандинской области от 25 ноября 2021 года № 86. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26094. Утратило силу решением Сатпаевского городского маслихата области Ұлытау от 28 февраля 2024 года № 106 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Улытауского районного маслихата от 12 октября 2016 года № 49 "Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Улытаускому району"
    kaz: Ұлытау аудандық мәслихатының 2016 жылғы 12 қазандағы № 49 «Ұлытау ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/162272/rus
