act_code: '127875'
requisite: Решение Шахтинского городского маслихата Карагандинской области от 26 декабря 2018 года № 1576/28. Зарегистрировано Департаментом юстиции Карагандинской области 28 декабря 2018 года № 5102
title:
  rus: О городском бюджете на 2019 - 2021 годы
  kaz: 2019 - 2021 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-26
approved_by:
- '160004000002'
version_date:
  kaz: 2019-12-20
  rus: 2019-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/127875/kaz/20.12.2019
  rus: https://zan.gov.kz/client/#!/doc/127875/rus/20.12.2019
caused_by:
  code: '137378'
  requisite: Решение Шахтинского городского маслихата Карагандинской области от 20 декабря 2019 года № 1667/36. Зарегистрировано Департаментом юстиции Карагандинской области 25 декабря 2019 года № 5607
  title:
    rus: О внесении изменений в решение XXVIII сессии Шахтинского городского маслихата от 26 декабря 2018 года № 1576/28 «О городском бюджете на 2019 - 2021 годы»
    kaz: Шахтинск қалалық мәслихатының 2018 жылғы 26 желтоқсандағы XХVIII сессиясының № 1576/28 «2019-2021 жылдарға арналған қалалық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137378/rus
