act_code: '145179'
requisite: Решение Жезказганского городского маслихата Карагандинской области от 22 июля 2020 года № 49/424. Зарегистрировано Департаментом юстиции Карагандинской области 28 июля 2020 года № 5981
title:
  rus: Об утверждении Правил оказания социальной поддержки и установления размера по оплате коммунальных услуг и приобретению топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах города Жезказган
  kaz: Жезқазған қаласының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына коммуналдық қызметтерді төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету және мөлшерін белгілеу қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-07-22
approved_by:
- '160006000002'
version_date:
  kaz: 2020-07-22
  rus: 2020-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/145179/kaz/22.07.2020
  rus: https://zan.gov.kz/client/#!/doc/145179/rus/22.07.2020
