act_code: '122308'
requisite: Решение акима села Шахтерское Нуринского района Карагандинской области от 24 мая 2018 года № 1. Зарегистрировано Департаментом юстиции Карагандинской области 4 июня 2018 года № 4801
title:
  rus: О переименовании улиц
  kaz: Көшелерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-24
approved_by:
- '160012025002'
version_date:
  kaz: 2018-05-24
  rus: 2018-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/122308/kaz/24.05.2018
  rus: https://zan.gov.kz/client/#!/doc/122308/rus/24.05.2018
