act_code: '179606'
requisite: Решение Шахтинского городского маслихата Карагандинской области от 7 апреля 2023 года № 236/2. Зарегистрировано Департаментом юстиции Карагандинской области 11 апреля 2023 года № 6377-09
title:
  rus: О предоставлении льготного проезда на общественном транспорте (кроме такси) учащихся очной формы обучения
  kaz: Күндізгі оқу нысанындағы оқушыларға қоғамдық көлікте (таксиден басқа) жеңілдікпен жол жүруді ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-04-07
approved_by:
- '160004000002'
version_date:
  kaz: 2023-04-07
  rus: 2023-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/179606/kaz/07.04.2023
  rus: https://zan.gov.kz/client/#!/doc/179606/rus/07.04.2023
