act_code: '78271'
requisite: Решение 21 сессии Бухар-Жырауского районного маслихата Карагандинской области от 28 февраля 2014 года № 4. Зарегистрировано Департаментом юстиции Карагандинской области 27 марта 2014 года № 2571. Утратило силу решением Бухар-Жырауского районного маслихата Карагандинской области от 7 февраля 2024 года № 5 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Бухар-Жырауского района
  kaz: Бұқар жырау ауданының Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-02-28
approved_by:
- '160017000002'
version_date:
  kaz: 2020-12-20
  rus: 2020-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/78271/kaz/20.12.2020
  rus: https://zan.gov.kz/client/#!/doc/78271/rus/20.12.2020
caused_by:
  code: '150922'
  requisite: Решение Бухар-Жырауского районного маслихата Карагандинской области от 20 декабря 2020 года № 5. Зарегистрировано Департаментом юстиции Карагандинской области 30 декабря 2020 года № 6135. Утратило силу решением Бухар-Жырауского районного маслихата Карагандинской области от 7 февраля 2024 года № 5 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении дополнений в решение 21 сессии Бухар-Жырауского районного маслихата от 28 февраля 2014 года № 4 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Бухар-Жырауского района»
    kaz: Бұқар жырау аудандық мәслихатының 21 сессиясының 2014 жылғы 28 ақпандағы № 4 «Бұқар жырау ауданының Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/150922/rus
