act_code: '203901'
requisite: Решение акима поселка Осакаровка Осакаровского района Карагандинской области от 6 декабря 2024 года № 11
title:
  rus: Об установлении публичного сервитута на земельные участки для строительства и обслуживания кабельной линии 10 кВ ТОО «GCD Partner»
  kaz: '"GCD Partner" ЖШС жер учаскелеріндегі 10 кВ кабельдік желісін салу және қызмет көрсету үшін қоғамдық сервитутты орнату туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-06
approved_by:
- '160018001001'
version_date:
  kaz: 2024-12-06
  rus: 2024-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/203901/kaz/06.12.2024
  rus: https://zan.gov.kz/client/#!/doc/203901/rus/06.12.2024
