act_code: '51531'
requisite: Қарағанды облысы Жаңаарқа ауданы мәслихатының 2010 жылғы 24 ақпандағы № 22/195 шешімі. Қарағанды облысы Жаңаарқа ауданының Әділет басқармасында 2010 жылғы 1 сәуірде № 8-12-69 тіркелді. Күші жойылды - Қарағанды облысы Жаңаарқа аудандық мәслихатының XXXIV сессиясының 2011 жылғы 29 наурыздағы № 34/297 шешімімен
title:
  rus: Ауылдық елді мекендерге жұмыс істеу және тұру үшін келген мамандарға көтермелі жәрдемақы және тұрғын үй сатып алу үшін әлеуметтік қолдауды ұсыну туралы
  kaz: Ауылдық елді мекендерге жұмыс істеу және тұру үшін келген мамандарға көтермелі жәрдемақы және тұрғын үй сатып алу үшін әлеуметтік қолдауды ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-24
approved_by:
- '160016000002'
version_date:
  kaz: 2010-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/51531/kaz/24.02.2010
