act_code: '39579'
requisite: Решение 6 сессии Нуринского районного маслихата Карагандинской области от 28 марта 2008 года № 97. Зарегистрировано управлением юстиции Нуринского района Карагандинской области 13 мая 2008 года № 8-14-71. Утратило силу решением 12 сессии Нуринского районного маслихата Карагандинской области от 24 декабря 2008 года № 154
title:
  rus: Об установлении ставок на зарегистрированные объекты фиксированного суммарного налога
  kaz: Бір салық салу объектісінен алынатын тіркелген жиынтық салық ставкаларының мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-03-28
approved_by:
- '160012000002'
version_date:
  kaz: 2008-03-28
  rus: 2008-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/39579/kaz/28.03.2008
  rus: https://zan.gov.kz/client/#!/doc/39579/rus/28.03.2008
