act_code: '153850'
requisite: Решение акима Жанааркинского района Карагандинской области от 26 марта 2021 года № 1. Зарегистрировано Департаментом юстиции Карагандинской области 29 марта 2021 года № 6263
title:
  rus: Об объявлении чрезвычайной ситуации природного характера
  kaz: Табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-26
approved_by:
- '160016000003'
version_date:
  kaz: 2021-03-26
  rus: 2021-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/153850/kaz/26.03.2021
  rus: https://zan.gov.kz/client/#!/doc/153850/rus/26.03.2021
