act_code: '30828'
requisite: Решение XXIХ сессии Каражалского городского маслихата Карагандинской области от 20 декабря 2006 года № 29/290. Зарегистрировано управлением юстиции города Каражал 26 декабря 2006 года за № 8-5-29. Утратило силу в связи с истечением срока применения (письмо Каражалского городского маслихата Карагандинской области от 28 июня 2013 года № 1-24/167)
title:
  rus: О бюджете города на 2007 год
  kaz: 2007 жылға арналған қала бюджетi туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-20
approved_by:
- '160010000002'
version_date:
  kaz: 2006-12-20
  rus: 2006-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/30828/kaz/20.12.2006
  rus: https://zan.gov.kz/client/#!/doc/30828/rus/20.12.2006
