act_code: '102948'
requisite: Решение акима города Темиртау Карагандинской области от 18 мая 2015 года № 4
title:
  rus: О признании утратившим силу решения акима города Темиртау от 13 апреля 2015 года № 3 «Об объявлении чрезвычайной ситуации природного характера»
  kaz: Теміртау қаласы әкімінің 2015 жылғы 13 сәуірдегі № 3 «Табиғи сипаттағы төтенше жағдайды жариялау туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-05-18
approved_by:
- '160005000001'
version_date:
  kaz: 2015-05-18
  rus: 2015-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/102948/kaz/18.05.2015
  rus: https://zan.gov.kz/client/#!/doc/102948/rus/18.05.2015
