act_code: '113274'
requisite: Решение IХ сессии Карагандинского областного маслихата от 29 июня 2017 года № 200. Зарегистрировано Департаментом юстиции Карагандинской области 4 июля 2017 года № 4295. Утратило силу решением Карагандинского областного маслихата от 25 февраля 2021 года № 34 (вводится в действие со дня его официального опубликования)
title:
  rus: О предоставлении специализированных лечебных продуктов, медицинских изделий, лекарственного средства дополнительно
  kaz: Мамандандырылған емдеу өнімдерін, медициналық бұйымдарды, дәрілік заттарды қосымша беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-06-29
approved_by:
- '160000000002'
version_date:
  kaz: 2020-07-02
  rus: 2020-07-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/113274/kaz/02.07.2020
  rus: https://zan.gov.kz/client/#!/doc/113274/rus/02.07.2020
caused_by:
  code: '144434'
  requisite: Решение Карагандинского областного маслихата от 2 июля 2020 года № 553. Зарегистрировано Департаментом юстиции Карагандинской области 7 июля 2020 года № 5929. Утратило силу решением Карагандинского областного маслихата от 25 февраля 2021 года № 34 (вводится в действие со дня его официального опубликования)
  title:
    rus: О внесении изменений в некоторые решения Карагандинского областного маслихата и признании утратившими силу некоторых решений Карагандинского областного маслихата
    kaz: Қарағанды облыстық мәслихатының кейбір шешімдеріне өзгерістер енгізу және Қарағанды облыстық мәслихатының кейбір шешімдерінің күші жойылды деп тану туралы
  link: https://zan.gov.kz/client/#!/doc/144434/rus
