act_code: '34560'
requisite: Решение 37 сессии Саранского городского маслихата Карагандинской области от 11 июля 2007 года N 603-1. Зарегистрировано управлением юстиции города Сарани Карагандинской области 6 августа 2007 года за N 8-7-48. Утратило силу решением Саранского городского маслихата Карагандинской области от 23 июня 2016 года № 40
title:
  rus: О дополнительном регламентировании порядка проведения мирных собраний, митингов, шествий, пикетов и демонстраций
  kaz: Бейбіт жиналыстар, митингілер, шерулер, пикеттер және демонстрациялар ұйымдастыру мен өткізу тәртібі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-07-11
approved_by:
- '160003000002'
version_date:
  kaz: 2007-07-11
  rus: 2007-07-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/34560/kaz/11.07.2007
  rus: https://zan.gov.kz/client/#!/doc/34560/rus/11.07.2007
