act_code: '109154'
requisite: Решение VI сессии Карагандинского областного маслихата от 12 декабря 2016 года № 140. Зарегистрировано Департаментом юстиции Карагандинской области 10 января 2017 года № 4106
title:
  rus: Об утверждении границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки в городах Балхаш, Приозерск, Шахтинск Карагандинской области
  kaz: Қарағанды облысының Балқаш, Приозерск, Шахтинск қалаларында бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-12
approved_by:
- '160000000002'
version_date:
  kaz: 2023-06-22
  rus: 2023-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/109154/kaz/22.06.2023
  rus: https://zan.gov.kz/client/#!/doc/109154/rus/22.06.2023
caused_by:
  code: '183219'
  requisite: Решение Карагандинского областного маслихата от 22 июня 2023 года № 57. Зарегистрировано в Департаменте юстиции Карагандинской области 23 июня 2023 года № 6439-09
  title:
    rus: О внесении изменений в решение Карагандинского областного маслихата от 12 декабря 2016 года № 140 «Об утверждении границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки в городах Балхаш, Жезказган, Приозерск, Сатпаев, Шахтинск Карагандинской области»
    kaz: Қарағанды облыстық мәслихатының 2016 жылғы 12 желтоқсандағы № 140 «Қарағанды облысының Балқаш, Жезқазған, Приозерск, Сәтбаев, Шахтинск қалаларында бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183219/rus
