act_code: '171036'
requisite: Решение акима поселка Южный Абайского района Карагандинской области от 22 августа 2022 года № 9. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 августа 2022 года № 29319
title:
  rus: О переименовании улиц поселка Южный Абайского района Карагандинской области
  kaz: Қарағанды облысы Абай ауданы Южный кентінің көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-08-22
approved_by:
- '160011002001'
version_date:
  kaz: 2022-08-22
  rus: 2022-08-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/171036/kaz/22.08.2022
  rus: https://zan.gov.kz/client/#!/doc/171036/rus/22.08.2022
