act_code: '128094'
requisite: Решение Карагандинского областного маслихата от 10 января 2019 года № 376. Зарегистрировано Департаментом юстиции Карагандинской области 23 января 2019 года № 5161. Утратило силу решением Карагандинского областного маслихата от 30 января 2025 года № 254 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении целевых показателей качества окружающей среды Карагандинской области
  kaz: Қарағанды облысының қоршаған орта сапасының нысаналы көрсеткіштерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-10
approved_by:
- '160000000002'
version_date:
  kaz: 2019-01-10
  rus: 2019-01-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/128094/kaz/10.01.2019
  rus: https://zan.gov.kz/client/#!/doc/128094/rus/10.01.2019
