act_code: '90420'
requisite: Решение Жезказганского городского маслихата Карагандинской области от 28 апреля 2015 года № 33/302. Зарегистрировано Департаментом юстиции Карагандинской области 26 мая 2015 года № 3219. Утратило силу решением Жезказганского городского маслихата Карагандинской области от 11 мая 2016 года № 2/24
title:
  rus: Об утверждении Методики ежегодной оценки деятельности административных государственных служащих корпуса «Б» в государственном  учреждении «Аппарат Жезказганского городского маслихата»
  kaz: «Жезқазған қалалық мәслихатының аппараты» мемлекеттік мекемесінде «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2015-04-28
approved_by:
- '160006000002'
version_date:
  kaz: 2015-04-28
  rus: 2015-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/90420/kaz/28.04.2015
  rus: https://zan.gov.kz/client/#!/doc/90420/rus/28.04.2015
