act_code: '36351'
requisite: Қарағанды облысы Нұра аудандық мәслихатының 5 сессиясының 2007 жылғы 25 желтоқсандағы № 80 шешімі. Қарағанды облысы Нұра ауданы әділет басқармасында 2007 жылғы 27 желтоқсанда № 8-14-60 тіркелді
title:
  rus: Ауданның Киевка, Шұбаркөл кенттері елді мекен жерлерінен тысқары орңаласқан жер аумақтарын аймақтарға бөлу жобасын бекіту туралы
  kaz: Ауданның Киевка, Шұбаркөл кенттері елді мекен жерлерінен тысқары орңаласқан жер аумақтарын аймақтарға бөлу жобасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-25
approved_by:
- '160012000002'
version_date:
  kaz: 2007-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/36351/kaz/25.12.2007
