act_code: '79788'
requisite: Решение XХVI сессии V созыва Шахтинского городского маслихата Карагандинской области от 14 апреля 2014 года № 1024/26. Зарегистрировано Департаментом юстиции Карагандинской области 11 мая 2014 года № 2634. Утратило силу решением Шахтинского городского маслихата Карагандинской области от 9 апреля 2015 года № 1115/33
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-04-14
approved_by:
- '160004000002'
version_date:
  kaz: 2014-04-14
  rus: 2014-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/79788/kaz/14.04.2014
  rus: https://zan.gov.kz/client/#!/doc/79788/rus/14.04.2014
