act_code: '53821'
requisite: Решение XXХIV сессии IV созыва Карагандинского городского маслихата от 16 июня 2010 года № 366. Зарегистрировано Управлением юстиции города Караганды 5 августа 2010 года № 8-1-116. Утратило силу - решением Карагандинского городского маслихата от 23 мая 2012 года № 52
title:
  rus: Об утверждении Правил благоустройства города Караганды
  kaz: Қарағанды қаласын көріктендіру Ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-06-16
approved_by:
- '160002000002'
version_date:
  kaz: 2010-06-16
  rus: 2010-06-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/53821/kaz/16.06.2010
  rus: https://zan.gov.kz/client/#!/doc/53821/rus/16.06.2010
