act_code: '127596'
requisite: Решение Темиртауского городского маслихата Карагандинской области от 24 декабря 2018 года № 34/4. Зарегистрировано Департаментом юстиции Карагандинской области 27 декабря 2018 года № 5097
title:
  rus: О городском бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-24
approved_by:
- '160005000002'
version_date:
  kaz: 2019-09-02
  rus: 2019-09-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/127596/kaz/02.09.2019
  rus: https://zan.gov.kz/client/#!/doc/127596/rus/02.09.2019
caused_by:
  code: '134641'
  requisite: Решение Темиртауского городского маслихата Карагандинской области от 2 сентября 2019 года № 43/4. Зарегистрировано Департаментом юстиции Карагандинской области 13 сентября 2019 года № 5473
  title:
    rus: О внесении изменений в решение 34 сессии Темиртауского городского маслихата от 24 декабря 2018 года № 34/4 «О городском бюджете на 2019-2021 годы»
    kaz: Теміртау қалалық мәслихатының 2018 жылғы 24 желтоқсандағы 34 сессиясының № 34/4 «2019-2021 жылдарға арналған қалалық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134641/rus
