act_code: '62249'
requisite: Решение акима города Балхаш Карагандинской области от 14 декабря 2011 года № 13. Зарегистрировано Управлением юстиции города Балхаш Карагандинской области 26 декабря 2011 года № 8-4-260
title:
  rus: Об организации и проведении приписки граждан на воинский учет к призывному участку в январе-марте 2012 года
  kaz: 2012 жылғы қаңтар-наурызында әскерге шақыру учаскесіне азаматтарды тіркеуді ұйымдастыру және өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-14
approved_by:
- '160008000001'
version_date:
  kaz: 2014-01-31
  rus: 2014-01-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/62249/kaz/31.01.2014
  rus: https://zan.gov.kz/client/#!/doc/62249/rus/31.01.2014
