act_code: '61458'
requisite: Решение акима Нуринского района Карагандинской области от 18 ноября 2011 года № 9. Зарегистрировано Управлением юстиции Нуринского района Карагандинской области 18 ноября 2011 года № 8-14-152. Утратило силу решением акима Нуринского района Карагандинской области от 27 января 2015 года № 1
title:
  rus: Об образовании избирательных участков по Нуринскому району Карагандинской области
  kaz: Қарағанды облысы Нұра ауданы бойынша сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-18
approved_by:
- '160012000001'
version_date:
  kaz: 2011-11-18
  rus: 2011-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/61458/kaz/18.11.2011
  rus: https://zan.gov.kz/client/#!/doc/61458/rus/18.11.2011
