act_code: '150917'
requisite: Решение Балхашского городского маслихата Карагандинской области от 23 декабря 2020 года № 44/353. Зарегистрировано Департаментом юстиции Карагандинской области 30 декабря 2020 года № 6133
title:
  rus: О городском бюджете на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-23
approved_by:
- '160008000002'
version_date:
  kaz: 2021-04-26
  rus: 2021-04-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/150917/kaz/26.04.2021
  rus: https://zan.gov.kz/client/#!/doc/150917/rus/26.04.2021
caused_by:
  code: '155496'
  requisite: Решение Балхашского городского маслихата Карагандинской области от 26 апреля 2021 года № 4/30. Зарегистрировано Департаментом юстиции Карагандинской области 30 апреля 2021 года № 6324
  title:
    rus: О внесении изменений и дополнений в решение городского маслихата от 23 декабря 2020 года № 44/353 «О городском бюджете на 2021-2023 годы»
    kaz: Қалалық мәслихаттың 2020 жылғы 23 желтоқсандағы № 44/353 «2021-2023 жылдарға арналған қалалық бюджет туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/155496/rus
