act_code: '95824'
requisite: Решение 50 сессии Осакаровского районного маслихата Карагандинской области от 16 октября 2015 года № 540. Зарегистрировано Департаментом юстиции Карагандинской области 17 ноября 2015 года № 3502. Утратило силу решением Осакаровского районного маслихата Карагандинской области от 14 декабря 2018 года № 542 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении категорий автостоянок (паркингов) и увеличении базовой ставки налога на земли, выделенные под автостоянки (паркинги) Осакаровского района
  kaz: Осакаров ауданы бойынша автотұрақтардың (паркингтердің) санаттарын белгілеу және автотұрақтар (паркингтер) үшін бөлінген жерлерге салынатын салықтардың базалық ставкаларын ұлғайту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-16
approved_by:
- '160018000002'
version_date:
  kaz: 2015-10-16
  rus: 2015-10-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/95824/kaz/16.10.2015
  rus: https://zan.gov.kz/client/#!/doc/95824/rus/16.10.2015
