act_code: '125251'
requisite: Решение XXXIII сессии Жанааркинского районного маслихата Карагандинской области от 25 сентября 2018 года № 33/236. Зарегистрировано Департаментом юстиции Карагандинской области 15 октября 2018 года № 4974. Утратило силу решением Жанааркинского районного маслихата области Ұлытау от 22 сентября 2023 года № 7/46 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламента собрания местного сообщества по Жанааркинскому району
  kaz: Жаңаарқа ауданы бойынша жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-09-25
approved_by:
- '160016000002'
version_date:
  kaz: 2021-11-17
  rus: 2021-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/125251/kaz/17.11.2021
  rus: https://zan.gov.kz/client/#!/doc/125251/rus/17.11.2021
caused_by:
  code: '160607'
  requisite: Решение Жанааркинского районного маслихата Карагандинской области от 17 ноября 2021 года № 14/87. Утратило силу решением Жанааркинского районного маслихата области Ұлытау от 22 сентября 2023 года № 7/45 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнений в решение Жанааркинского районного маслихата от 25 сентября 2018 года № 33/236 «Об утверждении регламента собрания местного сообщества по Жанааркинскому району»
    kaz: Жаңаарқа аудандық мәслихатының 2018 жылғы 25 қыркүйектегі № 33/236 «Жаңаарқа ауданы бойынша жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/160607/rus
