act_code: '183833'
requisite: Решение акима сельского округа имени Ныгмета Нурмакова Каркаралинского района Карагандинской области от 12 июля 2023 года № 3
title:
  rus: О переименовании улиц села Осибай сельского округа имени Ныгмета Нурмакова Каркаралинского района
  kaz: Қарқаралы ауданы Нығмет Нұрмақов атындағы ауылдық округінің Өсібай ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-07-12
approved_by:
- '160013016002'
version_date:
  kaz: 2023-07-12
  rus: 2023-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/183833/kaz/12.07.2023
  rus: https://zan.gov.kz/client/#!/doc/183833/rus/12.07.2023
