act_code: '42975'
requisite: Қарағанды облысы Ұлытау аудандық мәслихатының IX сессиясының 2008 жылғы 25 желтоқсандағы № 111 шешімі. Қарағанды облысы Ұлытау ауданы Әділет басқармасында 2008 жылғы 29 желтоқсанда № 8-16-37 тіркелді
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-25
approved_by:
- '160019000002'
version_date:
  kaz: 2009-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/42975/kaz/30.11.2009
caused_by:
  code: '49257'
  requisite: Қарағанды облысы Ұлытау аудандық мәслихатының XV сессиясының 2009 жылғы 30 қарашадағы № 172 шешімі. Қарағанды облысы Ұлытау ауданының Әділет басқармасында 2009 жылғы 15 желтоқсанда № 8-16-50 тіркелді
  title:
    rus: Ұлытау аудандық мәслихатының 2008 жылғы 25 желтоқсандағы ІХ сессиясының "2009 жылға арналған аудандық бюджет туралы" № 111 шешіміне өзгерістер енгізу туралы
    kaz: Ұлытау аудандық мәслихатының 2008 жылғы 25 желтоқсандағы ІХ сессиясының "2009 жылға арналған аудандық бюджет туралы" № 111 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/49257/rus
