act_code: '42975'
requisite: Қарағанды облысы Ұлытау аудандық мәслихатының IX сессиясының 2008 жылғы 25 желтоқсандағы № 111 шешімі. Қарағанды облысы Ұлытау ауданы Әділет басқармасында 2008 жылғы 29 желтоқсанда № 8-16-37 тіркелді
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-25
approved_by:
- '160019000002'
version_date:
  kaz: 2009-09-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/42975/kaz/11.09.2009
caused_by:
  code: '48057'
  requisite: Қарағанды облысы Ұлытау аудандық мәслихатының XIV сессиясының 2009 жылғы 11 қыркүйектегі № 167 шешімі. Қарағанды облысы Ұлытау ауданы Әділет басқармасында 2009 жылғы 7 қазанда № 8-16-48 тіркелді
  title:
    rus: Ұлытау аудандық мәслихатының 2008 жылғы 25 желтоқсандағы ІХ сессиясының "2009 жылға арналған аудандық бюджет туралы" № 111 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Ұлытау аудандық мәслихатының 2008 жылғы 25 желтоқсандағы ІХ сессиясының "2009 жылға арналған аудандық бюджет туралы" № 111 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/48057/rus
