act_code: '55895'
requisite: Қарағанды облысы Ақтоғай ауданы Жидебай селолық округі әкімінің 2010 жылғы 17 қарашадағы № 1 шешімі. Қарағанды облысы Ақтоғай ауданының Әділет басқармасында 2010 жылғы 14 желтоқсанда № 8-10-124 тіркелді
title:
  rus: Жидебай селолық округіндегі көшелерін қайта атау туралы
  kaz: Жидебай селолық округіндегі көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-17
approved_by:
- '160014003001'
version_date:
  kaz: 2010-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/55895/kaz/17.11.2010
