act_code: '30875'
requisite: Қарағанды облысы Жаңаарқа аудандық мәслихатының 2006 жылғы 22 желтоқсандағы № 32/265 шешімі. Қарағанды облысы Жаңаарқа ауданы әділет басқармасында 2006 жылғы 28 желтоқсанда № 8-12-26 тіркелді. Қолданылу мерзімінің аяқталуына байланысты шешімнің күші жойылды - Қарағанды облысы Жаңаарқа аудандық мәслихат аппараты хатшысының 2013 жылғы 1 қазандағы № 01-18/48 хатымен
title:
  rus: 2007 жылға арналған аудандық бюджет туралы
  kaz: 2007 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-22
approved_by:
- '160016000002'
version_date:
  kaz: 2006-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/30875/kaz/22.12.2006
