act_code: '138458'
requisite: Решение Жанааркинского районного маслихата Карагандинской области от 31 декабря 2019 года № 49/337. Зарегистрировано Департаментом юстиции Карагандинской области 9 января 2020 года № 5672
title:
  rus: О бюджете поселков и сельских округов на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған кенттер және ауылдық округтердің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-31
approved_by:
- '160016000002'
version_date:
  kaz: 2019-12-31
  rus: 2019-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/138458/kaz/31.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138458/rus/31.12.2019
