act_code: '138408'
requisite: Решение Шетского районного маслихата Карагандинской области от 27 декабря 2019 года № 35/317. Зарегистрировано Департаментом юстиции Карагандинской области 9 января 2020 года № 5671
title:
  rus: Об утверждении бюджетов на 2020-2022 годы сельских округов и поселков Шетского района
  kaz: Шет ауданының ауылдық округтердің және кенттерінің 2020-2022 жылдарға арналған бюджеттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '160015000002'
version_date:
  kaz: 2020-11-09
  rus: 2020-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/138408/kaz/09.11.2020
  rus: https://zan.gov.kz/client/#!/doc/138408/rus/09.11.2020
caused_by:
  code: '148685'
  requisite: Решение Шетского районного маслихата Карагандинской области от 9 ноября 2020 года № 43/400. Зарегистрировано Департаментом юстиции Карагандинской области 20 ноября 2020 года № 6091
  title:
    rus: О внесении изменений в решение XХХV сессии Шетского районного маслихата от 27 декабря 2019 года № 35/317 «Об утверждении бюджетов на 2020-2022 годы сельских округов и поселков Шетского района»
    kaz: Шет аудандық мәслихатының 2019 жылғы 27 желтоқсандағы XXХV сессиясының «Шет ауданының ауылдық округтердің және кенттерінің 2020-2022 жылдарға арналған бюджеттерін бекіту туралы» № 35/317 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148685/rus
