act_code: '34384'
requisite: Решение Приозерского городского маслихата Карагандинской области от 12 июля 2007 года № 272/42. Зарегистрировано Управлением юстиции города Балхаша Карагандинской области 25 июля 2007 года № 8-4-81. Утратило силу решением Приозерского городского маслихата Карагандинской области от 25 февраля 2011 года N 234/37
title:
  rus: О согласовании мест проведения мирных собраний, митингов, шествий, пикетов и демонстрации во время выборов кандидатов в депутаты областного и городского маслихата, в Мажилис Парламента Республики Казахстан по партийным спискам по городу Приозерск
  kaz: Приозерск қаласы бойынша Қазақстан Республикасы Парламенті Мәжілісінің партиялық мәслихат депутаттарына үміткерлірінің сайлау мерзімінде бейбіт жиналыстар, митингілер, шерулер, пикеттер және демонтстрацияларды ұйымдастыру мен өткізу орандарын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-07-12
approved_by:
- '160009000002'
version_date:
  kaz: 2007-07-12
  rus: 2007-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/34384/kaz/12.07.2007
  rus: https://zan.gov.kz/client/#!/doc/34384/rus/12.07.2007
