act_code: '30993'
requisite: Решение 36 сессии Абайского районного маслихата Карагандинской области от 21 декабря 2006 года № 36/360. Зарегистрировано Управлением юстиции Абайского района 3 января 2007 года за № 8-9-26
title:
  rus: О районном бюджете на 2007 год
  kaz: 2007 жылға арналған бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-21
approved_by:
- '160011000002'
version_date:
  kaz: 2006-12-21
  rus: 2006-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/30993/kaz/21.12.2006
  rus: https://zan.gov.kz/client/#!/doc/30993/rus/21.12.2006
