act_code: '94596'
requisite: Решение 38 сессии Бухар-Жырауского районного маслихата Карагандинской области от 20 августа 2015 года № 6. Зарегистрировано Департаментом юстиции Карагандинской области 16 сентября 2015 года № 3410. Утратило силу решением Бухар-Жырауского районного маслихата Карагандинской области от 7 апреля 2016 года № 4
title:
  rus: О дополнительном регламентировании порядка проведения мирных собраний, митингов, шествий, пикетов и демонстраций
  kaz: Бейбiт жиналыстар, митингiлер, шерулер, пикеттер және демонстрациялар өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-08-20
approved_by:
- '160017000002'
version_date:
  kaz: 2015-08-20
  rus: 2015-08-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/94596/kaz/20.08.2015
  rus: https://zan.gov.kz/client/#!/doc/94596/rus/20.08.2015
