act_code: '138467'
requisite: Решение Осакаровского районного маслихата Карагандинской области от 30 декабря 2019 года № 794. Зарегистрировано Департаментом юстиции Карагандинской области 10 января 2020 года № 5676. Утратило силу решением Осакаровского районного маслихата Карагандинской области от 26 апреля 2022 года (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по Осакаровскому району
  kaz: Осакаров ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- НОРМ
- РЕШ
approved_on: 2019-12-30
approved_by:
- '160018000002'
version_date:
  kaz: 2019-12-30
  rus: 2019-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/138467/kaz/30.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138467/rus/30.12.2019
