act_code: '99353'
requisite: Решение XХХ сессии Улытауского районного маслихата Карагандинской области от 25 декабря 2015 года № 285. Зарегистрировано Департаментом юстиции Карагандинской области 18 января 2016 года № 3620
title:
  rus: О бюджете района на 2016-2018 годы
  kaz: 2016-2018 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-25
approved_by:
- '160019000002'
version_date:
  kaz: 2015-12-25
  rus: 2015-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/99353/kaz/25.12.2015
  rus: https://zan.gov.kz/client/#!/doc/99353/rus/25.12.2015
