act_code: '31286'
requisite: Решение 34 сессии Бухар Жырауского районного маслихата Карагандинской области от 21 декабря 2006 года № 6. Зарегистрировано управлением юстиции Бухар Жырауского района Карагандинской области 15 января 2007 года за № 8-11-32. Утратило силу решением Бухар-Жырауского районного маслихата Карагандинской области от 31 марта 2009 года № 7
title:
  rus: Об установлении ежемесячных ставок платы за размещение объектов наружной (визуальной) рекламы на территории Бухар - Жырауского района
  kaz: «Бұқар жырау ауданы аумағында сыртқы (көрнекі) жарнама объектілерін орналастыру үшін ай сайынғы төлемақы ставкаларын белгілеу туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-21
approved_by:
- '160017000002'
version_date:
  kaz: 2006-12-21
  rus: 2006-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/31286/kaz/21.12.2006
  rus: https://zan.gov.kz/client/#!/doc/31286/rus/21.12.2006
