act_code: '150859'
requisite: Решение Шахтинского городского маслихата Карагандинской области от 24 декабря 2020 года № 1781/45. Зарегистрировано в Министерстве юстиции Республики Казахстан 30 декабря 2020 года № 21966
title:
  rus: О бюджете поселков Шахтинского региона на 2021 - 2023 годы
  kaz: 2021-2023 жылдарға арналған Шахтинск аймағындағы кенттер бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-24
approved_by:
- '160004000002'
version_date:
  kaz: 2021-11-04
  rus: 2021-11-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/150859/kaz/04.11.2021
  rus: https://zan.gov.kz/client/#!/doc/150859/rus/04.11.2021
caused_by:
  code: '159980'
  requisite: Решение Шахтинского городского маслихата Карагандинской области от 4 ноября 2021 года № 88/9
  title:
    rus: О внесении изменений в решение 45 сессии Шахтинского городского маслихата от 24 декабря 2020 года № 1781/45 «О бюджете поселков Шахтинского региона на 2021-2023 годы»
    kaz: Шахтинск қалалық мәслихаттың 2020 жылғы 24 желтоқсандағы 45 сессиясының № 1781/45 «2021 – 2023 жылдарға арналған Шахтинск аймағындағы кенттер бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/159980/rus
