act_code: '228213'
requisite: Решение акима поселка Топар Абайского района Карагандинской области от 27 июля 2026 года № 01
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба в поселке Топар Абайского района
  kaz: Абай ауданының Топар кентінде жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-07-27
approved_by:
- '160011003001'
version_date:
  kaz: 2026-07-27
  rus: 2026-07-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/228213/kaz/27.07.2026
  rus: https://zan.gov.kz/client/#!/doc/228213/rus/27.07.2026
