act_code: '219231'
requisite: Решение Осакаровского районного маслихата Карагандинской области от 18 декабря 2025 года № 42/417
title:
  rus: О районном бюджете на 2026-2028 годы
  kaz: 2026 - 2028 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-18
approved_by:
- '160018000002'
version_date:
  kaz: 2026-02-06
  rus: 2026-02-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/219231/kaz/06.02.2026
  rus: https://zan.gov.kz/client/#!/doc/219231/rus/06.02.2026
caused_by:
  code: '221918'
  requisite: Решение Осакаровского районного маслихата Карагандинской области от 6 февраля 2026 года № 45/446
  title:
    rus: О внесении изменений в решение Осакаровского районного маслихата от 18 декабря 2025 года № 42/417 «О районном бюджете на 2026-2028 годы»
    kaz: Осакаров аудандық мәслихатының 2025 жылғы 18 желтоқсандағы № 42/417 «2026-2028 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/221918/rus
