act_code: '85329'
requisite: Решение Шетского районного маслихата Карагандинской области от 25 ноября 2014 года № 26/223. Зарегистрировано Департаментом юстиции Карагандинской области 25 декабря 2014 года № 2892. Утратило силу решением Шетского районного маслихата Карагандинской области от 24 ноября 2023 года № 6/63 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелген санаттарының тізбесін айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-11-25
approved_by:
- '160015000002'
version_date:
  kaz: 2014-11-25
  rus: 2014-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/85329/kaz/25.11.2014
  rus: https://zan.gov.kz/client/#!/doc/85329/rus/25.11.2014
