act_code: '63055'
requisite: Решение Шетского районного маслихата Карагандинской области от 13 января 2012 года № 42/397. Зарегистрировано Управлением юстиции Шетского района Карагандинской области 3 февраля 2012 года № 8-17-129
title:
  rus: О районном бюджете на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-01-13
approved_by:
- '160015000002'
version_date:
  kaz: 2012-06-12
  rus: 2012-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/63055/kaz/12.06.2012
  rus: https://zan.gov.kz/client/#!/doc/63055/rus/12.06.2012
caused_by:
  code: '66427'
  requisite: Решение Шетского районного маслихата Карагандинской области от 12 июня 2012 года № 3/41. Зарегистрировано Управлением юстиции Шетского района Карагандинской области 29 июня 2012 года № 8-17-136
  title:
    rus: О внесении изменений в решение XXХХII cессии районного маслихата от 13 января 2012 года № 42/397 "О районном бюджете на 2012-2014 годы"
    kaz: Аудандық мәслихаттың 2012 жылғы 13 қаңтардағы ХХХХII сессиясының "2012-2014 жылдарға арналған аудандық бюджет туралы" № 42/397 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/66427/rus
