act_code: '79166'
requisite: Решение XХIII сессии Карагандинского областного маслихата от 27 марта 2014 года № 260. Зарегистрировано Департаментом юстиции Карагандинской области 23 апреля 2014 года № 2610. Утратило силу решением Карагандинского областного маслихата от 12 декабря 2017 года № 267
title:
  rus: Об утверждении Регламента Карагандинского областного маслихата
  kaz: Қарағанды облыстық мәслихатының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-03-27
approved_by:
- '160000000002'
version_date:
  kaz: 2014-03-27
  rus: 2014-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/79166/kaz/27.03.2014
  rus: https://zan.gov.kz/client/#!/doc/79166/rus/27.03.2014
