act_code: '55847'
requisite: Қарағанды облысы Ұлытау аудандық мәслихатының XXV сессиясының 2010 жылғы 8 қарашадағы № 282 шешімі. Қарағанды облысы Ұлытау ауданының Әділет басқармасында 2010 жылғы 10 желтоқсанда № 8-16-66 тіркелді. Күші жойылды - Қарағанды облысы Ұлытау аудандық мәслихатының XXX сессиясының 2011 жылғы 16 қыркүйектегі № 360 шешімімен
title:
  rus: Автотұрақтар, автомобильге май құю станциялары орналасқан жер учаскелеріне салынатын салық ставкаларын белгілеу туралы
  kaz: Автотұрақтар, автомобильге май құю станциялары орналасқан жер учаскелеріне салынатын салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-08
approved_by:
- '160019000002'
version_date:
  kaz: 2010-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/55847/kaz/08.11.2010
