act_code: '79428'
requisite: Решение маслихата Актогайского района Павлодарской области от 30 апреля 2014 года № 116/30. Зарегистрировано Департаментом юстиции Павлодарской области 30 апреля 2014 года № 3785. Утратило силу решением Актогайского районного маслихата Павлодарской области от 4 марта 2021 года № 11/3 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении размеров социальной помощи для отдельно взятой категории получателей к памятным датам и праздничным дням
  kaz: Атаулы және мерекелік күндерге көмек алушылардың жекелеген санаттары үшін әлеуметтік көмек мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-30
approved_by:
- '160014000002'
version_date:
  kaz: 2015-02-23
  rus: 2015-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/79428/kaz/23.02.2015
  rus: https://zan.gov.kz/client/#!/doc/79428/rus/23.02.2015
caused_by:
  code: '87595'
  requisite: Решение маслихата Актогайского района Павлодарской области от 23 февраля 2015 года № 170/40. Зарегистрировано Департаментом юстиции Павлодарской области 13 марта 2015 года № 4355. Утратило силу решением Актогайского районного маслихата Павлодарской области от 4 марта 2021 года № 11/3 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Актогайского районного маслихата от 30 апреля 2014 года № 116/30 «Об установлении размеров социальной помощи для отдельно взятой категории получателей к памятным датам и праздничным дням»
    kaz: Ақтоғай аудандық мәслихатының 2014 жылғы 30 сәуірдегі «Атаулы және мерекелік күндерге көмек алушылардың жекелеген санаттары үшін әлеуметтік көмек мөлшерін белгілеу туралы» № 116/30 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/87595/rus
