act_code: '124616'
requisite: Решение XXII сессии Приозерского городского маслихата Карагандинской области от 23 августа 2018 года № 22/228. Зарегистрировано Департаментом юстиции Карагандинской области 17 сентября 2018 года № 4944
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по городу Приозерск
  kaz: Приозерск қаласы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- НОРМ
- РЕШ
approved_on: 2018-08-23
approved_by:
- '160009000002'
version_date:
  kaz: 2018-08-23
  rus: 2018-08-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/124616/kaz/23.08.2018
  rus: https://zan.gov.kz/client/#!/doc/124616/rus/23.08.2018
