act_code: '55986'
requisite: Решение акима города Темиртау Карагандинской области от 24 ноября 2010 года № 3. Зарегистрировано Управлением юстиции города Темиртау Карагандинской области 20 декабря 2010 года № 8-3-110
title:
  rus: Об организации приписки к призывному участку в 2011 году
  kaz: 2011 жылы шақыру учаскесінде есепке тіркеуді ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-24
approved_by:
- '160005000001'
version_date:
  kaz: 2010-11-24
  rus: 2010-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/55986/kaz/24.11.2010
  rus: https://zan.gov.kz/client/#!/doc/55986/rus/24.11.2010
