act_code: '127390'
requisite: Решение акима города Караганды от 19 декабря 2018 года № 12/01. Зарегистрировано Департаментом юстиции Карагандинской области 20 декабря 2018 года № 5081
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-19
approved_by:
- '160002000003'
version_date:
  kaz: 2025-07-14
  rus: 2025-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/127390/kaz/14.07.2025
  rus: https://zan.gov.kz/client/#!/doc/127390/rus/14.07.2025
caused_by:
  code: '212327'
  requisite: Решение акима города Караганды от 14 июля 2025 года № 03
  title:
    rus: О внесении изменений в решение акима города Караганды от 19 декабря 2018 года № 12/01 «Об образовании избирательных участков»
    kaz: Қарағанды қаласы әкімінің 2018 жылғы 19 желтоқсандағы № 12/01 «Сайлау учаскелерін құру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212327/rus
