act_code: '86438'
requisite: Решение XХXVIII сессии Жанааркинского районного маслихата Карагандинской области от 23 декабря 2014 года № 38/251. Зарегистрировано Департаментом юстиции Карагандинской области 12 января 2015 года № 2916
title:
  rus: О районном бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-23
approved_by:
- '160016000002'
version_date:
  kaz: 2015-04-21
  rus: 2015-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/86438/kaz/21.04.2015
  rus: https://zan.gov.kz/client/#!/doc/86438/rus/21.04.2015
caused_by:
  code: '89745'
  requisite: Решение XL сессии Жанааркинского районного маслихата Карагандинской области от 21 апреля 2015 года № 40/273. Зарегистрировано Департаментом юстиции Карагандинской области 30 апреля 2015 года № 3178
  title:
    rus: О внесении изменений в решение Жанааркинского районного маслихата от 23 декабря 2014 года № 38/251 «О районном бюджете на 2015-2017 годы»
    kaz: Жаңаарқа аудандық мәслихатының 2014 жылғы 23 желтоқсандағы № 38/251 «2015-2017 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/89745/rus
