act_code: '56117'
requisite: Решение акима города Караганды от 20 декабря 2010 года № 12/01. Зарегистрировано Управлением юстиции города Караганды 24 декабря 2010 года № 8-1-120.
title:
  rus: О проведении приписки граждан 1994 года рождения к призывным участкам Отделов по делам обороны Октябрьского района и района имени Казыбек би города Караганды
  kaz: Қарағанды қаласы Қазыбек би атындағы аудан және Октябрь ауданы қорғаныс істері жөніндегі бөлімдердің шақыру учаскелеріне 1994 жылы туған азаматтарды тіркеуге алуды өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-20
approved_by:
- '160002000001'
version_date:
  kaz: 2010-12-20
  rus: 2010-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/56117/kaz/20.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56117/rus/20.12.2010
