act_code: '76961'
requisite: Решение 26 сессии Осакаровского районного маслихата Карагандинской области от 25 декабря 2013 года № 262. Зарегистрировано Департаментом юстиции Карагандинской области 23 января 2014 года № 2523. Утратило силу решением Осакаровского районного маслихата Карагандинской области от 31 октября 2023 года № 12/110 (вводится в действие по истечению десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-12-25
approved_by:
- '160018000002'
version_date:
  kaz: 2019-06-19
  rus: 2019-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/76961/kaz/19.06.2019
  rus: https://zan.gov.kz/client/#!/doc/76961/rus/19.06.2019
caused_by:
  code: '132866'
  requisite: Решение Осакаровского районного маслихата Карагандинской области от 19 июня 2019 года № 691. Зарегистрировано Департаментом юстиции Карагандинской области 27 июня 2019 года № 5398. Утратило силу решением Осакаровского районного маслихата Карагандинской области от 31 октября 2023 года № 12/110 (вводится в действие по истечению десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнения в решение 26 сессии Осакаровского районного маслихата от 25 декабря 2013 года № 262 "Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан"
    kaz: Осакаров аудандық мәслихатының 2013 жылғы 25 желтоқсандағы 26 сессиясының № 262 "Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы" шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132866/rus
