act_code: '142035'
requisite: Решение акима Улытауского сельского округа Улытауского района Карагандинской области от 20 апреля 2020 года № 4. Зарегистрировано Департаментом юстиции Карагандинской области 22 апреля 2020 года № 5802
title:
  rus: О присвоении наименования безымянной улице Улытауского сельского округа Улытауского района
  kaz: Ұлытау ауданы Ұлытау ауылдық округіндегі атауы жоқ көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-04-20
approved_by:
- '160019001002'
version_date:
  kaz: 2020-04-20
  rus: 2020-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/142035/kaz/20.04.2020
  rus: https://zan.gov.kz/client/#!/doc/142035/rus/20.04.2020
