act_code: '118893'
requisite: Решение XXIII сессии Каркаралинского районного маслихата Карагандинской области от 30 января 2018 года № VI-23/201. Зарегистрировано Департаментом юстиции Карагандинской области 13 февраля 2018 года № 4612. Утратило силу решением Каркаралинского районного маслихата Карагандинской области от 24 февраля 2022 года № VII-15/123 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил управления бесхозяйными отходами, признанными решением суда поступившими в коммунальную собственность
  kaz: Сот шешімімен коммуналдық меншікке түскен болып танылған иесіз қалдықтарды басқару қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2018-01-30
approved_by:
- '160013000002'
version_date:
  kaz: 2018-01-30
  rus: 2018-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/118893/kaz/30.01.2018
  rus: https://zan.gov.kz/client/#!/doc/118893/rus/30.01.2018
