act_code: '30060'
requisite: Қарағанды облысы Шет аудандық мәслихатының 2006 жылғы 28 қыркүйектегі № 31/303 шешімі. Қарағанды облысы Шет ауданы Әділет басқармасында 2006 жылғы 27 қазанда № 8-17-27 тіркелді. Күші жойылды - Қарағанды облысы Шет аудандық мәслихатының 2010 жылғы 28 қыркүйектегі № 26/273 шешімімен
title:
  rus: Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақыларды беру және қалалық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы берудің Қағидасын бекіту туралы
  kaz: Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақыларды беру және қалалық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы берудің Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2006-09-28
approved_by:
- '160015000002'
version_date:
  kaz: 2006-09-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/30060/kaz/28.09.2006
