act_code: '104481'
requisite: Решение акима Доскейского сельского округа Бухар-Жырауского района Карагандинской области от 30 мая 2016 года № 3. Зарегистрировано Департаментом юстиции Карагандинской области 27 июня 2016 года № 3873
title:
  rus: О переименовании улицы в селе Доскей
  kaz: Доскей ауылындағы көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-05-30
approved_by:
- '160017018001'
version_date:
  kaz: 2016-05-30
  rus: 2016-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/104481/kaz/30.05.2016
  rus: https://zan.gov.kz/client/#!/doc/104481/rus/30.05.2016
