act_code: '77692'
requisite: Решение ХХХII сессии V созыва Карагандинского городского маслихата от 24 февраля 2014 года № 286. Зарегистрировано Департаментом юстиции Карагандинской области 27 февраля 2014 года № 2547.
title:
  rus: О льготном проезде на внутригородском общественном транспорте (кроме такси) обучающихся очной формы обучения на март, апрель, май месяцы 2014 года
  kaz: 2014 жылдың наурыз, сәуір, мамыр айларында күндізгі оқу нысанында оқитындардың қала ішіндегі қоғамдық көлікте (таксиден басқа) жеңілдікпен жол жүруі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-24
approved_by:
- '160002000002'
version_date:
  kaz: 2014-02-24
  rus: 2014-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/77692/kaz/24.02.2014
  rus: https://zan.gov.kz/client/#!/doc/77692/rus/24.02.2014
