act_code: '49561'
requisite: Қарағанды облысы Ұлытау аудандық мәслихатының XVI сессиясының 2009 жылғы 24 желтоқсандағы № 180 шешімі. Қарағанды облысы Ұлытау ауданының Әділет басқармасында 2009 жылғы 29 желтоқсанда № 8-16-51 тіркелді
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-24
approved_by:
- '160019000002'
version_date:
  kaz: 2009-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/49561/kaz/24.12.2009
