act_code: '62083'
requisite: Решение 54 сессии Осакаровского районного маслихата Карагандинской области от 14 ноября 2011 года № 426. Зарегистрировано Управлением юстиции Осакаровского района Карагандинской области 21 декабря 2011 года № 8-15-160
title:
  rus: Об установлении стоимости разовых талонов на 2012 год
  kaz: 2012 жылға біржолғы талондардың құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-14
approved_by:
- '160018000002'
version_date:
  kaz: 2013-04-23
  rus: 2013-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/62083/kaz/23.04.2013
  rus: https://zan.gov.kz/client/#!/doc/62083/rus/23.04.2013
