act_code: '28865'
requisite: Қарағанды облысы Осакаров ауданының мәслихатының 2006 жылғы 23 маусымдағы № 203 шешімі. Қарағанды облысы Осакаров ауданының Әділет басқармасында 2006 жылғы 17 шілдеде № 8-15-33 тіркелді. Күші жойылды - Қарағанды облысы Осакаров ауданының мәслихатының 2009 жылғы 8 қыркүйектегі № 172 шешімімен
title:
  rus: Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақыларды беру және қалалық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы берудің және тұрғын үй жәрдемақысын тағайындау кезінде отбасының (адамның) жиынтық табысын есептеу тәртібі туралы Қағидасын бекіту туралы
  kaz: Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақыларды беру және қалалық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы берудің және тұрғын үй жәрдемақысын тағайындау кезінде отбасының (адамның) жиынтық табысын есептеу тәртібі туралы Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2006-06-23
approved_by:
- '160018000002'
version_date:
  kaz: 2006-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/28865/kaz/23.06.2006
