act_code: '109265'
requisite: Решение Жезказганского городского маслихата Карагандинской области от 21 декабря 2016 года № 7/78. Зарегистрировано Департаментом юстиции Карагандинской области 10 января 2017 года № 4105
title:
  rus: Об утверждении Положения о награждении Почетной грамотой города Жезказган
  kaz: Жезқазған қаласының Құрмет грамотасымен наградтау туралы Ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2016-12-21
approved_by:
- '160006000002'
version_date:
  kaz: 2023-11-27
  rus: 2023-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/109265/kaz/27.11.2023
  rus: https://zan.gov.kz/client/#!/doc/109265/rus/27.11.2023
caused_by:
  code: '189137'
  requisite: Решение Жезказганского городского маслихата области Ұлытау от 27 ноября 2023 года № 11/65. Зарегистрировано в Департаменте юстиции области Ұлытау 28 ноября 2023 года № 74-20
  title:
    rus: О внесении изменений в решение Жезказганского городского маслихата от 21 декабря 2016 года № 7/78 «Об утверждении Положения о награждении Почетной грамотой города Жезказган»
    kaz: Жезқазған қалалық мәслихатының 2016 жылғы 21 желтоқсандағы № 7/78 «Жезқазған қаласының Құрмет грамотасымен наградтау туралы Ережені бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/189137/rus
