act_code: '54568'
requisite: Қарағанды облысы Жаңаарқа ауданы Ақтүбек селолық округі әкімінің 2010 жылғы 6 қыркүйектегі № 1 шешімі. Қарағанды облысы Жаңаарқа ауданының Әділет басқармасында 2010 жылғы 20 қыркүйекте № 8-12-88 тіркелді
title:
  rus: Ақтүбек селолық округі елді мекендеріндегі көшелерге атау беру туралы
  kaz: Ақтүбек селолық округі елді мекендеріндегі көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-06
approved_by:
- '160016003001'
version_date:
  kaz: 2010-09-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/54568/kaz/06.09.2010
