act_code: '212167'
requisite: Решение Осакаровского районного маслихата Карагандинской области от 9 июля 2025 года № 36/365
title:
  rus: Об утверждении Порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей поселка Осакаровка Осакаровского района Карагандинской области для участия в сходе местного сообщества
  kaz: Қарағанды облысы Осакаров ауданы Осакаровка кентінің жергілікті қоғамдастық жиындарына қатысу үшін жергілікті қоғамдастықтың бөлек жиындарын өткізу тәртібі және кент тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2025-07-09
approved_by:
- '160018000002'
version_date:
  kaz: 2025-07-09
  rus: 2025-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/212167/kaz/09.07.2025
  rus: https://zan.gov.kz/client/#!/doc/212167/rus/09.07.2025
