act_code: '71565'
requisite: Решение Сатпаевского городского маслихата Карагандинской области от 20 февраля 2013 года № 113. Зарегистрировано Департаментом юстиции Карагандинской области 18 марта 2013 года № 2238. Утратило силу решением Сатпаевского городского маслихата Карагандинской области от 31 марта 2014 года № 224
title:
  rus: О льготном проезде на общественном транспорте (кроме такси) учащихся очной формы обучения
  kaz: Күндізгі оқу нысанындағы оқушылардың қоғамдық көлікте (таксиден басқа) жеңілдікпен жүруі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-02-20
approved_by:
- '160007000002'
version_date:
  kaz: 2013-02-20
  rus: 2013-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/71565/kaz/20.02.2013
  rus: https://zan.gov.kz/client/#!/doc/71565/rus/20.02.2013
