act_code: '95553'
requisite: Решение Шетского районного маслихата Карагандинской области от 17 сентября 2015 года № 32/283. Зарегистрировано Департаментом юстиции Карагандинской области 1 октября 2015 года № 3421. Утратило силу решением Шетского районного маслихата Карагандинской области от 5 маяя 2018 года № 21/181
title:
  rus: О повышении ставки земельного налога и ставки единного земельного налога на неиспользуемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения
  kaz: Қазақстан Республикасының жер заңнамасына сәйкес пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-17
approved_by:
- '160015000002'
version_date:
  kaz: 2016-02-18
  rus: 2016-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/95553/kaz/18.02.2016
  rus: https://zan.gov.kz/client/#!/doc/95553/rus/18.02.2016
caused_by:
  code: '100239'
  requisite: Решение Шетского районного маслихата Карагандинской области от 18 февраля 2016 года № 38/325. Зарегистрировано Департаментом юстиции Карагандинской области 14 марта 2016 года № 3705
  title:
    rus: О внесении изменений в решение ХХХІІ сессии районного маслихата от 17 сентября 2015 года №32/283 «О повышении ставки земельного налога и ставки единного земельного налога на неиспользуемые в соответствии с земельным законодательством Республики Казахстан земли сельского хозяйственного  назначения»
    kaz: Аудандық мәслихаттың 2015 жылғы 17 қыркүйектегі ХХХІІ сессиясының «Қазақстан Республикасының жер заңнамасына сәйкес пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының ставкасын және бірыңғай жер салығының ставкасын жоғарылату туралы» №32/283 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/100239/rus
