act_code: '83684'
requisite: Решение XХXIV сессии Жанааркинского районного маслихата Карагандинской области от 10 сентября 2014 года № 34/225. Зарегистрировано Департаментом юстиции Карагандинской области 13 октября 2014 года № 2800. Утратило силу решением Жанааркинского районного маслихата Карагандинской области от 10 октября 2017 года № 17/138
title:
  rus: Об утверждении Регламента Жанааркинского районного маслихата
  kaz: Жаңаарқа аудандық мәслихатының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-09-10
approved_by:
- '160016000002'
version_date:
  kaz: 2015-06-26
  rus: 2015-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/83684/kaz/26.06.2015
  rus: https://zan.gov.kz/client/#!/doc/83684/rus/26.06.2015
caused_by:
  code: '92671'
  requisite: Решение XLI сессии Жанааркинского районного маслихата Карагандинской области от 26 июня 2015 года № 41/284. Зарегистрировано Департаментом юстиции Карагандинской области 13 июля 2015 года № 3329. Утратило силу решением Жанааркинского районного маслихата Карагандинской области от 10 октября 2017 года № 17/138
  title:
    rus: О внесении изменения в решение Жанааркинского районного маслихата от 10 сентября 2014 года № 34/225 «Об утверждении Регламента Жанааркинского районного маслихата»
    kaz: Жаңаарқа аудандық мәслихатының 2014 жылғы 10 қыркүйектегі № 34/225 «Жаңаарқа аудандық мәслихатының Регламентін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/92671/rus
