act_code: '95606'
requisite: Решение акима города Караганды от 21 октября 2015 года № 10/02. Зарегистрировано Департаментом юстиции Карагандинской области 18 ноября 2015 года № 3503. Утратило силу решением акима города Караганды от 19 декабря 2018 года № 12/01 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-21
approved_by:
- '160002000001'
version_date:
  kaz: 2017-04-14
  rus: 2017-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/95606/kaz/14.04.2017
  rus: https://zan.gov.kz/client/#!/doc/95606/rus/14.04.2017
caused_by:
  code: '112083'
  requisite: Решение акима города Караганды от 14 апреля 2017 года № 04/03. Зарегистрировано Департаментом юстиции Карагандинской области 2 мая 2017 года № 4245. Утратило силу решением акима города Караганды от 19 декабря 2018 года № 12/01 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение акима города Караганды от 21 октября 2015 года № 10/02 «Об образовании избирательных участков»
    kaz: «Сайлау учаскелерін құру туралы» Қарағанды қаласы әкімінің 2015 жылғы 21 қазандағы № 10/02 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/112083/rus
