act_code: '121466'
requisite: Решение 22 сессии Актогайского районного маслихата Карагандинской области от 18 апреля 2018 года № 199. Зарегистрировано Департаментом юстиции Карагандинской области 4 мая 2018 года № 4749. Утратило силу решением Актогайского районного маслихата Карагандинской области от 24 июня 2020 года № 405 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении единых ставок фиксированного налога
  kaz: Тіркелген салықтың бірыңғай мөлшерлемелерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-04-18
approved_by:
- '160014000002'
version_date:
  kaz: 2018-04-18
  rus: 2018-04-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/121466/kaz/18.04.2018
  rus: https://zan.gov.kz/client/#!/doc/121466/rus/18.04.2018
