act_code: '54363'
requisite: Қарағанды облысы Жаңаарқа ауданы мәслихатының 2010 жылғы 16 тамыздағы № 26/227 шешімі. Қарағанды облысы Жаңаарқа ауданының Әділет басқармасында 2010 жылғы 6 қыркүйекте № 8-12-80 тіркелді. Күші жойылды - Қарағанды облысы Жаңаарқа аудандық мәслихатының 2011 жылғы 15 қарашадағы № 41/353 шешімімен
title:
  rus: Жаңаарқа ауданы бойынша тұрғын үй көмегін көрсету Ережесін бекіту туралы
  kaz: Жаңаарқа ауданы бойынша тұрғын үй көмегін көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-08-16
approved_by:
- '160016000002'
version_date:
  kaz: 2010-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/54363/kaz/22.12.2010
caused_by:
  code: '56349'
  requisite: Қарағанды облысы Жаңаарқа ауданы мәслихатының 2010 жылғы 22 желтоқсандағы XXXI сессиясының № 31/272 шешімі. Қарағанды облысы Жаңаарқа ауданының Әділет басқармасында 2010 жылғы 29 желтоқсанда № 8-12-102 тіркелді. Күші жойылды - Қарағанды облысы Жаңаарқа ауданы мәслихатының 2013 жылғы 7 қазандағы № 22/143 шешімімен
  title:
    rus: Жаңаарқа аудандық мәслихатының 2010 жылғы 16 тамыздағы XXVI сессиясының "Жаңаарқа ауданы бойынша тұрғын үй көмегін көрсету Ережесін бекіту туралы" № 26/227 шешіміне толықтыру енгізу туралы
    kaz: Жаңаарқа аудандық мәслихатының 2010 жылғы 16 тамыздағы XXVI сессиясының "Жаңаарқа ауданы бойынша тұрғын үй көмегін көрсету Ережесін бекіту туралы" № 26/227 шешіміне толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/56349/rus
