act_code: '54363'
requisite: Қарағанды облысы Жаңаарқа ауданы мәслихатының 2010 жылғы 16 тамыздағы № 26/227 шешімі. Қарағанды облысы Жаңаарқа ауданының Әділет басқармасында 2010 жылғы 6 қыркүйекте № 8-12-80 тіркелді. Күші жойылды - Қарағанды облысы Жаңаарқа аудандық мәслихатының 2011 жылғы 15 қарашадағы № 41/353 шешімімен
title:
  rus: Жаңаарқа ауданы бойынша тұрғын үй көмегін көрсету Ережесін бекіту туралы
  kaz: Жаңаарқа ауданы бойынша тұрғын үй көмегін көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-08-16
approved_by:
- '160016000002'
version_date:
  kaz: 2011-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/54363/kaz/28.06.2011
caused_by:
  code: '59721'
  requisite: Решение XXXV сессии Жанааркинского районного маслихата Карагандинской области от 28 июня 2011 года № 35/309. Зарегистрировано Управлением юстиции Жанааркинского района Карагандинской области 21 июля 2011 года № 8-12-110. Утратило силу - решением Жанааркинского районного маслихата Карагандинской области от 15 ноября 2011 года № 41/353
  title:
    rus: О внесении изменений в решение XXVI сессии Жанааркинского районного маслихата от 16 августа 2010 года № 26/227 "Об утверждении Правил оказания жилищной помощи по Жанааркинскому району"
    kaz: Жаңаарқа аудандық мәслихатының 2010 жылғы 16 тамыздағы XXVI сессиясының "Жаңаарқа ауданы бойынша тұрғын үй көмегін көрсету Ережесін бекіту туралы" N 26/227 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/59721/rus
