act_code: '145287'
requisite: Решение Каражалского городского маслихата Карагандинской области от 29 июля 2020 года № 421. Зарегистрировано Департаментом юстиции Карагандинской области 4 августа 2020 года № 5999. Утратило силу решением Каражалского городского маслихата области Ұлытау от 9 февраля 2024 года № 133 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан города Каражал
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Қаражал қаласының мұқтаж азаматтарының жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-07-29
approved_by:
- '160010000002'
version_date:
  kaz: 2020-07-29
  rus: 2020-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/145287/kaz/29.07.2020
  rus: https://zan.gov.kz/client/#!/doc/145287/rus/29.07.2020
