act_code: '96883'
requisite: Решение маслихата Актогайского района Павлодарской области от 24 декабря 2015 года № 228/53. Зарегистрировано Департаментом юстиции Павлодарской области 30 декабря 2015 года № 4872. Утратило силу решением маслихата Актогайского района Павлодарской области от 26 января 2017 года № 72/13 (вводится в действие со дня его первого официального опубликования)
title:
  rus: О бюджете Актогайского района на 2016 - 2018 годы
  kaz: 2016 - 2018 жылдарға арналған Ақтоғай ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-24
approved_by:
- '160014000002'
version_date:
  kaz: 2016-12-23
  rus: 2016-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/96883/kaz/23.12.2016
  rus: https://zan.gov.kz/client/#!/doc/96883/rus/23.12.2016
caused_by:
  code: '108328'
  requisite: Решение маслихата Актогайского района Павлодарской области от 23 декабря 2016 года № 50/11. Зарегистрировано Департаментом юстиции Павлодарской области 23 декабря 2016 года № 5306. Утратило силу решением маслихата Актогайского района Павлодарской области от 26 января 2017 года № 72/13 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменений  в решение районного маслихата (LIII очередная сессия, V созыв) от 24 декабря 2015 года № 228/53 «О бюджете Актогайского района на 2016 - 2018 годы»
    kaz: Аудандық мәслихаттың 2015 жылғы 24 желтоқсандағы (V шақырылған, LIII кезекті сессиясы) «2016 - 2018 жылдарға арналған Ақтоғай ауданының бюджеті туралы» № 228/53 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/108328/rus
