act_code: '128236'
requisite: Решение XXVI сессии Приозерского городского маслихата Карагандинской области от 26 декабря 2018 года № 26/247. Зарегистрировано Департаментом юстиции Карагандинской области 29 декабря 2018 года № 5108
title:
  rus: О городском бюджете на 2019 - 2021 годы
  kaz: 2019 - 2021 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-26
approved_by:
- '160009000002'
version_date:
  kaz: 2019-11-21
  rus: 2019-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/128236/kaz/21.11.2019
  rus: https://zan.gov.kz/client/#!/doc/128236/rus/21.11.2019
caused_by:
  code: '136278'
  requisite: Решение Приозерского городского маслихата Карагандинской области от 21 ноября 2019 года № 35/340. Зарегистрировано Департаментом юстиции Карагандинской области 25 ноября 2019 года № 5531
  title:
    rus: О внесении изменений в решение Приозерского городского маслихата от 26 декабря 2018 года № 26/247 «О городском бюджете на 2019 - 2021 годы»
    kaz: Приозерск қалалық мәслихатының 2018 жылғы 26 желтоқсандағы № 26/247 «2019 - 2021 жылдарға арналған қалалық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136278/rus
