act_code: '34810'
requisite: Қарағанды облысы Жаңаарқа аудандық мәслихатының 2007 жылғы 9 шілдедегі № 39/315 шешімі. Қарағанды облысы Жаңаарқа ауданы Әділет басқармасында 2007 жылғы 17 тамызда № 8-12-34 тіркелді. Күші жойылды - Қарағанды облысы Жаңаарқа ауданы мәслихатының 2010 жылғы 16 тамыздағы № 26/227 шешімімен
title:
  rus: Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақыларды беру және аудандық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы берудің Қағидасын бекіту туралы
  kaz: Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақыларды беру және аудандық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы берудің Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-07-09
approved_by:
- '160016000002'
version_date:
  kaz: 2007-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/34810/kaz/09.07.2007
