act_code: '44039'
requisite: Решение акима Бухар-Жырауского района Карагандинской области от № 2 февраля 2009 года № 1. Зарегистрировано Управлением юстиции Бухар-Жырауского района Карагандинской области 4 февраля 2009 года № 8-11-71. Утратило силу - решением акима Бухар-Жырауского района Карагандинской области от 2 февраля 2010 года № 1
title:
  rus: О проведении приписки граждан 1992 года рождения к призывному участку
  kaz: 1992 жылы туған азаматтарды шақыру учаскесіне тіркеуді өткiзу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-02
approved_by:
- '160017000003'
version_date:
  kaz: 2009-02-02
  rus: 2009-02-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/44039/kaz/02.02.2009
  rus: https://zan.gov.kz/client/#!/doc/44039/rus/02.02.2009
