act_code: '190846'
requisite: Решение Карагандинского городского маслихата от 22 декабря 2023 года № 119
title:
  rus: О бюджете города Караганды на 2024-2026 годы
  kaz: Қала бюджеті туралы Қарағанды 2024-2026 жж
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-22
approved_by:
- '160002000002'
version_date:
  kaz: 2024-07-03
  rus: 2024-07-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/190846/kaz/03.07.2024
  rus: https://zan.gov.kz/client/#!/doc/190846/rus/03.07.2024
caused_by:
  code: '198508'
  requisite: Решение Карагандинского городского маслихата от 3 июля 2024 года № 171
  title:
    rus: О внесении изменений в решение Карагандинского городского маслихата от 22 декабря 2023 года № 119 «О бюджете города Караганды на 2024–2026 годы»
    kaz: Қарағанды қалалық мәслихатының 2023 жылғы 22 желтоқсандағы № 119 «Қарағанды қаласының 2024-2026 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198508/rus
