act_code: '94510'
requisite: Решение 39 сессии Бухар-Жырауского районного маслихата Карагандинской области от 21 сентября 2015 года № 4. Зарегистрировано Департаментом юстиции Карагандинской области 8 октября 2015 года № 3434. Утратило силу решением Бухар-Жырауского районного маслихата Карагандинской области от 21 июня 2018 года № 9
title:
  rus: О повышении ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения по Бухар-Жыраускому району
  kaz: Бұқар жырау ауданы бойынша пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының мөлшерлемесін және бірыңғай жер салығының мөлшерлемесін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-21
approved_by:
- '160017000002'
version_date:
  kaz: 2016-02-03
  rus: 2016-02-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/94510/kaz/03.02.2016
  rus: https://zan.gov.kz/client/#!/doc/94510/rus/03.02.2016
caused_by:
  code: '99280'
  requisite: Решение 45 сессии Бухар-Жырауского районного маслихата Карагандинской области от 3 февраля 2016 года № 6. Зарегистрировано Департаментом юстиции Карагандинской области 17 февраля 2016 года № 3667. Утратило силу решением Бухар-Жырауского районного маслихата Карагандинской области от 21 июня 2018 года № 9
  title:
    rus: О внесении изменения в решение 39 сессии Бухар-Жырауского районного маслихата от 21 сентября 2015 года №4 «О повышении ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения по Бухар-Жыраускому району»
    kaz: Бұқар жырау аудандық мәслихатының 2015 жылғы 21 қыркүйектегі 39 сессиясының №4 «Бұқар жырау ауданы бойынша пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының мөлшерлемесін және бірыңғай жер салығының мөлшерлемесін жоғарылату туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/99280/rus
