act_code: '56345'
requisite: Қарағанды облысы Ұлытау аудандық мәслихатының XXVI сессиясының 2010 жылғы 25 желтоқсандағы № 302 шешімі. Қарағанды облысы Ұлытау ауданының Әділет басқармасында 2010 жылғы 29 желтоқсанда № 8-16-68 тіркелді
title:
  rus: 2011-2013 жылдарға арналған аудандық бюджет туралы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-25
approved_by:
- '160019000002'
version_date:
  kaz: 2011-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/56345/kaz/14.11.2011
caused_by:
  code: '61622'
  requisite: Решение XXXII сессии Улытауского районного маслихата Карагандинской области от 14 ноября 2011 года № 371. Зарегистрировано Управлением юстиции Улытауского района Карагандинской области 24 ноября 2011 года № 8-16-73. Прекратило свое действие в связи с истечением срока - (письмо Улытауского районного маслихата Карагандинской области от 4 июля 2012 года № 2-9/76)
  title:
    rus: О внесении изменений и дополнений в решение ХХVI сессии Улытауского районного маслихата от 25 декабря 2010 года № 302 "О районном бюджете на 2011-2013 годы"
    kaz: Ұлытау аудандық мәслихаттың 2010 жылғы 25 желтоқсандағы XXVI сессиясының "2011-2013 жылдарға арналған аудандық бюджет туралы" № 302 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/61622/rus
