act_code: '56345'
requisite: Қарағанды облысы Ұлытау аудандық мәслихатының XXVI сессиясының 2010 жылғы 25 желтоқсандағы № 302 шешімі. Қарағанды облысы Ұлытау ауданының Әділет басқармасында 2010 жылғы 29 желтоқсанда № 8-16-68 тіркелді
title:
  rus: 2011-2013 жылдарға арналған аудандық бюджет туралы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-25
approved_by:
- '160019000002'
version_date:
  kaz: 2011-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/56345/kaz/07.04.2011
caused_by:
  code: '58454'
  requisite: Решение XXVIII сессии Улытауского районного маслихата Карагандинской области от 7 апреля 2011 года № 324. Зарегистрировано Управлением юстиции Улытауского района Карагандинской области 22 апреля 2011 года № 8-16-70
  title:
    rus: О внесении изменений и дополнений в решение ХХVI сессии Улытауского районного маслихата от 25 декабря 2010 года № 302 "О районном бюджете на 2011-2013 годы"
    kaz: Ұлытау аудандық мәслихатының 2010 жылғы 25 желтоқсандағы ХХVІ сессиясының "2011-2013 жылдарға арналған аудандық бюджет туралы" № 302 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/58454/rus
