act_code: '56345'
requisite: Қарағанды облысы Ұлытау аудандық мәслихатының XXVI сессиясының 2010 жылғы 25 желтоқсандағы № 302 шешімі. Қарағанды облысы Ұлытау ауданының Әділет басқармасында 2010 жылғы 29 желтоқсанда № 8-16-68 тіркелді
title:
  rus: 2011-2013 жылдарға арналған аудандық бюджет туралы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-25
approved_by:
- '160019000002'
version_date:
  kaz: 2010-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/56345/kaz/25.12.2010
