act_code: '145141'
requisite: Решение Жезказганского городского маслихата Карагандинской области от 22 июля 2020 года № 49/425. Зарегистрировано Департаментом юстиции Карагандинской области 27 июля 2020 года № 5973
title:
  rus: Об установлении повышенных на двадцать пять процентов окладов и тарифных ставок специалистам в области социального обеспечения, образования, культуры, спорта, являющимся гражданскими служащими и работающим в сельской местности, финансируемых из городского бюджета
  kaz: Қалалық бюджеттен қаржыландырылатын, азаматтық қызметші болып табылатын және ауылдық жерде жұмыс iстейтiн әлеуметтiк қамсыздандыру, бiлiм беру, мәдениет, спорт, саласындағы мамандарға жиырма бес пайызға жоғарылатылған айлықақылар мен тарифтiк мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-07-22
approved_by:
- '160006000002'
version_date:
  kaz: 2020-07-22
  rus: 2020-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/145141/kaz/22.07.2020
  rus: https://zan.gov.kz/client/#!/doc/145141/rus/22.07.2020
