act_code: '154456'
requisite: Решение акима поселка Осакаровка Осакаровского района Карагандинской области от 5 апреля 2021 года № 5. Зарегистрировано Департаментом юстиции Карагандинской области 8 апреля 2021 года № 6286
title:
  rus: О переименовании улицы поселка Осакаровка
  kaz: Осакаровка кентіндегі көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-05
approved_by:
- '160018001001'
version_date:
  kaz: 2021-04-05
  rus: 2021-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/154456/kaz/05.04.2021
  rus: https://zan.gov.kz/client/#!/doc/154456/rus/05.04.2021
