act_code: '76772'
requisite: Решение XVIII сессии Улытауского районного маслихата Карагандинской области от 25 декабря 2013 года № 140. Зарегистрировано Департаментом юстиции Карагандинской области 16 января 2014 года № 2507
title:
  rus: О бюджете района на 2014-2016 годы
  kaz: 2014-2016 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-25
approved_by:
- '160019000002'
version_date:
  kaz: 2014-09-11
  rus: 2014-09-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/76772/kaz/11.09.2014
  rus: https://zan.gov.kz/client/#!/doc/76772/rus/11.09.2014
caused_by:
  code: '83279'
  requisite: Решение XХII сессии Улытауского районного маслихата Карагандинской области от 11 сентября 2014 года № 184. Зарегистрировано Департаментом юстиции Карагандинской области 23 сентября 2014 года № 2766
  title:
    rus: О внесении изменений в решение ХVІІІ сессии Улытауского районного маслихата от 25 декабря 2013 года № 140 "О бюджете района на 2014-2016 годы"
    kaz: Ұлытау аудандық мәслихатының 2013 жылғы 25 желтоқсандағы ХVІІІ сессиясының № 140 "2014-2016 жылдарға арналған аудан бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/83279/rus
