act_code: '176592'
requisite: Решение Бухар-Жырауского районного маслихата Карагандинской области от 22 декабря 2022 года № 15
title:
  rus: О бюджетах сел, поселков и сельских округов района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған ауданның ауылдары, кенттері, ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-22
approved_by:
- '160017000002'
version_date:
  kaz: 2023-04-25
  rus: 2023-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/176592/kaz/25.04.2023
  rus: https://zan.gov.kz/client/#!/doc/176592/rus/25.04.2023
caused_by:
  code: '180729'
  requisite: Решение Бухар-Жырауского районного маслихата Карагандинской области от 25 апреля 2023 года № 5
  title:
    rus: О внесении изменений в решение 24 сессии Бухар-Жырауского районного маслихата от 22 декабря 2022 года № 15 «О бюджетах сел, поселков и сельских округов района на 2023-2025 годы»
    kaz: Бұқар жырау аудандық мәслихатының 24 сессиясының 2022 жылғы 22 желтоқсандағы № 15 «2023-2025 жылдарға арналған ауданның ауылдары, кенттері, ауылдық округтерінің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/180729/rus
