act_code: '145113'
requisite: Решение Жезказганского городского маслихата Карагандинской области от 22 июля 2020 года № 49/423. Зарегистрировано Департаментом юстиции Карагандинской области 24 июля 2020 года № 5971
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, порядка использования специализированных мест для организации и проведения мирных собраний, норм их предельной заполняемости, а также требований к материально-техническому и организационному обеспечению специализированных мест для организации и проведения мирных собраний и границ прилегающих территорий, в которых запрещено проведение пикетирования, на территории города Жезказган
  kaz: Жезқазған қаласының аумағында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды пайдалану тәртібін, олардың шекті толу нормаларын, сондай-ақ бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды және пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-07-22
approved_by:
- '160006000002'
version_date:
  kaz: 2024-02-13
  rus: 2024-02-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/145113/kaz/13.02.2024
  rus: https://zan.gov.kz/client/#!/doc/145113/rus/13.02.2024
caused_by:
  code: '193358'
  requisite: Решение Жезказганского городского маслихата области Ұлытау от 13 февраля 2024 года № 15/83. Зарегистрировано в Департаменте юстиции области Ұлытау 16 февраля 2024 года № 93-20
  title:
    rus: О внесении изменений и дополнения в решение Жезказганского городского маслихата от 22 июля 2020 года № 49/423 «О специализированных местах для организации и проведения мирных собраний и границах, прилегающих территорий, в которых запрещено проведение пикетирования на территории города Жезказган»
    kaz: Жезқазған қалалық мәслихатының 2020 жылғы 22 шілдедегі № 49/423 «Жезқазған қаласының аумағында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындар және пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекаралары туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/193358/rus
