act_code: '217288'
requisite: Решение акима поселка Осакаровка Осакаровского района Карагандинской области от 20 ноября 2025 года № 8
title:
  rus: Об установлении публичного сервитута на земельные участки для строительства высоковольтной линии ВЛ-10кВт протяженностью 1,2 км по объекту «Строительство полигона ТБО» расположенного на землях поселка Осакаровка. «проект решения»
  kaz: «ҚТҚ полигонын салу» объектісі бойынша ұзындығы 1,2 км болатын ӘЖ-10кВт жоғары вольтты желісін салу үшін қоғамдық сервитутты орнату туралы «шешім жобасы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-20
approved_by:
- '160018001001'
version_date:
  kaz: 2025-11-20
  rus: 2025-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/217288/kaz/20.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217288/rus/20.11.2025
