act_code: '138005'
requisite: Решение Каркаралинского районного маслихата Карагандинской области от 25 декабря 2019 года № VI-51/429. Зарегистрировано Департаментом юстиции Карагандинской области 5 января 2020 года № 5658
title:
  rus: Об утверждении Регламента собрания местного сообщества по Каркаралинскому району
  kaz: Қарқаралы ауданы бойынша жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2019-12-25
approved_by:
- '160013000002'
version_date:
  kaz: 2019-12-25
  rus: 2019-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/138005/kaz/25.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138005/rus/25.12.2019
