act_code: '170169'
requisite: Решение Бухар-Жырауского районного маслихата Карагандинской области от 30 июня 2022 года № 7
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Бухар-Жыраускому району на 2022 - 2023 годы
  kaz: Бұқар жырау ауданы бойынша 2022-2023 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-06-30
approved_by:
- '160017000002'
version_date:
  kaz: 2022-06-30
  rus: 2022-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/170169/kaz/30.06.2022
  rus: https://zan.gov.kz/client/#!/doc/170169/rus/30.06.2022
