act_code: '170058'
requisite: Решение акима Осакаровского района Карагандинской области от 15 июля 2022 года № 02. Зарегистрировано в Министерстве юстиции Республики Казахстан 25 июля 2022 года № 28877. Утратило силу решением акима Осакаровского района Карагандинской области от 13 января  2023 года № 02 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба на территории села Сенокосное Каратомарского сельского округа Осакаровского района
  kaz: Осакаров ауданы Қаратомар ауылдық округінің Сенокосное ауылының аумағында жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-07-15
approved_by:
- '160018000003'
version_date:
  kaz: 2022-07-15
  rus: 2022-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/170058/kaz/15.07.2022
  rus: https://zan.gov.kz/client/#!/doc/170058/rus/15.07.2022
