act_code: '167641'
requisite: Решение акима Тегисшилдикского сельского округа Каркаралинского района Карагандинской области от 6 мая 2022 года № 3. Зарегистрировано в Министерстве юстиции Республики Казахстан 13 мая 2022 года № 28040. Утратило силу решением акима Тегисшилдикского сельского округа Каркаралинского района Карагандинской области от 7 июля 2022 года № 4 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-05-06
approved_by:
- '160013018002'
version_date:
  kaz: 2022-05-06
  rus: 2022-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/167641/kaz/06.05.2022
  rus: https://zan.gov.kz/client/#!/doc/167641/rus/06.05.2022
