act_code: '7571'
requisite: Решение Акима Карагандинской области от 9 ноября 2000 года № 204. Зарегистрировано управлением юстиции Карагандинской области 30 ноября 2000 года за № 145. Прекратило действие в связи с истечением срока письмом руководителя аппарата акима Карагандинской области от 21 января 2005 года № 05-11/89
title:
  rus: О мерах по подготовке и проведению празднования в Карагандинской области 10-летия принятия Конституционного закона Республики Казахстан "О государственной независимости Республики Казахстан"
  kaz: Қарағанды облысында "Қазақстан Республикасының мемлекеттік тәуелсіздігі туралы" Қазақстан Республикасының Конституциялық заңы қабылдануының 10 жылдығын мерекелеуге даярлану мен оны өткізу жөніндегі шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-11-09
approved_by:
- '160000000001'
version_date:
  kaz: 2000-11-09
  rus: 2000-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/7571/kaz/09.11.2000
  rus: https://zan.gov.kz/client/#!/doc/7571/rus/09.11.2000
