act_code: '43833'
requisite: Решение акима Осакаровского района Карагандинской области от 22 декабря 2008 года № 1. Зарегистрировано Управлением юстиции Осакаровского района Карагандинской области 27 января 2009 года № 8-15-97
title:
  rus: О проведении приписки граждан 1992 года рождения к призывному участку отдела по делам обороны Осакаровского района
  kaz: Осакаров ауданының қорғаныс істері жөніндегі бөлімнің шақыру учаскесінде 1992 жылы туған азаматтарға тіркеу өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-22
approved_by:
- '160018000001'
version_date:
  kaz: 2008-12-22
  rus: 2008-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/43833/kaz/22.12.2008
  rus: https://zan.gov.kz/client/#!/doc/43833/rus/22.12.2008
