act_code: '86374'
requisite: Решение 39 сессии Саранского городского маслихата Карагандинской области от 23 декабря 2014 года № 405. Зарегистрировано Департаментом юстиции Карагандинской области 26 января 2015 года № 2946. Утратило силу решением Саранского городского маслихата Карагандинской области от 23 июня 2022 года № 143 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества поселка Актас Карагандинской области
  kaz: Қарағанды облысы Ақтас кентінің бөлек жергілікті қоғамдастық жиындарын өткізу қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-23
approved_by:
- '160003000002'
version_date:
  kaz: 2016-12-22
  rus: 2016-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/86374/kaz/22.12.2016
  rus: https://zan.gov.kz/client/#!/doc/86374/rus/22.12.2016
caused_by:
  code: '108861'
  requisite: Решение 9 сессии Саранского городского маслихата Карагандинской области от 22 декабря 2016 года № 102. Зарегистрировано Департаментом юстиции Карагандинской области 4 января 2017 года № 4076. Утратило силу решением Саранского городского маслихата Карагандинской области от 23 июня 2022 года № 143 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение 39 сессии Саранского городского маслихата от 23 декабря 2014 года № 405 «Об утверждении Правил проведения раздельных сходов местного сообщества поселка Актас Карагандинской области»
    kaz: Саран қалалық мәслихатының 2014 жылғы 23 желтоқсандағы 39 сессиясының № 405 «Қарағанды облысы Ақтас кентінің бөлек жергілікті қоғамдастық жиындарын өткізу қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/108861/rus
