act_code: '147873'
requisite: Решение акима поселка Жаңаарқа Жанааркинского района Карагандинской области от 22 октября 2020 года № 355. Зарегистрировано Департаментом юстиции Карагандинской области 28 октября 2020 года № 6062
title:
  rus: Об установлении публичного сервитута
  kaz: Жария сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-10-22
approved_by:
- '160016014001'
version_date:
  kaz: 2020-10-22
  rus: 2020-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/147873/kaz/22.10.2020
  rus: https://zan.gov.kz/client/#!/doc/147873/rus/22.10.2020
