act_code: '62386'
requisite: Решение LIX сессии IV созыва Карагандинского городского маслихата от 12 декабря 2011 года № 611. Зарегистрировано Управлением юстиции города Караганды 30 декабря 2011 года № 8-1-146. Утратило силу решением Карагандинского городского маслихата от 15 мая 2019 года № 409 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об оказании ежемесячной социальной помощи отдельным категориям нуждающихся граждан города Караганды
  kaz: Қарағанды қаласының мұқтаж азаматтарының жекелеген санаттарына ай сайынғы әлеуметік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-12
approved_by:
- '160002000002'
version_date:
  kaz: 2012-01-24
  rus: 2012-01-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/62386/kaz/24.01.2012
  rus: https://zan.gov.kz/client/#!/doc/62386/rus/24.01.2012
