act_code: '16528'
requisite: Решение от 15.07.2003 №30/395, Маслихат г. Жезказгана
title:
  rus: Yйде тәрбиеленіп, оқитын мүгедек балаларға мекенжайлық әлеуметтік көмек тағайындау мен төлеудің Қағидасын бекіту туралы
  kaz: Yйде тәрбиеленіп, оқитын мүгедек балаларға мекенжайлық әлеуметтік көмек тағайындау мен төлеудің Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2003-07-14
approved_by:
- '160006000002'
version_date:
  kaz: 2003-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/16528/kaz/14.07.2003
