act_code: '209128'
requisite: Решение акима города Караганды от 11 апреля 2025 года № 02. Отменено решением акима города Караганды от 22 сентября 2025 года № 04 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масшатаба
  kaz: Жергілікті ауқымдағы табиғи сипаттағы төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-04-11
approved_by:
- '160002000003'
version_date:
  kaz: 2025-04-11
  rus: 2025-04-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/209128/kaz/11.04.2025
  rus: https://zan.gov.kz/client/#!/doc/209128/rus/11.04.2025
