act_code: '32861'
requisite: Қарағанды облысы Шет аудандық мәслихатының 2007 жылғы 9 сәуірдегі № 37/361 шешімі. Шет ауданы әділет басқармасында 2007 жылғы 23 сәуірде № 8-17-42 тіркелді
title:
  rus: Шет ауданының кент және ауылдық округтері аумағында тұрғындардың жеке меншік малдарының бағылуы жайындағы Ережені бкіту туралы
  kaz: Шет ауданының кент және ауылдық округтері аумағында тұрғындардың жеке меншік малдарының бағылуы жайындағы Ережені бкіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-04-09
approved_by:
- '160015000002'
version_date:
  kaz: 2007-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/32861/kaz/09.04.2007
