act_code: '155154'
requisite: Решение акима Доскейского сельского округа Бухар-Жырауского района Карагандинской области от 23 апреля 2021 года № 4. Зарегистрировано Департаментом юстиции Карагандинской области 26 апреля 2021 года № 6320. Утратило силу решением акима Доскейского сельского округа Бухар-Жырауского района Карагандинской области от 26 февраля 2025 года № 3-р (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации техногенного характера местного масштаба
  kaz: Жергілікті ауқымдағы техногендік сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-23
approved_by:
- '160017018002'
version_date:
  kaz: 2021-04-23
  rus: 2021-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/155154/kaz/23.04.2021
  rus: https://zan.gov.kz/client/#!/doc/155154/rus/23.04.2021
