act_code: '176199'
requisite: Решение Нуринского районного маслихата Карагандинской области от 22 декабря 2022 года № 208
title:
  rus: О бюджете сел, поселков и сельских округов на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған ауылдар, кенттер және ауылдық округтердің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-22
approved_by:
- '160012000002'
version_date:
  kaz: 2023-04-27
  rus: 2023-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/176199/kaz/27.04.2023
  rus: https://zan.gov.kz/client/#!/doc/176199/rus/27.04.2023
caused_by:
  code: '180731'
  requisite: Решение Нуринского районного маслихата Карагандинской области от 27 апреля 2023 года № 14
  title:
    rus: О внесении изменений в решение Нуринского районного маслихата от 22 декабря 2022 года № 208 «О бюджете сел, поселков и сельских округов на 2023-2025 годы»
    kaz: Нұра аудандық мәслихатының 2022 жылғы 22 желтоқсандағы № 208 «2023-2025 жылдарға арналған ауылдардың, кенттердің және ауылдық округтердің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/180731/rus
