act_code: '56296'
requisite: Решение 32 сессии Саранского городского маслихата Карагандинской области от 23 декабря 2010 года № 510. Зарегистрировано Управлением юстиции города Сарани Карагандинской области 30 декабря 2010 года № 8-7-115
title:
  rus: О городском бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '160003000002'
version_date:
  kaz: 2011-10-06
  rus: 2011-10-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/56296/kaz/06.10.2011
  rus: https://zan.gov.kz/client/#!/doc/56296/rus/06.10.2011
caused_by:
  code: '60849'
  requisite: Решение 40 сессии Саранского городского маслихата Карагандинской области от 6 октября 2011 года № 636. Зарегистрировано Управлением юстиции города Сарани Карагандинской области 18 октября 2011 года № 8-7-122
  title:
    rus: О внесении изменений в решение 32 сессии Саранского городского маслихата от 23 декабря 2010 года № 510 "О городском бюджете на 2011-2013 годы"
    kaz: Саран қалалық мәслихатының 2010 жылғы 23 желтоқсандағы 32 сессиясының "2011-2013 жылдарға арналған қалалық бюджет туралы" № 510 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/60849/rus
