act_code: '197188'
requisite: Решение акима Босагинского сельского округа Шетского района Карагандинской области от 23 мая 2024 года № 1
title:
  rus: Об установлении ограничительных мероприятии на территории Босагинского сельского округа с.Босага
  kaz: Босаға ауылдық округінің Босаға ауылы орталығының аумағына шектеу шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-05-23
approved_by:
- '160015009002'
version_date:
  kaz: 2024-05-23
  rus: 2024-05-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/197188/kaz/23.05.2024
  rus: https://zan.gov.kz/client/#!/doc/197188/rus/23.05.2024
