act_code: '108539'
requisite: Решение VIII сессии VI созыва Карагандинского городского маслихата от 30 ноября 2016 года № 91. Зарегистрировано Департаментом юстиции Карагандинской области 23 декабря 2016 года № 4062. Утратило силу решением Карагандинского городского маслихата от 15 июня 2020 года № 518 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил выдачи служебного удостоверения государственного учреждения «Аппарат Карагандинского городского маслихата» и его описания
  kaz: «Қарағанды қалалық мәслихатының аппараты» мемлекеттік мекемесінің қызметтік куәлікті беру қағидаларын және оның сипаттамасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-11-30
approved_by:
- '160002000002'
version_date:
  kaz: 2016-11-30
  rus: 2016-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/108539/kaz/30.11.2016
  rus: https://zan.gov.kz/client/#!/doc/108539/rus/30.11.2016
