act_code: '138462'
requisite: Решение Улытауского районного маслихата Карагандинской области от 30 декабря 2019 года № 342. Зарегистрировано Департаментом юстиции Карагандинской области 9 января 2020 года № 5674
title:
  rus: О районном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '160019000002'
version_date:
  kaz: 2020-04-28
  rus: 2020-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/138462/kaz/28.04.2020
  rus: https://zan.gov.kz/client/#!/doc/138462/rus/28.04.2020
caused_by:
  code: '142432'
  requisite: Решение Улытауского районного маслихата Карагандинской области от 28 апреля 2020 года № 368. Зарегистрировано Департаментом юстиции Карагандинской области 30 апреля 2020 года № 5815
  title:
    rus: О внесении изменений в решение XXXIX сессии Улытауского районного маслихата от 30 декабря 2019 года № 342 «О районном бюджете на 2020-2022 годы»
    kaz: Ұлытау аудандық мәслихатының 2019 жылғы 30 желтоқсандағы XXXIX сессиясының «2020-2022 жылдарға арналған аудандық бюджет туралы» № 342 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142432/rus
