act_code: '206715'
requisite: Решение акима поселка Топар Абайского района Карагандинской области от 20 января 2025 года № 1
title:
  rus: Об установлении АО «Национальная компания «Қазақстан темір жолы» публичного сервитута
  kaz: «Қазақстан темір жолы» Ұлттық компания» АҚ-ға жария сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-01-20
approved_by:
- '160011003001'
version_date:
  kaz: 2025-01-20
  rus: 2025-01-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/206715/kaz/20.01.2025
  rus: https://zan.gov.kz/client/#!/doc/206715/rus/20.01.2025
