act_code: '43017'
requisite: Қарағанды облысы Ақтоғай аудандық мәслихатының 10 сессиясының 2008 жылғы 23 желтоқсандағы № 115 шешімі. Қарағанды облысы Ақтоғай ауданы Әділет басқармасында 2008 жылғы 29 желтоқсанда № 8-10-77 тіркелді. Күші жойылды - Қарағанды облысы Ақтоғай аудандық мәслихатының 18 сессиясының 2009 жылғы 23 желтоқсандағы № 192 шешімімен
title:
  rus: Ұлы Отан соғысының қатысушыларына, мүгедектеріне және соларға теңестірілген адамдарға, ардагерлерге және 1, 2 топтағы мүгедек азаматтарға, аз қамтамасыз етілген отбасыларға қаржылай, заттай көмек көрсету мөлшерлемесі туралы
  kaz: Ұлы Отан соғысының қатысушыларына, мүгедектеріне және соларға теңестірілген адамдарға, ардагерлерге және 1, 2 топтағы мүгедек азаматтарға, аз қамтамасыз етілген отбасыларға қаржылай, заттай көмек көрсету мөлшерлемесі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-23
approved_by:
- '160014000002'
version_date:
  kaz: 2008-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/43017/kaz/23.12.2008
