act_code: '186846'
requisite: Решение Шетского районного маслихата Карагандинской области от 22 сентября 2023 года № 5/52
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Шетскому району на 2024-2025 годы
  kaz: Шет ауданы бойынша 2024-2025 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-09-22
approved_by:
- '160015000002'
version_date:
  kaz: 2023-09-22
  rus: 2023-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/186846/kaz/22.09.2023
  rus: https://zan.gov.kz/client/#!/doc/186846/rus/22.09.2023
