act_code: '30379'
requisite: Решение XL сессии III созыва Карагандинского городского маслихата от 1 ноября 2006 года № 5. Зарегистрировано Управлением юстиции города Караганды Карагандинской области 21 ноября 2006 года № 8-1-44. Утратило силу решением III сессии IV созыва Карагандинского городского маслихата от 9 ноября 2007 года № 24
title:
  rus: Об установлении ставок фиксированного суммарного налога на отдельные виды предпринимательской деятельности
  kaz: Кәсіпкерлік қызметінің жекелеген түрлеріне тіркелген жиынтық салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-11-01
approved_by:
- '160002000002'
version_date:
  kaz: 2006-11-01
  rus: 2006-11-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/30379/kaz/01.11.2006
  rus: https://zan.gov.kz/client/#!/doc/30379/rus/01.11.2006
