act_code: '207417'
requisite: Решение Актогайского районного маслихата Карагандинской области от 20 февраля 2025 года № 259. Зарегистрировано Департаментом юстиции Карагандинской области 27 февраля 2025 года № 6721-09. Утратило силу решением Актогайского районного маслихата Карагандинской области от 8 мая 2026 года № 393 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Актогайского района
  kaz: Ақтоғай ауданының Әлеуметтiк көмек көрсетудің, оның мөлшерлерiн белгiлеудің және мұқтаж азаматтардың жекелеген санаттарының тiзбесiн айқындаудың қағидаларын бекiту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-02-20
approved_by:
- '160014000002'
version_date:
  kaz: 2025-02-20
  rus: 2025-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/207417/kaz/20.02.2025
  rus: https://zan.gov.kz/client/#!/doc/207417/rus/20.02.2025
