act_code: '79793'
requisite: Решение XХVI сессии V созыва Шахтинского городского маслихата Карагандинской области от 14 апреля 2014 года № 1010/26. Зарегистрировано Департаментом юстиции Карагандинской области 11 мая 2014 года № 2636. Утратило силу решением Шахтинского городского маслихата Карагандинской области от 5 мая 2016 года № 1292/2
title:
  rus: Об утверждении Регламента Шахтинского городского маслихата
  kaz: Шахтинск қалалық мәслихатының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-04-14
approved_by:
- '160004000002'
version_date:
  kaz: 2014-12-23
  rus: 2014-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/79793/kaz/23.12.2014
  rus: https://zan.gov.kz/client/#!/doc/79793/rus/23.12.2014
caused_by:
  code: '86132'
  requisite: Решение XXXII сессии V созыва Шахтинского городского маслихата Карагандинской области от 23 декабря 2014 года № 1095/32. Зарегистрировано Департаментом юстиции Карагандинской области 21 января 2015 года № 2942. Утратило силу решением Шахтинского городского маслихата Карагандинской области от 11 октября 2017 года № 1446/17
  title:
    rus: О внесении изменений в решение XХVI сессии Шахтинского городского маслихата от 14 апреля 2014 года № 1010/26 «Об утверждении Регламента Шахтинского городского маслихата»
    kaz: Шахтинск қалалық мәслихатының 2014 жылғы 14 сәуірдегі XХVI сессиясының № 1010/26 «Шахтинск қалалық мәслихатының Регламентін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86132/rus
