act_code: '79793'
requisite: Решение XХVI сессии V созыва Шахтинского городского маслихата Карагандинской области от 14 апреля 2014 года № 1010/26. Зарегистрировано Департаментом юстиции Карагандинской области 11 мая 2014 года № 2636. Утратило силу решением Шахтинского городского маслихата Карагандинской области от 5 мая 2016 года № 1292/2
title:
  rus: Об утверждении Регламента Шахтинского городского маслихата
  kaz: Шахтинск қалалық мәслихатының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-04-14
approved_by:
- '160004000002'
version_date:
  kaz: 2014-04-14
  rus: 2014-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/79793/kaz/14.04.2014
  rus: https://zan.gov.kz/client/#!/doc/79793/rus/14.04.2014
