act_code: '34557'
requisite: Решение XXХIV сессии Каражалского городского маслихата Карагандинской области от 12 июля 2007 года N 34/350. Зарегистрировано управлением юстиции города Каражал Карагандинской области 3 августа 2007 года N 8-5-37. Утратило силу решением Каражалского городского маслихата Карагандинской области от 24 июня 2014 года № 242
title:
  rus: О дополнительном регламентировании порядка проведения собраний, митингов, шествий, пикетов и демонстраций
  kaz: Жиналыстар, митингтер, шерулер, пикеттер және демонcтрациялар өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-07-12
approved_by:
- '160010000002'
version_date:
  kaz: 2007-07-12
  rus: 2007-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/34557/kaz/12.07.2007
  rus: https://zan.gov.kz/client/#!/doc/34557/rus/12.07.2007
