act_code: '20075'
requisite: Қарағанды облысы Саран қалалық мәслихатының 8 сессиясының 2004 жылғы 25 мамырдағы № 108 шешімі. Қарағанды облысының әділет Департаментінде 2004 жылғы 1 маусымда № 1530 тіркелді. Күші жойылды - Қарағанды облысы Cаран қаласы мәслихатының 36 сессиясының 2007 жылғы 13 маусымдағы № 583 шешімімен
title:
  rus: Саран қалалық мәслихаттың Регламентін бекіту туралы
  kaz: Саран қалалық мәслихаттың Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2004-05-24
approved_by:
- '160003000002'
version_date:
  kaz: 2006-06-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/20075/kaz/08.06.2006
caused_by:
  code: '28630'
  requisite: Қарағанды облысы Cаран қаласының мәслихатының 27 сессиясының 2006 жылғы 8 маусымдағы № 443 шешімі. Cаран қаласы әділет басқармасында 2006 жылғы 3 шілдеде № 8-7-25 тіркелді. Күші жойылды - Қарағанды облысы Cаран қаласы мәслихатының 36 сессиясының 2007 жылғы 13 маусымдағы № 583 шешімімен
  title:
    rus: 2004 жылғы 25 мамырдағы "Саран қалалық мәслихаттың Регламентін бекіту туралы" № 108 шешіміне толықтыру енгізу туралы
    kaz: 2004 жылғы 25 мамырдағы "Саран қалалық мәслихаттың Регламентін бекіту туралы" № 108 шешіміне толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/28630/rus
