act_code: '35702'
requisite: Решение 2 сессии Бухар Жырауского районного маслихата Карагандинской области от 22 октября 2007 года № 5. Зарегистрировано Управлением юстиции Бухар Жырауского района Карагандинской области 13 ноября 2007 года № 8-11-48. Утратило силу решением Бухар-Жырауского районного маслихата Карагандинской области от 31 октября 2014 года № 5
title:
  rus: Об утверждении размера социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры и спорта, проживающим и работающим в сельских населенных пунктах
  kaz: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмектің көлемін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-10-22
approved_by:
- '160017000002'
version_date:
  kaz: 2008-12-19
  rus: 2008-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/35702/kaz/19.12.2008
  rus: https://zan.gov.kz/client/#!/doc/35702/rus/19.12.2008
caused_by:
  code: '43464'
  requisite: Решение 10 сессии Бухар-Жырауского районного маслихата Карагандинской области от 19 декабря 2008 года № 7. Зарегистрировано Управлением юстиции Бухар-Жырауского района Карагандинской области 12 января 2009 года № 8-11-68. Утратило силу решением Бухар-Жырауского районного маслихата Карагандинской области от 31 октября 2014 года № 5
  title:
    rus: О внесении изменения в решение 2 сессии Бухар-Жырауского районного Маслихата от 22 октября 2007 года № 5 "Об утверждении размера социальной  помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры и спорта, проживающим и работающим в сельских населенных пунктах"
    kaz: Бұқар жырау аудандық мәслихатының 2007 жылғы 22 қазандағы 2 сессиясының "Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмектің көлемін бекіту туралы" № 5 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/43464/rus
