act_code: '213029'
requisite: Решение Каркаралинского районного маслихата Карагандинской области от 31 июля 2025 года № VIII-40/310
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Каркаралинскому району на 2025- 2029 годы
  kaz: Қарқаралы ауданы бойынша 2025 - 2029 жылдарға арналған жайылымдарды басқару және оларды пайдалану жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-07-31
approved_by:
- '160013000002'
version_date:
  kaz: 2025-07-31
  rus: 2025-07-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/213029/kaz/31.07.2025
  rus: https://zan.gov.kz/client/#!/doc/213029/rus/31.07.2025
