act_code: '137868'
requisite: Решение Абайского районного маслихата Карагандинской области от 27 декабря 2019 года № 58/634. Зарегистрировано Департаментом юстиции Карагандинской области 31 декабря 2019 года № 5635
title:
  rus: O бюджетах города районного значения, сел, поселков, сельских округов на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық маңызы бар қаланың, ауылдардың, кенттердің, ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '160011000002'
version_date:
  kaz: 2020-11-12
  rus: 2020-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/137868/kaz/12.11.2020
  rus: https://zan.gov.kz/client/#!/doc/137868/rus/12.11.2020
caused_by:
  code: '148627'
  requisite: Решение Абайского районного маслихата Карагандинской области от 12 ноября 2020 года № 72/753. Зарегистрировано Департаментом юстиции Карагандинской области 18 ноября 2020 года № 6086
  title:
    rus: О внесении изменений в решение 58 сессии Абайского районного маслихата от 27 декабря 2019 года № 58/634 «O бюджетах города районного значения, сел, поселков, сельских округов на 2020-2022 годы»
    kaz: Абай аудандық мәслихатының 2019 жылғы 27 желтоқсандағы 58 сессиясының № 58/634 «2020-2022 жылдарға арналған аудандық маңызы бар қаланың, ауылдардың, кенттердің, ауылдық округтердің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148627/rus
