act_code: '137868'
requisite: Решение Абайского районного маслихата Карагандинской области от 27 декабря 2019 года № 58/634. Зарегистрировано Департаментом юстиции Карагандинской области 31 декабря 2019 года № 5635
title:
  rus: O бюджетах города районного значения, сел, поселков, сельских округов на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық маңызы бар қаланың, ауылдардың, кенттердің, ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '160011000002'
version_date:
  kaz: 2019-12-27
  rus: 2019-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/137868/kaz/27.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137868/rus/27.12.2019
