act_code: '56202'
requisite: Решение XLIII сессии IV созыва Карагандинского городского маслихата от 23 декабря 2010 года № 442. Зарегистрировано Управлением юстиции города Караганды 27 декабря 2010 года № 8-1-121
title:
  rus: О бюджете города Караганды на 2011-2013 годы
  kaz: Қарағанды қаласының 2011-2013 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '160002000002'
version_date:
  kaz: 2010-12-23
  rus: 2010-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/56202/kaz/23.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56202/rus/23.12.2010
