act_code: '8142'
requisite: Решение VIII сессии Карагандинского областного Маслихата от 29 декабря 2000 года № 4. Зарегистрировано Управлением юстиции Карагандинской области 10 января 2001 года за № 173. Утратило силу в связи с истечением срока действия письмом Карагандинского областного Маслихата от 17 января 2005 года № 1-12/40
title:
  rus: Об утверждении региональной программы борьбы с наркоманией и наркобизнесом в Карагандинской области на 2001 год
  kaz: Қарағанды облысында нашақорлықпен және есірткіүбизнесімен күрестің 2001 жылға арналған аймақтық бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-12-29
approved_by:
- '160000000002'
version_date:
  kaz: 2000-12-29
  rus: 2000-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/8142/kaz/29.12.2000
  rus: https://zan.gov.kz/client/#!/doc/8142/rus/29.12.2000
