act_code: '49872'
requisite: Қарағанды облысы Шет аудандық мәслихатының 2009 жылғы 21 желтоқсандағы № 19/220 шешімі. Қарағанды облысы Шет ауданының Әділет басқармасында 2010 жылғы 12 қаңтарда № 8-17-88 тіркелді
title:
  rus: 2010 жылға бір жолғы талон құнын белгілеу туралы
  kaz: 2010 жылға бір жолғы талон құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '160015000002'
version_date:
  kaz: 2009-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/49872/kaz/21.12.2009
