act_code: '139149'
requisite: Решение акима Бухар-Жырауского района Карагандинской области от 27 января 2020 года № 1. Зарегистрировано Департаментом юстиции Карагандинской области 30 января 2020 года № 5691
title:
  rus: Об образовании избирательных участков на территории Бухар-Жырауского района
  kaz: Бұқар жырау ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-27
approved_by:
- '160017000003'
version_date:
  kaz: 2025-01-22
  rus: 2025-01-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/139149/kaz/22.01.2025
  rus: https://zan.gov.kz/client/#!/doc/139149/rus/22.01.2025
caused_by:
  code: '206796'
  requisite: Решение акима Бухар-Жырауского района Карагандинской области от 22 января 2025 года № 1. Зарегистрировано Департаментом юстиции Карагандинской области 27 января 2025 года № 6703-09
  title:
    rus: О внесении изменения в решение акима района от 27 января 2020 года № 1 «Об образовании избирательных участков на территории Бухар-Жырауского района»
    kaz: Аудан әкімінің 2020 жылғы 27 қаңтардағы № 1 «Бұқар жырау ауданының аумағында сайлау учаскелерін құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/206796/rus
