act_code: '126135'
requisite: Решение акима города Приозерск Карагандинской области от 9 ноября 2018 года № 1. Зарегистрировано Департаментом юстиции Карагандинской области 15 ноября 2018 года № 5006. Утратило силу решением акима города Приозерск Карагандинской области от 6 сентября 2019 года № 3 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков в городе Приозерск
  kaz: Приозерск қаласында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-09
approved_by:
- '160009000003'
version_date:
  kaz: 2018-11-09
  rus: 2018-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/126135/kaz/09.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126135/rus/09.11.2018
