act_code: '14914'
requisite: Қарағанды облысы Жаңаарқа аудандық мәслихатының кезектен тыс XXV сессиясының 2003 жылғы 17 ақпандағы № 25/218 шешімі. Қарағанды облысының Әділет басқармасында 2003 жылғы 11 наурызда № 1098 тіркелді. Күші жойылды - Қарағанды облысы Жаңаарқа ауданы мәслихатының 2012 жылғы 28 қыркүйектегі № 9/60 шешімімен
title:
  rus: Жаңаарқа ауданында «Ветеринария туралы» заң талаптарын сақтау қағидасын бекіту туралы
  kaz: Жаңаарқа ауданында «Ветеринария туралы» заң талаптарын сақтау қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2003-02-17
approved_by:
- '160016000002'
version_date:
  kaz: 2003-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/14914/kaz/17.02.2003
