act_code: '9155'
requisite: Решение Акима Карагандинской области от 28 апреля 2001 года № 74. Зарегистрировано управлением юстиции Карагандинской области 18 мая 2001 года за № 289. Утратило силу решением акима Карагандинской области от 14 мая 2004 года № 44
title:
  rus: Вопросы залогового обеспечения при кредитовании субъектов малого предпринимательства
  kaz: Шағын кәсіпкерлік субъектілеріне несие беру кепілдігін қамтамасыз ету мәселелері
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-04-27
approved_by:
- '160000000001'
version_date:
  kaz: 2001-04-27
  rus: 2001-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/9155/kaz/27.04.2001
  rus: https://zan.gov.kz/client/#!/doc/9155/rus/27.04.2001
