act_code: '43769'
requisite: Решение 10 сессии Саранского городского маслихата Карагандинской области от 19 декабря 2008 года № 197. Зарегистрировано Управлением юстиции города Сарани Карагандинской области 27 января 2009 года № 8-7-79
title:
  rus: О предоставлении социальной помощи отдельным категориям нуждающихся граждан по решению местных представительных органов на 2009 год
  kaz: Жергілікті өкілетті органдардың шешімі бойынша 2009 жылы мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '160003000002'
version_date:
  kaz: 2009-02-26
  rus: 2009-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/43769/kaz/26.02.2009
  rus: https://zan.gov.kz/client/#!/doc/43769/rus/26.02.2009
caused_by:
  code: '45111'
  requisite: Решение 13 сессии Саранского городского маслихата Карагандинской области от 26 февраля 2009 года № 226. Зарегистрировано Управлением юстиции города Сарани Карагандинской области 1 апреля 2009 года № 8-7-81
  title:
    rus: О внесении изменений и дополнений в решение 10 сессии Саранского городского маслихата Карагандинской области от 19 декабря 2008 года № 197 "О предоставлении социальной помощи отдельным категориям нуждающихся граждан по решению местных представительных органов на 2009 год"
    kaz: Қарағанды облысы Саран қалалық мәслихатының 2008 жылғы 19 желтоқсандағы 10 сессиясының "Жергілікті өкілетті органдардың шешімі бойынша 2009 жылы мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек беру туралы" № 197 шешіміне өзгертулер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/45111/rus
