act_code: '43217'
requisite: Решение Темиртауского городского маслихата Карагандинской области от 25 декабря 2008 года № 14/4. Зарегистрировано Управлением юстиции города Темиртау Карагандинской области 8 января 2009 года № 8-3-68. Утратило силу в связи с истечением срока действия (письмо Темиртауского городского маслихата Карагандинской области от 25 февраля 2010 года № 5-24/70)
title:
  rus: О городском бюджете на 2009 год
  kaz: 2009 жылға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '160005000002'
version_date:
  kaz: 2009-11-23
  rus: 2009-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/43217/kaz/23.11.2009
  rus: https://zan.gov.kz/client/#!/doc/43217/rus/23.11.2009
caused_by:
  code: '49088'
  requisite: Решение Темиртауского городского маслихата Карагандинской области от 23 ноября 2009 года № 21/4. Зарегистрировано Управлением юстиции города Темиртау Карагандинской области 7 декабря 2009 года № 8-3-88
  title:
    rus: О внесении изменений и дополнений в решение 14 сессии Темиртауского городского маслихата от 25 декабря 2008 года № 14/4 "О городском бюджете на 2009 год"
    kaz: Теміртау қалалық мәслихатының 2008 жылғы 25 желтоқсандағы 14 сессиясының "2009 жылға арналған қалалық бюджет туралы" № 14/4 шешіміне өзгертулер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/49088/rus
