act_code: '120252'
requisite: Решение ХIV сессии Карагандинского областного маслихата от 29 марта 2018 года № 289. Зарегистрировано Департаментом юстиции Карагандинской области 4 апреля 2018 года № 4678. Утратило силу решением Карагандинского областного маслихата от 2 июля 2020 года № 553 (вводится в действие со дня его первого официального опубликования)
title:
  rus: О предоставлении лекарственных средств дополнительно
  kaz: Дәрілік заттарды қосымша беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-29
approved_by:
- '160000000002'
version_date:
  kaz: 2018-03-29
  rus: 2018-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/120252/kaz/29.03.2018
  rus: https://zan.gov.kz/client/#!/doc/120252/rus/29.03.2018
