act_code: '42991'
requisite: Решение Сатпаевского городского маслихата Карагандинской области от 19 декабря 2008 года № 175. Зарегистрировано Управлением юстиции города Сатпаев Карагандинской области 29 декабря 2008 года № 8-6-74
title:
  rus: О городском бюджете на 2009 год
  kaz: 2009 жылға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '160007000002'
version_date:
  kaz: 2009-11-20
  rus: 2009-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/42991/kaz/20.11.2009
  rus: https://zan.gov.kz/client/#!/doc/42991/rus/20.11.2009
caused_by:
  code: '48825'
  requisite: Решение Сатпаевского городского маслихата Карагандинской области от 20 ноября 2009 года № 262. Зарегистрировано Управлением юстиции города Сатпаев Карагандинской области 25 ноября 2009 года № 8-6-91
  title:
    rus: О внесении изменений и дополнений в решение ХV сессии Сатпаевского городского маслихата от 19 декабря 2008 года № 175 "О городском бюджете на 2009 год"
    kaz: '"2009 жылға арналған қалалық бюджет туралы" Сәтбаев қалалық мәслихатының 2008 жылғы 19 желтоқсандағы ХV сессиясының № 175 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/48825/rus
