act_code: '43060'
requisite: Решение XVI сессии IV созыва Карагандинского городского маслихата от 24 декабря 2008 года № 184. Зарегистрировано управлением юстиции города Караганды Карагандинской области 26 декабря 2008 года № 8-1-85. Утратило силу - решением Карагандинского городского маслихата от 23 декабря 2009 года № 301
title:
  rus: О льготном проезде на внутригородском общественном транспорте (кроме такси) учащихся очной формы обучения
  kaz: Күндізгі оқу нысанында оқитын оқушылардың қала ішіндегі қоғамдық көлікте (таксиден басқа) жеңілдікпен жүруі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '160002000002'
version_date:
  kaz: 2009-04-29
  rus: 2009-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/43060/kaz/29.04.2009
  rus: https://zan.gov.kz/client/#!/doc/43060/rus/29.04.2009
caused_by:
  code: '46244'
  requisite: Решение XXII сессии IV созыва Карагандинского городского маслихата от 29 апреля 2009 года № 215. Зарегистрировано Управлением юстиции города Караганды Карагандинской области 29 мая 2009 года № 8-1-92. Утратило силу - решением Карагандинского городского маслихата от 23 декабря 2009 года № 301
  title:
    rus: О внесении изменений в решение № 184 от 24 декабря 2008 года Карагандинского городского маслихата "О льготном проезде на внутригородском общественном транспорте (кроме такси) учащихся очной формы обучения"
    kaz: Қарағанды қалалық мәслихатының 2008 жылғы 24 желтоқсанындағы "Күндізгі оқу нысанында оқитын оқушылардың қала ішіндегі қоғамдық көлікте (таксиден басқа) жеңілдікпен жүруі туралы" № 184 шешіміне өзгертулер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/46244/rus
