act_code: '128853'
requisite: Решение Абайского районного маслихата Карагандинской области от 10 января 2019 года № 42/460. Зарегистрировано Департаментом юстиции Карагандинской области 24 января 2019 года № 5163
title:
  rus: О повышении или понижении ставок земельного налога для целей налогообложения на территории города Абай Карагандинской области
  kaz: Қарағанды облысы Абай қаласының аумағында салық салу мақсатында жер салығының мөлшерлемелерін арттыру немесе азайту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-10
approved_by:
- '160011000002'
version_date:
  kaz: 2022-02-17
  rus: 2022-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/128853/kaz/17.02.2022
  rus: https://zan.gov.kz/client/#!/doc/128853/rus/17.02.2022
caused_by:
  code: '164779'
  requisite: Решение Абайского районного маслихата Карагандинской области от 17 февраля 2022 года № 18/172. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 февраля 2022 года № 26913
  title:
    rus: О внесении изменений в решение Абайского районного маслихата от 10 января 2019 года № 42/460 «Об утверждении схемы зонирования территории города Абай Карагандинской области с понижающими или повышающими ставками земельного налога для целей налогообложения»
    kaz: Абай аудандық мәслихатының 2019 жылғы 10 қаңтардағы № 42/460 «Салық салу мақсаты үшін жер салығының мөлшерлемелері азайтылған немесе арттырылған Қарағанды облысы Абай қаласының аумағын аймақтарға бөлу сызбасын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/164779/rus
