act_code: '56173'
requisite: Решение акима города Сарани Карагандинской области от 20 декабря 2010 года № 01. Зарегистрировано Управлением юстиции города Сарани Карагандинской области 24 декабря 2010 года № 8-7-113
title:
  rus: О проведении приписки граждан 1994 года рождения к призывному участку отдела по делам обороны города Сарань в 2011 году
  kaz: 2011 жылы 1994 жылы туған азаматтардың Саран қаласының қорғаныс істері жөніндегі бөлімінің әскерге шақыру учаскесінің есебіне алынуын өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-20
approved_by:
- '160003000001'
version_date:
  kaz: 2010-12-20
  rus: 2010-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/56173/kaz/20.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56173/rus/20.12.2010
