act_code: '31648'
requisite: Қарағанды облысы Жезқазған қалалық мәслихатының 2005 жылғы 14 желтоқсандағы № 24/261 шешімі. Қарағанды облысы Жезқазған қаласы Әділет басқармасында 2005 жылғы 27 желтоқсанда № 8-2-14 тіркелді
title:
  rus: 2006 жылға арналған қалалық бюджет туралы
  kaz: 2006 жылға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-12-14
approved_by:
- '160006000002'
version_date:
  kaz: 2005-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/31648/kaz/14.12.2005
