act_code: '56119'
requisite: Решение XХХ сессии Карагандинского областного маслихата от 13 декабря 2010 года № 359. Зарегистрировано Департаментом юстиции Карагандинской области 23 декабря 2010 года № 1887
title:
  rus: Об областном бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-13
approved_by:
- '160000000002'
version_date:
  kaz: 2011-07-29
  rus: 2011-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/56119/kaz/29.07.2011
  rus: https://zan.gov.kz/client/#!/doc/56119/rus/29.07.2011
caused_by:
  code: '59980'
  requisite: Решение XХХVI сессии Карагандинского областного маслихата от 29 июля 2011 года № 419. Зарегистрировано Департаментом юстиции Карагандинской области 8 августа 2011 года № 1897
  title:
    rus: О внесении изменений в решение XXX сессии Карагандинского областного маслихата от 13 декабря 2010 года № 359 "Об областном бюджете на 2011-2013 годы"
    kaz: Қарағанды облыстық мәслихатының 2010 жылғы 13 желтоқсандағы XXX сессиясының "2011-2013 жылдарға арналған облыстық бюджет туралы" № 359 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/59980/rus
