act_code: '49871'
requisite: Қарағанды облысы Шет аудандық мәслихатының 2009 жылғы 21 желтоқсандағы № 19/221 шешімі. Қарағанды облысы Шет ауданының Әділет басқармасында 2010 жылғы 12 қаңтарда № 8-17-87 тіркелді
title:
  rus: 2010 жылға жер салығының базалық ставкаларын төмендетіп және жоғарылатып бекіту туралы
  kaz: 2010 жылға жер салығының базалық ставкаларын төмендетіп және жоғарылатып бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '160015000002'
version_date:
  kaz: 2009-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/49871/kaz/21.12.2009
