act_code: '20052'
requisite: Қарағанды облысы Ұлытау аудандық Мәслихатының VI сессиясының 2004 жылғы 21 мамырдағы № 6-3 шешімі. Қарағанды облысының әділет Департаментінде 2004 жылғы 1 маусымда № 1529 тіркелді
title:
  rus: Аудандық Мәслихаттың Регламентін бекіту туралы
  kaz: Аудандық Мәслихаттың Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2004-05-20
approved_by:
- '160019000002'
version_date:
  kaz: 2004-05-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/20052/kaz/20.05.2004
