act_code: '13501'
requisite: Решение XХII сессии Бухар-Жырауского районного маслихата Карагандинской области от 7 ноября 2002 года № 6. Зарегистрировано Департаментом юстиции Карагандинской области 26 ноября 2002 года № 1011. Утратило силу решением 5 сессии Бухар-Жырауского районного маслихата Карагандинской области от 23 марта 2004 года № 5
title:
  rus: Об установлении ставок земельного налога на земли, занятые под автостоянки, автозаправочные станции и рынки
  kaz: Автотұрақтар, жанар-жағар май құю станциялары және базарлар алып жатқан жерлерге жер салығының мөлшерлемесін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-11-07
approved_by:
- '160017000002'
version_date:
  kaz: 2002-11-07
  rus: 2002-11-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/13501/kaz/07.11.2002
  rus: https://zan.gov.kz/client/#!/doc/13501/rus/07.11.2002
