act_code: '150364'
requisite: Решение Жанааркинского районного маслихата Карагандинской области от 10 декабря 2020 года № 64/517. Зарегистрировано Департаментом юстиции Карагандинской области 24 декабря 2020 года № 6131
title:
  rus: Об утверждении Правил и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Жанааркинского района
  kaz: Жаңаарқа ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету қағидалары мен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-12-10
approved_by:
- '160016000002'
version_date:
  kaz: 2022-05-17
  rus: 2022-05-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/150364/kaz/17.05.2022
  rus: https://zan.gov.kz/client/#!/doc/150364/rus/17.05.2022
caused_by:
  code: '167828'
  requisite: Решение Жанааркинского районного маслихата Карагандинской области от 17 мая 2022 года № 24/169. Зарегистрировано в Министерстве юстиции Республики Казахстан 18 мая 2022 года № 28089
  title:
    rus: О внесении изменения в решение Жанааркинского районного маслихата от 10 декабря 2020 года № 64/517 «Об утверждении Правил и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Жанааркинского района»
    kaz: Жаңаарқа аудандық мәслихатының 2020 жылғы 10 желтоқсандағы № 64/517 «Жаңаарқа ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету қағидалары мен мөлшерін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/167828/rus
