act_code: '144311'
requisite: Решение Каражалского городского маслихата Карагандинской области от 24 июня 2020 года № 410. Зарегистрировано Департаментом юстиции Карагандинской области 1 июля 2020 года № 5917. Утратило силу решением Каражалского городского маслихата области Ұлытау от 17 марта 2025 года № 248 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов
  kaz: Тұрғын үй сертификаттарының мөлшерін және алушылар санатының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-24
approved_by:
- '160010000002'
version_date:
  kaz: 2023-05-18
  rus: 2023-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/144311/kaz/18.05.2023
  rus: https://zan.gov.kz/client/#!/doc/144311/rus/18.05.2023
caused_by:
  code: '181790'
  requisite: Решение Каражалского городского маслихата области Ұлытау от 18 мая 2023 года № 28. Зарегистрировано Департаментом юстиции области Ұлытау 23 мая 2023 года № 16-20. Утратило силу решением Каражалского городского маслихата области Ұлытау от 17 марта 2025 года № 248 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Каражалского городского маслихата от 24 июня 2020 года № 410 «Об определении размера и перечня категорий получателей жилищных сертификатов»
    kaz: Қаражал қалалық мәслихатының 2020 жылғы 24 маусымдағы № 410 «Тұрғын үй сертификаттарының мөлшерін және алушылар санатының тізбесін айқындау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/181790/rus
