act_code: '168741'
requisite: Решение акима сельского округа Акмешит Нуринского района Карагандинской области от 3 июня 2022 года № 2. Зарегистрировано в Министерстве юстиции Республики Казахстан 10 июня 2022 года № 28428. Утратило силу решением акима сельского округа Акмешит Нуринского района Карагандинской области от 4 августа 2022 года № 5 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий на территории села Кантай сельского округа Акмешит Нуринского района
  kaz: Нұра ауданы Ақмешіт ауылдық округі Қантай ауылының аумағында шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-06-03
approved_by:
- '160012008002'
version_date:
  kaz: 2022-06-03
  rus: 2022-06-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/168741/kaz/03.06.2022
  rus: https://zan.gov.kz/client/#!/doc/168741/rus/03.06.2022
