act_code: '54832'
requisite: Қарағанды облысы Ұлытау аудандық мәслихатының XXIII сессиясының 2010 жылғы 20 тамыздағы № 261 шешімі. Қарағанды облысы Ұлытау ауданының Әділет басқармасында 2010 жылғы 6 қазанда № 8-16-64 тіркелді. Күші жойылды - Қарағанды облысы Ұлытау аудандық мәслихатының XXX сессиясының 2011 жылғы 16 қыркүйектегі № 360 шешімімен
title:
  rus: Ұлытау ауданының салық салу мақсатында жерді аймақтандырудың аудандық сызбасын бекіту туралы
  kaz: Ұлытау ауданының салық салу мақсатында жерді аймақтандырудың аудандық сызбасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
- СХЕМ
approved_on: 2010-08-20
approved_by:
- '160019000002'
version_date:
  kaz: 2010-08-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/54832/kaz/20.08.2010
