act_code: '56508'
requisite: Решение 34 сессии Бухар-Жырауского районного маслихата Карагандинской области от 23 декабря 2010 года № 8. Зарегистрировано Управлением юстиции Бухар-Жырауского района Карагандинской области 6 января 2011 года № 8-11-109
title:
  rus: О предоставлении мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры и спорта, прибывшим для работы и проживания в сельские населенные пункты Бухар-Жырауского района в 2011 году
  kaz: 2011 жылы Бұқар жырау ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '160017000002'
version_date:
  kaz: 2010-12-23
  rus: 2010-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/56508/kaz/23.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56508/rus/23.12.2010
