act_code: '36388'
requisite: Решение IV сессии Каражалского городского маслихата Карагандинской области от 21 декабря 2007 года № 37. Зарегистрировано управлением юстиции города Каражал Карагандинской области 28 декабря 2007 года № 8-5-47. Утратило силу в связи с истечением срока применения (письмо Каражалского городского маслихата Карагандинской области от 28 июня 2013 года № 1-24/167)
title:
  rus: О бюджете города на 2008 год
  kaz: 2008 жылға арналған қала бюджетi туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-21
approved_by:
- '160010000002'
version_date:
  kaz: 2007-12-21
  rus: 2007-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/36388/kaz/21.12.2007
  rus: https://zan.gov.kz/client/#!/doc/36388/rus/21.12.2007
