act_code: '69473'
requisite: Решение X сессии Карагандинского областного маслихата от 5 декабря 2012 года № 107. Зарегистрировано Департаментом юстиции Карагандинской области 24 декабря 2012 года № 2058
title:
  rus: Об областном бюджете на 2013-2015 годы
  kaz: 2013-2015 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-05
approved_by:
- '160000000002'
version_date:
  kaz: 2012-12-05
  rus: 2012-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/69473/kaz/05.12.2012
  rus: https://zan.gov.kz/client/#!/doc/69473/rus/05.12.2012
