act_code: '76931'
requisite: Решение Балхашского городского маслихата Карагандинской области от 24 декабря 2013 года № 24/176. Зарегистрировано Департаментом юстиции Карагандинской области 20 января 2014 года № 2519. Утратило силу решением Балхашского городского маслихата Карагандинской области от 3 ноября 2023 года № 8/71 (вводится в действие по истечению десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-12-24
approved_by:
- '160008000002'
version_date:
  kaz: 2016-12-23
  rus: 2016-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/76931/kaz/23.12.2016
  rus: https://zan.gov.kz/client/#!/doc/76931/rus/23.12.2016
caused_by:
  code: '109385'
  requisite: Решение Балхашского городского маслихата Карагандинской области от 23 декабря 2016 года № 7/67. Зарегистрировано Департаментом юстиции Карагандинской области 13 января 2017 года № 4108. Утратило силу решением Балхашского городского маслихата Карагандинской области от 3 ноября 2023 года № 8/71 (вводится в действие по истечению десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение городского маслихата от 24 декабря 2013 года № 24/176 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Қалалық мәслихаттың 2013 жылғы 24 желтоқсандағы № 24/176 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін  айқындаудың Қағидаларын бекіту туралы» шешіміне өзгертулер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/109385/rus
