act_code: '26432'
requisite: Қарағанды облысы Қарқаралы аудандық мәслихатының 2005 жылғы 14 желтоқсандағы № 23/94 шешімі. Қарағанды облысы Қарқаралы ауданы әділет басқармасында 2005 жылғы 21 желтоқсанда № 8-13-8 тіркелді
title:
  rus: 2006 жылға арналған аудандық бюджет туралы
  kaz: 2006 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-12-14
approved_by:
- '160013000002'
version_date:
  kaz: 2005-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/26432/kaz/14.12.2005
