act_code: '212945'
requisite: Решение акима города Балхаш Карагандинской области от 30 июля 2025 года № 3-Р
title:
  rus: Об образовании избирательных участков на территории города Балхаш
  kaz: Балқаш қаласының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-07-30
approved_by:
- '160008000003'
version_date:
  kaz: 2025-07-30
  rus: 2025-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/212945/kaz/30.07.2025
  rus: https://zan.gov.kz/client/#!/doc/212945/rus/30.07.2025
