act_code: '34146'
requisite: Қарағанды облысы Ақтоғай аудандық мәслихатының 37 сессиясының 2007 жылғы 12 шілдедегі № 422 шешімі. Қарағанды облысы Ақтоғай ауданы әділет басқармасында 2007 жылғы 17 шілдеде № 8-10-48 тіркелді
title:
  rus: Бейбіт жиналыстар, митингілер және пикеттер өткізудің тәртібі мен орнын қосымша белгілеу туралы
  kaz: Бейбіт жиналыстар, митингілер және пикеттер өткізудің тәртібі мен орнын қосымша белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-07-12
approved_by:
- '160014000002'
version_date:
  kaz: 2007-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/34146/kaz/12.07.2007
