act_code: '138091'
requisite: Решение Каркаралинского районного маслихата Карагандинской области от 27 декабря 2019 года № VI-52/439. Зарегистрировано Департаментом юстиции Карагандинской области 6 января 2020 года № 5666
title:
  rus: О бюджетах города районного значения, поселка, сельских округов на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық маңызы бар қала, кент, ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '160013000002'
version_date:
  kaz: 2019-12-27
  rus: 2019-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/138091/kaz/27.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138091/rus/27.12.2019
