act_code: '193349'
requisite: Решение акима города Балхаш Карагандинской области от 12 февраля 2024 года № 1-р. Утратило силу решением акима города Балхаш Карагандинской области от 7 февраля 2025 года № 1-р (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации техногенного характера местного масштаба на территории города Балхаш
  kaz: Балқаш қаласының аумағында жергілікті ауқымдағы техногендік сипаттағы төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-12
approved_by:
- '160008000003'
version_date:
  kaz: 2024-02-12
  rus: 2024-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/193349/kaz/12.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193349/rus/12.02.2024
