act_code: '29526'
requisite: Қарағанды облысы Қаражал қалалық мәслихатының XXVI сессиясының 2006 жылғы 13 шілдедегі № 26/259 шешімі. Қарағанды облысы Қаражал қаласының Әділет басқармасында 2006 жылғы 15 тамызда № 8-5-24 тіркелді. Күші жойылды - Қарағанды облысы Қаражал қалалық мәслихатының 2010 жылғы 23 маусымдағы № 253 шешімімен
title:
  rus: Қаражал қаласының аз қамтылған азаматтарына тұрғын үйді ұстау, коммуналдық қызметтер ақысын төлеу, қалалық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің көтерілуіне байланысты өтемақы төлеу үшін тұрғын үй жәрдемақысын беру Қағидасын бекіту туралы
  kaz: Қаражал қаласының аз қамтылған азаматтарына тұрғын үйді ұстау, коммуналдық қызметтер ақысын төлеу, қалалық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің көтерілуіне байланысты өтемақы төлеу үшін тұрғын үй жәрдемақысын беру Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2006-07-13
approved_by:
- '160010000002'
version_date:
  kaz: 2006-07-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/29526/kaz/13.07.2006
