act_code: '50847'
requisite: Қарағанды облысы Ақтоғай ауданы Нүркен селолық округі әкімінің 2010 жылғы 19 ақпандағы № 2 шешімі. Қарағанды облысы Ақтоғай ауданының Әділет басқармасында 2010 жылғы 25 ақпанда № 8-10-104 тіркелді
title:
  rus: Нүркен селолық округіндегі көшелерін қайта атау туралы
  kaz: Нүркен селолық округіндегі көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-19
approved_by:
- '160014009001'
version_date:
  kaz: 2010-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/50847/kaz/19.02.2010
