act_code: '207109'
requisite: Решение Осакаровского районного маслихата Карагандинской области от 12 февраля 2025 года № 30/290. Зарегистрировано Департаментом юстиции Карагандинской области 13 февраля 2025 года № 6714-09
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2025-02-12
approved_by:
- '160018000002'
version_date:
  kaz: 2026-04-15
  rus: 2026-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/207109/kaz/15.04.2026
  rus: https://zan.gov.kz/client/#!/doc/207109/rus/15.04.2026
caused_by:
  code: '224091'
  requisite: Решение Осакаровского районного маслихата Карагандинской области от 15 апреля 2026 года № 48/468
  title:
    rus: О внесении изменений в решение Осакаровского районного маслихата от 12 февраля 2025 года № 30/290 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Осакаров аудандық мәслихатының 2025 жылғы 12 ақпандағы № 30/290 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/224091/rus
