act_code: '137939'
requisite: Решение Саранского городского маслихата Карагандинской области от 24 декабря 2019 года № 470. Зарегистрировано Департаментом юстиции Карагандинской области 31 декабря 2019 года № 5652
title:
  rus: О городском бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-24
approved_by:
- '160003000002'
version_date:
  kaz: 2020-09-02
  rus: 2020-09-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/137939/kaz/02.09.2020
  rus: https://zan.gov.kz/client/#!/doc/137939/rus/02.09.2020
caused_by:
  code: '146292'
  requisite: Решение Саранского городского маслихата Карагандинской области от 2 сентября 2020 года № 534. Зарегистрировано Департаментом юстиции Карагандинской области 15 сентября 2020 года № 6038
  title:
    rus: О внесении изменений в решение 43 сессии Саранского городского маслихата от 24 декабря 2019 года № 470 «О городском бюджете на 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған қалалық бюджет туралы» Саран қалалық мәслихатының 2019 жылғы 24 желтоқсандағы 43 сессиясының № 470 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146292/rus
