act_code: '79213'
requisite: Решение 26 сессии Нуринского районного маслихата Карагандинской области от 27 марта 2014 года № 242. Зарегистрировано Департаментом юстиции Карагандинской области 24 апреля 2014 года № 2614. Утратило силу решением Нуринского районного маслихата Карагандинской области от 29 марта 2024 года № 82 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Нуринского района
  kaz: Нұра ауданының Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-03-27
approved_by:
- '160012000002'
version_date:
  kaz: 2020-08-28
  rus: 2020-08-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/79213/kaz/28.08.2020
  rus: https://zan.gov.kz/client/#!/doc/79213/rus/28.08.2020
caused_by:
  code: '145960'
  requisite: Решение Нуринского районного маслихата Карагандинской области от 28 августа 2020 года № 480. Зарегистрировано Департаментом юстиции Карагандинской области 2 сентября 2020 года № 6020. Утратило силу решением Нуринского районного маслихата Карагандинской области от 29 марта 2024 года № 82 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнения в Решение 26 сессии Нуринского районного маслихата от 27 марта 2014 года № 242 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Нуринского района»
    kaz: Нұра аудандық мәслихатының 2014 жылғы 27 наурыздағы 26 сессиясының № 242 «Нұра ауданының Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Шешіміне өзгертулер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/145960/rus
