act_code: '162890'
requisite: Решение Шетского районного маслихата Карагандинской области от 27 декабря 2021 года № 9/106. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 января 2022 года № 26335
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по Шетскому району
  kaz: Шет ауданы бойынша тұрғын үй сертификаттарының мөлшерін және алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '160015000002'
version_date:
  kaz: 2021-12-27
  rus: 2021-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/162890/kaz/27.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162890/rus/27.12.2021
