act_code: '192604'
requisite: Решение Шетского районного маслихата Карагандинской области от 21 декабря 2023 года № 7/80
title:
  rus: Об утверждении бюджетов на 2024-2026 годы сельских округов и поселков Шетского района
  kaz: Шет ауданының ауылдық округтерінің және кенттерінің 2024-2026 жылдарға арналған бюджеттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-21
approved_by:
- '160015000002'
version_date:
  kaz: 2024-12-03
  rus: 2024-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/192604/kaz/03.12.2024
  rus: https://zan.gov.kz/client/#!/doc/192604/rus/03.12.2024
caused_by:
  code: '203521'
  requisite: Решение Шетского районного маслихата Карагандинской области от 3 декабря 2024 года № 18/160
  title:
    rus: О внесении изменений в решение Шетского районного маслихата от 21 декабря 2023 года № 7/80 «Об утверждении бюджетов на 2024-2026 годы сельских округов и поселков Шетского района»
    kaz: Шет аудандық мәслихатының 2023 жылғы 21 желтоқсандағы «Шет ауданының ауылдық округтерінің және кенттерінің 2024-2026 жылдарға арналған бюджеттерін бекіту туралы» № 7/80 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/203521/rus
