act_code: '49428'
requisite: Решение XХI сессии Карагандинского областного маслихата от 12 декабря 2009 года № 262. Зарегистрировано Департаментом юстиции Карагандинской области 25 декабря 2009 года № 1874
title:
  rus: Об областном бюджете на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-12
approved_by:
- '160000000002'
version_date:
  kaz: 2010-04-09
  rus: 2010-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/49428/kaz/09.04.2010
  rus: https://zan.gov.kz/client/#!/doc/49428/rus/09.04.2010
caused_by:
  code: '51760'
  requisite: Решение XХIII сессии Карагандинского областного маслихата от 09 апреля 2010 года № 294. Зарегистрировано Департаментом юстиции Карагандинской области 15 апреля 2010 года № 1877
  title:
    rus: О внесении изменений в решение XXI сессии Карагандинского областного маслихата от 12 декабря 2009 года № 262 "Об областном бюджете на 2010-2012 годы"
    kaz: Қарағанды облыстық мәслихатының 2009 жылғы 12 желтоқсандағы XXI сессиясының "2010-2012 жылдарға арналған облыстық бюджет туралы" № 262 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51760/rus
