act_code: '141164'
requisite: Решение акима Кулаайгырского сельского округа Абайского района Карагандинской области от 4 марта 2020 года № 1. Зарегистрировано Департаментом юстиции Карагандинской области 10 марта 2020 года № 5737
title:
  rus: О переименовании улиц в селе Кулаайгыр
  kaz: Құлаайғыр ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-03-04
approved_by:
- '160011010001'
version_date:
  kaz: 2020-03-04
  rus: 2020-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/141164/kaz/04.03.2020
  rus: https://zan.gov.kz/client/#!/doc/141164/rus/04.03.2020
