act_code: '125546'
requisite: Решение акима поселка Молодежный Осакаровского района Карагандинской области от 15 октября 2018 года № 01. Зарегистрировано Департаментом юстиции Карагандинской области 30 октября 2018 года № 4987
title:
  rus: О переименовании улицы поселка Молодежный
  kaz: Молодежный кентіндегі көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-10-15
approved_by:
- '160018002001'
version_date:
  kaz: 2018-10-15
  rus: 2018-10-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/125546/kaz/15.10.2018
  rus: https://zan.gov.kz/client/#!/doc/125546/rus/15.10.2018
