act_code: '98126'
requisite: Решение XLIX сессии Жанааркинского районного маслихата Карагандинской области от 21 декабря 2015 года № 49/335. Зарегистрировано Департаментом юстиции Карагандинской области 8 января 2016 года № 3600
title:
  rus: О районном бюджете на 2016-2018 годы
  kaz: 2016-2018 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-21
approved_by:
- '160016000002'
version_date:
  kaz: 2016-09-09
  rus: 2016-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/98126/kaz/09.09.2016
  rus: https://zan.gov.kz/client/#!/doc/98126/rus/09.09.2016
caused_by:
  code: '106814'
  requisite: Решение IV сессии Жанааркинского районного маслихата Карагандинской области от 9 сентября 2016 года № 4/42. Зарегистрировано Департаментом юстиции Карагандинской области 20 сентября 2016 года № 3964
  title:
    rus: О внесении изменений в решение Жанааркинского районного маслихата от 21 декабря 2015 года №49/335 «О районном бюджете на 2016-2018 годы»
    kaz: Жаңаарқа аудандық мәслихатының 2015 жылғы 21 желтоқсандағы №49/335 «2016-2018 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/106814/rus
