act_code: '98126'
requisite: Решение XLIX сессии Жанааркинского районного маслихата Карагандинской области от 21 декабря 2015 года № 49/335. Зарегистрировано Департаментом юстиции Карагандинской области 8 января 2016 года № 3600
title:
  rus: О районном бюджете на 2016-2018 годы
  kaz: 2016-2018 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-21
approved_by:
- '160016000002'
version_date:
  kaz: 2015-12-21
  rus: 2015-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/98126/kaz/21.12.2015
  rus: https://zan.gov.kz/client/#!/doc/98126/rus/21.12.2015
