act_code: '36386'
requisite: Решение III сессии IV созыва Шахтинского городского маслихата Карагандинской области от 19 декабря 2007 года № 363/3. Зарегистрировано управлением юстиции города Шахтинск Карагандинской области 28 декабря 2007 года № 8-8-44
title:
  rus: «О городском бюджете на 2008 год»
  kaz: «2008 жылға арналған қалалық бюджет туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-19
approved_by:
- '160004000002'
version_date:
  kaz: 2007-12-19
  rus: 2007-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/36386/kaz/19.12.2007
  rus: https://zan.gov.kz/client/#!/doc/36386/rus/19.12.2007
