act_code: '61695'
requisite: Решение XXXVII сессии IV созыва Шахтинского городского маслихата Карагандинской области от 26 октября 2011 года № 739/37. Зарегистрировано Управлением юстиции города Шахтинск Карагандинской области 28 ноября 2011 года № 8-8-99. Утратило силу решением Шахтинского городского маслихата Карагандинской области от 10 мая 2018 года № 1515/21
title:
  rus: О некоторых вопросах налогообложения на территории Шахтинского региона
  kaz: Шахтинск аймағында салынатын салықтың кейбір мәселелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-10-26
approved_by:
- '160004000002'
version_date:
  kaz: 2011-10-26
  rus: 2011-10-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/61695/kaz/26.10.2011
  rus: https://zan.gov.kz/client/#!/doc/61695/rus/26.10.2011
