act_code: '16762'
requisite: Қарағанды облысы Қаражал қалалық мәслихатының XXVI сессиясының 2003 жылғы 21 шілдедегі № 26/286 шешімі. Қарағанды облысының Әділет басқармасында 2003 жылғы 26 тамызда № 1285 тіркелді. Күші жойылды - Қаражал қалалық мәслихатының XIX сессиясының 2009 жылғы 16 шілдедегі № 173 шешімімен
title:
  rus: Жәйрем-Атасу аймағындағы жасыл алқаптарды ұстау және қорғау Қағидасын бекіту туралы
  kaz: Жәйрем-Атасу аймағындағы жасыл алқаптарды ұстау және қорғау Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2003-07-20
approved_by:
- '160010000002'
version_date:
  kaz: 2003-07-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/16762/kaz/20.07.2003
