act_code: '76270'
requisite: Решение 24 сессии Нуринского районного маслихата Карагандинской области от 26 декабря 2013 года № 223. Зарегистрировано Департаментом юстиции Карагандинской области 30 декабря 2013 года № 2487
title:
  rus: О районном бюджете на 2014-2016 годы
  kaz: 2014-2016 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-26
approved_by:
- '160012000002'
version_date:
  kaz: 2014-06-27
  rus: 2014-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/76270/kaz/27.06.2014
  rus: https://zan.gov.kz/client/#!/doc/76270/rus/27.06.2014
caused_by:
  code: '81464'
  requisite: Решение 28 сессии Нуринского районного маслихата Карагандинской области от 27 июня 2014 года № 286. Зарегистрировано Департаментом юстиции Карагандинской области 22 июля 2014 года № 2695
  title:
    rus: О внесении изменения в решение 24 сессии Нуринского районного маслихата от 26 декабря 2013 года № 223 "О районном бюджете на 2014-2016 годы"
    kaz: Нұра аудандық мәслихатының 2013 жылғы 26 желтоқсандағы 24 сессиясының № 223 "2014-2016 жылдарға арналған аудандық бюджет туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/81464/rus
