act_code: '109317'
requisite: Решение VII сессии Улытауского районного маслихата Карагандинской области от 23 декабря 2016 года № 67. Зарегистрировано Департаментом юстиции Карагандинской области 6 января 2017 года № 4086
title:
  rus: О бюджете района на 2017-2019 годы
  kaz: 2017-2019 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-23
approved_by:
- '160019000002'
version_date:
  kaz: 2016-12-23
  rus: 2016-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/109317/kaz/23.12.2016
  rus: https://zan.gov.kz/client/#!/doc/109317/rus/23.12.2016
