act_code: '28707'
requisite: Қарағанды облысы Приозерск қалалық мәслихатының 2006 жылғы 7 маусымдағы № 167/31 шешімі. Балқаш қаласы әділет басқармасында 2006 жылғы 7 шілдеде № 8-4-43 тіркелді
title:
  rus: Ойын бизнесі объектілеріне бірыңғай акциз ставкаларын белгілеу туралы
  kaz: Ойын бизнесі объектілеріне бірыңғай акциз ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-06-07
approved_by:
- '160009000002'
version_date:
  kaz: 2006-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/28707/kaz/07.06.2006
