act_code: '86197'
requisite: Решение Шетского районного маслихата Карагандинской области от 23 декабря 2014 года № 27/229. Зарегистрировано Департаментом юстиции Карагандинской области 12 января 2015 года № 2917
title:
  rus: О районном бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-23
approved_by:
- '160015000002'
version_date:
  kaz: 2015-10-06
  rus: 2015-10-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/86197/kaz/06.10.2015
  rus: https://zan.gov.kz/client/#!/doc/86197/rus/06.10.2015
caused_by:
  code: '95151'
  requisite: Решение Шетского районного маслихата Карагандинской области от 6 октября 2015 года № 33/293. Зарегистрировано Департаментом юстиции Карагандинской области 2 ноября 2015 года № 3480
  title:
    rus: О внесении изменений в решение XXVII сессии Шетского районного маслихата от 23 декабря 2014 года №27/229 «О районном бюджете  на 2015-2017 годы
    kaz: Шет аудандық мәслихатының 2014 жылғы 23 желтоқсандағы XXVII сессиясының «2015-2017 жылдарға арналған аудандық бюджет туралы» № 27/229 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/95151/rus
