act_code: '162751'
requisite: Решение Абайского районного маслихата Карагандинской области от 24 декабря 2021 года № 17/161
title:
  rus: O бюджетах города районного значения, сел, поселков, сельских округов на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған аудандық маңызы бар қаланың, ауылдардың, кенттердің, ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '160011000002'
version_date:
  kaz: 2022-03-11
  rus: 2022-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/162751/kaz/11.03.2022
  rus: https://zan.gov.kz/client/#!/doc/162751/rus/11.03.2022
caused_by:
  code: '165257'
  requisite: Решение Абайского районного маслихата Карагандинской области от 11 марта 2022 года № 20/198
  title:
    rus: О внесении изменений в решение Абайского районного маслихата от 24 декабря 2021 года № 17/161 «O бюджетах города районного значения, сел, поселков, сельских округов на 2022-2024 годы»
    kaz: Абай аудандық мәслихатының 2021 жылғы 24 желтоқсандағы № 17/161 «2022-2024 жылдарға арналған аудандық маңызы бар қаланың, ауылдардың, кенттердің, ауылдық округтердің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165257/rus
