act_code: '179679'
requisite: Решение акима Бахтинского сельского округа Каркаралинского района Карагандинской области от 12 апреля 2023 года № 4
title:
  rus: О снятии карантина
  kaz: Карантинді алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-04-12
approved_by:
- '160013007002'
version_date:
  kaz: 2023-04-12
  rus: 2023-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/179679/kaz/12.04.2023
  rus: https://zan.gov.kz/client/#!/doc/179679/rus/12.04.2023
