act_code: '138095'
requisite: Решение Каражалского городского маслихата Карагандинской области от 27 декабря 2019 года № 357. Зарегистрировано Департаментом юстиции Карагандинской области 8 января 2020 года № 5668
title:
  rus: О бюджете поселков Жайрем и Шалгинский на 2020 - 2022 годы
  kaz: 2020 - 2022 жылдарға арналған Жәйрем және Шалғы кенттерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '160010000002'
version_date:
  kaz: 2020-11-20
  rus: 2020-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/138095/kaz/20.11.2020
  rus: https://zan.gov.kz/client/#!/doc/138095/rus/20.11.2020
caused_by:
  code: '149005'
  requisite: Решение Каражалского городского маслихата Карагандинской области от 20 ноября 2020 года № 441. Зарегистрировано Департаментом юстиции Карагандинской области 27 ноября 2020 года № 6108
  title:
    rus: О внесении изменений в решение ХХХХІІ сессии Каражалского городского маслихата от 27 декабря 2019 года № 357 «О бюджете поселков Жайрем и Шалгинский на 2020 - 2022 годы»
    kaz: Қаражал қалалық мәслихатының 2019 жылғы 27 желтоқсандағы ХХХХІІ сессиясының № 357 «2020 - 2022 жылдарға арналған Жәйрем және Шалғы кенттерінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149005/rus
