act_code: '120782'
requisite: Решение акима Коктенкольского сельского округа Шетского района Карагандинской области от 27 марта 2018 года № 01. Зарегистрировано Департаментом юстиции Карагандинской области 10 апреля 2018 года № 4690
title:
  rus: О переименовании улиц в селе Коктенколь Шетского района
  kaz: Шет ауданы Көктіңкөлі ауылындағы көшелерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-27
approved_by:
- '160015015002'
version_date:
  kaz: 2018-03-27
  rus: 2018-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/120782/kaz/27.03.2018
  rus: https://zan.gov.kz/client/#!/doc/120782/rus/27.03.2018
