act_code: '175960'
requisite: Решение Каркаралинского районного маслихата Карагандинской области от 21 декабря 2022 года № VII-28/226
title:
  rus: Об утверждении Порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей Кайнарбулакского сельского округа Каркаралинского района Карагандинской области для участия в сходе местного сообщества
  kaz: Қарағанды облысы Қарқаралы ауданының Қайнарбұлақ ауылдық округінің жергілікті қоғамдастық жиындарына қатысу үшін бөлек жергілікті қоғамдастық жиындарын өткізу тәртібі және ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2022-12-21
approved_by:
- '160013000002'
version_date:
  kaz: 2022-12-21
  rus: 2022-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/175960/kaz/21.12.2022
  rus: https://zan.gov.kz/client/#!/doc/175960/rus/21.12.2022
