act_code: '36389'
requisite: Решение IV сессии IV созыва Карагандинского городского маслихата от 21 декабря 2007 года № 47. Зарегистрировано управлением юстиции города Караганды Карагандинской области 29 декабря 2007 года № 8-1-68
title:
  rus: О бюджете города Караганды на 2008 год
  kaz: Қарағанды қаласының 2008 жылға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-21
approved_by:
- '160002000002'
version_date:
  kaz: 2008-03-31
  rus: 2008-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/36389/kaz/31.03.2008
  rus: https://zan.gov.kz/client/#!/doc/36389/rus/31.03.2008
caused_by:
  code: '39000'
  requisite: Решение VII сессии IV созыва Карагандинского городского маслихата от 31 марта 2008 года N 83. Зарегистрировано Управлением юстиции города Караганды Карагандинской области 21 апреля 2008 года № 8-1-70
  title:
    rus: О внесении изменений и дополнения в решение № 47 IV сессии от 21 декабря 2007 года Карагандинского городского маслихата IV созыва "О бюджете города Караганды на 2008 год"
    kaz: IV шақырылған Қарағанды қалалық мәслихатының 2007 жылғы 21 желтоқсандағы IV сессиясының "Қарағанды қаласының 2008 жылға арналған бюджеті туралы" № 47 шешіміне өзгертулер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/39000/rus
