act_code: '87835'
requisite: Решение Сатпаевского городского маслихата Карагандинской области от 26 февраля 2015 года № 318. Зарегистрировано Департаментом юстиции Карагандинской области 18 марта 2015 года № 3052. Утратило силу решением Сатпаевского городского маслихата Карагандинской области от 17 февраля 2016 года № 431
title:
  rus: О льготном проезде на общественном транспорте (кроме такси) учащихся очной формы обучения
  kaz: Күндізгі оқу нысанындағы оқушылардың қоғамдық көлікте (таксиден басқа) жеңілдікпен жол жүруі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-02-26
approved_by:
- '160007000002'
version_date:
  kaz: 2015-02-26
  rus: 2015-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/87835/kaz/26.02.2015
  rus: https://zan.gov.kz/client/#!/doc/87835/rus/26.02.2015
