act_code: '87653'
requisite: Решение маслихата Актогайского района от 23 февраля 2015 года № 172/40. Зарегистрировано Департаментом юстиции Павлодарской области 17 марта 2015 года № 4372. Утратило силу решением маслихата Актогайского района Павлодарской области от 14 апреля 2016 года № 10/2 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О дополнительном регламентировании проведения мирных собраний, митингов, шествий, пикетов и демонстраций на территории населенных пунктов Актогайского района
  kaz: Ақтоғай ауданы елді мекендер аумағында бейбіт жиналыстарды, митингілерді, шерулерді, пикеттерді және демонстрацияларды өткізуге қосымша регламенттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-02-23
approved_by:
- '160014000002'
version_date:
  kaz: 2015-02-23
  rus: 2015-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/87653/kaz/23.02.2015
  rus: https://zan.gov.kz/client/#!/doc/87653/rus/23.02.2015
