act_code: '43465'
requisite: Решение акима города Балхаша Карагандинской области от 30 декабря 2008 года № 06. Зарегистрировано Управлением юстиции города Балхаша Карагандинской области 14 января 2009 года № 8-4-129
title:
  rus: О проведении приписки граждан 1992 года рождения к призывному участку объединенного отдела по делам обороны города Балхаша Карагандинской области
  kaz: 1992 жылы туған азаматтарды Қарағанды облысы Балқаш қалалық қорғаныс істері жөніндегі біріктірілген бөлімі шақыру участкесіне тіркеуді өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-30
approved_by:
- '160008000001'
version_date:
  kaz: 2008-12-30
  rus: 2008-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/43465/kaz/30.12.2008
  rus: https://zan.gov.kz/client/#!/doc/43465/rus/30.12.2008
