act_code: '86441'
requisite: Решение 31 сессии Бухар-Жырауского районного маслихата Карагандинской области от 24 декабря 2014 года N 4. Зарегистрировано Департаментом юстиции Карагандинской области 6 января 2015 года N 2904
title:
  rus: 'О районном бюджете на 2015-2017 годы '
  kaz: '2015-2017 жылдарға арналған аудандық бюджет туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '160017000002'
version_date:
  kaz: 2014-12-24
  rus: 2014-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/86441/kaz/24.12.2014
  rus: https://zan.gov.kz/client/#!/doc/86441/rus/24.12.2014
