act_code: '26737'
requisite: Қарағанды облысы Балқаш қалалық мәслихатының 2006 жылғы 1 ақпандағы № 30/276 шешімі. Қарағанды облысы Балқаш қаласы Әділет басқармасында 2006 жылғы 7 наурызда № 8-4-26 тіркелді. Күші жойылды - Қарағанды облысы Балқаш қалалық мәслихатының 2010 жылғы 24 ақпандағы № 28/217 шешімімен
title:
  rus: Жеке санаттағы азаматтарға қала ішінде қоғамдық көлікте (таксиден басқа) жүру жолақысына әлеуметтік көмек көрсету туралы
  kaz: Жеке санаттағы азаматтарға қала ішінде қоғамдық көлікте (таксиден басқа) жүру жолақысына әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-02-01
approved_by:
- '160008000002'
version_date:
  kaz: 2008-03-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/26737/kaz/12.03.2008
caused_by:
  code: '38662'
  requisite: Решение Балхашского городского маслихата Карагандинской области от 12 марта 2008 года № 7/61. Зарегистрировано Управлением юстиции города Балхаша Карагандинской области 1 апреля 2008 года № 8-4-105. Утратило силу - решением Балхашского городского маслихата Карагандинской области от 24 февраля 2010 года № 28/217
  title:
    rus: О внесении изменений и дополнений в решение городского маслихата от 1 февраля 2006 года № 30/276 "Об оказании социальной помощи отдельным категориям граждан на проезд на внутригородском общественном транспорте (кроме такси)"
    kaz: '"Жеке санаттағы азаматтарға қала ішінде қоғамдық көлікте (таксиден басқа) жүру жолақысына әлеуметтік көмек көрсету туралы" қалалық мәслихаттың 2006 жылғы 1 ақпандағы № 30/276 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/38662/rus
