act_code: '31192'
requisite: Решение Жезказганского городского маслихата Карагандинской области от 20 декабря 2006 года № 33/376. Зарегистрировано управлением юстиции города Жезказган 10 января 2007 года за № 8-2-38. Утратило силу решением Жезказганского городского маслихата Карагандинской области от 4 апреля 2007 года № 36/412
title:
  rus: Об установлении размера фиксированного суммарного налога с единицы объектов налогообложения на территории города Жезказгана на 2007 год
  kaz: 2007 жылға арналған Жезқазған қаласы аумағында бірлік объектілерге салық салудың белгіленген жиынтық салықтың мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-20
approved_by:
- '160006000002'
version_date:
  kaz: 2006-12-20
  rus: 2006-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/31192/kaz/20.12.2006
  rus: https://zan.gov.kz/client/#!/doc/31192/rus/20.12.2006
