act_code: '118328'
requisite: Решение Балхашского городского маслихата Карагандинской области от 21 декабря 2017 года № 16/127. Зарегистрировано Департаментом юстиции Карагандинской области 16 января 2018 года № 4573
title:
  rus: О городском бюджете на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-21
approved_by:
- '160008000002'
version_date:
  kaz: 2018-02-21
  rus: 2018-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/118328/kaz/21.02.2018
  rus: https://zan.gov.kz/client/#!/doc/118328/rus/21.02.2018
caused_by:
  code: '119561'
  requisite: Решение Балхашского городского маслихата Карагандинской области от 21 февраля 2018 года № 17/148. Зарегистрировано Департаментом юстиции Карагандинской области 13 марта 2018 года № 4644
  title:
    rus: О внесении изменений в решение городского маслихата от 21 декабря 2017 года № 16/127 «О городском бюджете на 2018-2020 годы»
    kaz: Қалалық мәслихаттың 2017 жылғы 21 желтоқсандағы № 16/127 «2018-2020 жылдарға арналған қалалық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/119561/rus
