act_code: '120858'
requisite: Решение XXV сессии Каркаралинского районного маслихата Карагандинской области от 29 марта 2018 года № VI-25/222. Зарегистрировано Департаментом юстиции Карагандинской области 13 апреля 2018 года № 4701. Утратило силу решением Каркаралинского районного маслихата Карагандинской области от 18 июня 2020 года № VI-57/485 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении единых ставок фиксированного налога
  kaz: Бірыңғай тіркелген салық мөлшерлемелерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-29
approved_by:
- '160013000002'
version_date:
  kaz: 2018-03-29
  rus: 2018-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/120858/kaz/29.03.2018
  rus: https://zan.gov.kz/client/#!/doc/120858/rus/29.03.2018
