act_code: '109394'
requisite: Решение VIII сессии Жанааркинского районного маслихата Карагандинской области от 21 декабря 2016 года № 8/64. Зарегистрировано Департаментом юстиции Карагандинской области 10 января 2017 года № 4103
title:
  rus: О районном бюджете на 2017-2019 годы
  kaz: 2017-2019 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-21
approved_by:
- '160016000002'
version_date:
  kaz: 2017-07-04
  rus: 2017-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/109394/kaz/04.07.2017
  rus: https://zan.gov.kz/client/#!/doc/109394/rus/04.07.2017
caused_by:
  code: '113630'
  requisite: Решение ХV сессии Жанааркинского районного маслихата Карагандинской области от 4 июля 2017 года № 15/122. Зарегистрировано Департаментом юстиции Карагандинской области 17 июля 2017 года № 4310
  title:
    rus: О внесении изменений в решение Жанааркинского районного маслихата от 21 декабря 2016 года № 8/64 «О районном бюджете на 2017-2019 годы»
    kaz: Жаңаарқа аудандық мәслихатының 2016 жылғы 21 желтоқсандағы № 8/64 «2017-2019 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/113630/rus
