act_code: '111328'
requisite: Решение VIII сессии Карагандинского областного маслихата от 30 марта 2017 года № 168. Зарегистрировано Департаментом юстиции Карагандинской области 10 апреля 2017 года № 4207. Утратило силу решением Карагандинского областного маслихата от 25 февраля 2021 года № 34 (вводится в действие со дня его официального опубликования)
title:
  rus: О предоставлении лекарственных средств дополнительно
  kaz: Дәрілік заттарды қосымша беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-03-30
approved_by:
- '160000000002'
version_date:
  kaz: 2020-07-02
  rus: 2020-07-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/111328/kaz/02.07.2020
  rus: https://zan.gov.kz/client/#!/doc/111328/rus/02.07.2020
caused_by:
  code: '144434'
  requisite: Решение Карагандинского областного маслихата от 2 июля 2020 года № 553. Зарегистрировано Департаментом юстиции Карагандинской области 7 июля 2020 года № 5929. Утратило силу решением Карагандинского областного маслихата от 25 февраля 2021 года № 34 (вводится в действие со дня его официального опубликования)
  title:
    rus: О внесении изменений в некоторые решения Карагандинского областного маслихата и признании утратившими силу некоторых решений Карагандинского областного маслихата
    kaz: Қарағанды облыстық мәслихатының кейбір шешімдеріне өзгерістер енгізу және Қарағанды облыстық мәслихатының кейбір шешімдерінің күші жойылды деп тану туралы
  link: https://zan.gov.kz/client/#!/doc/144434/rus
