act_code: '69485'
requisite: Решение 14 сессии Саранского городского маслихата Карагандинской области от 14 декабря 2012 года № 144. Зарегистрировано Департаментом юстиции Карагандинской области 26 декабря 2012 года № 2070
title:
  rus: О городском бюджете на 2013-2015 годы
  kaz: 2013-2015 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-14
approved_by:
- '160003000002'
version_date:
  kaz: 2013-09-26
  rus: 2013-09-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/69485/kaz/26.09.2013
  rus: https://zan.gov.kz/client/#!/doc/69485/rus/26.09.2013
caused_by:
  code: '74726'
  requisite: Решение 24 сессии Саранского городского маслихата Карагандинской области от 26 сентября 2013 года № 248. Зарегистрировано Департаментом юстиции Карагандинской области 9 октября 2013 года № 2392
  title:
    rus: О внесении изменений в решение 14 сессии Саранского городского маслихата от 14 декабря 2012 года № 144 "О городском бюджете на 2013-2015 годы"
    kaz: Саран қалалық мәслихатының 2012 жылғы 14 желтоқсандағы 14 сессиясының "2013-2015 жылдарға арналған қалалық бюджет туралы" № 144 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/74726/rus
