act_code: '62240'
requisite: Решение 42 сессии Абайского районного маслихата Карагандинской области от 12 декабря 2011 года № 42/499. Зарегистрировано Управлением юстиции Абайского района Карагандинской области 28 декабря 2011 года № 8-9-120
title:
  rus: О районном бюджете на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-12
approved_by:
- '160011000002'
version_date:
  kaz: 2012-11-21
  rus: 2012-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/62240/kaz/21.11.2012
  rus: https://zan.gov.kz/client/#!/doc/62240/rus/21.11.2012
caused_by:
  code: '68812'
  requisite: Решение 12 сессии Абайского районного маслихата Карагандинской области от 21 ноября 2012 года № 12/111. Зарегистрировано Департаментом юстиции Карагандинской области 27 ноября 2012 года № 1991
  title:
    rus: О внесении изменений в решение 42 очередной сессии Абайского районного маслихата от 12 декабря 2011 года № 42/499 "О районном бюджете на 2012-2014 годы"
    kaz: Абай ауданы мәслихатының 2011 жылғы 12 желтоқсандағы 42 кезекті сессиясының "2012-2014 жылдарға арналған аудандық бюджет туралы" № 42/499 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/68812/rus
