act_code: '144126'
requisite: Решение Каркаралинского районного маслихата Карагандинской области от 18 июня 2020 года № VI-57/487. Зарегистрировано Департаментом юстиции Карагандинской области 25 июня 2020 года № 5910
title:
  rus: Об утверждении Правил и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Каркаралинского района
  kaz: Қарқаралы ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына коммуналдық қызметтерді төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету қағидаларын және мөлшерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-06-18
approved_by:
- '160013000002'
version_date:
  kaz: 2025-10-20
  rus: 2025-10-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/144126/kaz/20.10.2025
  rus: https://zan.gov.kz/client/#!/doc/144126/rus/20.10.2025
caused_by:
  code: '215841'
  requisite: Решение Каркаралинского районного маслихата Карагандинской области от 20 октября 2025 года № VIII-41/320. Зарегистрировано в Министерстве юстиции Республики Казахстан 21 октября 2025 года № 37177
  title:
    rus: О внесении изменения в решение Каркаралинского районного маслихата от 18 июня 2020 года № VI-57/487 «Об утверждении Правил и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Каркаралинского района»
    kaz: Қарқаралы аудандық мәслихатының 2020 жылғы 18 маусымдағы № VI-57/487 «Қарқаралы ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына коммуналдық қызметтерді төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету қағидаларын және мөлшерін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/215841/rus
