act_code: '7063'
requisite: Решение Акима Карагандинской области от 14 августа 2000 года № 141. Зарегистрировано управлением юстиции Карагандинской области 27 сентября 2000 года за № 123. Утратило силу распоряжением Акима Карагандинской области от 14 марта 2003 года № 23р
title:
  rus: О квоте иммиграции на 2000 год
  kaz: 2000 жылға арналған көшіп келу квотасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-08-13
approved_by:
- '160000000001'
version_date:
  kaz: 2000-08-13
  rus: 2000-08-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/7063/kaz/13.08.2000
  rus: https://zan.gov.kz/client/#!/doc/7063/rus/13.08.2000
