act_code: '54985'
requisite: Решение Темиртауского городского маслихата Карагандинской области от 14 сентября 2010 года № 31/5. Зарегистрировано Управлением юстиции города Темиртау Карагандинской области 22 октября 2010 года № 8-3-108
title:
  rus: Об утверждении Правил предоставления жилищной помощи населению города Темиртау и поселка Актау
  kaz: Теміртау қаласы мен Ақтау кенті тұрғындарына тұрғын үй көмегін көрсету ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-09-14
approved_by:
- '160005000002'
version_date:
  kaz: 2010-12-24
  rus: 2010-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/54985/kaz/24.12.2010
  rus: https://zan.gov.kz/client/#!/doc/54985/rus/24.12.2010
caused_by:
  code: '56290'
  requisite: Решение Темиртауского городского маслихата Карагандинской области от 24 декабря 2010 года № 34/9. Зарегистрировано Управлением юстиции города Темиртау Карагандинской области 29 декабря 2010 года № 8-3-111. Утратило силу - решением Темиртауского городского маслихата Карагандинской области от 9 декабря 2011 года № 47/5
  title:
    rus: О внесении изменений и дополнений в решение Темиртауского городского маслихата от 14 сентября 2010 года № 31/5 "Об утверждении Правил предоставления жилищной помощи населению города Темиртау и поселка Актау"
    kaz: Теміртау қалалық мәслихатының 2010 жылғы 14 қыркүйектегі № 31/5 "Теміртау қаласы мен Ақтау кенті тұрғындарына тұрғын үй көмегін көрсету ережесін бекіту туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/56290/rus
