act_code: '188568'
requisite: Решение Осакаровского районного маслихата Карагандинской области от 17 ноября 2023 года № 13/125
title:
  rus: Об утверждении Порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей Мирного сельского округа Осакаровского района Карагандинской области для участия в сходе местного сообщества
  kaz: Қарағанды облысы Осакаров ауданы Мирный ауылдық округінің жергілікті қоғамдастық жиынына қатысу үшін жергілікті қоғамдастықтың бөлек жиындарын өткізу тәртібі және тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2023-11-17
approved_by:
- '160018000002'
version_date:
  kaz: 2025-07-09
  rus: 2025-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/188568/kaz/09.07.2025
  rus: https://zan.gov.kz/client/#!/doc/188568/rus/09.07.2025
caused_by:
  code: '212165'
  requisite: Решение Осакаровского районного маслихата Карагандинской области от 9 июля 2025 года № 36/369
  title:
    rus: О внесении изменения в решение Осакаровского районного маслихата от 17 ноября 2023 года № 13/125 «Об утверждении Порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей Мирного сельского округа Осакаровского района Карагандинской области для участия в сходе местного сообщества»
    kaz: Осакаров аудандық мәслихатының 2023 жылғы 17 қарашадағы «Қарағанды облысы Осакаров ауданы Мирный ауылдық округінің жергілікті қоғамдастық жиынына қатысу үшін жергілікті қоғамдастықтың бөлек жиындарын өткізу тәртібі және тұрғындары өкілдерінің сандық құрамын бекіту туралы» № 13/125 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212165/rus
