act_code: '137765'
requisite: Решение Сатпаевского городского маслихата Карагандинской области от 30 декабря 2019 года № 497. Зарегистрировано Департаментом юстиции Карагандинской области 30 декабря 2019 года № 5624
title:
  rus: О бюджете поселка Жезказган на 2020 – 2022 годы
  kaz: 2020 – 2022 жылдарға арналған Жезқазған кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '160007000002'
version_date:
  kaz: 2020-11-27
  rus: 2020-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/137765/kaz/27.11.2020
  rus: https://zan.gov.kz/client/#!/doc/137765/rus/27.11.2020
caused_by:
  code: '149308'
  requisite: Решение Сатпаевского городского маслихата Карагандинской области от 27 ноября 2020 года № 620. Зарегистрировано Департаментом юстиции Карагандинской области 4 декабря 2020 года № 6113
  title:
    rus: О внесении изменений в решение Сатпаевского городского маслихата от 30 декабря 2019 года № 497 «О бюджете поселка Жезказган на 2020 – 2022 годы»
    kaz: Сәтбаев қалалық мәслихатының 2019 жылғы 30 желтоқсандағы № 497 «2020 – 2022 жылдарға арналған Жезқазған кентінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149308/rus
