act_code: '138000'
requisite: Решение Осакаровского районного маслихата Карагандинской области от 30 декабря 2019 года № 790. Зарегистрировано Департаментом юстиции Карагандинской области 5 января 2020 года № 5655
title:
  rus: О бюджете поселков, сельских округов Осакаровского района на 2020-2022 годы
  kaz: Осакаров ауданының кенттерінің, ауылдық округтарының 2020-2022 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '160018000002'
version_date:
  kaz: 2019-12-30
  rus: 2019-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/138000/kaz/30.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138000/rus/30.12.2019
