act_code: '144923'
requisite: Решение Абайского районного маслихата Карагандинской области от 13 июля 2020 года № 66/708. Зарегистрировано Департаментом юстиции Карагандинской области 20 июля 2020 года № 5951
title:
  rus: О специализированных местах для организации и проведения мирных собраний и границах прилегающих территорий, в которых запрещено проведение пикетирования на территории Абайского района
  kaz: Абай ауданының аумағында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындар және пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекаралары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-07-13
approved_by:
- '160011000002'
version_date:
  kaz: 2020-07-13
  rus: 2020-07-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/144923/kaz/13.07.2020
  rus: https://zan.gov.kz/client/#!/doc/144923/rus/13.07.2020
