act_code: '26716'
requisite: Қарағанды облысы Балқаш қалалық мәслихатының 2006 жылғы 1 ақпандағы № 30/275 шешімі. Қарағанды облысы Балқаш қаласы Әділет басқармасында 2006 жылғы 7 наурызда № 8-4-25 тіркелді. Күші жойылды - Қарағанды облысы Балқаш қалалық мәслихатының 2011 жылғы 24 наурыздағы № 43/335 шешімімен
title:
  rus: Коммуналдық қызметті төлеуге және тұрғын жайды ұстауға Ұлы Отан соғысының мүгедектеріне және қатысушыларына әлеуметтік көмек көрсету туралы
  kaz: Коммуналдық қызметті төлеуге және тұрғын жайды ұстауға Ұлы Отан соғысының мүгедектеріне және қатысушыларына әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-02-01
approved_by:
- '160008000002'
version_date:
  kaz: 2007-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/26716/kaz/21.02.2007
caused_by:
  code: '32195'
  requisite: Решение Балхашского городского маслихата Карагандинской области от 21 февраля 2007 года № 40/388. Зарегистрировано Управлением юстиции города Балхаша Карагандинской области 5 марта 2007 года за № 8-4-64
  title:
    rus: О внесении изменений в решение городского маслихата от 1 февраля 2006 года № 30/275 "Об оказании социальной помощи участникам и инвалидам Великой Отечественной войны на содержание жилища и оплату коммунальных услуг"
    kaz: '"Коммуналдық қызметті төлеуге және тұрғын жайды ұстауға Ұлы Отан соғысының мүгедектеріне және қатысушыларына әлеуметтік көмек көрсету туралы" қалалық мәслихаттың 2006 жылғы 1 ақпандағы № 30/275 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/32195/rus
