act_code: '56650'
requisite: Решение Темиртауского городского маслихата Карагандинской области от 24 декабря 2010 года № 34/5. Зарегистрировано Управлением юстиции города Темиртау Карагандинской области 11 января 2011 года № 8-3-112
title:
  rus: О городском бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '160005000002'
version_date:
  kaz: 2011-03-25
  rus: 2011-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/56650/kaz/25.03.2011
  rus: https://zan.gov.kz/client/#!/doc/56650/rus/25.03.2011
caused_by:
  code: '58128'
  requisite: Решение Темиртауского городского маслихата Карагандинской области от 25 марта 2011 года № 37/4. Зарегистрировано Управлением юстиции города Темиртау Карагандинской области 8 апреля 2011 года № 8-3-116
  title:
    rus: О внесении изменений и дополнений в решение 34 сессии Темиртауского городского маслихата от 24 декабря 2010 года N№ 34/5 "О городском бюджете на 2011-2013 годы"
    kaz: Теміртау қалалық мәслихатының 2010 жылғы 24 желтоқсандағы 34 сессиясының № 34/5 "2011-2013 жылдарға арналған қалалық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/58128/rus
