act_code: '126005'
requisite: Решение акима Успенского сельского округа Шетского района Карагандинской области от 26 октября 2018 года № 2ө. Зарегистрировано Департаментом юстиции Карагандинской области 13 ноября 2018 года № 5004
title:
  rus: О переименовании улицы в селе Успен Шетского района
  kaz: Шет ауданы Өспен ауылындағы көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-10-26
approved_by:
- '160015024002'
version_date:
  kaz: 2018-10-26
  rus: 2018-10-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/126005/kaz/26.10.2018
  rus: https://zan.gov.kz/client/#!/doc/126005/rus/26.10.2018
