act_code: '137926'
requisite: Решение Шахтинского городского маслихата Карагандинской области от 30 декабря 2019 года № 1691/37. Зарегистрировано Департаментом юстиции Карагандинской области 31 декабря 2019 года № 5644
title:
  rus: О бюджете поселков Шахтинского региона на 2020 - 2022 годы
  kaz: 2020-2022 жылдарға арналған Шахтинск аймағындағы кенттер бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '160004000002'
version_date:
  kaz: 2019-12-30
  rus: 2019-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/137926/kaz/30.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137926/rus/30.12.2019
