act_code: '180728'
requisite: Решение акима Умуткерского сельского округа Бухар-Жырауского района Карагандинской области от 3 мая 2023 года № 4-р
title:
  rus: Об установлении карантина
  kaz: Карантин белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-05-03
approved_by:
- '160017027002'
version_date:
  kaz: 2023-05-03
  rus: 2023-05-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/180728/kaz/03.05.2023
  rus: https://zan.gov.kz/client/#!/doc/180728/rus/03.05.2023
