act_code: '187970'
requisite: Решение Балхашского городского маслихата Карагандинской области от 3 ноября 2023 года № 8/70. Зарегистрировано в Департаменте юстиции Карагандинской области 6 ноября 2023 года № 6516-09
title:
  rus: О предоставлении льготного проезда на общественном транспорте (кроме такси) учащихся очной формы обучения
  kaz: Күндізгі оқу нысанындағы оқушыларға қоғамдық көлікте (таксиден басқа) жеңілдікпен жол жүруді қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-11-03
approved_by:
- '160008000002'
version_date:
  kaz: 2023-11-03
  rus: 2023-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/187970/kaz/03.11.2023
  rus: https://zan.gov.kz/client/#!/doc/187970/rus/03.11.2023
