act_code: '34491'
requisite: Қарағанды облысы Жаңаарқа аудандық мәслихатының 2007 жылғы 9 шілдедегі N 39/315 шешімі. Қарағанды облысы Жаңаарқа ауданы Әділет басқармасында 2007 жылғы 27 шілдеде N 8-12-33 тіркелді. Күші жойылды - Қарағанды облысы Жаңаарқа аудандық мәслихатының 2016 жылғы 11 мамырдағы № 2/18 шешімімен
title:
  rus: Жиналыстар, митингілер, шерулер, пикеттер мен демонстрациялар өткізу тәртібін қосымша реттеу туралы
  kaz: Жиналыстар, митингілер, шерулер, пикеттер мен демонстрациялар өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-07-09
approved_by:
- '160016000002'
version_date:
  kaz: 2007-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/34491/kaz/09.07.2007
