act_code: '214990'
requisite: Решение Саранского городского маслихата Карагандинской области от 25 сентября 2025 года № 234
title:
  rus: Об утверждении План по управлению пастбищами и их использованию по городу Сарань на 2025-2029 годы
  kaz: Саран қаласы бойынша жайылымдарды басқару және оларды пайдалану жөніндегі 2025-2029 жылдарға арналған жоспар
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-25
approved_by:
- '160003000002'
version_date:
  kaz: 2025-09-25
  rus: 2025-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/214990/kaz/25.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214990/rus/25.09.2025
