act_code: '25938'
requisite: Нұра аудандық мәслихатының 18 сессиясының 2005 жылғы 20 қазандағы № 191 шешімі. Нұра ауданы Әділет басқармасында 2005 жылғы 21 қарашада № 8-14-10 тіркелді.
title:
  rus: Нұра ауданы аумағында ит пен мысықты ұстау Қағидасы туралы
  kaz: Нұра ауданы аумағында ит пен мысықты ұстау Қағидасы туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2005-10-20
approved_by:
- '160012000002'
version_date:
  kaz: 2005-10-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/25938/kaz/20.10.2005
