act_code: '127695'
requisite: Решение Сатпаевского городского маслихата Карагандинской области от 27 декабря 2018 года № 360. Зарегистрировано Департаментом юстиции Карагандинской области 27 декабря 2018 года № 5101
title:
  rus: О бюджете поселка Жезказган на 2019 – 2021 годы
  kaz: 2019 – 2021 жылдарға арналған Жезқазған кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-27
approved_by:
- '160007000002'
version_date:
  kaz: 2019-05-17
  rus: 2019-05-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/127695/kaz/17.05.2019
  rus: https://zan.gov.kz/client/#!/doc/127695/rus/17.05.2019
caused_by:
  code: '131964'
  requisite: Решение Сатпаевского городского маслихата Карагандинской области от 17 мая 2019 года № 398. Зарегистрировано Департаментом юстиции Карагандинской области 24 мая 2019 года № 5361
  title:
    rus: О внесении изменений в решение Сатпаевского городского маслихата от 27 декабря 2018 года № 360 "О бюджете поселка Жезказган на 2019 - 2021 годы"
    kaz: Сәтбаев қалалық мәслихатының 2018 жылғы 27 желтоқсандағы № 360 «2019 – 2021 жылдарға арналған Жезқазған кентінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131964/rus
