act_code: '150809'
requisite: Решение Абайского районного маслихата Карагандинской области от 25 декабря 2020 года № 73/762. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 декабря 2020 года № 21958
title:
  rus: О районном бюджете на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-25
approved_by:
- '160011000002'
version_date:
  kaz: 2021-07-08
  rus: 2021-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/150809/kaz/08.07.2021
  rus: https://zan.gov.kz/client/#!/doc/150809/rus/08.07.2021
caused_by:
  code: '157048'
  requisite: Решение Абайского районного маслихата Карагандинской области от 8 июля 2021 года № 10/102. Зарегистрировано в Министерстве юстиции Республики Казахстан 16 июля 2021 года № 23563
  title:
    rus: О внесении изменений в решение Абайского районного маслихата от 25 декабря 2020 года № 73/762 «O районном бюджет на 2021-2023 годы»
    kaz: Абай аудандық мәслихатының 2020 жылғы 25 желтоқсандағы № 73/762 «2021-2023 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157048/rus
