act_code: '97916'
requisite: Решение маслихата Актогайского района Павлодарской области от 18 января 2016 года № 238/55
title:
  rus: Об отмене решения районного маслихата (XLVIII внеочередная сессия, V созыв) от 17 сентября 2015 года № 204/48 «Об утверждении методики ежегодной оценки деятельности административных государственных служащих корпуса «Б» аппарата маслихата Актогайского района»
  kaz: Аудандық мәслихаттың (V шақырылған, кезектен тыс XLVIII сессиясы) 2015 жылғы Ақтоғай 17 қыркүйектегі «Аудандық мәслихаты аппаратының «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалаудың әдістемесін бекіту туралы» № 204/48 шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-01-18
approved_by:
- '160014000002'
version_date:
  kaz: 2016-01-18
  rus: 2016-01-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/97916/kaz/18.01.2016
  rus: https://zan.gov.kz/client/#!/doc/97916/rus/18.01.2016
