act_code: '62380'
requisite: Решение XXXIX сессии IV созыва Шахтинского городского маслихата Карагандинской области от 9 декабря 2011 года № 760/39. Зарегистрировано Управлением юстиции города Шахтинск Карагандинской области 30 декабря 2011 года № 8-8-102
title:
  rus: О городском бюджете на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-09
approved_by:
- '160004000002'
version_date:
  kaz: 2012-04-06
  rus: 2012-04-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/62380/kaz/06.04.2012
  rus: https://zan.gov.kz/client/#!/doc/62380/rus/06.04.2012
caused_by:
  code: '64804'
  requisite: Решение III сессии V созыва Шахтинского городского маслихата Карагандинской области от 6 апреля 2012 года № 788/3. Зарегистрировано Управлением юстиции города Шахтинск Карагандинской области 18 апреля 2012 года № 8-8-108
  title:
    rus: О внесении изменений в решение XXXIX сессии Шахтинского городского маслихата от 9 декабря 2011 года № 760/39 "О городском бюджете на 2012-2014 годы"
    kaz: Шахтинск қалалық  мәслихаттың "2012-2014 жылдарға арналған қалалық бюджет туралы" 2011 жылғы 9 желтоқсандағы XХXIX сессиясының № 760/39 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/64804/rus
