act_code: '183426'
requisite: Решение акима Киргизского сельского округа Каркаралинского района Карагандинской области от 29 июня 2023 года № 3. Зарегистрировано в Департаменте юстиции Карагандинской области 30 июня 2023 года № 6463-09
title:
  rus: О переименовании улицы в селе Буркитты Киргизского сельского округа Каркаралинского района
  kaz: Қарқаралы ауданы Қырғыз ауылдық округінің Бүркітті ауылындағы көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-06-29
approved_by:
- '160013012002'
version_date:
  kaz: 2023-06-29
  rus: 2023-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/183426/kaz/29.06.2023
  rus: https://zan.gov.kz/client/#!/doc/183426/rus/29.06.2023
