act_code: '183271'
requisite: Решение Карагандинского областного маслихата от 22 июня 2023 года № 64
title:
  rus: Об утверждении Положения Государственного учреждения «Ревизионная комиссия по Карагандинской области»
  kaz: «Қарағанды облысы бойынша тексеру комиссиясы» мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2023-06-22
approved_by:
- '160000000002'
version_date:
  kaz: 2023-06-22
  rus: 2023-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/183271/kaz/22.06.2023
  rus: https://zan.gov.kz/client/#!/doc/183271/rus/22.06.2023
