act_code: '217158'
requisite: Решение Карагандинского областного маслихата от 20 ноября 2025 года № 334
title:
  rus: Об утверждении размера платы за один кубический метр питьевой воды, поданной из систем водоснабжения, включенных в перечень систем водоснабжения, стоимость услуг по подаче питьевой воды которых подлежит субсидированию по Карагандинской области
  kaz: Қарағанды облысы бойынша ауызсуды беру жөніндегі қызметтердің құны субсидиялауға жататын сумен жабдықтау жүйелерінің тізбесіне енгізілген сумен жабдықтау жүйелерінен берілген ауызсудың бір текше метріне төлемақы мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-20
approved_by:
- '160000000002'
version_date:
  kaz: 2025-11-20
  rus: 2025-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/217158/kaz/20.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217158/rus/20.11.2025
