act_code: '183388'
requisite: Решение Бухар-Жырауского районного маслихата Карагандинской области от 27 июня 2023 года № 10. Зарегистрировано в Департаменте юстиции Карагандинской области 29 июня 2023 года № 6460-09
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Бухар-Жырауском районе
  kaz: Бұқар жырау ауданында кентінде жеке оқу жоспары бойынша мүгедектігі бар балалар қатарындағы кемтар балаларды үйде оқытуға жұмсалған шығындарды  өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-06-27
approved_by:
- '160017000002'
version_date:
  kaz: 2023-06-27
  rus: 2023-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/183388/kaz/27.06.2023
  rus: https://zan.gov.kz/client/#!/doc/183388/rus/27.06.2023
