act_code: '51630'
requisite: Решение 21 сессии Абайского районного маслихата Карагандинской области от 18 марта 2010 года № 21/258. Зарегистрировано Управлением юстиции Абайского района Карагандинской области 7 апреля 2010 года № 8-9-79. Утратило силу - решением 34 сессии Абайского районного маслихата Карагандинской области от 28 марта 2011 года № 34/406
title:
  rus: О предоставлении мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры и спорта прибывшим для работы и проживания в сельские населенные пункты
  kaz: Ауылдық елді мекендерге жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына әлеуметтік қолдау шараларын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-18
approved_by:
- '160011000002'
version_date:
  kaz: 2010-03-18
  rus: 2010-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/51630/kaz/18.03.2010
  rus: https://zan.gov.kz/client/#!/doc/51630/rus/18.03.2010
