act_code: '78938'
requisite: Решение XХIV сессии Карагандинского областного маслихата от 15 апреля 2014 года № 278. Зарегистрировано Департаментом юстиции Карагандинской области 17 апреля 2014 года № 2592. Утратило силу решением Карагандинского областного маслихата от 25 февраля 2021 года № 34 (вводится в действие со дня его официального опубликования)
title:
  rus: О предоставлении дополнительных специализированных лечебных продуктов
  kaz: Қосымша мамандандырылған емдік өнімдерді беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-15
approved_by:
- '160000000002'
version_date:
  kaz: 2014-04-15
  rus: 2014-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/78938/kaz/15.04.2014
  rus: https://zan.gov.kz/client/#!/doc/78938/rus/15.04.2014
