act_code: '138682'
requisite: Решение акима Каркаралинского района Карагандинской области от 15 января 2020 года № 1. Зарегистрировано Департаментом юстиции Карагандинской области 16 января 2020 года № 5685. Утратило силу решением акима Каркаралинского района Карагандинской области от 24 апреля 2020 года № 2 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации
  kaz: Төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-15
approved_by:
- '160013000003'
version_date:
  kaz: 2020-01-15
  rus: 2020-01-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/138682/kaz/15.01.2020
  rus: https://zan.gov.kz/client/#!/doc/138682/rus/15.01.2020
