act_code: '53905'
requisite: Решение акима Егиндыбулакского сельского округа Каркаралинского района Карагандинской области от 12 июля 2010 года № 1. Зарегистрировано Управлением юстиции Каркаралинского района Карагандинской области 9 августа 2010 года № 8-13-85
title:
  rus: О переименовании улицы села Егиндыбулак
  kaz: Егіндібұлақ ауылының көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-12
approved_by:
- '160013003001'
version_date:
  kaz: 2010-07-12
  rus: 2010-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/53905/kaz/12.07.2010
  rus: https://zan.gov.kz/client/#!/doc/53905/rus/12.07.2010
