act_code: '53976'
requisite: Қарағанды облысы Жаңаарқа ауданының Атасу кенті әкімінің 2010 жылғы 4 тамыздағы № 2 шешімі. Қарағанды облысы Жаңаарқа ауданының Әділет басқармасында 2010 жылғы 13 тамызда № 8-12-78 тіркелді
title:
  rus: Атасу кентіндегі ДЭУ-43 көшесіне Қоңырбай Асановтың атын беру туралы
  kaz: Атасу кентіндегі ДЭУ-43 көшесіне Қоңырбай Асановтың атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-04
approved_by:
- '160016014001'
version_date:
  kaz: 2010-08-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/53976/kaz/04.08.2010
