act_code: '49531'
requisite: Решение XXVIII сессии IV созыва Карагандинского городского маслихата от 23 декабря 2009 года № 302. Зарегистрировано Управлением юстиции города Караганды 29 декабря 2009 года № 8-1-106
title:
  rus: О бюджете города Караганды на 2010-2012 годы
  kaz: Қарағанды қаласының 2010 - 2012 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '160002000002'
version_date:
  kaz: 2010-09-14
  rus: 2010-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/49531/kaz/14.09.2010
  rus: https://zan.gov.kz/client/#!/doc/49531/rus/14.09.2010
caused_by:
  code: '54644'
  requisite: Решение XXХVIII сессии IV созыва Карагандинского городского маслихата от 14 сентября 2010 года № 398. Зарегистрировано Управлением юстиции города Караганды 23 сентября 2010 года № 8-1-117
  title:
    rus: О внесении изменений в решение XXVIII сессии Карагандинского городского маслихата от 23 декабря 2009 года № 302 "О бюджете города Караганды на 2010-2012 годы"
    kaz: Қарағанды қалалық мәслихатының 2009 жылғы 23 желтоқсандағы XХVІІІ сессиясының "Қарағанды қаласының 2010-2012 жылдарға арналған бюджеті туралы" № 302 шешіміне өзгертулер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/54644/rus
