act_code: '85080'
requisite: Решение XХXIII сессии Каркаралинского районного маслихата Карагандинской области от 21 ноября 2014 года № 33/282. Зарегистрировано Департаментом юстиции Карагандинской области 18 декабря 2014 года № 2867. Утратило силу решением Каркаралинского районного маслихата Карагандинской области от 24 февраля 2022 года № VII-15/122 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества Каркаралинского района
  kaz: Қарқаралы ауданының бөлек жергілікті қоғамдастық жиындарын өткізу қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-11-21
approved_by:
- '160013000002'
version_date:
  kaz: 2014-11-21
  rus: 2014-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/85080/kaz/21.11.2014
  rus: https://zan.gov.kz/client/#!/doc/85080/rus/21.11.2014
