act_code: '66591'
requisite: Решение VI сессии Карагандинского областного маслихата от 28 июня 2012 года № 62. Зарегистрировано Департаментом юстиции Карагандинской области 13 июля 2012 года № 1915
title:
  rus: О правилах присвоения звания "Почетный гражданин области (города, района)"
  kaz: '"Облыстың (қаланың, ауданның) құрметті азаматы" атағын беру ережесі туралы'
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2012-06-28
approved_by:
- '160000000002'
version_date:
  kaz: 2022-03-17
  rus: 2022-03-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/66591/kaz/17.03.2022
  rus: https://zan.gov.kz/client/#!/doc/66591/rus/17.03.2022
caused_by:
  code: '166265'
  requisite: Решение Карагандинского областного маслихата от 17 марта 2022 года № 150. Зарегистрировано в Министерстве юстиции Республики Казахстан 8 апреля 2022 года № 27491
  title:
    rus: О внесении изменения в решение Карагандинского областного маслихата от 28 июня 2012 года № 62 «О правилах присвоения звания «Почетный гражданин области (города, района)»
    kaz: «Облыстың (қаланың, ауданның) Құрметті азаматы» атағын беру Ережесі туралы» Қарағанды облыстық мәслихатының 2012 жылғы 28 маусымдағы № 62 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166265/rus
