act_code: '107083'
requisite: Решение IV сессии Карагандинского областного маслихата от 29 сентября 2016 года № 84. Зарегистрировано Департаментом юстиции Карагандинской области 18 октября 2016 года № 3995
title:
  rus: Об определении перечня социально значимых городских (сельских), пригородных и внутрирайонных сообщений Карагандинской области
  kaz: Қарағанды облысының әлеуметтік маңызы бар қалалық (ауылдық), қала маңындағы және ауданішілік қатынастар тізбесін айқындау туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2016-09-29
approved_by:
- '160000000002'
version_date:
  kaz: 2024-06-20
  rus: 2024-06-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/107083/kaz/20.06.2024
  rus: https://zan.gov.kz/client/#!/doc/107083/rus/20.06.2024
caused_by:
  code: '198003'
  requisite: Решение Карагандинского областного маслихата от 20 июня 2024 года № 183. Зарегистрировано в Департаменте юстиции Карагандинской области 24 июня 2024 года № 6613-09
  title:
    rus: О внесении изменения в решение Карагандинского областного маслихата от 29 сентября 2016 года № 84 «Об определении перечня социально значимых городских (сельских), пригородных и внутрирайонных сообщений Карагандинской области»
    kaz: «Қарағанды облысының әлеуметтік маңызы бар қалалық (ауылдық), қала маңындағы және ауданішілік қатынастар тізбесін айқындау туралы» Қарағанды облыстық мәслихатының 2016 жылғы 29 қыркүйектегі № 84 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198003/rus
