act_code: '128006'
requisite: Решение Балхашского городского маслихата Карагандинской области от 26 декабря 2018 года № 25/215. Зарегистрировано Департаментом юстиции Карагандинской области 28 декабря 2018 года № 5104
title:
  rus: О бюджете посёлка Саяк на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Саяқ кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-26
approved_by:
- '160008000002'
version_date:
  kaz: 2019-11-14
  rus: 2019-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/128006/kaz/14.11.2019
  rus: https://zan.gov.kz/client/#!/doc/128006/rus/14.11.2019
caused_by:
  code: '136281'
  requisite: Решение Балхашского городского маслихата Карагандинской области от 14 ноября 2019 года № 34/275. Зарегистрировано Департаментом юстиции Карагандинской области 25 ноября 2019 года № 5533
  title:
    rus: О внесении изменений в решение городского маслихата от 26 декабря 2018 года № 25/215 «О бюджете посёлка Саяк на 2019-2021 годы»
    kaz: Қалалық мәслихатының 2018 жылғы 26 желтоқсандағы № 25/215 «2019-2021 жылдарға арналған Саяқ кентінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136281/rus
