act_code: '56048'
requisite: Решение акима Бухар-Жырауского района Карагандинской области от 9 декабря 2010 года № 7. Зарегистрировано управлением юстиции Бухар-Жырауского района Карагандинской области 21 декабря 2010 года № 8-11-105. Утратило силу - решением акима Бухар-Жырауского района Карагандинской области от 15 декабря 2011 года № 6
title:
  rus: О проведении приписки граждан 1994 года рождения к призывному участку
  kaz: 1994 жылы туған азаматтарды шақыру учаскесіне тіркеуді өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-09
approved_by:
- '160017000003'
version_date:
  kaz: 2010-12-09
  rus: 2010-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/56048/kaz/09.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56048/rus/09.12.2010
