act_code: '85422'
requisite: Решение XLI сессии V созыва Карагандинского городского маслихата от 27 ноября 2014 года № 363. Зарегистрировано Департаментом юстиции Карагандинской области 29 декабря 2014 года № 2898. Утратило силу решением Карагандинского городского маслихата от 27 сентября 2023 года № 96 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан города Караганды
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Қарағанды қаласындағы мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-11-27
approved_by:
- '160002000002'
version_date:
  kaz: 2015-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/85422/kaz/25.02.2015
caused_by:
  code: '89317'
  requisite: Решение XLIV сессии V созыва Карагандинского городского маслихата от 25 февраля 2015 года № 423. Зарегистрировано Департаментом юстиции Карагандинской области 17 марта 2015 года № 3048. Утратило силу решением Карагандинского городского маслихата от 27 сентября 2023 года № 96 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в некоторые решения Карагандинского городского маслихата
    kaz: Қарағанды қалалық мәслихатының кейбір шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/89317/rus
