act_code: '85422'
requisite: Решение XLI сессии V созыва Карагандинского городского маслихата от 27 ноября 2014 года № 363. Зарегистрировано Департаментом юстиции Карагандинской области 29 декабря 2014 года № 2898. Утратило силу решением Карагандинского городского маслихата от 27 сентября 2023 года № 96 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан города Караганды
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Қарағанды қаласындағы мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-11-27
approved_by:
- '160002000002'
version_date:
  kaz: 2023-05-25
  rus: 2023-05-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/85422/kaz/25.05.2023
  rus: https://zan.gov.kz/client/#!/doc/85422/rus/25.05.2023
caused_by:
  code: '182083'
  requisite: Решение Карагандинского городского маслихата от 25 мая 2023 года № 33. Зарегистрировано Департаментом юстиции Карагандинской области 26 мая 2023 года № 6418-09. Утратило силу решением Карагандинского городского маслихата от 27 сентября 2023 года № 96 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении дополнения в решение Карагандинского городского маслихата от 27 ноября 2014 года № 363 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан города Караганды»
    kaz: Қарағанды қалалық мәслихатының 2014 жылғы 27 қарашадағы № 363 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Қарағанды қаласындағы мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау Қағидасын бекіту туралы» шешіміне толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/182083/rus
