act_code: '53676'
requisite: Решение 23 сессии Абайского районного маслихата Карагандинской области от 17 июня 2010 года № 23/278. Зарегистрировано Управлением юстиции Абайского района Карагандинской области 26 июля 2010 года № 8-9-84. Утратило силу - решением 40 сессии Абайского районного маслихата Карагандинской области от 28 ноября 2011 года № 40/488
title:
  rus: Об утверждении Правил предоставления жилищной помощи по Абайскому району
  kaz: Абай ауданы бойынша тұрғын үй көмегін беру Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-06-17
approved_by:
- '160011000002'
version_date:
  kaz: 2010-12-23
  rus: 2010-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/53676/kaz/23.12.2010
  rus: https://zan.gov.kz/client/#!/doc/53676/rus/23.12.2010
caused_by:
  code: '56283'
  requisite: Решение 31 сессии Абайского районного маслихата Карагандинской области от 23 декабря 2010 года N 31/385. Зарегистрировано Управлением юстиции Абайского района Карагандинской области 29 декабря 2010 года № 8-9-94. Утратило силу - решением 40 сессии Абайского районного маслихата Карагандинской области от 28 ноября 2011 года № 40/488
  title:
    rus: О внесении дополнения в решение 23 очередной сессии Абайского районного маслихата от 17 июня 2010 года № 23/278 "Об утверждении Правил предоставления жилищной помощи по Абайскому району"
    kaz: Абай аудандық мәслихатының 2010 жылғы 17 маусымдағы 23 кезекті сессиясының № 23/278 "Абай ауданы бойынша тұрғын үй көмегін беру Ережесін бекіту туралы" шешіміне толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/56283/rus
