act_code: '189594'
requisite: Решение Шетского районного маслихата Карагандинской области от 24 ноября 2023 года № 6/63. Зарегистрировано в Департаменте юстиции Карагандинской области 6 декабря 2023 года № 6529-09
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-11-24
approved_by:
- '160015000002'
version_date:
  kaz: 2024-12-24
  rus: 2024-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/189594/kaz/24.12.2024
  rus: https://zan.gov.kz/client/#!/doc/189594/rus/24.12.2024
caused_by:
  code: '205130'
  requisite: Решение Шетского районного маслихата Карагандинской области от 24 декабря 2024 года № 19/170. Зарегистрировано Департаментом юстиции Карагандинской области 27 декабря 2024 года № 6695-09
  title:
    rus: О внесении изменения в решение Шетского районного маслихата от 24 ноября 2023 года № 6/63 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Шет аудандық мәслихатының 2023 жылғы 24 қарашадағы № 6/63 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/205130/rus
