act_code: '187568'
requisite: Решение Нуринского районного маслихата Карагандинской области от 23 октября 2023 года № 47. Зарегистрировано в Департаменте юстиции Карагандинской области 26 октября 2023 года № 6506-09
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану
  kaz: Мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқу жоспары бойынша үйде оқытуға жұмсалған шығындарды өтеу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2023-10-23
approved_by:
- '160012000002'
version_date:
  kaz: 2024-12-06
  rus: 2024-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/187568/kaz/06.12.2024
  rus: https://zan.gov.kz/client/#!/doc/187568/rus/06.12.2024
caused_by:
  code: '203893'
  requisite: Решение Нуринского районного маслихата Карагандинской области от 6 декабря 2024 года № 125. Зарегистрировано в Департаменте юстиции Карагандинской области 10 декабря 2024 года № 6689-09
  title:
    rus: О внесении изменений в решение Нуринского районного маслихата от 23 октября 2023 года № 47 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану»
    kaz: Нұра аудандық мәслихатының 2023 жылғы 23 қазандағы № 47 «Мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқу жоспары бойынша үйде оқытуға жұмсалған шығындарды өтеу тәртібі мен мөлшерін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/203893/rus
