act_code: '176043'
requisite: Решение Балхашского городского маслихата Карагандинской области от 21 декабря 2022 года № 19/143. Зарегистрировано в Министерстве юстиции Республики Казахстан 26 декабря 2022 года № 31271. Утратило силу решением Балхашского городского маслихата Карагандинской области от 28 декабря 2023 года № 11/92 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по городу Балхаш
  kaz: Балқаш қаласы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-21
approved_by:
- '160008000002'
version_date:
  kaz: 2023-11-03
  rus: 2023-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/176043/kaz/03.11.2023
  rus: https://zan.gov.kz/client/#!/doc/176043/rus/03.11.2023
caused_by:
  code: '187972'
  requisite: Решение Балхашского городского маслихата Карагандинской области от 3 ноября 2023 года № 8/72. Утратило силу решением Балхашского городского маслихата Карагандинской области от 28 декабря 2023 года № 11/92 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Балхашского городского маслихата от 21 декабря 2022 года № 19/143 «Об утверждении норм образования и накопления коммунальных отходов по городу Балхаш»
    kaz: Балқаш қалалық мәслихатының 2022 жылғы 21 желтоқсандағы № 19/143 «Балқаш қаласы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/187972/rus
