act_code: '56352'
requisite: Қарағанды облысы Ақтоғай аудандық мәслихатының 29 сессиясының 2010 жылғы 23 желтоқсандағы № 273 шешімі. Қарағанды облысы Ақтоғай ауданының Әділет басқармасында 2010 жылғы 28 желтоқсанда № 8-10-128 тіркелді
title:
  rus: 2011-2013 жылдарға арналған аудандық бюджет туралы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '160014000002'
version_date:
  kaz: 2011-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/56352/kaz/25.03.2011
caused_by:
  code: '58184'
  requisite: Решение 31 сессии Актогайского районного маслихата Карагандинской области от 25 марта 2011 года № 293. Зарегистрировано Управлением юстиции Актогайского района Карагандинской области 13 апреля 2011 года № 8-10-132
  title:
    rus: О внесении изменений в решение 29 сессии Актогайского районного маслихата от 23 декабря 2010 года № 273 "О районном бюджете на 2011-2013 годы"
    kaz: Ақтоғай аудандық мәслихатының 2010 жылғы 23 желтоқсандағы 29 сессиясының "2011-2013 жылдарға арналған аудандық бюджет туралы" № 273 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/58184/rus
