act_code: '58534'
requisite: Решение Темиртауского городского маслихата Карагандинской области от 1 апреля 2011 года № 38/4. Зарегистрировано Управлением юстиции города Темиртау Карагандинской области 25 апреля 2011 года № 8-3-117
title:
  rus: О льготном проезде на внутригородском общественном транспорте (кроме такси) обучающихся и воспитанников очной формы обучения
  kaz: Күндiзгi білім беру нысандарында оқитындарға және тәрбиеленушілерге қала ішіндегі қоғамдық көлiктерде (таксиден басқа) жол жүрулеріне жеңiлдiк беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-04-01
approved_by:
- '160005000002'
version_date:
  kaz: 2012-01-01
  rus: 2012-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/58534/kaz/01.01.2012
  rus: https://zan.gov.kz/client/#!/doc/58534/rus/01.01.2012
