act_code: '29236'
requisite: Қарағанды облысы Сәтбаев қалалық мәслихатының 2006 жылғы 28 шілдедегі № 359 шешімі. Қарағанды облысы Сәтбаев қаласы Әділет басқармасында 2006 жылғы 4 тамызда № 8-6-30 тіркелді. Күші жойылды - Қарағанды облысы Сәтбаев қалалық мәслихатының 2010 жылғы 14 мамырдағы № 336 шешімімен
title:
  rus: Аз қамтылған азаматтарға тұрғын үйді ұстауға, тұрғын үйлерді күрделі жөндеуден өткізуге, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақысын және қалалық және селолық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы беру қағидасын бекіту туралы
  kaz: Аз қамтылған азаматтарға тұрғын үйді ұстауға, тұрғын үйлерді күрделі жөндеуден өткізуге, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақысын және қалалық және селолық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы беру қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2006-07-28
approved_by:
- '160007000002'
version_date:
  kaz: 2008-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/29236/kaz/01.07.2008
caused_by:
  code: '40348'
  requisite: Решение Сатпаевского городского маслихата Карагандинской области от 1 июля 2008 года № 121. Зарегистрировано Управлением юстиции города Сатпаев Карагандинской области 4 июля 2008 года № 8-6-66. Утратило силу - решением Сатпаевского городского маслихата Карагандинской области от 14 мая 2010 года № 336
  title:
    rus: О внесении изменения в решение XXXIII сессии городского маслихата от 28 июля 2006 года № 359 "Об утверждении Правил предоставления малообеспеченным гражданам жилищного пособия на содержание жилья, включая капитальный ремонт жилого дома, оплату коммунальных услуг и компенсацию повышения тарифов абонентской платы за телефон абонентам городских сетей телекоммуникаций"
    kaz: '"Аз қамтылған азаматтарға тұрғын үйді ұстауға, тұрғын үйлерді күрделі жөндеуден өткізуге, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақысын беру және қалалық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы беру қағидасын бекіту туралы" қалалық мәслихаттың 2006 жылғы 28 шілдедегі XXXIII сессиясының № 359 шешіміне өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/40348/rus
