act_code: '62722'
requisite: Решение 42 сессии Абайского районного маслихата Карагандинской области от 12 декабря 2011 года № 42/501. Зарегистрировано Управлением юстиции Абайского района Карагандинской области 12 января 2012 года № 8-9-123. Утратило силу решением Абайского районного маслихата Карагандинской области от 19 апреля 2018 года № 29/324
title:
  rus: Об увеличении базовых ставок налога на земли Абайского района, выделенные под автостоянки
  kaz: Абай ауданындағы автотұрақтар үшін бөлінген жерлерге салынатын базалық салық мөлшерлемелерінің көбеюі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-12
approved_by:
- '160011000002'
version_date:
  kaz: 2011-12-12
  rus: 2011-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/62722/kaz/12.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62722/rus/12.12.2011
