act_code: '178135'
requisite: Решение акима поселка Саяк города Балхаш Карагандинской области от 20 января 2023 года № 03р. Зарегистрировано Департаментом юстиции Карагандинской области 20 января 2023 года № 6349
title:
  rus: О переименовании некоторых улиц поселка Саяк
  kaz: Саяқ кентінің кейбір көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-01-20
approved_by:
- '160008003001'
version_date:
  kaz: 2023-01-20
  rus: 2023-01-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/178135/kaz/20.01.2023
  rus: https://zan.gov.kz/client/#!/doc/178135/rus/20.01.2023
