act_code: '34209'
requisite: Қарағанды облысы Қарқаралы аудандық мәслихатының 2007 жылғы 17 шілдедегі N 33/216 шешімі. Қарағанды облысы Қарқаралы ауданы әділет басқармасында 2007 жылғы 19 шілдеде N 8-13-32 тіркелді. Күші жойылды - Қарағанды облысы Қарқаралы аудандық мәслихатының 2016 жылғы 19 мамырдағы № VI-3/24 шешімімен
title:
  rus: Қарқаралы ауданы бойынша бейбіт жиналыстар, митингілер, шерулер, пикеттер және демонстрациялар ұйымдастыру мен өткізу орнын қосымша реттеу туралы
  kaz: Қарқаралы ауданы бойынша бейбіт жиналыстар, митингілер, шерулер, пикеттер және демонстрациялар ұйымдастыру мен өткізу орнын қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-07-17
approved_by:
- '160013000002'
version_date:
  kaz: 2007-07-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/34209/kaz/17.07.2007
