act_code: '144307'
requisite: Решение Карагандинского городского маслихата от 24 июня 2020 года № 525. Зарегистрировано Департаментом юстиции Карагандинской области 1 июля 2020 года № 5913
title:
  rus: О специализированных местах для организации и проведения мирных собраний и границах, прилегающих территорий, в которых запрещено проведение пикетирования на территории города Караганды
  kaz: Қарағанды қаласының аумағында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындар және пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекаралары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-24
approved_by:
- '160002000002'
version_date:
  kaz: 2024-02-28
  rus: 2024-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/144307/kaz/28.02.2024
  rus: https://zan.gov.kz/client/#!/doc/144307/rus/28.02.2024
caused_by:
  code: '194392'
  requisite: Решение Карагандинского городского маслихата от 28 февраля 2024 года № 16/133. Зарегистрировано в Департаменте юстиции Карагандинской области 14 марта 2024 года № 6568-09
  title:
    rus: О внесении изменения в решение Карагандинского городского маслихата от 24 июня 2020 года № 525 «О специализированных местах для организации и проведения мирных собраний и границах, прилегающих территорий, в которых запрещено проведение пикетирования на территории города Караганды»
    kaz: Қарағанды қалалық мәслихатының 2020 жылғы 24 маусымдағы № 525 «Қарағанды қаласының аумағында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындар және пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекаралары туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/194392/rus
