act_code: '11206'
requisite: Решение Акима Карагандинской области от 26 декабря 2001 года № 263. Зарегистрировано управлением юстиции Карагандинской области 31 января 2002 года за № 613. Утратило силу решением акима Карагандинской области от 14 апреля 2008 года № 01
title:
  rus: О профилактических и противоэпидемических мероприятиях по предупреждению биотерроризма
  kaz: Биотерроризмді ескерту жөніндегі алдын алу және эпидемияға қарсы шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-12-26
approved_by:
- '160000000001'
version_date:
  kaz: 2001-12-26
  rus: 2001-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/11206/kaz/26.12.2001
  rus: https://zan.gov.kz/client/#!/doc/11206/rus/26.12.2001
