act_code: '65553'
requisite: Решение II сессии V созыва Карагандинского городского маслихата от 16 апреля 2012 года № 32. Зарегистрировано Управлением юстиции города Караганды 14 мая 2012 года № 8-1-154. Утратило силу решением Карагандинского городского маслихата от 3 июля 2024 года № 165 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил предоставления жилищной помощи населению города Караганды
  kaz: Қарағанды қаласының тұрғындарына тұрғын үй көмегін көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2012-04-16
approved_by:
- '160002000002'
version_date:
  kaz: 2018-07-18
  rus: 2018-07-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/65553/kaz/18.07.2018
  rus: https://zan.gov.kz/client/#!/doc/65553/rus/18.07.2018
caused_by:
  code: '123799'
  requisite: Решение ХХVII сессии VI созыва Карагандинского городского маслихата от 18 июля 2018 года № 308. Зарегистрировано Департаментом юстиции Карагандинской области 24 июля 2018 года № 4883. Утратило силу решением Карагандинского городского маслихата от 3 июля 2024 года № 165 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения и дополнения в решение II сессии V созыва Карагандинского городского маслихата от 16 апреля 2012 года № 32 «Об утверждении Правил предоставления жилищной помощи населению города Караганды»
    kaz: V шақырылған Қарағанды қалалық мәслихатының 2012 жылғы 16 сәуірдегі II сессиясының «Қарағанды қаласының тұрғындарына тұрғын үй көмегін көрсету Ережесін бекіту туралы» № 32 шешіміне өзгеріс пен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123799/rus
