act_code: '193275'
requisite: Решение акима Мадийского сельского округа Каркаралинского района Карагандинской области от 13 февраля 2024 года № 1
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын алып тастау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-13
approved_by:
- '160013013002'
version_date:
  kaz: 2024-02-13
  rus: 2024-02-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/193275/kaz/13.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193275/rus/13.02.2024
