act_code: '55037'
requisite: Қарағанды облысы Жаңаарқа ауданы Атасу кенті әкімінің 2010 жылғы 29 қыркүйектегі № 4 шешімі. Қарағанды облысы Жаңаарқа ауданының Әділет басқармасында 2010 жылғы 25 қазанда № 8-12-94 тіркелді
title:
  rus: Атасу кентіндегі Железнодорожная көшесіне Смаилов Туребайдың атын беру туралы
  kaz: Атасу кентіндегі Железнодорожная көшесіне Смаилов Туребайдың атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-29
approved_by:
- '160016014001'
version_date:
  kaz: 2010-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/55037/kaz/29.09.2010
