act_code: '138469'
requisite: Решение акима Абайского района Карагандинской области от 9 января 2020 года № 1. Зарегистрировано Департаментом юстиции Карагандинской области 13 января 2020 года № 5677
title:
  rus: О проведении приписки граждан мужского пола 2003 года рождения к призывному участку отдела по делам обороны Абайского района
  kaz: Абай ауданының қорғаныс істері жөніндегі бөлімінің шақыру учаскесіне 2003 жылы туған ер азаматтарды тіркеуді өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-09
approved_by:
- '160011000003'
version_date:
  kaz: 2020-01-09
  rus: 2020-01-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/138469/kaz/09.01.2020
  rus: https://zan.gov.kz/client/#!/doc/138469/rus/09.01.2020
