act_code: '138009'
requisite: Решение Балхашского городского маслихата Карагандинской области от 25 декабря 2019 года № 35/283. Зарегистрировано Департаментом юстиции Карагандинской области 5 января 2020 года № 5660
title:
  rus: Об утверждении регламента собрания местного сообщества поселка Гулшат
  kaz: Гүлшат кенті жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2019-12-25
approved_by:
- '160008000002'
version_date:
  kaz: 2019-12-25
  rus: 2019-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/138009/kaz/25.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138009/rus/25.12.2019
