act_code: '104689'
requisite: Решение 4 сессии Актогайского районного маслихата Карагандинской области от 29 июня 2016 года № 42. Зарегистрировано Департаментом юстиции Карагандинской области 12 июля 2016 года № 3887. Утратило силу решением Актогайского районного маслихата Карагандинской области от 28 мая 2018 года № 218
title:
  rus: О повышении базовой ставки земельного налога на не используемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения
  kaz: Қазақстан Республикасының жер заңнамасына сәйкес пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге базалық жер салығының мөлшерлемесін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-06-29
approved_by:
- '160014000002'
version_date:
  kaz: 2016-06-29
  rus: 2016-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/104689/kaz/29.06.2016
  rus: https://zan.gov.kz/client/#!/doc/104689/rus/29.06.2016
