act_code: '97467'
requisite: Решение Жезказганского городского маслихата Карагандинской области от 25 декабря 2015 года № 38/344. Зарегистрировано Департаментом юстиции Карагандинской области 8 января 2016 года № 3601
title:
  rus: О городском бюджете на 2016-2018 годы
  kaz: 2016-2018  жылдарға  арналған қалалық  бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-25
approved_by:
- '160006000002'
version_date:
  kaz: 2016-05-11
  rus: 2016-05-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/97467/kaz/11.05.2016
  rus: https://zan.gov.kz/client/#!/doc/97467/rus/11.05.2016
caused_by:
  code: '103065'
  requisite: Решение Жезказганского городского маслихата Карагандинской области от 11 мая 2016 года № 2/19. Зарегистрировано Департаментом юстиции Карагандинской области 16 мая 2016 года № 3786
  title:
    rus: О внесении изменений в решение XXXVIII сессии Жезказганского городского маслихата от 25 декабря 2015 года №38/344 «О городском бюджете на 2016-2018 годы»
    kaz: Жезқазған қалалық мәслихатының 2015 жылғы 25 желтоқсандағы ХХХVIII сессиясының №38/344 «2016-2018  жылдарға арналған қалалық бюджет туралы»  шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/103065/rus
