act_code: '120882'
requisite: Решение акима Босагинского сельского округа Шетского района Карагандинской области от 9 апреля 2018 года № 01. Зарегистрировано Департаментом юстиции Карагандинской области 18 апреля 2018 года № 4710
title:
  rus: О переименовании улицы в селе Босага Шетского района
  kaz: Шет ауданы Босаға ауылындағы көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-04-09
approved_by:
- '160015009002'
version_date:
  kaz: 2018-04-09
  rus: 2018-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/120882/kaz/09.04.2018
  rus: https://zan.gov.kz/client/#!/doc/120882/rus/09.04.2018
