act_code: '27989'
requisite: Қарағанды облысы Нұра аудандық мәслихатының 23 сессиясының 2006 жылғы 20 сәуірдегі № 240 шешімі. Нұра ауданы Әділет басқармасында 2006 жылғы 29 мамырда № 8-14-26 тіркелді
title:
  rus: Біржолғы талондардың құнын белгілеу туралы
  kaz: Біржолғы талондардың құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-04-20
approved_by:
- '160012000002'
version_date:
  kaz: 2006-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/27989/kaz/20.04.2006
