act_code: '166135'
requisite: Решение акима Осакаровского района Карагандинской области от 5 апреля 2022 года № 01. Зарегистрировано в Министерстве юстиции Республики Казахстан 6 апреля 2022 года № 27460. Утратило силу решением акима Осакаровского района Карагандинской области от 22 августа 2022 года № 03 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба на территории Осакаровского района
  kaz: Осакаров ауданы аумағында жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-05
approved_by:
- '160018000003'
version_date:
  kaz: 2022-04-05
  rus: 2022-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/166135/kaz/05.04.2022
  rus: https://zan.gov.kz/client/#!/doc/166135/rus/05.04.2022
