act_code: '137911'
requisite: Решение Каркаралинского районного маслихата Карагандинской области от 25 декабря 2019 года № VI-51/418. Зарегистрировано Департаментом юстиции Карагандинской области 31 декабря 2019 года № 5642
title:
  rus: О районном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '160013000002'
version_date:
  kaz: 2020-09-03
  rus: 2020-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/137911/kaz/03.09.2020
  rus: https://zan.gov.kz/client/#!/doc/137911/rus/03.09.2020
caused_by:
  code: '146227'
  requisite: Решение Каркаралинского районного маслихата Карагандинской области от 3 сентября 2020 года № VI-60/508. Зарегистрировано Департаментом юстиции Карагандинской области 11 сентября 2020 года № 6037
  title:
    rus: О внесении изменений в решение LI сессии Каркаралинского районного маслихата от 25 декабря 2019 года № VI-51/418 «О районном бюджете на 2020-2022 годы»
    kaz: Қарқаралы аудандық мәслихатының 2019 жылғы 25 желтоқсандағы LI сессиясының № VI-51/418 «2020-2022 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146227/rus
