act_code: '31126'
requisite: Решение маслихата города Приозерска Карагандинской области от 15 декабря 2006 года № 204/36. Зарегистрировано управлением юстиции города Балхаша 8 января 2007 года за № 8-4-56
title:
  rus: О городском бюджете на 2007 год
  kaz: 2007 жылға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-15
approved_by:
- '160009000002'
version_date:
  kaz: 2006-12-15
  rus: 2006-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/31126/kaz/15.12.2006
  rus: https://zan.gov.kz/client/#!/doc/31126/rus/15.12.2006
