act_code: '50540'
requisite: Решение Темиртауского городского маслихата Карагандинской области от 5 января 2010 года № 24/4. Зарегистрировано Управлением юстиции города Темиртау Карагандинской области 5 февраля 2010 года № 8-3-92. Утратило силу - решением Темиртауского городского маслихата Карагандинской области от 16 апреля 2010 года № 28/6
title:
  rus: О льготном проезде на внутригородском общественном транспорте (кроме такси) учащихся очной формы обучения
  kaz: Күндізгі білім беру ұйымдарының оқушыларына қала ішіндегі қоғамдық көліктерде (таксиден басқа) жол жүрулеріне жеңілдік беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-01-05
approved_by:
- '160005000002'
version_date:
  kaz: 2010-01-05
  rus: 2010-01-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/50540/kaz/05.01.2010
  rus: https://zan.gov.kz/client/#!/doc/50540/rus/05.01.2010
