act_code: '124931'
requisite: Решение акима поселка Дарья Шетского района Карагандинской области от 7 сентября 2018 года № 1. Зарегистрировано Департаментом юстиции Карагандинской области 1 октября 2018 года № 4963
title:
  rus: О переименовании улицы поселка Дарья Шетского района
  kaz: Шет ауданы Дәрия кентіндегі көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-09-07
approved_by:
- '160015007001'
version_date:
  kaz: 2018-09-07
  rus: 2018-09-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/124931/kaz/07.09.2018
  rus: https://zan.gov.kz/client/#!/doc/124931/rus/07.09.2018
