act_code: '197687'
requisite: Решение Абайского районного маслихата Карагандинской области от 12 июня 2024 года № 20/194. Зарегистрировано в Департаменте юстиции Карагандинской области 13 июня 2024 года № 6606-09
title:
  rus: Об утверждении ставки туристского взноса для иностранцев в Абайском районе Карагандинской области на 2024 год
  kaz: Қарағанды облысының Абай ауданында шетелдіктер үшін 2024 жылға арналған туристік жарнаның мөлшерлемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-06-12
approved_by:
- '160011000002'
version_date:
  kaz: 2024-06-12
  rus: 2024-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/197687/kaz/12.06.2024
  rus: https://zan.gov.kz/client/#!/doc/197687/rus/12.06.2024
