act_code: '126666'
requisite: Решение акима Новоузенского сельского округа Бухар-Жырауского района Карагандинской области от 22 ноября 2018 года № 1. Зарегистрировано Департаментом юстиции Карагандинской области 10 декабря 2018 года № 5036
title:
  rus: О составных частях населенных пунктов Новоузенского сельского округа
  kaz: Новоузенка ауылдық округінің елді мекендерінің құрамдас бөлiктерi туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-22
approved_by:
- '160017019002'
version_date:
  kaz: 2018-11-22
  rus: 2018-11-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/126666/kaz/22.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126666/rus/22.11.2018
