act_code: '105495'
requisite: Решение акима села Жанаталап Бухар-Жырауского района Карагандинской области от 30 мая 2016 года № 3. Зарегистрировано Департаментом юстиции Карагандинской области 27 июня 2016 года № 3871
title:
  rus: О переименовании улицы в селе Жанаталап
  kaz: Жаңаталап ауылындағы көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-05-30
approved_by:
- '160017017001'
version_date:
  kaz: 2016-05-30
  rus: 2016-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/105495/kaz/30.05.2016
  rus: https://zan.gov.kz/client/#!/doc/105495/rus/30.05.2016
