act_code: '32899'
requisite: Решение Жезказганского городского маслихата Карагандинской области от 04 апреля 2007 года № 36/413. Зарегистрировано управлением юстиции города Жезказган 25 апреля 2007 года № 8-2-45. Утратило силу решением Жезказганского городского маслихата Карагандинской области от 18 января 2008 года № 4/52
title:
  rus: Об установлении размера фиксированного суммарного налога с единицы объектов налогообложения на территории города Жезказгана на 2007 год
  kaz: 2007 жылға арналған Жезқазған қаласы аумағында бірлік объектілерге салық салудың белгіленген жиынтық салықтың мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-04-04
approved_by:
- '160006000002'
version_date:
  kaz: 2007-04-04
  rus: 2007-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/32899/kaz/04.04.2007
  rus: https://zan.gov.kz/client/#!/doc/32899/rus/04.04.2007
