act_code: '189086'
requisite: Решение Каркаралинского районного маслихата Карагандинской области от 22 ноября 2023 года № VII-12/93. Зарегистрировано в Департаменте юстиции Карагандинской области 27 ноября 2023 года № 6522-09
title:
  rus: Об утверждении проекта (схемы) зонирования земель, повышении ставок земельного налога Каркаралинского района
  kaz: Қарқаралы ауданының жерлерін аймақтарға бөлу жобасын (схемасын) бекіту және жер салығының базалық мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-11-22
approved_by:
- '160013000002'
version_date:
  kaz: 2023-11-22
  rus: 2023-11-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/189086/kaz/22.11.2023
  rus: https://zan.gov.kz/client/#!/doc/189086/rus/22.11.2023
