act_code: '51483'
requisite: Решение Жезказганского городского маслихата Карагандинской области от 12 марта 2010 года № 21/247. Зарегистрировано Управлением юстиции города Жезказган Карагандинской области 30 марта 2010 года № 8-2-112. Утратило силу - решением Жезказганского городского маслихата Карагандинской области от 23 декабря 2010 года № 28/331
title:
  rus: О предоставлении подъемного пособия специалистам здравоохранения, образования, социального обеспечения, культуры и спорта, прибывшим для работы и проживания в сельские населенные пункты на 2010 год
  kaz: 2010 жылға арналған ауылдық елді мекендерге жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына көтерме жәрдемақы ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-12
approved_by:
- '160006000002'
version_date:
  kaz: 2010-03-12
  rus: 2010-03-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/51483/kaz/12.03.2010
  rus: https://zan.gov.kz/client/#!/doc/51483/rus/12.03.2010
