act_code: '179959'
requisite: Решение Карагандинского областного маслихата от 18 апреля 2023 года № 33. Зарегистрировано Департаментом юстиции Карагандинской области 19 апреля 2023 года № 6384-09
title:
  rus: Об определении системы мер социальной поддержки медицинских и фармацевтических работников
  kaz: Медициналық және фармацевтикалық қызметкерлерінің әлеуметтік қолдау шараларының жүйесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-04-18
approved_by:
- '160000000002'
version_date:
  kaz: 2025-06-26
  rus: 2025-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/179959/kaz/26.06.2025
  rus: https://zan.gov.kz/client/#!/doc/179959/rus/26.06.2025
caused_by:
  code: '211754'
  requisite: Решение Карагандинского областного маслихата от 26 июня 2025 года № 296
  title:
    rus: О внесении изменения в решение Карагандинского областного маслихата от 18 апреля 2023 года № 33 «Об определении системы мер социальной поддержки медицинских и фармацевтических работников»
    kaz: Қарағанды облыстық мәслихатының 2023 жылғы 18 сәуірдегі № 33 «Медицина және фармацевтика қызметкерлерін әлеуметтік қолдау шараларының жүйесін айқындау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/211754/rus
