act_code: '179959'
requisite: Решение Карагандинского областного маслихата от 18 апреля 2023 года № 33. Зарегистрировано Департаментом юстиции Карагандинской области 19 апреля 2023 года № 6384-09
title:
  rus: Об определении системы мер социальной поддержки медицинских и фармацевтических работников
  kaz: Медициналық және фармацевтикалық қызметкерлерінің әлеуметтік қолдау шараларының жүйесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-04-18
approved_by:
- '160000000002'
version_date:
  kaz: 2024-02-22
  rus: 2024-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/179959/kaz/22.02.2024
  rus: https://zan.gov.kz/client/#!/doc/179959/rus/22.02.2024
caused_by:
  code: '193724'
  requisite: Решение Карагандинского областного маслихата от 22 февраля 2024 года № 144. Зарегистрировано в Департаменте юстиции Карагандинской области 27 февраля 2024 года № 6561-09
  title:
    rus: О внесении изменений в решение Карагандинского областного маслихата от 18 апреля 2023 года № 33 «Об определении системы мер социальной поддержки медицинских и фармацевтических работников»
    kaz: Қарағанды облыстық мәслихатының 2023 жылғы 18 сәуірдегі № 33 «Медициналық және фармацевтикалық қызметкерлерін әлеуметтік қолдау шараларының жүйесін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/193724/rus
