act_code: '49586'
requisite: Решение 21 сессии Саранского городского маслихата Карагандинской области от 22 декабря 2009 года № 356. Зарегистрировано Управлением юстиции города Сарани Карагандинской области 30 декабря 2009 года № 8-7-98
title:
  rus: О городском бюджете на 2010-2012 годы
  kaz: 2010 - 2012 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-22
approved_by:
- '160003000002'
version_date:
  kaz: 2010-02-25
  rus: 2010-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/49586/kaz/25.02.2010
  rus: https://zan.gov.kz/client/#!/doc/49586/rus/25.02.2010
caused_by:
  code: '51245'
  requisite: Решение 23 сессии Саранского городского маслихата Карагандинской области от 25 февраля 2010 года № 388. Зарегистрировано Управлением юстиции города Сарани Карагандинской области 18 марта 2010 года № 8-7-102
  title:
    rus: О внесении изменений в решение 21 сессии Саранского городского маслихата от 22 декабря 2009 года № 356 "О городском бюджете на 2010 - 2012 годы"
    kaz: Саран қалалық мәслихатының 2009 жылғы 22 желтоқсандағы 21 сессиясының "2010-2012 жылдарға арналған қалалық бюджет туралы" № 356 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51245/rus
