act_code: '29233'
requisite: Қарағанды қалалық мәслихатының III шақырылған XXXVI сессиясының 2006 жылғы 14 шілдедегі № 3 шешімі. Қарағанды қаласы әділет басқармасында 2006 жылғы 31 шілдеде № 8-1-37 тіркелді
title:
  rus: ІІІ шақырылған Қарағанды қалалық мәслихатының 2005 жылғы 15 желтоқсандағы XХVI сессиясының «Қарағанды қаласының 2006 жылға арналған бюджеті туралы» № 8 шешіміне өзгертулер  енгізу туралы
  kaz: ІІІ шақырылған Қарағанды қалалық мәслихатының 2005 жылғы 15 желтоқсандағы XХVI сессиясының «Қарағанды қаласының 2006 жылға арналған бюджеті туралы» № 8 шешіміне өзгертулер  енгізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-07-14
approved_by:
- '160002000002'
version_date:
  kaz: 2006-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/29233/kaz/14.07.2006
