act_code: '121576'
requisite: Решение 34 сессии Осакаровского районного маслихата Карагандинской области от 4 мая 2018 года № 433. Зарегистрировано Департаментом юстиции Карагандинской области 5 мая 2018 года № 4750. Утратило силу решением Осакаровского районного маслихата Карагандинской области от 10 июня 2022 года № 244 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Осакаровского районного маслихата»
  kaz: «Осакаров аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2018-05-04
approved_by:
- '160018000002'
version_date:
  kaz: 2018-05-04
  rus: 2018-05-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/121576/kaz/04.05.2018
  rus: https://zan.gov.kz/client/#!/doc/121576/rus/04.05.2018
