act_code: '88835'
requisite: Решение акима Шетского района Карагандинской области от 25 марта 2015 года № 02. Зарегистрировано Департаментом юстиции Карагандинской области 30 марта 2015 года № 3079. Утратило силу решением акима Шетского района Карагандинской области от 7 июля 2015 года № 05
title:
  rus: Об объявлении чрезвычайной ситуации природного характера
  kaz: Табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-03-25
approved_by:
- '160015000001'
version_date:
  kaz: 2015-04-14
  rus: 2015-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/88835/kaz/14.04.2015
  rus: https://zan.gov.kz/client/#!/doc/88835/rus/14.04.2015
caused_by:
  code: '90214'
  requisite: Решение №03 от 14.04.2015, Акимат Шетского района. Утратило силу решением акима Шетского района Карагандинской области от 7 июля 2015 года N 05
  title:
    rus: О внесении изменений в решение акима Шетского района от 25 марта 2015 года №02 «Об объявлении чрезвычайной ситуации природного характера»
    kaz: Шет ауданы әкімінің 2015 жылғы  25 наурыздағы «Табиғи сипаттағы төтенше жағдайды жариялау туралы» №02  шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/90214/rus
