act_code: '51637'
requisite: Қарағанды облысы Ақтоғай ауданы Қусақ селолық округі әкімінің 2010 жылғы 25 ақпандағы № 1 шешімі. Қарағанды облысы Ақтоғай ауданының Әділет басқармасында 2010 жылғы 7 сәуірде № 8-10-110 тіркелді
title:
  rus: Қусақ селолық округі көлеміндегі құрамдас бөлігінің елді-мекендердегі көшеге ат беру туралы
  kaz: Қусақ селолық округі көлеміндегі құрамдас бөлігінің елді-мекендердегі көшеге ат беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-25
approved_by:
- '160014007001'
version_date:
  kaz: 2010-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/51637/kaz/25.02.2010
