act_code: '123551'
requisite: Решение внеочередной XXII сессии VI созыва Шахтинского городского маслихата Карагандинской области от 29 июня 2018 года № 1520/22. Зарегистрировано Департаментом юстиции Карагандинской области 12 июля 2018 года № 4869. Утратило силу решением Шахтинского городского маслихата Карагандинской области от 19 июня 2020 года № 1724/39 (вводится в действие со дня официального опубликования)
title:
  rus: Об установлении единых ставок фиксированного налога на единицу объекта налогообложения
  kaz: Салық салу нысаны бірлігіне тіркелген салықтың бірыңғай мөлшерлемелерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-29
approved_by:
- '160004000002'
version_date:
  kaz: 2018-06-29
  rus: 2018-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/123551/kaz/29.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123551/rus/29.06.2018
