act_code: '128001'
requisite: Решение Жезказганского городского маслихата Карагандинской области от 26 декабря 2018 года № 31/284. Зарегистрировано Департаментом юстиции Карагандинской области 29 декабря 2018 года № 5118
title:
  rus: О бюджете Кенгирского сельского округа на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Кеңгір ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-26
approved_by:
- '160006000002'
version_date:
  kaz: 2018-12-26
  rus: 2018-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/128001/kaz/26.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128001/rus/26.12.2018
