act_code: '91869'
requisite: Решение Темиртауского городского маслихата Карагандинской области от 9 июня 2015 года № 39/6. Зарегистрировано Департаментом юстиции Карагандинской области 13 июля 2015 года № 3327. Утратило силу решением Темиртауского городского маслихата Карагандинской области от 16 февраля 2016 года № 52/4
title:
  rus: Об утверждении методики ежегодной оценки деятельности административных государственных служащих корпуса "Б" государственного учреждения «Аппарат маслихата города Темиртау»
  kaz: «Теміртау қаласы мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-06-09
approved_by:
- '160005000002'
version_date:
  kaz: 2015-06-09
  rus: 2015-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/91869/kaz/09.06.2015
  rus: https://zan.gov.kz/client/#!/doc/91869/rus/09.06.2015
