act_code: '41822'
requisite: Решение XI сессии Карагандинского областного маслихата от 4 октября 2008 года № 161. Зарегистрировано Департаментом юстиции Карагандинской области 10 октября 2008 года № 1854. Утратило силу решением Карагандинского областного маслихата от 29 сентября 2016 года № 92
title:
  rus: О дополнительном предоставлении лекарственного средства отдельным категориям граждан при амбулаторном лечении бесплатно
  kaz: Азаматтардың жекелеген санаттарына амбулаториялық емдеу кезінде тегін дәрілік затты қосымша беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-10-04
approved_by:
- '160000000002'
version_date:
  kaz: 2008-10-04
  rus: 2008-10-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/41822/kaz/04.10.2008
  rus: https://zan.gov.kz/client/#!/doc/41822/rus/04.10.2008
