act_code: '43529'
requisite: Решение 10 сессии Саранского городского маслихата Карагандинской области от 19 декабря 2008 года № 198. Зарегистрировано Управлением юстиции города Сарань Карагандинской области 19 января 2009 года № 8-7-76. Утратило силу - решением 21 сессии Саранского городского маслихата Карагандинской области от 22 декабря 2009 года № 371
title:
  rus: Об установлении стоимости разовых талонов и размера единых ставок фиксированного суммарного налога на отдельные виды деятельности на 2009 год
  kaz: 2009 жылға жекеленген қызмет түрлеріне белгіленген жиынтық салық бағаларының мөлшерін және бір жолғы талондар құнын тағайындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '160003000002'
version_date:
  kaz: 2009-02-26
  rus: 2009-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/43529/kaz/26.02.2009
  rus: https://zan.gov.kz/client/#!/doc/43529/rus/26.02.2009
caused_by:
  code: '45242'
  requisite: Решение 13 сессии Саранского городского маслихата Карагандинской области от 26 февраля 2009 года № 227. Зарегистрировано Управлением юстиции города Сарани Карагандинской области 8 апреля 2009 года № 8-7-82. Утратило силу - решением 21 сессии Саранского городского маслихата Карагандинской области от 22 декабря 2009 года № 371
  title:
    rus: О внесении изменений в решение 10 сессии Саранского городского маслихата от 19 декабря 2008 года № 198 "Об установлении стоимости разовых талонов и размера единых ставок фиксированного суммарного налога на отдельные виды деятельности на 2009 год"
    kaz: Саран қалалық мәслихатының 2008 жылғы 19 желтоқсандағы 10 сессиясының "2009 жылға жекеленген қызмет түрлеріне белгіленген жиынтық салық бағаларының мөлшерін және бір жолғы талондар құнын тағайындау туралы" № 198 шешіміне  өзгертулер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/45242/rus
