act_code: '187737'
requisite: Решение Осакаровского районного маслихата Карагандинской области от 31 октября 2023 года № 12/111
title:
  rus: Об утверждении Порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей Николаевского сельского округа Осакаровского района Карагандинской области для участия в сходе местного сообщества
  kaz: Қарағанды облысы Осакаров ауданы Николаев ауылдық округінің жергілікті қоғамдастық жиынына қатысу үшін жергілікті қоғамдастықтың бөлек жиындарын өткізу тәртібі және тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2023-10-31
approved_by:
- '160018000002'
version_date:
  kaz: 2025-07-09
  rus: 2025-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/187737/kaz/09.07.2025
  rus: https://zan.gov.kz/client/#!/doc/187737/rus/09.07.2025
caused_by:
  code: '212159'
  requisite: Решение Осакаровского районного маслихата Карагандинской области от 9 июля 2025 года № 36/363
  title:
    rus: О внесении изменения в решение Осакаровского районного маслихата от 31 октября 2023 года № 12/111 «Об утверждении Порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей Николаевского сельского округа Осакаровского района Карагандинской области для участия в сходе местного сообщества»
    kaz: Осакаров аудандық мәслихатының 2023 жылғы 31 қазандағы «Қарағанды облысы Осакаров ауданы Николаев ауылдық округінің жергілікті қоғамдастық жиынына қатысу үшін жергілікті қоғамдастықтың бөлек жиындарын өткізу тәртібі және тұрғындары өкілдерінің сандық құрамын бекіту туралы» № 12/111 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212159/rus
