act_code: '49870'
requisite: Қарағанды облысы Жаңаарқа ауданы әкімінің 2009 жылғы 30 желтоқсандағы № 1 шешімі. Қарағанды облысы Жаңаарқа ауданының Әділет басқармасында 2010 жылғы 11 қаңтарда № 8-12-65 тіркелді. Күші жойылды - Қарағанды облысы Жаңаарқа ауданы әкімінің 2010 жылғы 6 желтоқсандағы № 1 шешімімен
title:
  rus: Жаңаарқа ауданы аумағында тұратын 1993 жылы туған азаматтарды 2010 жылғы әскерге шақыру учаскесіне тіркеу шараларын ұйымдастыру туралы
  kaz: Жаңаарқа ауданы аумағында тұратын 1993 жылы туған азаматтарды 2010 жылғы әскерге шақыру учаскесіне тіркеу шараларын ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-30
approved_by:
- '160016000001'
version_date:
  kaz: 2009-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/49870/kaz/30.12.2009
