act_code: '100583'
requisite: Решение маслихата Актогайского района Павлодарской области от 3 марта 2016 года № 249/57. Зарегистрировано Департаментом юстиции Павлодарской области 28 марта 2016 года № 5024. Утратило силу решением маслихата Актогайского района Павлодарской области от 12 января 2018 года № 153/27 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об определении для заказчиков единого организатора государственных закупок и определении бюджетных программ и товаров, работ, услуг, по которым  организация и проведение государственных закупок выполняется единым организатором
  kaz: Тапсырыс берушілер үшін мемлекеттік сатып алуды бірыңғай ұйымдастырушысын анықтау мен мемлекеттік сатып алуларды ұйымдастыру мен өткізуді бірыңғай ұйымдастырушы орындалатын бюджеттік бағдарламаларды және тауарларды, жұмыстарды, қызметтерді айқындау туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2016-03-03
approved_by:
- '160014000002'
version_date:
  kaz: 2016-03-03
  rus: 2016-03-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/100583/kaz/03.03.2016
  rus: https://zan.gov.kz/client/#!/doc/100583/rus/03.03.2016
