act_code: '202606'
requisite: Решение акима поселка Габидена Мустафина Бухар-Жырауского района Карагандинской области от 8 ноября 2024 года № 7
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-08
approved_by:
- '160017001001'
version_date:
  kaz: 2024-11-08
  rus: 2024-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/202606/kaz/08.11.2024
  rus: https://zan.gov.kz/client/#!/doc/202606/rus/08.11.2024
