act_code: '18554'
requisite: Решение V сессии Абайского районного Маслихата Карагандинской области от 8 января 2004 года № 5/37. Зарегистрировано Департаментом юстиции Карагандинской области 2 февраля 2004 года за № 1406. Утратило силу решением Абайского районного маслихата Карагандинской области от 12 июня 2014 года № 30/325
title:
  rus: Об утверждении Регламента Абайского районного Маслихата
  kaz: Абай аудандық Мәслихатының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2004-01-08
approved_by:
- '160011000002'
version_date:
  kaz: 2004-05-23
  rus: 2004-05-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/18554/kaz/23.05.2004
  rus: https://zan.gov.kz/client/#!/doc/18554/rus/23.05.2004
caused_by:
  code: '20091'
  requisite: Решение VIII сессии Абайского районного Маслихата Карагандинской области от 24 мая 2004 года № 8/77. Зарегистрировано Департаментом юстиции Карагандинской области 3 июня 2004 года за № 1532. Утратило силу решением Абайского районного маслихата Карагандинской области от 12 июня 2014 года № 30/325
  title:
    rus: О внесении дополнений в Регламент районного Маслихата, утвержденный решением V сессии районного Маслихата № 5/37 от 8 января 2004 года, регистрационный номер в Реестре нормативных правовых актов - 1406
    kaz: Аудандық Мәслихаттың 2004 жылғы 8 қаңтардағы V кезекті сессиясының № 5/37 шешімімен бекітілген аудандық Мәслихаттың Регламентіне, нормативтік құқықтық актілер Реестріндегі тіркелу нөмірі - 1406, қосымшалар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/20091/rus
