act_code: '208972'
requisite: Решение Осакаровского районного маслихата Карагандинской области от 4 апреля 2025 года № 32/321. Зарегистрировано Департаментом юстиции Карагандинской области 8 апреля 2025 года № 6748-09
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2025 год по Осакаровскому району
  kaz: Осакаров ауданы бойынша 2025 жылға арналған шетелдіктер үшін туристік жарнаның мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-04-04
approved_by:
- '160018000002'
version_date:
  kaz: 2025-04-04
  rus: 2025-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/208972/kaz/04.04.2025
  rus: https://zan.gov.kz/client/#!/doc/208972/rus/04.04.2025
