act_code: '57888'
requisite: Решение 34 сессии Нуринского районного маслихата Карагандинской области от 11 марта 2011 года № 327. Зарегистрировано Управлением юстиции Нуринского района Карагандинской области 28 марта 2011 года № 8-14-142. Утратило силу - решением 2 сессии Нуринского районного маслихата Карагандинской области от 16 февраля 2012 года № 20
title:
  rus: О предоставлении мер социальной поддержки в виде подъемного пособия и кредита для покупки жилья специалистам здравоохранения, образования, социального обеспечения, культуры и спорта, прибывшим для работы и проживания в сельские населенные пункты Нуринского района в 2011 году
  kaz: 2011 жылғы Нұра ауданының ауылдық елді мекендерге жұмыс істеуге және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына әлеуметтік қолдау көтерме жәрдемақы және тұрғын үй сатып алу үшін кредит ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-03-11
approved_by:
- '160012000002'
version_date:
  kaz: 2011-09-21
  rus: 2011-09-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/57888/kaz/21.09.2011
  rus: https://zan.gov.kz/client/#!/doc/57888/rus/21.09.2011
caused_by:
  code: '60851'
  requisite: Решение 38 сессии Нуринского районного маслихата Карагандинской области от 21 сентября 2011 года № 369. Зарегистрировано Управлением юстиции Нуринского района Карагандинской области 17 октября 2011 года № 8-14-150. Утратило силу - решением 2 сессии Нуринского районного маслихата Карагандинской области от 16 февраля 2012 года № 20
  title:
    rus: О внесении изменения в решение 34 сессии Нуринского районного маслихата от 11 марта 2011 года № 327 "О предоставлении мер социальной поддержки в виде подъемного пособия и кредита для покупки жилья специалистам  здравоохранения, образования, социального обеспечения, культуры и спорта, прибывшим для работы и проживания в сельские населенные пункты Нуринского района в 2011 году"
    kaz: Нұра аудандық мәслихатының 2011 жылғы 11 наурыздағы 34 cессиясының "2011 жылғы Нұра ауданының ауылдық елді мекендерге жұмыс істеуге және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына әлеуметтік қолдау көтерме жәрдемақы және тұрғын үй сатып алу үшін кредит ұсыну туралы" № 327 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/60851/rus
