act_code: '149419'
requisite: Решение Актогайского районного маслихата Карагандинской области от 30 ноября 2020 года № 453. Зарегистрировано Департаментом юстиции Карагандинской области 7 декабря 2020 года № 6117
title:
  rus: О специализированных местах для организации и проведения мирных собраний и границах, прилегающих территорий, в которых запрещено проведение пикетирования на территории Актогайского района
  kaz: Ақтоғай ауданының аумағында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындар және пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекаралары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-11-30
approved_by:
- '160014000002'
version_date:
  kaz: 2020-11-30
  rus: 2020-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/149419/kaz/30.11.2020
  rus: https://zan.gov.kz/client/#!/doc/149419/rus/30.11.2020
