act_code: '151422'
requisite: Решение Каркаралинского районного маслихата Карагандинской области от 30 декабря 2020 года № VI-65/545. Зарегистрировано Департаментом юстиции Карагандинской области 8 января 2021 года № 6144
title:
  rus: О бюджетах города районного значения, поселка, сельских округов на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған аудандық маңызы бар қала, кент, ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-30
approved_by:
- '160013000002'
version_date:
  kaz: 2021-03-26
  rus: 2021-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/151422/kaz/26.03.2021
  rus: https://zan.gov.kz/client/#!/doc/151422/rus/26.03.2021
caused_by:
  code: '154504'
  requisite: Решение Каркаралинского районного маслихата Карагандинской области от 26 марта 2021 года № VII-4/32. Зарегистрировано Департаментом юстиции Карагандинской области 9 апреля 2021 года № 6287
  title:
    rus: О внесении изменений в решение LXV сессии Каркаралинского районного маслихата от 30 декабря 2020 года № VI-65/545 «О бюджетах города районного значения, поселка, сельских округов на 2021-2023 годы»
    kaz: Қарқаралы аудандық мәслихатының 2020 жылғы 30 желтоқсандағы LXV сессиясының № VI-65/545 «2021-2023 жылдарға арналған аудандық маңызы бар қала, кент, ауылдық округтердің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/154504/rus
