act_code: '134216'
requisite: Решение Саранского городского маслихата Карагандинской области от 15 августа 2019 года № 435. Зарегистрировано Департаментом юстиции Карагандинской области 22 августа 2019 года № 5438. Утратило силу решением Саранского городского маслихата Карагандинской области от 28 апреля 2022 года № 121 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О повышении базовых ставок земельного налога на не используемые земли сельскохозяйственного назначения по городу Сарани
  kaz: Саран қаласы бойынша пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-08-15
approved_by:
- '160003000002'
version_date:
  kaz: 2019-08-15
  rus: 2019-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/134216/kaz/15.08.2019
  rus: https://zan.gov.kz/client/#!/doc/134216/rus/15.08.2019
