act_code: '32947'
requisite: Решение Приозерского городского маслихата Карагандинской области от 3 апреля 2007 года № 231/38. Зарегистрировано Управлением юстиции города Балхаша Карагандинской области 24 апреля 2007 года за № 8-4-70. Утратило силу - решением Приозерского городского маслихата Карагандинской области от 13 сентября 2010 года № 201/29
title:
  rus: Об утверждении Правил предоставления малообеспеченным гражданам жилищных пособий на содержание жилья, оплату коммунальных услуг и компенсацию повышения тарифов абонентской платы за телефон абонентам городских сетей телекоммуникаций
  kaz: Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақыларын беру және қалалық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы беру Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-04-03
approved_by:
- '160009000002'
version_date:
  kaz: 2007-07-12
  rus: 2007-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/32947/kaz/12.07.2007
  rus: https://zan.gov.kz/client/#!/doc/32947/rus/12.07.2007
caused_by:
  code: '34809'
  requisite: Решение Приозерского городского маслихата Карагандинской области от 12 июля 2007 года № 273/42. Зарегистрировано Управлением юстиции города Балхаша Карагандинской области 20 августа 2007 года № 8-4-87. Утратило силу - решением Приозерского городского маслихата Карагандинской области от 13 сентября 2010 года № 201/29
  title:
    rus: О внесении изменений и дополнений в решение городского Маслихата от 3 апреля 2007 года № 231/38 "Об утверждении Правил предоставления малообеспеченным гражданам жилищных пособий на содержание жилья, оплату коммунальных услуг и компенсацию повышения тарифов абонентской платы за телефон абонентам городских сетей телекоммуникаций"
    kaz: Қалалық Мәслихаттың 2007 жылғы 3 сәуірдегі № 231/38 "Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақыларын беру және қалалық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы беру Қағидаларын бекіту туралы" шешіміне өзгертулер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/34809/rus
