act_code: '30795'
requisite: Қарағанды облысы Қарқаралы аудандық мәслихатының 2006 жылғы 21 желтоқсандағы № 29/164 шешімі. Қарқаралы ауданы Әділет басқармасында 2006 жылғы 22 желтоқсанда № 8-13-23 тіркелді
title:
  rus: 2007 жылға арналған аудандық бюджет туралы
  kaz: 2007 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-21
approved_by:
- '160013000002'
version_date:
  kaz: 2006-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/30795/kaz/21.12.2006
