act_code: '29008'
requisite: Қарағанды облысы Бұқар Жырау аудандық мәслихатының 29 сессиясының 2006 жылғы 27 маусымдағы № 4 шешімі. Бұқар Жырау ауданы Әділет басқармасында 2006 жылғы 25 шілдеде № 8-11-23 тіркелді. Күші жойылды - Қарағанды облысы Бұқар Жырау аудандық мәслихатының 32 сессиясының 2010 жылғы 28 қыркүйектегі № 7 шешімімен
title:
  rus: '"Аз қамтылған азаматтарға тұрғын үйді ұстауға, кондоминиум объектісінің ортақ мүлкін күрделі жөндеуді қоса, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақыларын беру және селолық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы беру Қағидасын" бекіту туралы'
  kaz: '"Аз қамтылған азаматтарға тұрғын үйді ұстауға, кондоминиум объектісінің ортақ мүлкін күрделі жөндеуді қоса, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақыларын беру және селолық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы беру Қағидасын" бекіту туралы'
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2006-06-27
approved_by:
- '160017000002'
version_date:
  kaz: 2009-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/29008/kaz/21.07.2009
caused_by:
  code: '47399'
  requisite: Решение 17 сессии Бухар-Жырауского районного маслихата Карагандинской области от 21 июля 2009 года № 5. Зарегистрировано Управлением юстиции Бухар-Жырауского района Карагандинской области 17 августа 2009 года № 8-11-80. Утратило силу - решением 32 сессии Бухар-Жырауского районного маслихата Карагандинской области от 28 сентября 2010 года № 7
  title:
    rus: О внесении изменений и дополнений в решение 29 сессии Бухар-Жырауского районного Маслихата от 27 июня 2006 года № 4 "Об утверждении Правил предоставления малообеспеченным гражданам жилищных пособий на содержание жилья, включая на капитальный ремонт общего имущества объекта кондоминиума, оплату коммунальных услуг и компенсацию повышения тарифов абонентской платы за телефон абонентам сельских сетей телекоммуникаций"
    kaz: Бұқар жырау аудандық мәслихатының 2006 жылғы 27 маусымдағы 29 сессиясының "Аз қамтылған азаматтарға тұрғын үйді ұстауға, кондоминиум объектісінің ортақ мүлкін күрделі жөндеуді қоса, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақыларын беру және селолық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы беру Қағидасын бекіту туралы" № 4 шешіміне өзгертулер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/47399/rus
