act_code: '29008'
requisite: Қарағанды облысы Бұқар Жырау аудандық мәслихатының 29 сессиясының 2006 жылғы 27 маусымдағы № 4 шешімі. Бұқар Жырау ауданы Әділет басқармасында 2006 жылғы 25 шілдеде № 8-11-23 тіркелді. Күші жойылды - Қарағанды облысы Бұқар Жырау аудандық мәслихатының 32 сессиясының 2010 жылғы 28 қыркүйектегі № 7 шешімімен
title:
  rus: '"Аз қамтылған азаматтарға тұрғын үйді ұстауға, кондоминиум объектісінің ортақ мүлкін күрделі жөндеуді қоса, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақыларын беру және селолық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы беру Қағидасын" бекіту туралы'
  kaz: '"Аз қамтылған азаматтарға тұрғын үйді ұстауға, кондоминиум объектісінің ортақ мүлкін күрделі жөндеуді қоса, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақыларын беру және селолық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы беру Қағидасын" бекіту туралы'
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2006-06-27
approved_by:
- '160017000002'
version_date:
  kaz: 2006-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/29008/kaz/27.06.2006
