act_code: '225397'
requisite: Решение Каркаралинского районного маслихата Карагандинской области от 20 мая 2026 года № VIII-53/409
title:
  rus: Об утверждении минимального размера расходов на управление объектом кондоминиума и содержание общего имущества объекта кондоминиума по Каркаралинскому району на 2026 год
  kaz: 2026 жылға Қарқаралы ауданы бойынша кондоминиум объектісін басқаруға және кондоминиум объектісінің ортақ мүлкін күтіп-ұстауға арналған шығыстардың ең төмен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-05-20
approved_by:
- '160013000002'
version_date:
  kaz: 2026-05-20
  rus: 2026-05-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/225397/kaz/20.05.2026
  rus: https://zan.gov.kz/client/#!/doc/225397/rus/20.05.2026
