act_code: '127996'
requisite: Решение Жезказганского городского маслихата Карагандинской области от 24 декабря 2018 года № 30/274. Зарегистрировано Департаментом юстиции Карагандинской области 25 декабря 2018 года № 5090
title:
  rus: О бюджете города Жезказган на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Жезқазған қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-24
approved_by:
- '160006000002'
version_date:
  kaz: 2019-11-29
  rus: 2019-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/127996/kaz/29.11.2019
  rus: https://zan.gov.kz/client/#!/doc/127996/rus/29.11.2019
caused_by:
  code: '136844'
  requisite: Решение Жезказганского городского маслихата Карагандинской области от 29 ноября 2019 года № 39/341. Зарегистрировано Департаментом юстиции Карагандинской области 10 декабря 2019 года № 5578
  title:
    rus: О внесении изменений в решение XХХ сессии Жезказганского городского маслихата от 24 декабря 2018 года № 30/274 «О бюджете города Жезказган на 2019-2021 годы»
    kaz: Жезқазған қалалық мәслихатының 2018 жылғы 24 желтоқсандағы XХХ сессиясының № 30/274 «2019-2021 жылдарға арналған Жезқазған қаласының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136844/rus
