act_code: '222146'
requisite: Решение Темиртауского городского маслихата Карагандинской области от 13 февраля 2026 года № 40/4
title:
  rus: О ставках налога на земли, выделенные под автостоянки (паркинги)
  kaz: Автотұрақтар (паркингтер) үшін бөлінген жерлерге салық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-02-13
approved_by:
- '160005000002'
version_date:
  kaz: 2026-02-13
  rus: 2026-02-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/222146/kaz/13.02.2026
  rus: https://zan.gov.kz/client/#!/doc/222146/rus/13.02.2026
