act_code: '207329'
requisite: Решение акима Шетского района Карагандинской области от 21 февраля 2025 года № 01
title:
  rus: Об объявлении чрезвычайной ситуации техногенного характера
  kaz: Техногендік сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-02-21
approved_by:
- '160015000003'
version_date:
  kaz: 2025-02-21
  rus: 2025-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/207329/kaz/21.02.2025
  rus: https://zan.gov.kz/client/#!/doc/207329/rus/21.02.2025
