act_code: '63259'
requisite: Решение I сессии V созыва Карагандинского городского маслихата от 24 января 2012 года № 15. Зарегистрировано Управлением юстиции города Караганды 8 февраля 2012 года № 8-1-151
title:
  rus: О льготном проезде на внутригородском общественном транспорте (кроме такси) обучающихся очной формы обучения на январь и февраль месяцы 2012 года
  kaz: Күндізгі оқу нысанында оқитын білім алушылардың қала ішіндегі қоғамдық көлікте (таксиден басқа) 2012 жылғы қаңтар және ақпан айларында жеңілдікпен жол жүруі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-01-24
approved_by:
- '160002000002'
version_date:
  kaz: 2012-01-24
  rus: 2012-01-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/63259/kaz/24.01.2012
  rus: https://zan.gov.kz/client/#!/doc/63259/rus/24.01.2012
