act_code: '49562'
requisite: Қарағанды облысы Ақтоғай аудандық мәслихатының 17 сессиясының 2009 жылғы 24 қарашадағы № 183 шешімі. Қарағанды облысы Ақтоғай ауданының Әділет басқармасында 2009 жылғы 28 желтоқсанда № 8-10-92 тіркелді. Күші жойылды - Қарағанды облысы Ақтоғай аудандық мәслихатының 32 сессиясының 2011 жылғы 9 маусымдағы № 309 шешімімен
title:
  rus: Кәсіпкерлік қызметтің түрлеріне бір жолғы талон құнының бағасын белгілеу туралы
  kaz: Кәсіпкерлік қызметтің түрлеріне бір жолғы талон құнының бағасын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-24
approved_by:
- '160014000002'
version_date:
  kaz: 2009-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/49562/kaz/24.11.2009
