act_code: '56286'
requisite: Решение XХXIV сессии Каражалского городского маслихата Карагандинской области от 23 декабря 2010 года № 300. Зарегистрировано Управлением юстиции города Каражал Карагандинской области 29 декабря 2010 года № 8-5-105
title:
  rus: О бюджете города на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған қала бюджетi туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '160010000002'
version_date:
  kaz: 2011-11-14
  rus: 2011-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/56286/kaz/14.11.2011
  rus: https://zan.gov.kz/client/#!/doc/56286/rus/14.11.2011
caused_by:
  code: '61623'
  requisite: Решение ХХXХIV сессии Каражалского городского маслихата Карагандинской области от 14 ноября 2011 года № 396. Зарегистрировано Управлением юстиции города Каражал Карагандинской области 24 ноября 2011 года № 8-5-116
  title:
    rus: О внесении изменений в решение ХХХIV сессии Каражалского городского маслихата от 23 декабря 2010 года № 300 "О бюджете города на 2011-2013 годы"
    kaz: Қаражал қалалық мәслихатының 2010 жылғы 23 желтоқсандағы ХХХIV сессиясының № 300 "2011-2013 жылдарға арналған қала бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/61623/rus
