act_code: '12275'
requisite: Решение акима Карагандинской области от 24 апреля 2002 года №  74. Зарегистрировано Управлением юстиции Карагандинской области 20 мая 2002 года за № 818. Утратило силу в связи с истечением срока письмом руководителя аппарата акима Карагандинской области от 21 января 2005 года № 05-11/89
title:
  rus: Об утверждении Правил использования средств, предусмотренных в бюджете на 2002 год на представительские расходы и норм представительских расходов
  kaz: 2002 жылға арналған облыстық бюджетте өкілеттік шығындар мен өкілеттік шығындар нормаларына қарастырылған қаражаттарды пайдалану Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-04-23
approved_by:
- '160000000001'
version_date:
  kaz: 2002-04-23
  rus: 2002-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/12275/kaz/23.04.2002
  rus: https://zan.gov.kz/client/#!/doc/12275/rus/23.04.2002
