act_code: '80322'
requisite: Решение ХXIX сессии Каражалского городского маслихата Карагандинской области от 18 апреля 2014 года № 234. Зарегистрировано Департаментом юстиции Карагандинской области 26 мая 2014 года № 2652. Утратило силу решением Каражалского городского маслихата от 17 августа 2018 года № 228 (вводится в действие с 1 января 2019 года)
title:
  rus: Об утверждении проектов (схем) зонирования земель города Каражал, поселков Шалгинск и Жайрем для целей налогооблажения
  kaz: Салық салу мақсаттары үшін Қаражал қаласының, Шалғы және Жәйрем кенттерінің жерлерін өңірлерге бөлу жобаларын (схемаларын) бекіту туралы
form: РЕШ
type_codes:
- ПРОЕ
- РЕШ
- СХЕМ
approved_on: 2014-04-18
approved_by:
- '160010000002'
version_date:
  kaz: 2014-11-26
  rus: 2014-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/80322/kaz/26.11.2014
  rus: https://zan.gov.kz/client/#!/doc/80322/rus/26.11.2014
caused_by:
  code: '86092'
  requisite: Решение XXXV сессии Каражалского городского маслихата Карагандинской области от 26 ноября 2014 года № 281. Зарегистрировано Департаментом юстиции Карагандинской области 6 января 2015 года № 2905. Утратило силу решением Каражалского городского маслихата от 17 августа 2018 года № 228 (вводится в действие с 1 января 2019 года)
  title:
    rus: О внесении изменении в решение ХХIХ сессии Каражалского городского маслихата от 18 апреля 2014 года № 234 «Об утверждении проектов (схем) зонирования земель города Каражал, поселков Шалгинск и Жайрем для целей налогооблажения»
    kaz: Қаражал қалалық мәслихатының 2014 жылғы 18 сәуірдегі ХХІХ сессиясының № 234 «Салық салу мақсаттары үшін Қаражал қаласының, Шалғы және Жәйрем кенттерінің жерлерін өңірлерге бөлу жобаларын (схемаларын) бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86092/rus
