act_code: '55570'
requisite: Қарағанды облысы Жаңаарқа ауданы мәслихатының XXIX сессиясының 2010 жылғы 8 қарашадағы № 29/246 шешімі. Қарағанды облысы Жаңаарқа ауданының Әділет басқармасында 2010 жылғы 23 қарашада № 8-12-96 тіркелді. Күші жойылды - Қарағанды облысы Жаңаарқа ауданы мәслихатының 35 сессиясының 2011 жылғы 28 маусымдағы № 35/308 шешімімен
title:
  rus: Жаңаарқа ауданының елді мекендерін көркейту, абаттандыру Ережесін бекіту туралы
  kaz: Жаңаарқа ауданының елді мекендерін көркейту, абаттандыру Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-11-08
approved_by:
- '160016000002'
version_date:
  kaz: 2010-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/55570/kaz/08.11.2010
