act_code: '138030'
requisite: Решение акима Ынталинского сельского округа Каркаралинского района Карагандинской области от 25 декабря 2019 года № 03. Зарегистрировано Департаментом юстиции Карагандинской области 5 января 2020 года № 5653. Утратило силу решением акима Ынталинского сельского округа Каркаралинского района Карагандинской области от 24 февраля 2020 года № 06 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '160013023002'
version_date:
  kaz: 2019-12-25
  rus: 2019-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/138030/kaz/25.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138030/rus/25.12.2019
