act_code: '62806'
requisite: Решение 41 сессии Актогайского районного маслихата Карагандинской области от 14 декабря 2011 года № 386. Зарегистрировано Управлением юстиции Актогайского района Карагандинской области 17 января 2012 года № 8-10-142. Утратило силу решением 11 сессии Актогайского районного маслихата Карагандинской области от 13 февраля 2013 года № 106
title:
  rus: Об установлении стоимости разовых талонов на рынках Актогайского района и для отдельных видов предпринимательской деятельности, носящих эпизодический характер
  kaz: Ақтоғай ауданы базарларында және дүркін–дүркін сипаттағы кәсіпкерлік қызметінің жекелеген түрлеріне біржолғы талондардың құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-14
approved_by:
- '160014000002'
version_date:
  kaz: 2011-12-14
  rus: 2011-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/62806/kaz/14.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62806/rus/14.12.2011
