act_code: '39822'
requisite: Решение акима села Карой Нуринского района Карагандинской области от 13 мая 2008 года № 1. Зарегистрировано управлением юстиции Нуринского района Карагандинской области 23 мая 2008 года № 8-14-72
title:
  rus: О переименовании улиц села Карой
  kaz: Қарой ауылы көшелерінің атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-05-13
approved_by:
- '160012011001'
version_date:
  kaz: 2008-05-13
  rus: 2008-05-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/39822/kaz/13.05.2008
  rus: https://zan.gov.kz/client/#!/doc/39822/rus/13.05.2008
