act_code: '83543'
requisite: Решение ХХII сессии Улытауского районного маслихата Карагандинской области от 11 сентября 2014 года № 187. Зарегистрировано Департаментом юстиции Карагандинской области 7 октября 2014 года № 2793. Утратило силу решением Улытауского районного маслихата области Ұлытау от 27 декабря 2023 года № 82 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О возмещении затрат
  kaz: Шығындарды өтеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-09-11
approved_by:
- '160019000002'
version_date:
  kaz: 2014-09-11
  rus: 2014-09-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/83543/kaz/11.09.2014
  rus: https://zan.gov.kz/client/#!/doc/83543/rus/11.09.2014
