act_code: '43059'
requisite: Решение XVI сессии IV созыва Карагандинского городского маслихата от 24 декабря 2008 года № 172. Зарегистрировано Управлением юстиции города Караганды Карагандинской области 26 декабря 2008 года № 8-1-84. Утратило силу решением Карагандинского городского маслихата от 21 июня 2017 года № 171
title:
  rus: Об оказании социальной помощи на проезд на городском общественном транспорте (кроме такси) отдельным категориям граждан города Караганды
  kaz: Қарағанды қаласы азаматтарының жекелеген санаттарына қалалық қоғамдық көліктерде (таксиден басқа) жүруге әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '160002000002'
version_date:
  kaz: 2009-12-23
  rus: 2009-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/43059/kaz/23.12.2009
  rus: https://zan.gov.kz/client/#!/doc/43059/rus/23.12.2009
caused_by:
  code: '49533'
  requisite: Решение XXVIII сессии IV созыва Карагандинского городского маслихата от 23 декабря 2009 года № 300. Зарегистрировано Управлением юстиции города Караганды 29 декабря 2009 года № 8-1-108. Утратило силу решением Карагандинского городского маслихата от 21 июня 2017 года № 171
  title:
    rus: О внесении изменения в решение ХVI сессии Карагандинского городского маслихата IV созыва от 24 декабря 2008 года № 172 "Об оказании социальной помощи на проезд на городском общественном транспорте (кроме такси) отдельным категориям граждан города Караганды"
    kaz: IV шақырылған Қарағанды қалалық мәслихатының 2008 жылғы 24 желтоқсандағы ХVІ сессиясының "Қарағанды қаласы азаматтарының жекелеген санаттарына қалалық қоғамдық көліктерде (таксиден басқа) жүруге әлеуметтік көмек көрсету туралы" № 172 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/49533/rus
