act_code: '54572'
requisite: Қарағанды облысы Жаңаарқа ауданы Айнабұлақ селолық округі әкімінің 2010 жылғы 9 қыркүйектегі № 1 шешімі. Қарағанды облысы Жаңаарқа ауданының Әділет басқармасында 2010 жылғы 22 қыркүйекте № 8-12-92 тіркелді
title:
  rus: Айнабұлақ селолық округінің Айнабұлақ ауылының көшелерін ретке келтіру және оларға атау беру туралы
  kaz: Айнабұлақ селолық округінің Айнабұлақ ауылының көшелерін ретке келтіру және оларға атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-09
approved_by:
- '160016011001'
version_date:
  kaz: 2010-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/54572/kaz/09.09.2010
