act_code: '176590'
requisite: Решение Каркаралинского районного маслихата Карагандинской области от 21 декабря 2022 года № VII-28/211
title:
  rus: О районном бюджете на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-21
approved_by:
- '160013000002'
version_date:
  kaz: 2023-04-13
  rus: 2023-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/176590/kaz/13.04.2023
  rus: https://zan.gov.kz/client/#!/doc/176590/rus/13.04.2023
caused_by:
  code: '179860'
  requisite: Решение Каркаралинского районного маслихата Карагандинской области от 13 апреля 2023 года № VIII-2/16
  title:
    rus: О внесении изменений в решение Каркаралинского районного маслихата от 21 декабря 2022 года № VII-28/211 «О районном бюджете на 2023-2025 годы»
    kaz: Қарқаралы аудандық мәслихатының 2022 жылғы 21 желтоқсандағы № VII-28/211 «2023-2025 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/179860/rus
