act_code: '72456'
requisite: Решение Шетского районного маслихата Карагандинской области от 4 апреля 2013 года № 12/118. Зарегистрировано Департаментом юстиции Карагандинской области 8 мая 2013 года № 2328. Утратило силу решением Шетского районного маслихата Карагандинской области от 27 июня 2018 года № 22/190 (вводится в действие с 1 января 2019 года)
title:
  rus: Об утверждении схемы зонирования земель и процентов повышения (понижения) ставок земельного налога Шетского района
  kaz: Шет ауданының жерлерін аймақтарға бөлу схемасын және жер салығының ставкаларын жоғарылату (төмендету) пайыздарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
- СХЕМ
approved_on: 2013-04-04
approved_by:
- '160015000002'
version_date:
  kaz: 2013-04-04
  rus: 2013-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/72456/kaz/04.04.2013
  rus: https://zan.gov.kz/client/#!/doc/72456/rus/04.04.2013
