act_code: '204816'
requisite: Решение Каркаралинского районного маслихата Карагандинской области от 25 декабря 2024 года № VIII-30/223
title:
  rus: О районном бюджете на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '160013000002'
version_date:
  kaz: 2025-11-28
  rus: 2025-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/204816/kaz/28.11.2025
  rus: https://zan.gov.kz/client/#!/doc/204816/rus/28.11.2025
caused_by:
  code: '217657'
  requisite: Решение Каркаралинского районного маслихата Карагандинской области от 28 ноября 2025 года № VIII-42/325
  title:
    rus: О внесении изменений в решение Каркаралинского районного маслихата от 25 декабря 2024 года № VIII-30/223 «О районном бюджете на 2025-2027 годы»
    kaz: Қарқаралы аудандық мәслихатының 2024 жылғы 25 желтоқсандағы № VIII-30/223 «2025-2027 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/217657/rus
