act_code: '22533'
requisite: Решение X сессии Карагандинского областного Маслихата от 11 декабря 2004 года № 149. Зарегистрировано Департаментом юстиции Карагандинской области 7 января 2005 года за № 1678
title:
  rus: Об областном бюджете на 2005 год
  kaz: 2005 жылға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-12-11
approved_by:
- '160000000002'
version_date:
  kaz: 2005-11-11
  rus: 2005-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/22533/kaz/11.11.2005
  rus: https://zan.gov.kz/client/#!/doc/22533/rus/11.11.2005
caused_by:
  code: '25939'
  requisite: Решение XVI сессии Карагандинского областного Маслихата от 11 ноября 2005 года № 224. Зарегистрировано Департаментом юстиции Карагандинской области 22 ноября 2005 года за № 1803
  title:
    rus: О внесении изменений и дополнений в решение X сессии Карагандинского областного Маслихата от 11 декабря 2004 года № 149 "Об областном бюджете на 2005 год"
    kaz: Қарағанды облыстық Мәслихатының 2004 жылғы 11 желтоқсандағы "2005 жылға арналған облыстық бюджет туралы" Х сессиясының № 149 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/25939/rus
