act_code: '79149'
requisite: Решение Сатпаевского городского маслихата Карагандинской области от 31 марта 2014 года № 219. Зарегистрировано Департаментом юстиции Карагандинской области 23 апреля 2014 года № 2603. Утратило силу решением Сатпаевского городского маслихата Карагандинской области от 29 апреля 2016 года № 27
title:
  rus: Об утверждении Регламента Сатпаевского городского маслихата
  kaz: Сәтбаев қалалық мәслихатының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-03-31
approved_by:
- '160007000002'
version_date:
  kaz: 2015-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/79149/kaz/21.05.2015
caused_by:
  code: '91296'
  requisite: Решение Сатпаевского городского маслихата Карагандинской области от 21 мая 2015 года № 346. Зарегистрировано Департаментом юстиции Карагандинской области 25 июня 2015 года № 3300
  title:
    rus: О внесении изменения в решение Сатпаевского городского маслихата от 31 марта 2014 года № 219 «Об утверждении Регламента Сатпаевского городского маслихата»
    kaz: Сәтбаев қалалық мәслихатының 2014 жылғы 31 наурыздағы № 219 «Сәтбаев қалалық мәслихатының Регламентін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/91296/rus
