act_code: '46181'
requisite: Решение Жезказганского городского маслихата Карагандинской области от 14 апреля 2009 года № 13/154. Зарегистрировано Управлением юстиции города Жезказган Карагандинской области 28 мая 2009 года № 8-2-89. Утратило силу - решением Жезказганского городского маслихата Карагандинской области от 7 апреля 2011 года № 30/371
title:
  rus: Об утверждении Правил застройки территории города Жезказгана
  kaz: Жезқазған қаласы аумағында құрылыс салу Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2009-04-14
approved_by:
- '160006000002'
version_date:
  kaz: 2009-04-14
  rus: 2009-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/46181/kaz/14.04.2009
  rus: https://zan.gov.kz/client/#!/doc/46181/rus/14.04.2009
