act_code: '7388'
requisite: Решение Акима Карагандинской области от 10 ноября 2000 года № 205. Зарегистрировано управлением юстиции Карагандинской области 13 ноября 2000 года за № 139. Утратило силу решением акима Карагандинской области от 14 мая 2004 года № 44
title:
  rus: Об утверждении Правил проведения расчетов за товары и услуги государственными учреждениями и хозяйствующими субъектами через ОАО "Межрегиональная клиринговая палата"
  kaz: Шаруашылық субъектілер мен мемлекеттік мекемелердің тауарлар мен қызмет көрсетулер үшін "Аймақаралық клирингтік палаталар" ашық акционерлік қоғамы арқылы есеп айырысуды өткізу Ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2000-11-10
approved_by:
- '160000000001'
version_date:
  kaz: 2000-11-10
  rus: 2000-11-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/7388/kaz/10.11.2000
  rus: https://zan.gov.kz/client/#!/doc/7388/rus/10.11.2000
