act_code: '161676'
requisite: Решение Сатпаевского городского маслихата Карагандинской области от 9 декабря 2021 года № 135
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по городу Сатпаев на 2022 – 2023 годы
  kaz: Сәтбаев қаласы бойынша жайылымдарды басқару және оларды пайдалану жөніндегі 2022 – 2023 жылдарға арналған жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2021-12-09
approved_by:
- '160007000002'
version_date:
  kaz: 2021-12-09
  rus: 2021-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/161676/kaz/09.12.2021
  rus: https://zan.gov.kz/client/#!/doc/161676/rus/09.12.2021
