act_code: '42487'
requisite: Қарағанды облысы Ақтоғай аудандық мәслихатының 9 сессиясының 2008 жылғы 18 қарашадағы № 104 шешімі. Қарағанды облысы Ақтоғай ауданы Әділет басқармасында 2008 жылғы 26 қарашада № 8-10-69 тіркелді
title:
  rus: Бір салық салу объектісінен алынатын тіркелген жиынтық салық ставкаларының мөлшерін белгілеу туралы
  kaz: Бір салық салу объектісінен алынатын тіркелген жиынтық салық ставкаларының мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-11-18
approved_by:
- '160014000002'
version_date:
  kaz: 2008-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/42487/kaz/18.11.2008
