act_code: '56509'
requisite: Решение 34 сессии Бухар-Жырауского районного маслихата Карагандинской области от 23 декабря 2010 года № 5. Зарегистрировано Управлением юстиции Бухар-Жырауского района Карагандинской области 6 января 2011 года № 8-11-110
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '160017000002'
version_date:
  kaz: 2011-12-06
  rus: 2011-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/56509/kaz/06.12.2011
  rus: https://zan.gov.kz/client/#!/doc/56509/rus/06.12.2011
caused_by:
  code: '61931'
  requisite: Решение 48 сессии Бухар-Жырауского районного маслихата Карагандинской области от 6 декабря 2011 года № 4. Зарегистрировано Управлением юстиции Бухар-Жырауского района Карагандинской области 12 декабря 2011 года № 8-11-125
  title:
    rus: О внесении изменений в решение 34 сессии Бухар-Жырауского районного маслихата от 23 декабря 2010 года № 5 "О районном бюджете на 2011-2013 годы"
    kaz: Бұқар жырау аудандық мәслихатының 2010 жылғы 23 желтоқсандағы 34 сессиясының "2011-2013 жылдарға арналған аудандық бюджет туралы" № 5 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/61931/rus
