act_code: '145148'
requisite: Решение Каркаралинского районного маслихата Карагандинской области от 21 июля 2020 года № VI-58/493. Зарегистрировано Департаментом юстиции Карагандинской области 27 июля 2020 года № 5977
title:
  rus: О специализированных местах для организации и проведения мирных собраний и границах, прилегающих территорий, в которых запрещено проведение пикетирования на территории Каркаралинского района
  kaz: Қарқаралы ауданының аумағында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындар және пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекаралары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-07-21
approved_by:
- '160013000002'
version_date:
  kaz: 2024-02-22
  rus: 2024-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/145148/kaz/22.02.2024
  rus: https://zan.gov.kz/client/#!/doc/145148/rus/22.02.2024
caused_by:
  code: '193723'
  requisite: Решение Каркаралинского районного маслихата Карагандинской области от 22 февраля 2024 года № VIII-18/139. Зарегистрировано в Департаменте юстиции Карагандинской области 27 февраля 2024 года № 6560-09
  title:
    rus: О внесении изменений в решение Каркаралинского районного маслихата Карагандинской области от 21 июля 2020 года № VI-58/493 «О специализированных местах для организации и проведения мирных собраний и границах, прилегающих территорий, в которых запрещено проведение пикетирования на территории Каркаралинского района»
    kaz: Қарағанды облысы Қарқаралы аудандық мәслихатының 2020 жылғы 21 шілдедегі № VI-58/493 «Қарқаралы ауданының аумағында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындар және пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекаралары туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/193723/rus
