act_code: '145148'
requisite: Решение Каркаралинского районного маслихата Карагандинской области от 21 июля 2020 года № VI-58/493. Зарегистрировано Департаментом юстиции Карагандинской области 27 июля 2020 года № 5977
title:
  rus: О специализированных местах для организации и проведения мирных собраний и границах, прилегающих территорий, в которых запрещено проведение пикетирования на территории Каркаралинского района
  kaz: Қарқаралы ауданының аумағында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындар және пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекаралары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-07-21
approved_by:
- '160013000002'
version_date:
  kaz: 2020-07-21
  rus: 2020-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/145148/kaz/21.07.2020
  rus: https://zan.gov.kz/client/#!/doc/145148/rus/21.07.2020
