act_code: '162371'
requisite: Решение Осакаровского районного маслихата Карагандинской области от 24 декабря 2021 года № 157
title:
  rus: О бюджете поселков, сельских округов Осакаровского района на 2022-2024 годы
  kaz: Осакаров ауданының кенттерінің, ауылдық округтарының 2022-2024 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '160018000002'
version_date:
  kaz: 2022-09-21
  rus: 2022-09-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/162371/kaz/21.09.2022
  rus: https://zan.gov.kz/client/#!/doc/162371/rus/21.09.2022
caused_by:
  code: '172187'
  requisite: Решение Осакаровского районного маслихата Карагандинской области от 21 сентября 2022 года № 289
  title:
    rus: О внесении изменений в решение 14 сессии Осакаровского районного маслихата от 24 декабря 2021 года № 157 «О бюджете поселков, сельских округов Осакаровского района на 2022-2024 годы»
    kaz: Осакаров аудандық мәслихатының 14 сессиясының 2021 жылғы 24 желтоқсандағы № 157 «Осакаров ауданының кенттерінің, ауылдық округтарының 2022-2024 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172187/rus
