act_code: '97410'
requisite: Решение 54 сессии Осакаровского районного маслихата Карагандинской области от 18 декабря 2015 года № 577. Зарегистрировано Департаментом юстиции Карагандинской области 29 декабря 2015 года № 3586
title:
  rus: О районном бюджете на 2016-2018 годы
  kaz: 2016-2018 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-18
approved_by:
- '160018000002'
version_date:
  kaz: 2016-05-11
  rus: 2016-05-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/97410/kaz/11.05.2016
  rus: https://zan.gov.kz/client/#!/doc/97410/rus/11.05.2016
caused_by:
  code: '102957'
  requisite: Решение 3 сессии Осакаровского районного маслихата Карагандинской области от 11 мая 2016 года № 41. Зарегистрировано Департаментом юстиции Карагандинской области 23 мая 2016 года № 3805
  title:
    rus: О внесении изменений в решение 54 сессии Осакаровского районного маслихата от 18 декабря  2015 года № 577 «О районном бюджете на 2016-2018 годы»
    kaz: Осакаров аудандық мәслихатының 54 сессиясының 2015 жылғы 18 желтоқсандағы № 577 «2016-2018 жылдарға арналған аудандық бюджет туралы»  шешіміне өзгерістер  енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/102957/rus
