act_code: '7804'
requisite: Решение Акима Карагандинской области от 11 декабря 2000 года № 226. Зарегистрировано управлением юстиции Карагандинской области 22 декабря 2000 года за № 161.Утратило силу решением акима Карагандинской области от 14 мая 2004 года № 44
title:
  rus: О плате за загрязнение окружающей среды на 2001 год
  kaz: 2001 жылға арналған қоршаған ортаны ластағаны үшін алынатын төлемдер туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-12-11
approved_by:
- '160000000001'
version_date:
  kaz: 2000-12-11
  rus: 2000-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/7804/kaz/11.12.2000
  rus: https://zan.gov.kz/client/#!/doc/7804/rus/11.12.2000
