act_code: '97002'
requisite: Решение ХL сессии Карагандинского областного маслихата от 11 декабря 2015 года № 452. Зарегистрировано Департаментом юстиции Карагандинской области 28 декабря 2015 года № 3575
title:
  rus: Об областном бюджете на 2016-2018 годы
  kaz: 2016-2018 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-11
approved_by:
- '160000000002'
version_date:
  kaz: 2016-06-30
  rus: 2016-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/97002/kaz/30.06.2016
  rus: https://zan.gov.kz/client/#!/doc/97002/rus/30.06.2016
caused_by:
  code: '104030'
  requisite: Решение III сессии Карагандинского областного маслихата от 30 июня 2016 года № 58. Зарегистрировано Департаментом юстиции Карагандинской области 5 июля 2016 года № 3886
  title:
    rus: О внесении изменений и дополнений в решение XL сессии Карагандинского областного маслихата от 11 декабря 2015 года №452  «Об областном бюджете на 2016-2018 годы»
    kaz: Қарағанды облыстық мәслихатының 2015 жылғы 11 желтоқсандағы ХL сессиясының «2016-2018 жылдарға арналған облыстық бюджет туралы» №452  шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/104030/rus
