act_code: '146700'
requisite: Решение акима села Изенда Нуринского района Карагандинской области от 25 сентября 2020 года № 5. Зарегистрировано Департаментом юстиции Карагандинской области 25 сентября 2020 года № 6043. Утратило силу решением акима села Изенда Нуринского района Карагандинской области от 2 ноября 2020 года № 6 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении карантина на территории села Изенда
  kaz: Изенді ауылының аумағында карантин белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-25
approved_by:
- '160012010002'
version_date:
  kaz: 2020-09-25
  rus: 2020-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/146700/kaz/25.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146700/rus/25.09.2020
