act_code: '43057'
requisite: Решение XVI сессии IV созыва Карагандинского городского маслихата от 24 декабря 2008 года № 169. Зарегистрировано управлением юстиции города Караганды Карагандинской области 26 декабря 2008 года № 8-1-82. Утратило силу решением Карагандинского городского маслихата от 25 апреля 2019 года № 387 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении ставок фиксированного налога на отдельные виды предпринимательской деятельности
  kaz: Кәсіпкерлік қызметінің жекелеген түрлеріне тіркелген салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '160002000002'
version_date:
  kaz: 2008-12-24
  rus: 2008-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/43057/kaz/24.12.2008
  rus: https://zan.gov.kz/client/#!/doc/43057/rus/24.12.2008
