act_code: '49869'
requisite: Қарағанды облысы Жаңаарқа ауданы мәслихатының 2009 жылғы 21 желтоқсандағы № 20/174 шешімі. Қарағанды облысы Жаңаарқа ауданының Әділет басқармасында 2010 жылғы 11 қаңтарда № 8-12-64 тіркелді
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '160016000002'
version_date:
  kaz: 2009-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/49869/kaz/21.12.2009
