act_code: '15195'
requisite: Решение акима Карагандинской области от 10 апреля 2003 года № 20. Зарегистрировано Управлением юстиции Карагандинской области 21 апреля 2003 года за № 1145. Утратило силу решением акима Карагандинской области от 23 мая 2005 года № 03
title:
  rus: О плане мероприятий по обеспечению пожарной безопасности и организации тушения природных пожаров на территории Карагандинской области
  kaz: Қарағанды облысы аймағындағы табиғи өрттердi сөндiрудi ұйымдастыру және өрт қауiпсiздiгiн қамтамасыз ету жөнiндегi шаралар жоспары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-04-09
approved_by:
- '160000000001'
version_date:
  kaz: 2003-04-09
  rus: 2003-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/15195/kaz/09.04.2003
  rus: https://zan.gov.kz/client/#!/doc/15195/rus/09.04.2003
