act_code: '101657'
requisite: Решение XXXXIX сессии Каражалского городского маслихата Карагандинской области от 17 марта 2016 года № 418. Зарегистрировано Департаментом юстиции Карагандинской области 14 апреля 2016 года № 3751. Утратило силу решением Каражалского городского маслихата Карагандинской области от 30 апреля 2020 года № 374 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О повышении ставки единого земельного налога на не используемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения на территории города Каражал
  kaz: Қаражал қаласының аумағында Қазақстан Республикасының жер заңнамасына сәйкес пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-03-17
approved_by:
- '160010000002'
version_date:
  kaz: 2016-03-17
  rus: 2016-03-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/101657/kaz/17.03.2016
  rus: https://zan.gov.kz/client/#!/doc/101657/rus/17.03.2016
