act_code: '227961'
requisite: Решение Абайского районного маслихата Карагандинской области от 21 июля 2026 года № 56/510
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по Абайскому району Карагандинской области
  kaz: Қарағанды облысы Абай ауданы бойынша тұрғын үй сертификаттарының мөлшері мен алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2026-07-21
approved_by:
- '160011000002'
version_date:
  kaz: 2026-07-21
  rus: 2026-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/227961/kaz/21.07.2026
  rus: https://zan.gov.kz/client/#!/doc/227961/rus/21.07.2026
