act_code: '153411'
requisite: Решение Жанааркинского районного маслихата Карагандинской области от 1 марта 2021 года № 3/30. Зарегистрировано Департаментом юстиции Карагандинской области 11 марта 2021 года № 6242. Утратило силу решением Жанааркинского районного маслихата области Ұлытау от 20 февраля 2024 года № 14/91 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Жанааркинского района
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Жаңаарқа ауданының мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2021-03-01
approved_by:
- '160016000002'
version_date:
  kaz: 2021-03-01
  rus: 2021-03-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/153411/kaz/01.03.2021
  rus: https://zan.gov.kz/client/#!/doc/153411/rus/01.03.2021
