act_code: '127725'
requisite: Решение Шетского районного маслихата Карагандинской области от 20 декабря 2018 года № 26/239. Зарегистрировано Департаментом юстиции Карагандинской области 27 декабря 2018 года № 5098. Утратило силу решением Шетского районного маслихата Карагандинской области от 27 декабря 2021 года № 9/108 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламента собрания местного сообщества по Шетскому району
  kaz: Шет ауданы бойынша жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-20
approved_by:
- '160015000002'
version_date:
  kaz: 2018-12-20
  rus: 2018-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/127725/kaz/20.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127725/rus/20.12.2018
