act_code: '127188'
requisite: Решение акима поселка Жайрем Карагандинской области от 21 ноября 2018 года № 5. Зарегистрировано Департаментом юстиции Карагандинской области 12 декабря 2018 года № 5063
title:
  rus: О переименовании улиц в поселке Жайрем
  kaz: Жәйрем кентіндегі көшелерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-21
approved_by:
- '160010001001'
version_date:
  kaz: 2018-11-21
  rus: 2018-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/127188/kaz/21.11.2018
  rus: https://zan.gov.kz/client/#!/doc/127188/rus/21.11.2018
