act_code: '97693'
requisite: Решение Темиртауского городского маслихата Карагандинской области от 24 декабря 2015 года № 50/4. Зарегистрировано Департаментом юстиции Карагандинской области 8 января 2016 года № 3603
title:
  rus: О городском бюджете на 2016-2018 годы
  kaz: 2016-2018 жылға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-24
approved_by:
- '160005000002'
version_date:
  kaz: 2016-05-05
  rus: 2016-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/97693/kaz/05.05.2016
  rus: https://zan.gov.kz/client/#!/doc/97693/rus/05.05.2016
caused_by:
  code: '102637'
  requisite: Решение Темиртауского городского маслихата Карагандинской области от 5 мая 2016 года № 3/5. Зарегистрировано Департаментом юстиции Карагандинской области 19 мая 2016 года № 3798
  title:
    rus: О внесении изменений и дополнения в решение 50 сессии Темиртауского городского маслихата от 24 декабря 2015 года № 50/4 «О городском бюджете на 2016-2018 годы»
    kaz: Теміртау қалалық мәслихатының 2015 жылғы 24 желтоқсандағы 50 сессиясының № 50/4 «2016-2018 жылға арналған қалалық бюджет туралы» шешіміне өзгерістер және толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/102637/rus
