act_code: '56085'
requisite: Решение акима Осакаровского района Карагандинской области от 18 ноября 2010 года № 01. Зарегистрировано Управлением юстиции Осакаровского района Карагандинской области 21 декабря 2010 года № 8-15-132
title:
  rus: О проведении приписки граждан 1994 года рождения к призывному участку отдела по делам обороны Осакаровского района
  kaz: Осакаров ауданының қорғаныс істері жөніндегі бөлімнің шақыру учаскесінде 1994 жылы туған азаматтарға тіркеу өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-18
approved_by:
- '160018000001'
version_date:
  kaz: 2010-11-18
  rus: 2010-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/56085/kaz/18.11.2010
  rus: https://zan.gov.kz/client/#!/doc/56085/rus/18.11.2010
