act_code: '49462'
requisite: Решение 19 сессии Каркаралинского районного маслихата Карагандинской области от 22 декабря 2009 года № 19/192. Зарегистрировано управлением юстиции Каркаралинского района Карагандинской области 25 декабря 2009 года № 8-13-72
title:
  rus: О районном бюджете на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-22
approved_by:
- '160013000002'
version_date:
  kaz: 2010-09-10
  rus: 2010-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/49462/kaz/10.09.2010
  rus: https://zan.gov.kz/client/#!/doc/49462/rus/10.09.2010
caused_by:
  code: '54499'
  requisite: Решение XXVI сессии Каркаралинского районного маслихата Карагандинской области от 10 сентября 2010 года № 26/264. Зарегистрировано Управлением юстиции Каркаралинского района Карагандинской области 16 сентября 2010 года № 8-13-88
  title:
    rus: О внесении изменений в решение районного маслихата от 22 декабря 2009 года № 19/192 "О районном бюджете на 2010-2012 годы"
    kaz: Аудандық мәслихаттың 2009 жылғы 22 желтоқсандағы "2010-2012 жылдарға арналған аудандық бюджет туралы" № 19/192 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/54499/rus
