act_code: '29053'
requisite: Қарағанды облысы Ақтоғай аудандық мәслихатының 28 сессиясының 2006 жылғы 22 маусымдағы № 308 шешімі. Ақтоғай ауданы Әділет басқармасында 2006 жылғы 25 шілдеде № 8-10-27 тіркелді. Күші жойылды - Қарағанды облысы Ақтоғай аудандық мәслихатының 12 сессиясының 2009 жылғы 24 сәуірдегі № 141 шешімімен
title:
  rus: Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақыcын беру және телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы берудің Қағидасын бекіту туралы
  kaz: Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақыcын беру және телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы берудің Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2006-06-22
approved_by:
- '160014000002'
version_date:
  kaz: 2007-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/29053/kaz/24.12.2007
caused_by:
  code: '37558'
  requisite: Қарағанды облысы Ақтоғай аудандық мәслихатының 4 сессиясының 2007 жылғы 24 желтоқсандағы № 48 шешімі. Қарағанды облысы Ақтоғай ауданы Әділет басқармасында 2008 жылғы 8 ақпанда № 8-10-58 тіркелді. Күші жойылды - Қарағанды облысы Ақтоғай аудандық мәслихатының 12 сессиясының 2009 жылғы 24 сәуірдегі № 141 шешімімен
  title:
    rus: Аудандық мәслихаттың 2006 жылғы 22 маусымдағы 28 сессиясының "Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй  жәрдемақысын беру және телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы берудің Қағидасын бекіту туралы" N 308 шешіміне ішінара өзгеріс енгізу туралы
    kaz: Аудандық мәслихаттың 2006 жылғы 22 маусымдағы 28 сессиясының "Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй  жәрдемақысын беру және телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы берудің Қағидасын бекіту туралы" N 308 шешіміне ішінара өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/37558/rus
