act_code: '34262'
requisite: Қарағанды облысы Шет аудандық мәслихатының 2007 жылғы 9 шілдедегі № 39/407 шешімі. Қарағанды облысы Шет ауданы әділет басқармасында 2007 жылғы 19 шілдеде № 8-17-46 тіркелді
title:
  rus: Аудан аумағындағы инфрақұрылымдар нысандарын тиімді пайдаланудың кейбір мәселелері туралы
  kaz: Аудан аумағындағы инфрақұрылымдар нысандарын тиімді пайдаланудың кейбір мәселелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-07-09
approved_by:
- '160015000002'
version_date:
  kaz: 2007-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/34262/kaz/09.07.2007
