act_code: '109159'
requisite: Решение 12 сессии Абайского районного маслихата Карагандинской области от 22 декабря 2016 года № 12/107. Зарегистрировано Департаментом юстиции Карагандинской области 5 января 2017 года № 4081
title:
  rus: О районном бюджете на 2017-2019 годы
  kaz: 2017-2019 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-22
approved_by:
- '160011000002'
version_date:
  kaz: 2017-07-05
  rus: 2017-07-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/109159/kaz/05.07.2017
  rus: https://zan.gov.kz/client/#!/doc/109159/rus/05.07.2017
caused_by:
  code: '113519'
  requisite: Решение 19 сессии Абайского районного маслихата Карагандинской области от 5 июля 2017 года № 19/195. Зарегистрировано Департаментом юстиции Карагандинской области 12 июля 2017 года № 4303
  title:
    rus: О внесении изменений в решение 12 сессии Абайского районного маслихата от 22 декабря 2016 года № 12/107 «О районном бюджете на 2017-2019 годы»
    kaz: Абай аудандық мәслихатының 2016 жылғы 22 желтоқсандағы 12 сессиясының № 12/107 «2017-2019 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/113519/rus
