act_code: '51272'
requisite: Решение Балхашского городского маслихата Карагандинской области от 24 февраля 2010 года № 28/217. Зарегистрировано Управлением юстиции города Балхаш Карагандинской области 19 марта 2010 года № 8-4-176. Утратило силу - решением Балхашского городского маслихата Карагандинской области от 24 марта 2011 года № 43/337
title:
  rus: Об оказании социальной помощи отдельным категориям граждан на проезд на внутригородском общественном транспорте (кроме такси)
  kaz: Жеке санаттағы азаматтарға қала ішінде қоғамдық көлікте (таксиден басқа) жүру жолақысына әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-24
approved_by:
- '160008000002'
version_date:
  kaz: 2010-02-24
  rus: 2010-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/51272/kaz/24.02.2010
  rus: https://zan.gov.kz/client/#!/doc/51272/rus/24.02.2010
