act_code: '43068'
requisite: Қарағанды облысы Жаңаарқа ауданы мәслихатының 2008 жылғы 22 желтоқсандағы № 12/109 шешімі. Қарағанды облысы Жаңаарқа ауданы Әділет басқармасында 2008 жылғы 29 желтоқсанда N№ 8-12-47 тіркелді
title:
  rus: Жаңаарқа аудандық Мәслихатының 2008 жылғы 22 желтоқсандағы XII сессиясының "2009 жылға арналған аудандық бюджет туралы" № 12/109 шешімі
  kaz: Жаңаарқа аудандық Мәслихатының 2008 жылғы 22 желтоқсандағы XII сессиясының "2009 жылға арналған аудандық бюджет туралы" № 12/109 шешімі
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-22
approved_by:
- '160016000002'
version_date:
  kaz: 2011-04-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/43068/kaz/06.04.2011
