act_code: '49877'
requisite: Қарағанды облысы Шет ауданы әкімінің 2009 жылғы 21 желтоқсандағы № 01 шешімі. Қарағанды облысы Шет ауданының Әділет басқармасында 2010 жылғы 12 қаңтарда № 8-17-93 тіркелді. Күші жойылды - Қарағанды облысы Шет ауданы әкімінің 2010 жылғы 6 желтоқсандағы № 01 шешімімен
title:
  rus: Шет ауданы аумағында тұратын 1993 жылы туған азаматтарды 2010 жылғы әскерге шақыру учаскесіне тіркеу туралы
  kaz: Шет ауданы аумағында тұратын 1993 жылы туған азаматтарды 2010 жылғы әскерге шақыру учаскесіне тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '160015000001'
version_date:
  kaz: 2009-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/49877/kaz/21.12.2009
