act_code: '148168'
requisite: Решение акима Кайнарбулакского сельского округа Каркаралинского района Карагандинской области от 2 ноября 2020 года № 5. Зарегистрировано Департаментом юстиции Карагандинской области 4 ноября 2020 года № 6066. Утратило силу решением акима Кайнарбулакского сельского округа Каркаралинского района Карагандинской области от 28 января 2021 года № 1 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-11-02
approved_by:
- '160013006002'
version_date:
  kaz: 2020-11-02
  rus: 2020-11-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/148168/kaz/02.11.2020
  rus: https://zan.gov.kz/client/#!/doc/148168/rus/02.11.2020
