act_code: '151284'
requisite: Решение Приозерского городского маслихата Карагандинской области от 29 декабря 2020 года № 43/444. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 января 2021 года № 22028
title:
  rus: О городском бюджете на 2021 - 2023 годы
  kaz: 2021 – 2023 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-29
approved_by:
- '160009000002'
version_date:
  kaz: 2021-02-25
  rus: 2021-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/151284/kaz/25.02.2021
  rus: https://zan.gov.kz/client/#!/doc/151284/rus/25.02.2021
caused_by:
  code: '153239'
  requisite: Решение Приозерского городского маслихата Карагандинской области от 25 февраля 2021 года № 2/21. Зарегистрировано Департаментом юстиции Карагандинской области 3 марта 2021 года № 6224
  title:
    rus: О внесении изменений в решение Приозерского городского маслихата от 29 декабря 2020 года № 43/444 «О городском бюджете на 2021 – 2023 годы»
    kaz: Приозерск қалалық мәслихатының 2020 жылғы 29 желтоқсандағы № 43/444 «2021 - 2023 жылдарға арналған қалалық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/153239/rus
