act_code: '56893'
requisite: Қарағанды облысы Шет аудандық мәслихатының 2010 жылғы 23 желтоқсандағы № 28/297 шешімі. Қарағанды облысы Шет ауданының Әділет басқармасында 2011 жылғы 20 қаңтарда № 8-17-113 тіркелді. Күші жойылды - Қарағанды облысы Шет аудандық мәслихатының 2011 жылғы 30 қарашадағы № 40/382 шешімімен
title:
  rus: Шет ауданы бойынша тұрғын үй көмегін көрсету ережесін бекіту туралы
  kaz: Шет ауданы бойынша тұрғын үй көмегін көрсету ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-12-23
approved_by:
- '160015000002'
version_date:
  kaz: 2011-06-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/56893/kaz/03.06.2011
caused_by:
  code: '59473'
  requisite: Решение Шетского районного маслихата Карагандинской области от 3 июня 2011 года № 32/331. Зарегистрировано Управлением юстиции Шетского района Карагандинской области 4 июля 2011 года № 8-17-121. Утратило силу решением Шетского районного маслихата Карагандинской области от 26 июня 2012 года № 4/51
  title:
    rus: О внесении изменений в некоторые решения районного маслихата
    kaz: Аудандық мәслихаттың кейбiр шешiмдерiне өзгерiстер енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/59473/rus
