act_code: '225913'
requisite: Решение Осакаровского районного маслихата Карагандинской области от 28 мая 2026 года № 50/486
title:
  rus: Об утверждении Положения государственного учреждения «Аппарат Осакаровского районного маслихата Карагандинской области»
  kaz: «Қарағанды облысы Осакаров аудандық мәслихатының аппараты» мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2026-05-28
approved_by:
- '160018000002'
version_date:
  kaz: 2026-05-28
  rus: 2026-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/225913/kaz/28.05.2026
  rus: https://zan.gov.kz/client/#!/doc/225913/rus/28.05.2026
