act_code: '162081'
requisite: Решение Нуринского районного маслихата Карагандинской области от 23 декабря 2021 года № 99. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 декабря 2021 года № 25985
title:
  rus: О районном бюджете на 2022-2024 годы
  kaz: 2022 – 2024 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-23
approved_by:
- '160012000002'
version_date:
  kaz: 2022-04-28
  rus: 2022-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/162081/kaz/28.04.2022
  rus: https://zan.gov.kz/client/#!/doc/162081/rus/28.04.2022
caused_by:
  code: '167173'
  requisite: Решение Нуринского районного маслихата Карагандинской области от 28 апреля 2022 года № 126
  title:
    rus: О внесении изменений в решение Нуринского районного маслихата от 23 декабря 2021 года № 99 «О районном бюджете на 2022-2024 годы»
    kaz: Нұра аудандық мәслихатының 2021 жылғы 23 желтоқсандағы № 99 «2022 – 2024 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/167173/rus
