act_code: '71377'
requisite: Решение Жезказганского городского маслихата Карагандинской области от 7 февраля 2013 года № 12/102. Зарегистрировано Департаментом юстиции Карагандинской области 5 марта 2013 года № 2205. Утратило силу решением Жезказганского городского маслихата Карагандинской области от 9 июля 2014 года № 25/218
title:
  rus: О предоставлении в 2013 году мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии, прибывшим для работы и проживания в сельские населенные пункты города Жезказгана
  kaz: Жезқазған қаласының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және ветеринария мамандарына әлеуметтік қолдау шараларын 2013 жылы ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-02-07
approved_by:
- '160006000002'
version_date:
  kaz: 2013-02-07
  rus: 2013-02-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/71377/kaz/07.02.2013
  rus: https://zan.gov.kz/client/#!/doc/71377/rus/07.02.2013
