act_code: '166309'
requisite: Решение Жанааркинского районного маслихата Карагандинской области от 5 апреля 2022 года № 21/146. Утратило силу решением Жанааркинского районного маслихата области Ұлытау от 19 октября 2023 года № 8/58 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества сельского округа Ералиев Жанааркинского района
  kaz: Жаңаарқа ауданының Ералиев ауылдық округінің бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2022-04-05
approved_by:
- '160016000002'
version_date:
  kaz: 2022-04-05
  rus: 2022-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/166309/kaz/05.04.2022
  rus: https://zan.gov.kz/client/#!/doc/166309/rus/05.04.2022
