act_code: '195372'
requisite: Решение акима города Каркаралинск Каркаралинского района Карагандинской области от 5 апреля 2024 года № 3
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын алып тастау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-05
approved_by:
- '160013001001'
version_date:
  kaz: 2024-04-05
  rus: 2024-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/195372/kaz/05.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195372/rus/05.04.2024
