act_code: '29231'
requisite: Қарағанды облысы Ұлытау аудандық мәслихатының XX сессиясының 2006 жылғы 11 шілдедегі № 20-8 шешімі. Қарағанды облысы Ұлытау ауданы Әділет басқармасында 2006 жылғы 3 тамызда № 8-16-16 тіркелді. Күші жойылды - Қарағанды облысы Ұлытау аудандық мәслихатының XXXII сессиясының 2011 жылғы 14 қарашадағы № 378 шешімімен
title:
  rus: Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақысын беру және қалалық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы берудің Қағидасын бекіту туралы
  kaz: Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақысын беру және қалалық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы берудің Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2006-07-11
approved_by:
- '160019000002'
version_date:
  kaz: 2008-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/29231/kaz/31.03.2008
caused_by:
  code: '39181'
  requisite: Қарағанды облысы Ұлытау аудандық мәслихатының V сессиясының 2008 жылғы 31 наурыздағы № 66 шешімі. Қарағанды облысы Ұлытау ауданы әділет басқармасында 2008 жылғы 28 сәуірде № 8-16-31 тіркелді
  title:
    rus: Ұлытау аудандық мәслихатының 2006 жылғы 11 шілдедегі ХХ сессиясының "Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақысын беру және қалалық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы берудің Қағидасын бекіту туралы" № 20-8 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Ұлытау аудандық мәслихатының 2006 жылғы 11 шілдедегі ХХ сессиясының "Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақысын беру және қалалық телекоммуникация желілерінің абоненттеріне телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы берудің Қағидасын бекіту туралы" № 20-8 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/39181/rus
