act_code: '123545'
requisite: Решение XXX сессии Каркаралинского районного маслихата Карагандинской области от 29 июня 2018 года № VI-30/269. Зарегистрировано Департаментом юстиции Карагандинской области 11 июля 2018 года № 4862
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов, а также тарифов на сбор, вывоз и захоронение твердых бытовых отходов по Каркаралинскому району
  kaz: Қарқаралы ауданы бойынша коммуналдық қалдықтардың пайда болуы және жинақталу нормаларын, сондай-ақ тұрмыстық қатты қалдықтарды жинауға, әкетуге және көмуге арналған тарифті бекіту туралы
form: РЕШ
type_codes:
- НОРМ
- РЕШ
approved_on: 2018-06-29
approved_by:
- '160013000002'
version_date:
  kaz: 2019-10-22
  rus: 2019-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/123545/kaz/22.10.2019
  rus: https://zan.gov.kz/client/#!/doc/123545/rus/22.10.2019
caused_by:
  code: '135628'
  requisite: Решение Каркаралинского районного маслихата Карагандинской области от 22 октября 2019 года № VI-47/398. Зарегистрировано Департаментом юстиции Карагандинской области 30 октября 2019 года № 5515
  title:
    rus: О внесении изменения в решение ХХХ сессии Каркаралинского районного маслихата от 29 июня 2018 года № VI-30/269 «Об утверждении норм образования и накопления коммунальных отходов, а также тарифов на сбор, вывоз и захоронение твердых бытовых отходов по Каркаралинскому району»
    kaz: Қарқаралы аудандық мәслихатының 2018 жылғы 29 маусымдағы XXX сессиясының № VI-30/269 «Қарқаралы ауданы бойынша коммуналдық қалдықтардың пайда болуы және жинақталу нормаларын, сондай-ақ тұрмыстық қатты қалдықтарды жинауға, әкетуге және көмуге арналған тарифті бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/135628/rus
