act_code: '104169'
requisite: Решение акима села Акоре Бухар-Жырауского района Карагандинской области от 6 июня 2016 года № 3. Зарегистрировано Департаментом юстиции Карагандинской области 27 июня 2016 года № 3872
title:
  rus: О переименовании улиц в селе Акоре
  kaz: Ақөре ауылындағы көшелерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-06-06
approved_by:
- '160017006001'
version_date:
  kaz: 2016-06-06
  rus: 2016-06-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/104169/kaz/06.06.2016
  rus: https://zan.gov.kz/client/#!/doc/104169/rus/06.06.2016
