act_code: '110915'
requisite: Решение Х сессии Жанааркинского районного маслихата Карагандинской области от 28 февраля 2017 года № 10/83. Зарегистрировано Департаментом юстиции Карагандинской области 30 марта 2017 года № 4197
title:
  rus: Об утверждении Положения о награждении Почетной грамотой Жанааркинского района
  kaz: Жаңаарқа ауданының Құрмет грамотасымен наградтау туралы Ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2017-02-28
approved_by:
- '160016000002'
version_date:
  kaz: 2023-09-22
  rus: 2023-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/110915/kaz/22.09.2023
  rus: https://zan.gov.kz/client/#!/doc/110915/rus/22.09.2023
caused_by:
  code: '186663'
  requisite: Решение Жанааркинского районного маслихата области Ұлытау от 22 сентября 2023 года № 7/44. Зарегистрировано в Департаменте юстиции области Ұлытау 29 сентября 2023 года № 57-20
  title:
    rus: О внесении изменений в решение Жанааркинского районного маслихата от 28 февраля 2017 года № 10/83 «Об утверждении Положения о награждении Почетной грамотой Жанааркинского района»
    kaz: Жаңаарқа аудандық мәслихатының 2017 жылғы 28 ақпандағы № 10/83 «Жаңаарқа ауданының Құрмет грамотасымен наградтау туралы ережені бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/186663/rus
