act_code: '128659'
requisite: Решение акима Егиндыбулакского сельского округа Каркаралинского района Карагандинской области от 11 января 2019 года № 01. Зарегистрировано Департаментом юстиции Карагандинской области 16 января 2019 года № 5155
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-11
approved_by:
- '160013003002'
version_date:
  kaz: 2019-01-11
  rus: 2019-01-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/128659/kaz/11.01.2019
  rus: https://zan.gov.kz/client/#!/doc/128659/rus/11.01.2019
