act_code: '48116'
requisite: Решение Осакаровского районного маслихата Карагандинской области от 8 сентября 2009 года № 172. Зарегистрировано Управлением юстиции Осакаровского района Карагандинской области 13 октября 2009 года № 8-15-109. Утратило силу - решением Осакаровского районного маслихата Карагандинской области от 30 июля 2010 года № 255
title:
  rus: Об утверждении Правил предоставления малообеспеченным гражданам жилищных пособий на содержание жилья, оплату коммунальных услуг и компенсацию повышения тарифов абонентской платы за оказание услуг телекоммуникаций социально защищаемым гражданам и порядка исчисления совокупного дохода лица (семьи) при назначении жилищного пособия
  kaz: Аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсету үшін тұрғын үй жәрдемақыларды беру және әлеуметтік қорғалынатын  азаматтарға телекоммуникация қызметі үшін абоненттік ақы тарифтерінің арттырылуына өтемақы берудің және тұрғын үй жәрдемақысын тағайындау кезінде адамның (отбасының) жиынтық табысын есептеу тәртібі туралы Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2009-09-08
approved_by:
- '160018000002'
version_date:
  kaz: 2009-09-08
  rus: 2009-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/48116/kaz/08.09.2009
  rus: https://zan.gov.kz/client/#!/doc/48116/rus/08.09.2009
