act_code: '33884'
requisite: Қарағанды облысы Ақтоғай ауданының әкімінің 2007 жылғы 25 маусымдағы № 02-ш шешімі. Қарағанды облысы Ақтоғай ауданы Әділет басқармасында 2007 жылғы 28 маусымда № 8-10-46 тіркелді. Күші жойылды - Қарағанды облысы Ақтоғай ауданының әкімінің 2011 жылғы 24 қарашадағы № 08ш шешімімен
title:
  rus: Қазақстан Республикасы Парламенті Мәжілісінің депутаттарының және Қазақстан Республикасы мәслихаттары депутаттарының сайлауын өткізу жөніндегі сайлау учаскелерін құру туралы
  kaz: Қазақстан Республикасы Парламенті Мәжілісінің депутаттарының және Қазақстан Республикасы мәслихаттары депутаттарының сайлауын өткізу жөніндегі сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-06-25
approved_by:
- '160014000003'
version_date:
  kaz: 2007-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/33884/kaz/25.06.2007
