act_code: '161462'
requisite: Решение Нуринского районного маслихата Карагандинской области от 9 декабря 2021 года № 95. Зарегистрировано в Министерстве юстиции Республики Казахстан 10 декабря 2021 года № 25702. Утратило силу решением Нуринского районного маслихата Карагандинской области от 18 июня 2026 года № 251 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по Нуринскому району
  kaz: Нұра ауданы бойынша тұрғын үй сертификаттарының мөлшерін және алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-09
approved_by:
- '160012000002'
version_date:
  kaz: 2021-12-09
  rus: 2021-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/161462/kaz/09.12.2021
  rus: https://zan.gov.kz/client/#!/doc/161462/rus/09.12.2021
