act_code: '58361'
requisite: Решение 34 сессии Абайского районного маслихата Карагандинской области от 28 марта 2011 года № 34/406. Зарегистрировано Управлением юстиции Абайского района Карагандинской области 19 апреля 2011 года № 8-9-106. Утратило силу - решением 42 сессии Абайского районного маслихата Карагандинской области от 12 декабря 2011 года № 42/502
title:
  rus: О предоставлении мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры и спорта прибывшим для работы и проживания в сельские населенные пункты Абайского района на 2011 год
  kaz: 2011 жылға арналған Абай ауданының ауылдық елді мекендерінде жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына әлеуметтік қолдау шараларын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-03-28
approved_by:
- '160011000002'
version_date:
  kaz: 2011-03-28
  rus: 2011-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/58361/kaz/28.03.2011
  rus: https://zan.gov.kz/client/#!/doc/58361/rus/28.03.2011
