act_code: '119978'
requisite: Решение акима Курмиинского сельского округа Абайского района Карагандинской области от 5 марта 2018 года № 01. Зарегистрировано Департаментом юстиции Карагандинской области 28 марта 2018 года № 4670
title:
  rus: О переименовании улиц в селе Жумабек Курминского сельского округа
  kaz: Курмин ауылдық округі Жұмабек ауылындағы көшелерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-05
approved_by:
- '160011009001'
version_date:
  kaz: 2018-03-05
  rus: 2018-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/119978/kaz/05.03.2018
  rus: https://zan.gov.kz/client/#!/doc/119978/rus/05.03.2018
