act_code: '127089'
requisite: Решение акима села Ахмет Нуринского района Карагандинской области от 6 декабря 2018 года № 3. Зарегистрировано Департаментом юстиции Карагандинской области 12 декабря 2018 года № 5061
title:
  rus: О переименовании улицы
  kaz: Көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-06
approved_by:
- '160012021001'
version_date:
  kaz: 2018-12-06
  rus: 2018-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/127089/kaz/06.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127089/rus/06.12.2018
