act_code: '51848'
requisite: Қарағанды облысы Ақтоғай ауданы Тасарал селолық округі әкімінің 2010 жылғы 11 наурыздағы № 1 шешімі. Қарағанды облысы Ақтоғай ауданының Әділет басқармасында 2010 жылғы 21 сәуірде № 8-10-113 тіркелді
title:
  rus: Тасарал селолық округіндегі көшелерін қайта атау туралы
  kaz: Тасарал селолық округіндегі көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-11
approved_by:
- '160014011001'
version_date:
  kaz: 2010-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/51848/kaz/11.03.2010
