act_code: '56350'
requisite: Қарағанды облысы Ақтоғай ауданы әкімінің 2010 жылғы 15 желтоқсандағы № 02-ш шешімі. Қарағанды облысы Ақтоғай ауданының Әділет басқармасында 2010 жылғы 28 желтоқсанда № 8-10-126 тіркелді. Күші жойылды - Қарағанды облысы Ақтоғай ауданы әкімінің 2012 жылғы 18 қаңтардағы № 01ш шешімімен
title:
  rus: Ақтоғай ауданы бойынша 1994 жылғы туған азаматтарды Балқаш қаласының қорғаныс істері жөніндегі біріктірілген бөлімінің шақыру учаскесіне тіркеуді өткізу туралы
  kaz: Ақтоғай ауданы бойынша 1994 жылғы туған азаматтарды Балқаш қаласының қорғаныс істері жөніндегі біріктірілген бөлімінің шақыру учаскесіне тіркеуді өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-15
approved_by:
- '160014000003'
version_date:
  kaz: 2010-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/56350/kaz/15.12.2010
