act_code: '72824'
requisite: Решение Темиртауского городского маслихата Карагандинской области от 26 апреля 2013 года № 15/5. Зарегистрировано Департаментом юстиции Карагандинской области 30 мая 2013 года № 2339. Утратило силу решением Темиртауского городского маслихата от 4 октября 2018 года № 31/4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении размера ставок фиксированного налога с единицы объекта налогообложения
  kaz: Салық салу объектісінің бірлігінен тіркелген салық ставкаларының мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-04-26
approved_by:
- '160005000002'
version_date:
  kaz: 2015-06-09
  rus: 2015-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/72824/kaz/09.06.2015
  rus: https://zan.gov.kz/client/#!/doc/72824/rus/09.06.2015
caused_by:
  code: '91077'
  requisite: Решение Темиртауского городского маслихата Карагандинской области от 9 июня 2015 года № 39/5. Зарегистрировано Департаментом юстиции Карагандинской области 19 июня 2015 года № 3278. Утратило силу решением Темиртауского городского маслихата от 4 октября 2018 года № 31/4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение 15 сессии Темиртауского городского маслихата от 26 апреля 2013 года № 15/5 «Об установлении размера ставок фиксированного налога с единицы объекта налогообложения»
    kaz: Теміртау қалалық мәслихатының 2013 жылғы 26 сәуірдегі 15 сессиясының № 15/5 «Салық салу объектісінің бірлігінен тіркелген салық ставкаларының мөлшерін белгілеу туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/91077/rus
