act_code: '144080'
requisite: Решение акима города Темиртау Карагандинской области от 24 июня 2020 года № 1. Зарегистрировано Департаментом юстиции Карагандинской области 25 июня 2020 года № 5904
title:
  rus: Об образовании избирательных участков в городе Темиртау
  kaz: Теміртау қаласында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-24
approved_by:
- '160005000003'
version_date:
  kaz: 2020-06-24
  rus: 2020-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/144080/kaz/24.06.2020
  rus: https://zan.gov.kz/client/#!/doc/144080/rus/24.06.2020
