act_code: '1947'
requisite: Решение Акима Карагандинской области от 8 октября 1998 г. № 146. Зарегистрировано управлением юстиции Карагандинской области 05.11.1998 г. за № 22. Утратило силу решением акима Карагандинской области от 14 мая 2004 года № 44
title:
  rus: О работе акимов г.Балхаша и Осакаровского района по организации выполнения Закона Республики Казахстан "О языках в Республике Казахстан"
  kaz: Балқаш қаласы мен Осакаровка ауданы әкімдерінің Қазақстан Республикасының "Қазақстан Республикасындағы тілдер туралы" Заңының орындалуын ұйымдастыру жөніндегі есептері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-10-07
approved_by:
- '160000000001'
version_date:
  kaz: 1998-10-07
  rus: 1998-10-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/1947/kaz/07.10.1998
  rus: https://zan.gov.kz/client/#!/doc/1947/rus/07.10.1998
