act_code: '137929'
requisite: Решение Жанааркинского районного маслихата Карагандинской области от 25 декабря 2019 года № 48/328. Зарегистрировано Департаментом юстиции Карагандинской области 31 декабря 2019 года № 5646
title:
  rus: О районном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '160016000002'
version_date:
  kaz: 2020-09-08
  rus: 2020-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/137929/kaz/08.09.2020
  rus: https://zan.gov.kz/client/#!/doc/137929/rus/08.09.2020
caused_by:
  code: '146200'
  requisite: Решение Жанааркинского районного маслихата Карагандинской области от 8 сентября 2020 года № 58/394. Зарегистрировано Департаментом юстиции Карагандинской области 10 сентября 2020 года № 6032
  title:
    rus: О внесении изменений и дополнений в решение Жанааркинского районного маслихата от 25 декабря 2019 года № 48/328 «О районном бюджете на 2020-2022 годы»
    kaz: Жаңаарқа аудандық мәслихатының 2019 жылғы 25 желтоқсандағы № 48/328 «2020-2022 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146200/rus
