act_code: '54904'
requisite: Решение Сатпаевского городского маслихата Карагандинской области от 14 сентября 2010 года № 363. Зарегистрировано Управлением юстиции города Сатпаев Карагандинской области 15 октября 2010 года № 8-6-109. Утратило силу - решением Сатпаевского городского маслихата Карагандинской области от 23 ноября 2011 года № 478
title:
  rus: Об утверждении Правил оказания жилищной помощи населению города Сатпаев
  kaz: Сәтбаев қаласының тұрғындарына тұрғын үй көмегін көрсету қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-09-14
approved_by:
- '160007000002'
version_date:
  kaz: 2010-12-23
  rus: 2010-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/54904/kaz/23.12.2010
  rus: https://zan.gov.kz/client/#!/doc/54904/rus/23.12.2010
caused_by:
  code: '56292'
  requisite: Решение Сатпаевского городского маслихата Карагандинской области от 23 декабря 2010 года № 393. Зарегистрировано Управлением юстиции города Сатпаев Карагандинской области 29 декабря 2010 года № 8-6-112. Утратило силу решением Сатпаевского городского маслихата Карагандинской области от 24 декабря 2014 года № 302
  title:
    rus: О внесении дополнения в решение ХХIХ сессии Сатпаевского городского маслихата от 14 сентября 2010 года № 363 "Об утверждении Правил оказания жилищной помощи населению города Сатпаев"
    kaz: '"Сәтбаев қаласының тұрғындарына тұрғын үй көмегін көрсету қағидасын бекіту туралы" Сәтбаев қалалық мәслихатының 2010 жылғы 14 қыркүйектегі ХХІХ сессиясының № 363 шешіміне толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/56292/rus
