act_code: '80651'
requisite: Решение 32 сессии Саранского городского маслихата Карагандинской области от 22 мая 2014 года № 337. Зарегистрировано Департаментом юстиции Карагандинской области 5 июня 2014 года № 2655. Утратило силу решением Саранского городского маслихата Карагандинской области от 27 июня 2023 года № 39 (вводится в действие по истечении десяти календарных дней после его первого официального опубликования)
title:
  rus: О возмещении затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индиувидуальному учебному плану
  kaz: Мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-05-22
approved_by:
- '160003000002'
version_date:
  kaz: 2014-05-22
  rus: 2014-05-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/80651/kaz/22.05.2014
  rus: https://zan.gov.kz/client/#!/doc/80651/rus/22.05.2014
