act_code: '153703'
requisite: Решение Карагандинского областного маслихата от 18 марта 2021 года № 58. Зарегистрировано Департаментом юстиции Карагандинской области 19 марта 2021 года № 6256. Утратило силу решением Карагандинского областного маслихата от 18 апреля 2023 года № 35 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О предоставлении лекарственных средств дополнительно
  kaz: Дәрілік заттарды қосымша беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-18
approved_by:
- '160000000002'
version_date:
  kaz: 2021-03-18
  rus: 2021-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/153703/kaz/18.03.2021
  rus: https://zan.gov.kz/client/#!/doc/153703/rus/18.03.2021
