act_code: '192519'
requisite: Решение акима Абайского района Карагандинской области от 15 января 2024 года № 01. Утратило силу решением акима Абайского района Карагандинской области от 27 февраля 2024 года № 02 (вводится в действие со дня первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба
  kaz: Жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-01-15
approved_by:
- '160011000003'
version_date:
  kaz: 2024-01-15
  rus: 2024-01-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/192519/kaz/15.01.2024
  rus: https://zan.gov.kz/client/#!/doc/192519/rus/15.01.2024
