act_code: '56171'
requisite: Решение Каркаралинского районного маслихата Карагандинской области от 23 декабря 2010 года № 28/276. Зарегистрировано Управлением юстиции Каркаралинского района Карагандинской области 24 декабря 2010 года № 8-13-92
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '160013000002'
version_date:
  kaz: 2011-10-18
  rus: 2011-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/56171/kaz/18.10.2011
  rus: https://zan.gov.kz/client/#!/doc/56171/rus/18.10.2011
caused_by:
  code: '60995'
  requisite: Решение XXXX сессии Каркаралинского районного маслихата Карагандинской области от 18 октября 2011 года № 40/398. Зарегистрировано Управлением юстиции Каркаралинского района Карагандинской области 28 октября 2011 года № 8-13-106
  title:
    rus: О внесении изменений в решение районного маслихата от 23 декабря 2010 года № 28/276 "О районном бюджете на 2011-2013 годы"
    kaz: Аудандық мәслихаттың 2010 жылғы 23 желтоқсандағы "2011-2013 жылдарға арналған аудандық бюджет туралы" № 28/276 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/60995/rus
