act_code: '1966'
requisite: Решение Акима Карагандинской области от 25 ноября 1998 года № 178. Зарегистрировано управлением юстиции Карагандинской области 25.12.1998 г. за № 25. Утратило силу в связи с истечением срока письмом руководителя аппарата акима Карагандинской области от 21 января 2005 года № 05-11/89
title:
  rus: О ходе реализации Указа Президента РК № 3558 от 20.06.97 г. "О государственной программе Республики Казахстан по борьбе с преступностью на 1997-1998 гг. и основным направлениям правоохранительной деятельности до 2000 года"
  kaz: Қазақстан Республикасы Президентінің 1997 жылғы 20 маусымдағы "Қазақстан Республикасының 1997-1998 жылдарға арналған қылмыспен күресу жөніндегі мемлекеттік бағдарламасы және 2000 жылға дейінгі құқық қорғау қызметінің негізгі бағыттары туралы" № 3558 Жарлығын жүзеге асыру барысы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-11-25
approved_by:
- '160000000001'
version_date:
  kaz: 1998-11-25
  rus: 1998-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/1966/kaz/25.11.1998
  rus: https://zan.gov.kz/client/#!/doc/1966/rus/25.11.1998
