act_code: '219307'
requisite: Решение Нуринского районного маслихата Карагандинской области от 18 декабря 2025 года № 200
title:
  rus: О бюджете сел, поселков и сельских округов на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған ауылдар, кенттер және ауылдық округтердің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-18
approved_by:
- '160012000002'
version_date:
  kaz: 2026-07-16
  rus: 2026-07-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/219307/kaz/16.07.2026
  rus: https://zan.gov.kz/client/#!/doc/219307/rus/16.07.2026
caused_by:
  code: '227808'
  requisite: Решение Нуринского районного маслихата Карагандинской области от 16 июля 2026 года № 259
  title:
    rus: О внесении изменений в решение Нуринского районного маслихата от 18 декабря 2025 года № 200 «О бюджете сел, поселков и сельских округов на 2026-2028 годы»
    kaz: Нұра аудандық мәслихатының 2025 жылғы 18 желтоқсандағы № 200 «2026-2028 жылдарға арналған ауылдар, кенттер және ауылдық округтердің бюджеті туралы» шешіміне өзгерітер еңгізу туралы
  link: https://zan.gov.kz/client/#!/doc/227808/rus
