act_code: '179503'
requisite: Решение Осакаровского районного маслихата Карагандинской области от 31 марта 2023 года № 2/15. Утратило силу решением Осакаровского районного маслихата Карагандинской области от 31 октября 2023 года № 12/113 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей сельского округа Сарыозек Осакаровского района Карагандинской области для участия в сходе местного сообщества
  kaz: Қарағанды облысы Осакаров ауданы Сарыөзек ауылдық округінің жергілікті қоғамдастықтың бөлек жиындарын өткізу тәртібін және жергілікті қоғамдастық жиындарына қатысу үшін ауылдық округ тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2023-03-31
approved_by:
- '160018000002'
version_date:
  kaz: 2023-03-31
  rus: 2023-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/179503/kaz/31.03.2023
  rus: https://zan.gov.kz/client/#!/doc/179503/rus/31.03.2023
