act_code: '85131'
requisite: Решение Шетского районного маслихата Карагандинской области от 25 ноября 2014 года № 26/224. Зарегистрировано Департаментом юстиции Карагандинской области 19 декабря 2014 года № 2880. Утратило силу решением Шетского районного маслихата Карагандинской области от 21 апреля 2015 года № 29/261
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества Шетского района
  kaz: Шет ауданының бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-11-25
approved_by:
- '160015000002'
version_date:
  kaz: 2014-11-25
  rus: 2014-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/85131/kaz/25.11.2014
  rus: https://zan.gov.kz/client/#!/doc/85131/rus/25.11.2014
