act_code: '162413'
requisite: Решение Саранского городского маслихата Карагандинской области от 23 декабря 2021 года № 82. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 декабря 2021 года № 26162
title:
  rus: О городском бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-23
approved_by:
- '160003000002'
version_date:
  kaz: 2022-10-19
  rus: 2022-10-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/162413/kaz/19.10.2022
  rus: https://zan.gov.kz/client/#!/doc/162413/rus/19.10.2022
caused_by:
  code: '173219'
  requisite: Решение Саранского городского маслихата Карагандинской области от 19 октября 2022 года № 177
  title:
    rus: О внесении изменений в решение Саранского городского маслихата от 23 декабря 2021 года № 82 «О городском бюджете на 2022-2024 годы»
    kaz: Саран қалалық мәслихатының 2021 жылғы 23 желтоқсандағы № 82 «2022 - 2024 жылдарға арналған қалалық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173219/rus
