act_code: '106930'
requisite: Решение 6 сессии Актогайского районного маслихата Карагандинской области от 28 сентября 2016 года № 61. Зарегистрировано Департаментом юстиции Карагандинской области 10 октября 2016 года № 3981. Утратило силу решением Актогайского районного маслихата Карагандинской области от 24 июня 2020 года № 405 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении Правил выдачи служебного удостоверения государственного учреждения «Аппарат Актогайского районного маслихата» и его описание
  kaz: «Ақтоғай аудандық мәслихатының аппараты» мемлекеттік мекемесінің қызметтік куәлігін беру қағидаларын және оның сипаттамасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-09-28
approved_by:
- '160014000002'
version_date:
  kaz: 2016-09-28
  rus: 2016-09-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/106930/kaz/28.09.2016
  rus: https://zan.gov.kz/client/#!/doc/106930/rus/28.09.2016
