act_code: '150927'
requisite: Решение Жанааркинского районного маслихата Карагандинской области от 28 декабря 2020 года № 67/534. Зарегистрировано в Министерстве юстиции Республики Казахстан 30 декабря 2020 года № 21969
title:
  rus: О районном бюджете на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-28
approved_by:
- '160016000002'
version_date:
  kaz: 2021-11-09
  rus: 2021-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/150927/kaz/09.11.2021
  rus: https://zan.gov.kz/client/#!/doc/150927/rus/09.11.2021
caused_by:
  code: '160302'
  requisite: Решение Жанааркинского районного маслихата Карагандинской области от 9 ноября 2021 года № 13/81. Зарегистрировано в Министерстве юстиции Республики Казахстан 17 ноября 2021 года № 25199
  title:
    rus: О внесении изменений в решение Жанааркинского районного маслихата от 28 декабря 2020 года № 67/534 «О районном бюджете на 2021-2023 годы»
    kaz: Жаңаарқа аудандық мәслихатының 2020 жылғы 28 желтоқсандағы № 67/534 «2021-2023 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/160302/rus
