act_code: '32057'
requisite: Решение Осакаровского районного маслихата Карагандинской области от 11 января 2007 года № 243. Зарегистрировано Управлением юстиции Осакаровского района Карагандинской области 23 февраля 2007 года № 8-15-59. Утратило силу решением Осакаровского районного маслихата Карагандинской области от 11 апреля 2007 года № 258
title:
  rus: Об установлении ставки на игровой стол на 2007 год
  kaz: 2007 жылға арналған ойын столы ставкасын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-01-11
approved_by:
- '160018000002'
version_date:
  kaz: 2007-01-11
  rus: 2007-01-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/32057/kaz/11.01.2007
  rus: https://zan.gov.kz/client/#!/doc/32057/rus/11.01.2007
