act_code: '18253'
requisite: Решение III сессии Карагандинского областного Маслихата от 25 декабря 2003 года № 33. Зарегистрировано Департаментом юстиции Карагандинской области 16 января 2004 года за № 1377
title:
  rus: О ставках платы за загрязнение окружающей среды на 2004 год
  kaz: 2004 жылға арналған қоршаған ортаны ластағаны үшін төлемақы ставкасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-12-25
approved_by:
- '160000000002'
version_date:
  kaz: 2003-12-25
  rus: 2003-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/18253/kaz/25.12.2003
  rus: https://zan.gov.kz/client/#!/doc/18253/rus/25.12.2003
