act_code: '76266'
requisite: Решение ХХХ сессии V созыва Карагандинского городского маслихата от 23 декабря 2013 года № 271. Зарегистрировано Департаментом юстиции Карагандинской области 28 декабря 2013 года № 2483
title:
  rus: О бюджете города Караганды на 2014-2016 годы
  kaz: Қарағанды қаласының 2014-2016 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-23
approved_by:
- '160002000002'
version_date:
  kaz: 2014-09-17
  rus: 2014-09-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/76266/kaz/17.09.2014
  rus: https://zan.gov.kz/client/#!/doc/76266/rus/17.09.2014
caused_by:
  code: '83217'
  requisite: Решение ХL сессии V созыва Карагандинского городского маслихата от 17 сентября 2014 года № 353. Зарегистрировано Департаментом юстиции Карагандинской области 19 сентября 2014 года № 2751
  title:
    rus: О внесении изменений в решение XXX сессии Карагандинского городского маслихата от 23 декабря 2013 года № 271 "О бюджете города Караганды на 2014-2016 годы"
    kaz: Қарағанды қалалық мәслихатының XXX сессиясының 2013 жылғы 23 желтоқсандағы № 271 "Қарағанды қаласының 2014-2016 жылдарға арналған бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/83217/rus
