act_code: '55423'
requisite: Решение 27 сессии Абайского районного маслихата Карагандинской области от 7 октября 2010 года № 27/328. Зарегистрировано Управлением юстиции Абайского района Карагандинской области 15 ноября 2010 года № 8-9-89. Утратило силу - решением 6 сессии Абайского районного маслихата Карагандинской области от 8 июня 2012 года № 6/58
title:
  rus: Об утверждении Правил содержания и защиты зеленых насаждений в населенных пунктах Абайского района
  kaz: Абай ауданының елді мекендеріндегі жасыл көшеттерді ұстау және қорғау Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-10-07
approved_by:
- '160011000002'
version_date:
  kaz: 2011-06-16
  rus: 2011-06-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/55423/kaz/16.06.2011
  rus: https://zan.gov.kz/client/#!/doc/55423/rus/16.06.2011
caused_by:
  code: '59674'
  requisite: Решение 35 сессии Абайского районного маслихата Карагандинской области от 16 июня 2011 года № 35/424. Зарегистрировано Управлением юстиции Абайского района Карагандинской области 18 июля 2011 года № 8-9-109. Утратило силу - решением 6 сессии Абайского районного маслихата Карагандинской области от 8 июня 2012 года N 6/58
  title:
    rus: О внесении изменения в решение 27 внеочередной сессии Абайского районного маслихата от 7 октября 2010 года № 27/328 "Об утверждении Правил содержания и защиты зеленых насаждений в населенных пунктах Абайского района"
    kaz: Абай аудандық мәслихатының 2010 жылғы 7 қазандағы 27 кезектен тыс сессиясының № 27/328 "Абай ауданының елді мекендеріндегі жасыл көшеттерді ұстау және қорғау Ережесін бекіту туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/59674/rus
