act_code: '31492'
requisite: Қарағанды облысы Ақтоғай аудандық мәслихатының 32 сессиясының 2006 жылғы 21 желтоқсандағы № 356 шешімі. Ақтоғай ауданы әділет басқармасында 2007 жылғы 26 қаңтарда № 8-10-36 тіркелді
title:
  rus: 2007 жылға жер салығының базалық ставкасына түзету коэффициенттерін енгізу туралы
  kaz: 2007 жылға жер салығының базалық ставкасына түзету коэффициенттерін енгізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-21
approved_by:
- '160014000002'
version_date:
  kaz: 2006-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/31492/kaz/21.12.2006
