act_code: '64273'
requisite: Решение 2 сессии Жанааркинского районного маслихата Карагандинской области от 25 февраля 2012 года № 2/17. Зарегистрировано Управлением юстиции Жанааркинского района Карагандинской области 29 марта 2012 года № 8-12-125. Утратило силу решением Жанааркинского районного маслихата области Ұлытау от 28 июня 2024 года № 16/119 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания жилищной помощи населению Жанааркинского района
  kaz: Жаңаарқа ауданының тұрғындарына тұрғын үй көмегін көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2012-02-25
approved_by:
- '160016000002'
version_date:
  kaz: 2021-02-18
  rus: 2021-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/64273/kaz/18.02.2021
  rus: https://zan.gov.kz/client/#!/doc/64273/rus/18.02.2021
caused_by:
  code: '153128'
  requisite: Решение Жанааркинского районного маслихата Карагандинской области от 18 февраля 2021 года № 2/17. Зарегистрировано Департаментом юстиции Карагандинской области 25 февраля 2021 года № 6210. Утратило силу решением Жанааркинского районного маслихата области Ұлытау от 28 июня 2024 года № 16/119 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Жанааркинского районного маслихата от 25 февраля 2012 года № 2/17 «Об утверждении Правил оказания жилищной помощи населению Жанааркинского района»
    kaz: Жаңаарқа аудандық мәслихатының 2012 жылғы 25 ақпандағы № 2/17 «Жаңаарқа ауданының тұрғындарына тұрғын үй көмегін көрсету Ережесін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/153128/rus
