act_code: '126304'
requisite: Решение акима города Шахтинск Карагандинской области от 19 ноября 2018 года № 2. Зарегистрировано Департаментом юстиции Карагандинской области 29 ноября 2018 года № 5016. Утратило силу решением акима города Шахтинск Карагандинской области от 24 сентября 2019 года № 1 (вводится в действие со дня первого официального опубликования)
title:
  rus: Об образовании избирательных участков в городе Шахтинске
  kaz: Шахтинск қаласында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-19
approved_by:
- '160004000003'
version_date:
  kaz: 2018-11-19
  rus: 2018-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/126304/kaz/19.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126304/rus/19.11.2018
