act_code: '175637'
requisite: Решение Карагандинского областного маслихата от 8 декабря 2022 года № 277. Зарегистрировано в Министерстве юстиции Республики Казахстан 20 декабря 2022 года № 31170
title:
  rus: Об утверждении Правил отлова, временного содержания и умерщвления животных на территории Карагандинской области
  kaz: Қарағанды облысының аумағында жануарларды аулау, уақытша ұстау және жансыздандыру Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2022-12-08
approved_by:
- '160000000002'
version_date:
  kaz: 2022-12-08
  rus: 2022-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/175637/kaz/08.12.2022
  rus: https://zan.gov.kz/client/#!/doc/175637/rus/08.12.2022
