act_code: '56293'
requisite: Решение Сатпаевского городского маслихата Карагандинской области от 23 декабря 2010 года № 385. Зарегистрировано Управлением юстиции города Сатпаев Карагандинской области 29 декабря 2010 года № 8-6-113
title:
  rus: О городском бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '160007000002'
version_date:
  kaz: 2011-03-25
  rus: 2011-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/56293/kaz/25.03.2011
  rus: https://zan.gov.kz/client/#!/doc/56293/rus/25.03.2011
caused_by:
  code: '58183'
  requisite: Решение Сатпаевского городского маслихата Карагандинской области от 25 марта 2011 года № 415. Зарегистрировано Управлением юстиции города Сатпаев Карагандинской области 12 апреля 2011 года N 8-6-119
  title:
    rus: О внесении изменений и дополнений в решение ХХХI сессии Сатпаевского городского маслихата от 23 декабря 2010 года № 385 "О городском бюджете на 2011-2013 годы"
    kaz: Сәтбаев қалалық мәслихаттың "2011-2013 жылдарға арналған қалалық бюджет туралы" 2010 жылғы 23 желтоқсандағы XXXI сессиясының № 385 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/58183/rus
