act_code: '176596'
requisite: Решение Каркаралинского районного маслихата Карагандинской области от 23 декабря 2022 года № VII-29/237
title:
  rus: О бюджетах города районного значения, поселка, сельских округов на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған аудандық маңызы бар қала, кент, ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-23
approved_by:
- '160013000002'
version_date:
  kaz: 2023-04-18
  rus: 2023-04-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/176596/kaz/18.04.2023
  rus: https://zan.gov.kz/client/#!/doc/176596/rus/18.04.2023
caused_by:
  code: '179993'
  requisite: Решение Каркаралинского районного маслихата Карагандинской области от 18 апреля 2023 года № VIII-3/30
  title:
    rus: О внесении изменений в решение Каркаралинского районного маслихата от 23 декабря 2022 года № VII-29/237 «О бюджетах города районного значения, поселка, сельских округов на 2023-2025 годы»
    kaz: Қарқаралы аудандық мәслихатының 2022 жылғы 23 желтоқсандағы № VII-29/237 «2023-2025 жылдарға арналған аудандық маңызы бар қала, кент, ауылдық округтердің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/179993/rus
