act_code: '86439'
requisite: Решение Темиртауского городского маслихата Карагандинской области от 24 декабря 2014 года № 35/4. Зарегистрировано Департаментом юстиции Карагандинской области 9 января 2015 года № 2911
title:
  rus: О городском бюджет на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '160005000002'
version_date:
  kaz: 2015-12-15
  rus: 2015-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/86439/kaz/15.12.2015
  rus: https://zan.gov.kz/client/#!/doc/86439/rus/15.12.2015
caused_by:
  code: '96753'
  requisite: Решение Темиртауского городского маслихата Карагандинской области от 15 декабря 2015 года № 49/4. Зарегистрировано Департаментом юстиции Карагандинской области 21 декабря 2015 года № 3563
  title:
    rus: О внесении изменения в решение 35 сессии Темиртауского городского маслихата от 24 декабря 2014 года № 35/4 «О городском бюджете на 2015-2017 годы»
    kaz: Теміртау қалалық мәслихатының 2014 жылғы 24 желтоқсандағы 35 сессиясының № 35/4 «2015-2017 жылдарға арналған қалалық бюджет туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/96753/rus
