act_code: '137694'
requisite: Решение Нуринского районного маслихата Карагандинской области от 26 декабря 2019 года № 406. Зарегистрировано Департаментом юстиции Карагандинской области 30 декабря 2019 года № 5619
title:
  rus: О предоставлении в 2020 году мер социальной поддержки в виде подъемного пособия и бюджетного кредита для приобретения или строительства жилья специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, прибывшим для работы и проживания в сельские населенные пункты Нуринского района
  kaz: Нұра ауданының ауылдық елді мекендерге жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға көтерме жәрдемақы және тұрғын үй сатып алу немесе салу үшін бюджеттік кредит түрінде әлеуметтік қолдау шараларын 2020 жылы ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-26
approved_by:
- '160012000002'
version_date:
  kaz: 2019-12-26
  rus: 2019-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/137694/kaz/26.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137694/rus/26.12.2019
