act_code: '117475'
requisite: Решение 20 сессии Бухар-Жырауского районного маслихата Карагандинской области от 22 декабря 2017 года № 6. Зарегистрировано Департаментом юстиции Карагандинской области 29 декабря 2017 года № 4526
title:
  rus: О районном бюджете на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-22
approved_by:
- '160017000002'
version_date:
  kaz: 2018-09-28
  rus: 2018-09-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/117475/kaz/28.09.2018
  rus: https://zan.gov.kz/client/#!/doc/117475/rus/28.09.2018
caused_by:
  code: '125266'
  requisite: Решение 26 сессии Бухар-Жырауского районного маслихата Карагандинской области от 28 сентября 2018 года № 8. Зарегистрировано Департаментом юстиции Карагандинской области 15 октября 2018 года № 4975
  title:
    rus: О внесении изменений в решение 20 сессии Бухар-Жырауского районного маслихата от 22 декабря 2017 года № 6 «О районном бюджете на 2018-2020 годы»
    kaz: Бұқар жырау аудандық мәслихатының 20 сессиясының 2017 жылғы 22 желтоқсандағы № 6 «2018-2020 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/125266/rus
