act_code: '49564'
requisite: Қарағанды облысы Ақтоғай аудандық мәслихатының 18 сессиясының 2009 жылғы 23 желтоқсандағы № 188 шешімі. Қарағанды облысы Ақтоғай ауданының Әділет басқармасында 2009 жылғы 28 желтоқсанда № 8-10-94 тіркелді
title:
  rus: 2010 - 2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010 - 2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '160014000002'
version_date:
  kaz: 2010-02-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/49564/kaz/10.02.2010
caused_by:
  code: '50843'
  requisite: Қарағанды облысы Ақтоғай аудандық мәслихатының 20 сессиясының 2010 жылғы 10 ақпандағы № 208 шешімі. Қарағанды облысы Ақтоғай ауданының Әділет басқармасында 2010 жылғы 24 ақпанда № 8-10-100 тіркелді
  title:
    rus: Ақтоғай аудандық мәслихатының 2009 жылғы 23 желтоқсандағы 18 сессиясының "2010-2012 жылдарға арналған аудандық бюджет туралы" № 188 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Ақтоғай аудандық мәслихатының 2009 жылғы 23 желтоқсандағы 18 сессиясының "2010-2012 жылдарға арналған аудандық бюджет туралы" № 188 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/50843/rus
