act_code: '167092'
requisite: Решение Карагандинского областного маслихата от 15 апреля 2022 года № 180. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 апреля 2022 года № 27796. Утратило силу решением Карагандинского областного маслихата от 20 ноября 2025 года № 334 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении размера платы за один кубический метр поданной питьевой воды населению из особо важных групповых и локальных систем водоснабжения, являющихся безальтернативными источниками питьевого водоснабжения по Карагандинской области
  kaz: Қарағанды облысы бойынша ауызсумен жабдықтаудың баламасыз көздері болып табылатын сумен жабдықтаудың ерекше маңызды топтық және оқшау жүйелерінен халыққа берілген ауызсудың бір текше метрі үшін төлемақы мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-15
approved_by:
- '160000000002'
version_date:
  kaz: 2022-04-15
  rus: 2022-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/167092/kaz/15.04.2022
  rus: https://zan.gov.kz/client/#!/doc/167092/rus/15.04.2022
