act_code: '54571'
requisite: Қарағанды облысы Жаңаарқа ауданы Ералиев селолық округі әкімінің 2010 жылғы 5 қыркүйектегі № 1 шешімі. Қарағанды облысы Жаңаарқа ауданының Әділет басқармасында 2010 жылғы 21 қыркүйекте № 8-12-91 тіркелді
title:
  rus: Ералиев селолық округінің Ералиев ауылының көшелерін ретке келтіру және оларға атау беру туралы
  kaz: Ералиев селолық округінің Ералиев ауылының көшелерін ретке келтіру және оларға атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-05
approved_by:
- '160016002001'
version_date:
  kaz: 2010-09-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/54571/kaz/05.09.2010
