act_code: '140201'
requisite: Решение Абайского районного маслихата Карагандинской области от 12 марта 2020 года № 60/653. Зарегистрировано Департаментом юстиции Карагандинской области 13 марта 2020 года № 5748
title:
  rus: Об утверждении Правил оказания социальной поддержки и установления размера по оплате коммунальных услуг и приобретению топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Абайского района
  kaz: Абай ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына коммуналдық қызметтерді төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету және мөлшерін белгілеу қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-03-12
approved_by:
- '160011000002'
version_date:
  kaz: 2020-06-24
  rus: 2020-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/140201/kaz/24.06.2020
  rus: https://zan.gov.kz/client/#!/doc/140201/rus/24.06.2020
caused_by:
  code: '144527'
  requisite: Решение Абайского районного маслихата Карагандинской области от 24 июня 2020 года № 65/699. Зарегистрировано Департаментом юстиции Карагандинской области 7 июля 2020 года № 5936
  title:
    rus: О внесении изменения и дополнения в решение Абайского районного маслихата от 12 марта 2020 года № 60/653 «Об утверждении Правил оказания социальной поддержки и установления размера по оплате коммунальных услуг и приобретению топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Абайского района»
    kaz: Абай аудандық мәслихатының 2020 жылғы 12 наурыздағы № 60/653 «Абай ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына коммуналдық қызметтерді төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету және мөлшерін белгілеу қағидаларын бекіту туралы» шешіміне өзгерту мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/144527/rus
